"""Stream 5 of the r8int4 integration (27 September 2026, MESHSAT-1357): the handover pages after set 4. The integrator
lines of layers 1, 2, 3, 5 and 7 say what landed and what remains; ENGINEERING-QUESTIONS gains EQ-22 (HOT-R1), EQ-23
(the non-destructive hardware stage, S-58) and EQ-24 (the QMX lid tray), EQ-05 carries the hot stop's firing inside the
envelope and EQ-20 its merge; START-HERE and CONTINUATION-BRIEF state the re-take driver. Each edit asserts its old
text. Run from the worktree root."""
import re
def edit(p, pairs):
    t = open(p).read()
    for a, b in pairs:
        assert t.count(a) == 1, (p, t.count(a), a[:100]); assert a != b; t = t.replace(a, b)
    assert chr(0x2014) not in t; open(p, 'w').write(t)
def line_start(p, prefix, new):
    t = open(p).read().split('\n'); hit = [i for i, l in enumerate(t) if l.startswith(prefix)]
    assert len(hit) == 1, (p, prefix, len(hit)); t[hit[0]] = new; assert chr(0x2014) not in new
    open(p, 'w').write('\n'.join(t))
LS = 'v2/docs/handover/LAYER-STATUS.md'
B = "branch `fnd/r8int4` (set 4 after H1.1; commits `e5fde2ed` the re-take driver, `95e078a1` and `53292f81` layers 2 and 3, `0da2778b` layer 5, `c351115d` layer 7)"
line_start(LS, "> **INTEGRATOR LINE, layer 1:**",
 "> **INTEGRATOR LINE, layer 1:** status at `e3aedb25` IN_PROGRESS; status now: IN_PROGRESS; as of commit: " + B + "; items closed since `e3aedb25`: acceptance items 1 to 13 of `v2/docs/reviews/REVIEW-A-LAYER-1-2026-09-27.md` section 6 (purpose, users, scope, exclusions, outcome, commitments, claims against the baseline, rulings recorded, stale texts, the SIM description by SC-13, the mass limit REQ-023 by SC-14, records filed, the review held); its minors N1 and N2 fixed (`2ef6aa2a`); the registry half applied (`public-docs`, SC-13 to SC-16, REQ-023, CFL-010, S-13); item 14 met in part by H1 and H1.1, partial handovers. **Since H1.1:** finding I5 answered in the text: `fnd/hc1`'s held `drafts/layer2-emcon-face.patch` re-derived onto board B's round 8 (`95e078a1`: CONOPS M4, section 4's EMCON and Service rows, 4b's RockBLOCK row and the D-05 paragraph state EMCON as `feasibility/EMCON.md` section 0a does, 15 of 17 transmitters closed locally at desk and 0 of 17 end to end; the Service row names case choice C1's ten 6-32 screws; PANEL line 5 no longer lists the TX lamp as acting without software); I2 (`drafts/conops.patch`: the `public-docs` ruling in CONOPS section 7; its other two hunks were already in the layer 2 closer's text); NEED-03's public statements (V2-SPEC line 29 and correction 29, the brief's compute paragraph; ASM-002); V2-SPEC correction 22, correction 28, line 41 and the brief's SIM row reconciled with round 8's TVS arrays and with CFL-010 resolved on correction 22's description (the eSIM variant's order code stays under S-13); review record: as above. Remaining: (1) a check of I5 and I2 on the merged CONOPS and PANEL by Review A layer 1's reviewer or a fresh one (not run), then the brief's status set to BASELINED in that commit; (2) the fresh usability check of the snapshot (owner's prompt section 7); (3) minors N3 (the EMCON toggle's cover), N4, N5 and I7. Owner: the integrator.")
line_start(LS, "> **INTEGRATOR LINE, layer 2:**",
 "> **INTEGRATOR LINE, layer 2:** status at `e3aedb25` IN_PROGRESS; status now: IN_PROGRESS; as of commit: " + B + "; items closed since `e3aedb25`: round 8's pack temperature ladder (`dd39fb15`, `73d5df1e`); **the closer hc2 merged** (`95e078a1`: CONOPS, OPERATING-ENVELOPE, PANEL section 9, TEST-PLAN with the new row E3-H, `pcb_envelope.yaml` re-pinned, records `v2/docs/records/hc2/`), its Review A layer 2 record filed (`v2/docs/reviews/REVIEW-A-LAYER-2-2026-09-27.md`, AI review: first pass FAIL on B1 to B7, second pass FAIL on P2-B1 and P2-B2); the targeted fixer c23 answered P2-B1 (CONOPS section 7's D-02b row names the session's choices apart from the ruling) and P2-B2 (the hot stop past the heat stage on the cells' measured temperature, H1 at +56.5 C shedding to the minimum load and H2 at +57.0 C shutting the kit down; session choices SC-49 and SC-50, requirement REQ-077; `records/hc3/c23-response.md`), both CLOSED by a fresh verifier (AI); the verifier's new contradictions fixed at integration: OPERATING-ENVELOPE section 4 and `pcb_envelope.yaml` state CONOPS 4c's release (H1 by itself at +46.5 C and after 30 minutes, H2 only by MAIN), the Heat stage row says the gauge's charge window acts first and the hot stop before OTD, board P's second level, SOT and the PTC, and the present-tense guarantees in CONOPS 4c and OPERATING-ENVELOPE 4 are restated as what REQ-077 requires and the design intends, FEA-004 open; the mock-up's timing in CONOPS 4a and the D-06 row (`c351115d`); the needs pin re-pinned twice, the needs table unchanged. Remaining: (1) Review A layer 2's re-check of P2-B1 and P2-B2 on the merged text (not run; the c23 verifier's CLOSED read the drafts); (2) HOT-R1 drawn on boards A and E before their layout entry (S-57, EQ-22; REQ-077 reads FAIL on the generated boards until then); (3) whether a non-destructive hardware stage stands behind the hot stop (S-58, EQ-23, for the D-09 battery reviewer); (4) whether the hot stop fires inside the envelope (FEA-004, EQ-05; T-H1); (5) BANK-R1 on board B so the heat stage carries its required set (S-54; `records/hc2/handoffs.md`); (6) the cold end's 3.6 W/K bound (S-55); (7) E3-H has no forced-trigger step, so a chamber that never drives a cell to +56.5 C never exercises the stop (the verifier's residual); (8) layer 1's I5 check (its line). Owner: the integrator, the board A, B and E authors and the TEST-PLAN owner.")
line_start(LS, "> **INTEGRATOR LINE, layer 3:**",
 "> **INTEGRATOR LINE, layer 3:** status at `e3aedb25` IN_PROGRESS; status now: IN_PROGRESS; as of commit: " + B + "; items closed since `e3aedb25`: S-43 (closed on `dd39fb15`); S-46 (BAT-F20, EQ-15) and S-47 (HC9-E1) opened; from the merged closers hc1, hc9 and hc6 as at H1. **Since H1.1:** the closer hc3's registry change through its apply script (`95e078a1`, 404 changes, `records/hc3/apply_registry.py`): REQ-072 to REQ-077 (REQ-077 the hot stop), CON-023 to CON-025 (CON-025 the SIM TVS array, PASS on round 8's U222 and U223), CFL-018, S-48 to S-58, SC-17 to SC-50; REQ-041's mast-down alarm, REQ-034's NVIS target (MIL-STD-3009 Type I, Class B), REQ-016's 25 V solar window, M1's September design day, CFL-010 resolved (ADVISORY), CON-012 separating the owner's acceptance from the session's choices; the citations re-anchored from `eadbe571` to `95e078a1` (`53292f81`: 87 carried, 20 of them read by hand at integration, `records/r8int4/citations-reread-r8int4.md`); Review B layer 3 record filed (`v2/docs/reviews/REVIEW-B-LAYER-3-2026-09-27.md`, AI review), its findings B1 to B6 answered by c23 and CLOSED by the fresh verifier (AI); REQ-024 and FEA-004's notes restated on REQ-077; the layer 5 records CON-020 at 0x34 to 0x36, S-59 to S-62 and CON-026 (`0da2778b`); the layer 7 records REQ-047 (6-32), CON-006, L-07, FEA-007, REQ-019 without its fabrication-release fallback and S-63 (`c351115d`); `rules_lib.py requirements` 144 records, 0 errors, 0 warnings. Remaining: (1) Review B's re-check on the merged registry (not run); (2) REQ-077 FAIL until HOT-R1 (S-57); (3) SC-HF-01 to 06 recorded in `HW-FW-CONTRACT.md` section 8 but not as registry session choices; (4) E5's INT-001 binds only once the coverage map names `check_contracts_e5` (the re-take driver's finding, a registry writer's change); (5) the 42 PROTOTYPE_MEASUREMENT records no test plan names (hc3's finding for the TEST-PLAN owner); (6) GND-002 unruled (layer 4, `records/hc3/blocked-questions-layer-3.md` item 6); the acceptance items of this section. Owner: the integrator as registry writer.")
line_start(LS, "> **INTEGRATOR LINE, layer 5:**",
 "> **INTEGRATOR LINE, layer 5:** status at `e3aedb25` IN_PROGRESS; status now: IN_PROGRESS; as of commit: " + B + "; items closed since `e3aedb25`: R8E-N01 recorded (round 8, EQ-16); board E's raw bus from both feeds (`bc0f562f`). **Since H1.1, the closer hc5 merged** (`0da2778b`): `v2/docs/HW-FW-CONTRACT.md` version 1 (the FW rows of boards A to P and the kit bus, the heartbeat source resolved from the netlist, V-nn checks, findings HF-F01 to F08, session choices SC-HF-01 to 06); eighteen new contracts in `pcb_interfaces.yaml` (30 in all; `records/hc5/check_contract_fields.py` reads 18 of 18); the monitor's touch USB given a board end (SC-HF-06, board D's `J_USB3`, carried in IF-MON, ASSEMBLY, PANEL, ARCHITECTURE section 12 and these pages); the supervisors' block 0x34 to 0x36 in CON-020, PANEL 7, IOHA 6 and ZEROIZE Z-C3; the kit I2C budget (CON-026 FAIL at desk: as one segment the bus cannot meet its 300 ns targets; SC-HF-02's three segments owed); ARCHITECTURE section 12 keeping board B's round 8 facts on IF-BC-PANEL; both of hc5's second-review blocking items CLOSED by the fresh verifier (AI); the claims-screen regression fixed at integration (ENV-002 PASS) and the second review's wording minors taken (V-B19, FW-A08, HF-F06 raised to major, IF-E-WATER, IF-E-SENSORS, IF-DA-VHF, IF-MON's D8_EN, IF-EXT-DC with D-16, IF-AE-RF and W4-F10 after the clamp bar). Remaining: (1) the first twelve contracts carry none of the pass-2 field list (`records/hc5/check_contract_fields.out.txt`); (2) SC-HF-02 drawn on A and B (S-59), HF-F02 on A (S-60), HF-F06 on D before its layout entry (S-61), HF-F07 on E (S-62), HF-F08 (the MDI side, judged by nothing); (3) the SLOT_EN hold, the dock contact remedy (EQ-16), GND-002, D-07's site on A; (4) INT-001 re-taken on the committed netlists (the re-take driver) and E5's INT-001 bound; (5) SC-HF-01 to 06 into the registry's session choices; (6) a Review C over the contracts; EQ-12. Owner: the integrator and the board A, B, D and E authors.")
line_start(LS, "> **INTEGRATOR LINE, layer 7:**",
 "> **INTEGRATOR LINE, layer 7:** status at `e3aedb25` IN_PROGRESS; status now: IN_PROGRESS; as of commit: " + B + "; items closed since `e3aedb25`: board E's clamp bar (`45f6d83f`); hc4's case drawings (at `e3aedb25`). **Since H1.1, the closer hc7 merged** (`c351115d`): the case choices C1 to C6 in `panel1450.py`, `z_budget.py`, `case_wall_cutouts.py` and the CAD; the board reading required (`ZstackMissing`) and in board C's gate's evidence identity (`check_pcb_c.py` declared in `rules_status.CONFIG_INPUTS`); `frame_seat.py` reading U51 at ST's maximum (no figure moved); `v2/release/case-2026-09-27/` (the made parts' STEP and DXF, fourteen sheets with the QMX lid tray on sheet 14, MANIFEST checked); `CASE-FIT-UNCERTAINTIES.md`; FEA-007 and L-07 (the layout entry of boards A, B, E and P BLOCKED on the mock-up purchase; C, D and E5 not held); `test_case_geometry.py`; the fresh verifier CLOSED the tray release and left the timing NOT_CLOSED on six passages and two new contradictions, all fixed at integration (READY-TO-ACT's one-case order with its consequence, S-1 and S-8; REQ-019; ARCHITECTURE section 7; the layout-constraint README; OPERATING-ENVELOPE's pack row; V2-SPEC correction 18; EQ-08, the brief and this page). Remaining: (1) the mock-up purchase (L-07, EQ-08) and, with one case, the heat test before it (EQ-05); (2) the QMX lid tray revised from the unit's enclosure drawing before it is printed: the unit has jacks on both end panels and the tray notches one (S-63, EQ-24); (3) the jumper plug pick (M17g, M17x), the pack's hold-down (S-27), the sealed RJ45; (4) `v2/images/face-section.png` and `v2/cad/render/` still draw the superseded face (their owners'); (5) `CASE-MARGINS.md`'s 'Implemented in CAD' note and the `v2/cad` README call `panel1450.py` the single source including the tray, whose Y place lives in `lid_bracket_qmx.PLACE_Y` (c7's choice), and `scene.py`'s QY is a typed copy no test ties to it; (6) the snapshot's ZIP cap: the case release adds about 1.6 MB compressed where H1.1 left 1.3 MB under `pack.yaml`'s max_zip_bytes. Owner: the case writer and the integrator.")
edit(LS, [
    ("referred to here by id.", "referred to here by id. **After H1.1 (set 4):** EQ-22 to EQ-24 are added and EQ-05 carries the hot stop."),
    ("| r8b | 8 (board B) | board B's round 8 circuit, `FAILOVER-FABRIC` and IOHA patches | not merged; residual stated (EQ-20); its IOHA patch must be re-derived on hc6's reconciled text; `candidates/r8b.patch` |\n",
     "| r8b | 8 (board B) | board B's round 8 circuit, `FAILOVER-FABRIC` and IOHA patches | not merged; residual stated (EQ-20); its IOHA patch must be re-derived on hc6's reconciled text; `candidates/r8b.patch` |\n\n"
     "**Merged after H1.1.** Board B's round 8 landed on main at `b76c18cb` (integrated in `cc3313f3`). The set 4 branch `fnd/r8int4` then merged the re-take driver (`e5fde2ed`, REGENERATE section 9), hc2 and hc3 with the targeted fixer c23 and `fnd/hc1`'s held patches (`95e078a1`, `53292f81`), hc5 with c5 (`0da2778b`) and hc7 with c7 (`c351115d`), so `candidates/hc2.patch`, `hc3.patch`, `hc5.patch`, `hc7.patch` and `r8b.patch` are superseded by those commits; each layer's integrator line says what landed and what remains.\n"),
])
# ------------------------------------------------------------------------------------------ ENGINEERING-QUESTIONS
EQ = 'v2/docs/handover/ENGINEERING-QUESTIONS.md'
edit(EQ, [
    ("design file those questions cite). Internal names",
     "design file those questions cite). **After H1.1 (set 4, branch `fnd/r8int4`, 27 September 2026)** EQ-22 to EQ-24 are added, EQ-05 carries the hot stop's firing inside the envelope and EQ-20 its merge; their citations are at that branch's commits. Internal names"),
    ("| EQ-05 | What is the sealed case's thermal conductance, and is the hot end feasible? | B. physical evidence | 2, 4, 7, 9 | A, B, D, P | freezing hot-part placement and the pack location; the +35 and +25 C figures |",
     "| EQ-05 | What is the sealed case's thermal conductance, and is the hot end feasible (the hot stop's firing inside the envelope included)? | B. physical evidence | 2, 3, 4, 7, 9 | A, B, D, P | freezing hot-part placement and the pack location; the +35 and +25 C figures; REQ-052 and REQ-024 at +40 C wherever the hot stop fires |"),
    ("| EQ-20 | Board B's round 8 circuit is unmerged, with a sub-13 ns enable pulse window left | A. design work | 4, 8 | B | B's netlist, every B reading, FEA-003's fabric half |",
     "| EQ-20 | Board B's round 8 circuit (merged at `b76c18cb` after H1.1), with a sub-13 ns enable pulse window left | A. design work | 4, 8 | B | the residual's judgement (R-HSD); FEA-003's fabric half |"),
    ("| EQ-21 | The generators write no MPN; 1497 of 2205 BOM rows carry no order code | A. design work | 6, 8 | all six | layer 6's exact identity per BOM line |",
     "| EQ-21 | The generators write no MPN; 1497 of 2205 BOM rows carry no order code | A. design work | 6, 8 | all six | layer 6's exact identity per BOM line |\n"
     "| EQ-22 | The hot stop's signal path HOT-R1 is in neither board A's nor board E's generator | A. design work | 2, 3, 5, 8 | A, E | REQ-077 (FAIL until drawn); the layout entry of A and E |\n"
     "| EQ-23 | Does a non-destructive, firmware-free hardware stage stand behind the hot stop (S-58)? | C. external authorisation | 2, 3, 4, 8 | A, E, P | the layout entry of A, E and P; REQ-044, REQ-046, REQ-077 |\n"
     "| EQ-24 | The QMX lid tray does not fit the unit's connector layout (jacks on both end panels) | A. design work | 7 | none (a made part) | printing the tray (S-63) |"),
    ("| **Recommended next action** | Merge r8b (apply `candidates/r8b.patch` to `fc144600`, re-derive its drafted page patches on the current text) with parity and the residual written into FAILOVER-FABRIC; R-HSD (EQ-12) judges whether a sub-13 ns enable pulse matters to the switches it drives. |",
     "| **Recommended next action** | Merge r8b (apply `candidates/r8b.patch` to `fc144600`, re-derive its drafted page patches on the current text) with parity and the residual written into FAILOVER-FABRIC; R-HSD (EQ-12) judges whether a sub-13 ns enable pulse matters to the switches it drives. **Done for the merge after H1.1:** board B's round 8 is on main at `b76c18cb` (integrated in `cc3313f3`) and FAILOVER-FABRIC states the residual (its round 8 section); what remains is R-HSD's judgement and the re-take of B's readings on its new netlist. |"),
])
t = open(EQ).read()
anchor = "\n## B. Physical evidence\n"
assert t.count(anchor) == 1
new_a = '''
### EQ-22. The hot stop's signal path, HOT-R1, is in no generator (S-57)

| | |
|---|---|
| **Exact issue** | Past the heat stage the kit acts on the pack's measured cell temperature (the hot stop, `v2/docs/CONOPS.md` section 4c; requirement REQ-077; session choices SC-49 and SC-50). Board E's sensor controller is the pack gauge's only SMBus host; the panel controller, which owns the slot enables, the switched loads and `PI_KILL`, reaches it as generated only over USB through a compute module's bridge, which the heat stage as board B is generated does not host and which the stop's own first step removes. HOT-R1, the session's line from the sensor controller's GPIO19 through an open-drain 2N7002 on board E over the dock's spare contact (E `J_BLK` pin 12 to A `J_DOCK` pin 12) to board A's expander input and `EXP_INT`, with a 10 k pull-up on A, is drawn on neither board. |
| **Affected** | REQ-077 (FAIL on the generated boards until drawn), boards A and E, IF-AE-DOCK's pin 12, the sensor and panel controllers' firmware contracts, `TEST-PLAN.md` E3-H. |
| **Evidence** | `gen_sch_e.py` at `a8652172` (unchanged since): `J_BLK` pin 12 (`BLK_SPARE`) reaches only TP7, U10's GPIO19 (pin 30) is not connected; `gen_sch_a.py`: `J_DOCK` pin 12 (`DOCK_SPARE`) lands on U27 pin 18, whose `EXP_INT` (R110) is the panel controller's interrupt; `gen_sch_c.py` (U3 GPIO24 `EXP_INT`, GPIO13 to 15 `SLOT_EN`, GPIO19 `PI_KILL`); `v2/docs/records/hc3/blocked-questions-layer-3.md` item 13. |
| **Attempts and results** | A stand-in on board B's TMP117 was drafted and kept only as the fallback for a lost sensor controller (+55.0 and +56.0 C), because the finding asks for the cells' own temperature on every input state. |
| **Viable options** | (a) HOT-R1 as taken (SC-50): four line states (1 Hz ok, 5 Hz H1, held low H2, held high detector lost); (b) a USB-only path, which needs a module hosting both controllers' banks to keep running in the heat stage (not as generated; H1 stops it anyway); (c) a kit-bus device on board E that the panel polls (a part and a bus branch through a dock with no spare pair). |
| **Recommended next action** | (a) at the next regeneration of boards A and E, before their layout entry; then E3-H on the bench. |
| **Expertise or equipment** | The board A and E authors; the E3-H bench check. |
| **Cost and lead time** | One transistor and two resistors per kit; desk work at the next regeneration. |
'''
new_b = '''
### EQ-24. The QMX lid tray does not fit the unit's connector layout (S-63)

| | |
|---|---|
| **Exact issue** | The QMX lid tray released in `v2/release/case-2026-09-27/lid-tray-qmx/` (sheet 14) has cable notches in one end wall only, while the held QRP Labs QMX manual (1_04_004, pages 7 to 9) puts the DC jack on the left panel and the BNC and USB-C on the right panel. The unit's 95 x 63 x 25 and the notch heights are checked against no maker drawing. |
| **Affected** | The tray (a made part) and its print; the lid harness' route; nothing on a board (`J_QMX`, `J_HF` and `J_RF2` stay). |
| **Evidence** | `v2/docs/CASE-FIT-UNCERTAINTIES.md` section 3; sheet 14 note 4; `ASSEMBLY.md`'s QMX row; the release README; `v2/docs/records/hc7/c7-response.md`. |
| **Attempts and results** | Found by the layer 7 fixer c7 while drawing sheet 14, which draws the part where `scene.py` places it with its turned-end twin dotted; no direction is chosen for the notched end. |
| **Viable options** | (a) Revise the tray from the QMX enclosure drawing (notches or openings at both ends, the pocket from the maker's figures) before it is printed; (b) keep the tray and route the DC lead round the unit (a cable strain and a lid-closing risk); (c) a strap-only mount without a tray (loses the tray's retention). |
| **Recommended next action** | (a): desk work on a made part, no board moves and no money. |
| **Expertise or equipment** | The case writer; the maker's enclosure drawing (to be filed in `v2/vendor/`). |
| **Cost and lead time** | Desk work; a reprint of the tray when the prototype's printed parts are made. |
'''
new_c = '''
### EQ-23. A non-destructive hardware stage behind the hot stop (S-58)

| | |
|---|---|
| **Exact issue** | The hot stop is firmware in two controllers (the sensor controller detects, the panel controller acts). What stands behind it on an input is destructive: board P's second level from 62.7 C blows the chemical fuse F2, and the gauge's SOT from 64.2 C and the PTC are permanent. Whether a firmware-free stage that removes the kit's heat without destroying the pack is required is a protection-architecture judgement. |
| **Affected** | REQ-077, REQ-044, REQ-046; boards A, E and P; Q-P15 of the battery packet. |
| **Evidence** | `v2/docs/review-packets/battery/THERMAL-COORDINATION.md` sections 4 (L8 to L12), 7 and 8 (the hold that would enforce 60 C in hardware opens the pack's FETs, which removes no heat on an input); `v2/docs/records/hc3/blocked-questions-layer-3.md` item 14. |
| **Attempts and results** | None drawn; the battery packet's section 8 put its hold to the reviewer rather than adding it. |
| **Viable options** | (a) None: the firmware stop, then the destructive backstops (TI's own layering); (b) the packet's hold on board P alone (removes no heat on an input); (c) a comparator on its own thermistor on the hottest cell, at most 57.5 C with its tolerance and 5 K of hysteresis, taking board A's `KILL` low without firmware (a second dock contact, or a hardware decode of HOT-R1's held-low state on board A). |
| **Recommended next action** | (c), put to the D-09 battery-and-protection reviewer (R-BAT, EQ-10) together with Q-P15; the session keeps (a) with HOT-R1 until the review answers. Decided before the layout entry of boards A, E and P. |
| **Expertise or equipment** | Battery protection and functional safety (the D-09 reviewer); the bench readings P14 and E3-H. |
| **Cost and lead time** | A comparator, a reference, a thermistor and a transistor per kit (no part filed: TBD); R-BAT's quote and lead time (the owner's money, approved in principle by D-09). |
'''
# EQ-22 and EQ-24 at the end of group A; EQ-23 at the end of group C (before the file's end or the next section)
t = t.replace(anchor, new_a + new_b + anchor, 1)
t = t.rstrip('\n') + '\n' + new_c
# EQ-05: the hot stop
a = "| **Affected** | FEA-004; D-02b's reduced mode (S-24) and its accepted consequences;"
assert t.count(a) == 1
t = t.replace(a, "| **Affected** | FEA-004; REQ-077 and, wherever the hot stop fires at +40 C, REQ-052's stage criteria and REQ-024's use at +40 C; D-02b's reduced mode (S-24) and its accepted consequences;")
a = "The bound includes failure and nothing has been measured. |"
assert t.count(a) == 1
t = t.replace(a, "The bound includes failure and nothing has been measured. **Since the layer 2 merge (set 4, `95e078a1`) the question also decides whether the hot stop fires inside the envelope:** past the heat stage the kit sheds to its minimum load when the hottest cell reads +56.5 C and shuts down at +57.0 C (REQ-077, SC-49); at the independent bound's worst corner its first step acts from +33.2 C lid closed and +36.1 C lid open, on appendix 32.53's conductance not below +40.3 C and +48.1 C (`v2/docs/records/hc2/hotstop_bounds.out`, INFERRED). Where it fires at +40 C the kit runs no module there on any supply, so REQ-052's stage criteria and REQ-024's use at +40 C are not met there (recorded, not waived); REQ-077 requires the stop to keep the cells inside +60 C and the design intends it to, once HOT-R1 is drawn (EQ-22) and on the provisional error budget (`TEST-PLAN.md` P14). |")
a = "32.56 (line 2940); the owner's second review, finding B. |"
assert t.count(a) == 1
t = t.replace(a, "32.56 (line 2940); the owner's second review, finding B; for the hot stop, `v2/docs/CONOPS.md` section 4c, `v2/docs/records/hc2/hotstop_bounds.py` and `.out`, and `v2/docs/records/hc3/blocked-questions-layer-3.md` item 15. |")
assert chr(0x2014) not in t
open(EQ, 'w').write(t)
# ------------------------------------------------------------------------------------------ START-HERE and the brief
edit('v2/docs/handover/START-HERE.md', [
    ("recipient re-takes a reading rather than reading it back. REGENERATE.md section 9 states the re-take procedure in\n"
     "  words: on a KiCad 9.0.9 host, every writer of a schematic-phase rule per board with `VERDICT_DIR` set, then\n"
     "  `rules_status.py` and `rules_render.py`, which reproduces and updates the layout-entry status (A 17 ... E5 5). The\n"
     "  driver that runs it in one command arrives in the next snapshot (H2); it is not in H1.1, and was not run for it.",
     "recipient re-takes a reading rather than reading it back. REGENERATE.md section 9 states the re-take procedure,\n"
     "  which H1.1 carries in words only. **Since the set 4 branch after H1.1 (`e5fde2ed`) the driver exists:**\n"
     "  `v2/ecad/tools/retake_schematic_phase.py` plans every schematic-phase writer per board from the registries\n"
     "  (`--plan`) and runs them on the committed netlists (`--run --in-place --routed` in a throwaway git clone outside\n"
     "  `/tmp` on a KiCad 9.0.9 host), then `rules_status.py` three times and `rules_render.py`; its trial on `a8652172`\n"
     "  took the layout-entry reasons from 95 to 37 with no board ready (REGENERATE.md section 9). It is in no snapshot\n"
     "  before H2."),
])
edit('v2/docs/handover/CONTINUATION-BRIEF.md', [
    ("  section 9 states the re-take procedure that reproduces and updates them, in words: its driver arrives in the next\n  snapshot (H2) and is not in H1.1.",
     "  section 9 states the re-take procedure that reproduces and updates them, in words in H1.1; **its driver,\n"
     "  `v2/ecad/tools/retake_schematic_phase.py`, landed after H1.1** (`e5fde2ed`, branch `fnd/r8int4`): `--plan` lists\n"
     "  every schematic-phase writer per board from the registries, `--run --in-place --routed` takes them on the committed\n"
     "  netlists in a throwaway git clone outside `/tmp` on a KiCad 9.0.9 host, then `rules_status.py` three times and\n"
     "  `rules_render.py` (REGENERATE.md section 9, with its trial on `a8652172`: 73 commands, reasons 95 to 37)."),
    ("| 2 | One consolidated re-take of every schematic-phase reading in a clean clone on a KiCad 9.0.9 host; CURRENT-EVIDENCE re-rendered (procedure: REGENERATE.md section 9) | step 1 | no |",
     "| 2 | One consolidated re-take of every schematic-phase reading in a clean clone on a KiCad 9.0.9 host with `retake_schematic_phase.py --run --in-place --routed`, its `routed/` copies committed; CURRENT-EVIDENCE re-rendered (procedure: REGENERATE.md section 9) | step 1 | no |"),
])
print("edit_handover_set4: done")
# (applied after the first run, inline) candidates/README.md: a "Superseded after H1.1" paragraph under the header
