#!/usr/bin/env python3
"""The open owner decisions, as one page (MESHSAT-862, 17 September 2026).

`v2/docs/OWNER-DECISIONS-2026-09-11.md` is the record: every decision with its evidence, its options and their
costs, in the order they were asked. It is 2,400 lines because the evidence is worth that. What it cannot
answer is the question that decides what this project can finish: WHAT IS OPEN, AND WHAT DOES EACH ONE HOLD
UP. This generates that page from `pcb_decisions.yaml` and the rule registry, so the count of rule-board pairs
behind each decision is computed rather than asserted.

  decisions_render.py            write v2/docs/OWNER-DECISIONS-OPEN.md
  decisions_render.py --check    refuse a hand-edited copy (exit 1)
"""
import os, sys, json

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import rules_status as S
import rules_render as RR

DECISIONS = os.path.join(HERE, "pcb_decisions.yaml")
RECORD = "v2/docs/OWNER-DECISIONS-2026-09-11.md"
HEAD = ("<!-- GENERATED by tools/decisions_render.py from tools/pcb_decisions.yaml and the rule registry.\n"
        "     Do not edit: `python3 tools/decisions_render.py --check` refuses a hand-edited copy. -->\n")


def load():
    import yaml
    return yaml.safe_load(open(DECISIONS, encoding="utf-8"))["decisions"]


def _state():
    """{(rule, board): result} from the audit this tree last computed, when it is there."""
    out = {}
    d = os.path.join(os.path.dirname(HERE), "out", "rule-audit")
    for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if not f.endswith(".json") or f == "summary.json": continue
        try: st = json.load(open(os.path.join(d, f), encoding="utf-8"))
        except ValueError: continue
        for r in st.get("rows", []): out[(r["rule"], st["board"])] = r["result"]
    return out


def render():
    ds = load(); reg = R.load(); state = _state()
    names = {r["id"]: r["short_name"] for r in reg["rules"]}
    effect = {r["id"]: r["release_effect"] for r in reg["rules"]}
    L = [HEAD, "# Owner decisions, open", "",
         RR._wrap("One line per decision that is still open, what it holds up, and where its evidence is. The "
                  "record is %s and this page is generated from the same registry the readiness table is, so "
                  "the pair counts below are the ones the gates use." % RECORD), ""]
    op = [d for d in ds if d.get("status") == "open"]
    pairs = 0
    for d in op:
        for rid, boards in (d.get("blocks") or {}).items(): pairs += len(boards)
    L += [RR._wrap("**%d decisions are open and they hold %d rule-board pairs of the 300 the set is judged on.** "
                   "A pair held by a decision is not a defect in the board: it is a question nobody has answered, "
                   "and until it is answered the rule can be neither passed nor failed." % (len(op), pairs)), ""]
    L += ["| # | what is being decided | holds | boards | asked |", "|---|---|---|---|---|"]
    for d in op:
        b = sorted({x for v in (d.get("blocks") or {}).values() for x in v})
        rules = sorted(d.get("blocks") or {})
        L.append("| **%d** | %s | %s | %s | %s |"
                 % (d["n"], d["title"], ", ".join(rules) or "nothing today, see below",
                    ", ".join(x.upper() for x in b) or "-", d.get("asked", "")))
    L += ["", "## Each one, with what it holds", ""]
    for d in op:
        L += ["### Decision %d: %s" % (d["n"], d["title"]), ""]
        if d.get("ask"): L += [RR._wrap("**The question:** " + d["ask"]), ""]
        if d.get("recommendation"): L += [RR._wrap("**Recommended:** " + d["recommendation"]), ""]
        if d.get("evidence"): L += [RR._wrap("**Measured:** " + d["evidence"]), ""]
        if d.get("holds_nothing_today"):
            L += [RR._wrap("**Holds no rule today:** " + d["holds_nothing_today"]), ""]
        if d.get("blocks"):
            L += ["| rule | | boards | result today |", "|---|---|---|---|"]
            for rid, boards in sorted(d["blocks"].items()):
                res = sorted({state.get((rid, x.lower()), "not computed") for x in boards})
                L.append("| %s | %s | %s | %s |" % (rid, names.get(rid, ""), ", ".join(x.upper() for x in boards),
                                                   ", ".join(res)))
            L.append("")
        L.append("")
    closed = [d for d in ds if d.get("status") != "open"]
    if closed:
        L += ["## Closed, for the record", "", "| # | what it was | how it ended |", "|---|---|---|"]
        for d in closed:
            L.append("| %d | %s | %s |" % (d["n"], d["title"], d.get("outcome", d.get("status", ""))))
        L.append("")
    return {os.path.join(RR.DOCS, "OWNER-DECISIONS-OPEN.md"): "\n".join(L) + "\n"}


def main(argv):
    files = render()
    if "--check" in argv:
        bad = [p for p, body in files.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != body]
        for p in bad: print("decisions_render: %s differs from what the register renders" % os.path.relpath(p))
        return 1 if bad else 0
    for p, body in files.items():
        open(p, "w", encoding="utf-8").write(body)
        print("decisions_render: wrote %s (%d lines)" % (os.path.relpath(p), body.count("\n")))
    return 0


if __name__ == "__main__": sys.exit(main(sys.argv[1:]))
