#!/usr/bin/env python3
"""PCB-C, phase C6 mechanical: the BACKER BOARD under the aluminium face plate of the Peli 1450 (owner rulings 5 Sep 2026, appendix 32.40 items 4 and 5, 32.42).
Usage: gen_pcb_c.py <out.kicad_pcb>
The face is the 3 mm plate of v2/cad/face_plate.py (365.5 x 249.5, clamped under the 1450PF frame ring, PORON gasket on its band, every seal a named part as in
32.34). This board hangs 10 mm under the plate on six self-clinching M3 standoffs and carries the electronics only: the expanders and LED drivers, the sixteen
LEDs under the plate's light pipes, the lead lands of the seven switches and the sounder, the ribbon J_PANEL, the e-paper lead J_EPD and the MAIN / PI lands.
It is a U in the strips outside PCB-B's outline (left: toggles, bottom: sounder and battery bar, right: buttons, status LEDs, the drivers), open over the
display and the e-paper, whose modules bond to the plate. Positions come from tools/panel1450.py, the single source shared with the plate.
Case-centred frame (origin = case cavity centre = frame centre, +X starboard, +Y back wall), the same as the plate and the render scene."""
import math, sys, os
import pcbnew
from pcbnew import VECTOR2I, FromMM
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import panel1450 as L
OUT = sys.argv[1] if len(sys.argv) > 1 else "pcb-c-display.kicad_pcb"
PRJDIR = os.path.dirname(os.path.abspath(OUT)); MSLIB = os.path.join(PRJDIR, "..", "meshsat.pretty")
open(os.path.join(PRJDIR, "fp-lib-table"), "w").write('(fp_lib_table\n  (version 7)\n  (lib (name "meshsat")(type "KiCad")(uri "${KIPRJMOD}/../meshsat.pretty")(options "")(descr "MeshSat carrier in-code footprints"))\n)\n')
# ---------------------------------------------------------------- geometry
BOARD_T = L.BACKER_T
SL, SB, SR = L.STRIP_L, L.STRIP_B, L.STRIP_R          # (x0, y0, x1, y1) each
OUTER = (SL[0], SB[1], SR[2], SL[3])                  # -172, -114, 172, 114
VOID = (SL[2], SB[3], SR[0], SL[3])                   # -120, -88, 120, 114: open over the display and the e-paper
# ---------------------------------------------------------------- KiCad plumbing (A2 sheet holds the 344 x 228 U at 1:1 with room for the plate outline)
OX, OY = 297.0, 210.0
def P(x, y): return VECTOR2I(FromMM(OX + x), FromMM(OY - y))
board = pcbnew.BOARD()
tb = pcbnew.TITLE_BLOCK(); tb.SetTitle("MeshSat Field Kit carrier - PCB-C CONTROL PANEL BACKER"); tb.SetRevision("A (C6)"); tb.SetDate("2026-09-05"); tb.SetCompany("MeshSat")
tb.SetComment(0, "MESHSAT-709 / 505. Case-centred frame, +Y = case back wall. Backer board under the aluminium face plate in the Peli 1450PF frame. Generated by tools/gen_pcb_c.py + gen_pcb_c3.py"); board.SetTitleBlock(tb)
ds = board.GetDesignSettings(); ds.SetBoardThickness(FromMM(BOARD_T)); ds.SetAuxOrigin(P(0, 0)); ds.SetGridOrigin(P(0, 0))
for attr, val in (("m_MinClearance", 0.127), ("m_TrackMinWidth", 0.127), ("m_ViasMinSize", 0.5), ("m_MinThroughDrill", 0.3), ("m_HoleToHoleMin", 0.3), ("m_CopperEdgeClearance", 0.3), ("m_HoleClearance", 0.25), ("m_SolderMaskMinWidth", 0.1)):
    try: setattr(ds, attr, FromMM(val))
    except Exception as e: print("note: could not set", attr, e)
def shape(layer, width=0.1):
    s = pcbnew.PCB_SHAPE(board); s.SetLayer(layer); s.SetWidth(FromMM(width)); board.Add(s); return s
def line(x1, y1, x2, y2, layer, width=0.1):
    s = shape(layer, width); s.SetShape(pcbnew.SHAPE_T_SEGMENT); s.SetStart(P(x1, y1)); s.SetEnd(P(x2, y2)); return s
def arc(cx, cy, r, a0, a1, layer, width=0.1):
    am = (a0 + a1) / 2.0; pt = lambda a: (cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a)))
    s = shape(layer, width); s.SetShape(pcbnew.SHAPE_T_ARC); s.SetArcGeometry(P(*pt(a0)), P(*pt(am)), P(*pt(a1))); return s
def circle(cx, cy, d, layer, width=0.1):
    s = shape(layer, width); s.SetShape(pcbnew.SHAPE_T_CIRCLE); s.SetStart(P(cx, cy)); s.SetEnd(P(cx + d / 2.0, cy)); return s
def rounded_rect(x0, y0, x1, y1, r, layer, width=0.1):
    x0, x1 = min(x0, x1), max(x0, x1); y0, y1 = min(y0, y1), max(y0, y1)
    line(x0 + r, y0, x1 - r, y0, layer, width); line(x1, y0 + r, x1, y1 - r, layer, width); line(x1 - r, y1, x0 + r, y1, layer, width); line(x0, y1 - r, x0, y0 + r, layer, width)
    arc(x1 - r, y0 + r, r, 270, 360, layer, width); arc(x1 - r, y1 - r, r, 0, 90, layer, width); arc(x0 + r, y1 - r, r, 90, 180, layer, width); arc(x0 + r, y0 + r, r, 180, 270, layer, width)
def text(txt, x, y, layer, size=2.0, thick=0.3, angle=0.0, mirror=False, halign="center"):
    t = pcbnew.PCB_TEXT(board); t.SetText(txt); t.SetPosition(P(x, y)); t.SetLayer(layer)
    t.SetTextSize(VECTOR2I(FromMM(size), FromMM(size))); t.SetTextThickness(FromMM(thick)); t.SetTextAngleDegrees(angle)
    t.SetHorizJustify({"center": pcbnew.GR_TEXT_H_ALIGN_CENTER, "left": pcbnew.GR_TEXT_H_ALIGN_LEFT, "right": pcbnew.GR_TEXT_H_ALIGN_RIGHT}[halign])
    if mirror: t.SetMirrored(True)
    board.Add(t); return t
def footprint(libpath, name, ref, x, y, value, rot=0.0):
    fp = pcbnew.FootprintLoad(libpath, name)
    if fp is None: raise SystemExit("footprint %s not found in %s" % (name, libpath))
    fp.SetReference(ref); fp.SetValue(value); fp.Reference().SetVisible(False); fp.Value().SetVisible(False)
    fp.SetPosition(P(x, y)); fp.SetOrientationDegrees(rot); board.Add(fp); return fp
def rule_area(points, name, tracks=False, vias=False, pads=True, footprints=True, pour=True):
    """Rule area on both copper layers; every keyword says what stays ALLOWED inside it."""
    z = pcbnew.ZONE(board); z.SetIsRuleArea(True); z.SetDoNotAllowCopperPour(not pour); z.SetDoNotAllowTracks(not tracks); z.SetDoNotAllowVias(not vias); z.SetDoNotAllowPads(not pads); z.SetDoNotAllowFootprints(not footprints)
    z.SetLayerSet(pcbnew.LSET.AllCuMask(2)); z.SetZoneName(name); o = z.Outline(); o.NewOutline()
    for x, y in points: p = P(x, y); o.Append(p.x, p.y)
    board.Add(z); return z
def rule_circle(cx, cy, r, name):
    rule_area([(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in range(0, 360, 15)], name)
# ---------------------------------------------------------------- outline: the U, 3 mm corner radius on the outer corners, square inner corners
R = 3.0
x0, y0, x1, y1 = OUTER; vx0, vy0, vx1, vy1 = VOID
E = pcbnew.Edge_Cuts
line(x0 + R, y0, x1 - R, y0, E); arc(x1 - R, y0 + R, R, 270, 360, E); line(x1, y0 + R, x1, y1 - R, E); arc(x1 - R, y1 - R, R, 0, 90, E)
line(x1 - R, y1, vx1, y1, E); line(vx1, y1, vx1, vy0, E); line(vx1, vy0, vx0, vy0, E); line(vx0, vy0, vx0, y1, E); line(vx0, y1, x0 + R, y1, E)
arc(x0 + R, y1 - R, R, 90, 180, E); line(x0, y1 - R, x0, y0 + R, E); arc(x0 + R, y0 + R, R, 180, 270, E)
# ---------------------------------------------------------------- the six standoff screws (M3 into the plate's self-clinching standoffs), on GND: the plate's bond
for i, (x, y) in enumerate(L.STANDOFFS, 1):
    footprint(MSLIB, "BackerScrew_M3_GND", "H%d" % i, x, y, "M3 x 6 into the plate's self-clinching standoff (PEM SO-M3-10), GND bond to the plate")
# ---------------------------------------------------------------- router keep-outs around every panel-mount cut-out (Freerouting ignores the edge clearance of inner cut-outs)
K = L.CUTOUT_KEEPOUT
for ref, (x, y), hole, depth in L.BUTTONS: rule_circle(x, y, hole / 2 + K, "cut-out keep-out " + ref)
for ref, (x, y) in L.TOGGLES:
    w, h = L.TOGGLE_BODY; rule_area([(x - w / 2 - K, y - h / 2 - K), (x + w / 2 + K, y - h / 2 - K), (x + w / 2 + K, y + h / 2 + K), (x - w / 2 - K, y + h / 2 + K)], "cut-out keep-out " + ref)
lx, ly = L.LIGHT[1]; w, h = L.LIGHT_BODY; rule_area([(lx - w / 2 - K, ly - h / 2 - K), (lx + w / 2 + K, ly - h / 2 - K), (lx + w / 2 + K, ly + h / 2 + K), (lx - w / 2 - K, ly + h / 2 + K)], "cut-out keep-out SW_LIGHT")
sx, sy = L.SOUNDER[1]; rule_circle(sx, sy, L.SOUNDER[2] / 2 + K, "cut-out keep-out BZ1")
# the outer edge of the U: a 0.6 mm band (no tracks, no vias) so the router keeps the board's copper-to-edge clearance (C6 run 3: tracks at 0.3 mm from the right edge)
for (ax0, ay0, ax1, ay1) in ((x0, y0, x0 + K, y1), (x1 - K, y0, x1, y1), (x0, y0, x1, y0 + K), (x0, y1 - K, vx0, y1), (vx1, y1 - K, x1, y1)):
    rule_area([(ax0, ay0), (ax1, ay0), (ax1, ay1), (ax0, ay1)], "outer edge keep-out (router)")
# the inner edge of the U: 0.6 mm edge clearance for the router
rule_area([(vx0 - K, vy0 - K), (vx1 + K, vy0 - K), (vx1 + K, y1 + 1), (vx1 - K, y1 + 1), (vx1 - K, vy0 + K), (vx0 + K, vy0 + K), (vx0 + K, y1 + 1), (vx0 - K, y1 + 1)], "inner edge keep-out (router edge clearance)")
# ---------------------------------------------------------------- reference graphics: the plate, the window, the display and e-paper modules above the void
pw, ph, pt = L.PLATE
rounded_rect(-pw / 2, -ph / 2, pw / 2, ph / 2, L.PLATE_R, pcbnew.Dwgs_User, 0.15); text("face plate 365.5 x 249.5 x 3 (v2/cad/face_plate.py), 10 mm above this board", 0, ph / 2 - 4.0, pcbnew.Dwgs_User, 2.0, 0.3)
rounded_rect(-L.WINDOW[0] / 2, -L.WINDOW[1] / 2, L.WINDOW[0] / 2, L.WINDOW[1] / 2, 5.85, pcbnew.Dwgs_User, 0.15); text("frame window 349.65 x 233.83", 0, L.WINDOW[1] / 2 - 9.0, pcbnew.Dwgs_User, 1.6, 0.25)
gx, gy = L.DISPLAY["c"]; gw, gh = L.DISPLAY["glass"]; rounded_rect(gx - gw / 2, gy - gh / 2, gx + gw / 2, gy + gh / 2, 8.0, pcbnew.Dwgs_User, 0.1); text("Touch Display 2 glass on the plate (7 mm below it)", gx, gy, pcbnew.Dwgs_User, 2.0, 0.3)
ex, ey = L.EPAPER["c"]; mw, mh = L.EPAPER["module"]; rounded_rect(ex - mw / 2, ey - mh / 2, ex + mw / 2, ey + mh / 2, 1.4, pcbnew.Dwgs_User, 0.1); text("WeAct 3.7 e-paper on the plate, its 1x8 lead to J_EPD", ex, ey, pcbnew.Dwgs_User, 1.8, 0.3)
for (x, y) in L.FRAME_BOSSES: circle(x, y, 5.2, pcbnew.Dwgs_User, 0.1)
bx0, by0, bx1, by1 = L.B_OUTLINE; rounded_rect(bx0, by0, bx1, by1, 2.0, pcbnew.Dwgs_User, 0.1); text("PCB-B outline below: deep parts stay outside it (32.42)", 0, by0 + 4.0, pcbnew.Dwgs_User, 1.6, 0.25)
line(-4, 0, 4, 0, pcbnew.Dwgs_User, 0.1); line(0, -4, 0, 4, pcbnew.Dwgs_User, 0.1); text("CASE DATUM (0,0)", 0, -6.5, pcbnew.Dwgs_User, 1.2, 0.2)
# ---------------------------------------------------------------- legends on the board itself (the face legends are laser marked on the plate)
PHASE = "C6"
text("PCB-C %s BACKER  -  under the face plate  -  MESHSAT-709/505  -  2026-09-05" % PHASE, 0, y0 + 4.0, pcbnew.F_SilkS, 2.0, 0.3)
text("UNDERSIDE: ribbon J_PANEL, e-paper lead J_EPD, MAIN / PI lands, switch and sounder leads on their lands, the drivers on the right strip", 0, y0 + 8.0, pcbnew.B_SilkS, 1.6, 0.25, mirror=True)
text("LEFT: SOS, EMCON, ZEROIZE, LIGHT", x0 + 23, y1 - 5.0, pcbnew.F_SilkS, 1.6, 0.25); text("RIGHT: MAIN, PI, TEST, status LEDs", x1 - 23, y1 - 5.0, pcbnew.F_SilkS, 1.6, 0.25)
pcbnew.SaveBoard(OUT, board)
s = open(OUT).read().replace('(paper "A4")', '(paper "A2")'); open(OUT, "w").write(s)
print("saved", OUT, "outline U %.0f x %.0f, void %s, standoffs %d" % (x1 - x0, y1 - y0, VOID, len(L.STANDOFFS)))
