#!/usr/bin/env python3
"""Generate every rule document from the canonical registry (MESHSAT-862, 16 September 2026).

`pcb_rules.yaml` and `pcb_rules_coverage.yaml` are the authorities; the documents under v2/docs/ are their
rendering. Nothing here is hand-maintained: `--check` regenerates into memory and refuses a file on disk that
differs, which is what keeps a reader's document and the machine's registry the same thing.

  rules_render.py            write the documents
  rules_render.py --check    refuse if any document on disk differs from what the registry renders (exit 1)

Documents:
  v2/docs/PCB-GOLDEN-RULES.md      the rulebook, by domain
  v2/docs/PCB-RULE-COVERAGE.md     rule -> implementation, verification, fixtures, maturity
  v2/docs/PCB-GAP-REGISTER.md      the gaps, by category, with remediation, owner and effort
  v2/docs/PCB-ETA.md               the computed ETA from those remediations and the measured run history
  v2/docs/PCB-PROTOTYPE-UNKNOWNS.md what only hardware can decide, so it never reads as a pass
  v2/docs/PCB-RULE-STATUS-<L>.md   per board, from out/rule-audit/<L>.json when it exists
"""
import os, re, sys, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import rules_status as S

DOCS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "v2", "docs")
if not os.path.isdir(DOCS): DOCS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs")
GAP_ORDER = ("ABSENT", "GENERATED_ONLY", "PROSE_ONLY", "NO_BEHAVIOURAL_TEST", "NO_PROTOCOL",
             "DUPLICATED_OR_STALE", "HEURISTIC_AS_LAW", "SOURCE_OR_APPLICABILITY_UNRESOLVED",
             "CROSS_BOARD_INCONSISTENT", "NONE")
HEAD = ("<!-- GENERATED by tools/rules_render.py from tools/pcb_rules.yaml and tools/pcb_rules_coverage.yaml.\n"
        "     Do not edit: `python3 tools/rules_render.py --check` refuses a hand-edited copy, and the suite runs it. -->\n")


def _wrap(s, width=110, indent=""):
    words = " ".join(str(s or "").split()); out, line = [], indent
    for w in words.split(" "):
        if len(line) + len(w) + 1 > width: out.append(line.rstrip()); line = indent
        line += w + " "
    out.append(line.rstrip())
    return "\n".join(x for x in out if x.strip())


def rulebook(reg, cov):
    L = [HEAD, "# The PCB golden rules\n",
         _wrap("Every rule this project holds a board to, with its authority, its applicability, how it is "
               "verified and what its verification is currently worth. Generated from the registry: the "
               "registry is the authority and this page is its rendering."), "",
         "Registry version **%s**, fingerprint **%s**, %d rules over %d domains.\n"
         % (reg.get("registry_version"), R.fingerprint(reg), len(reg["rules"]), len({r["domain"] for r in reg["rules"]})),
         "## How to read a rule\n",
         _wrap("`BLOCKER` stops a release, `MUST_JUSTIFY` needs a written reason, `ADVISORY` informs. "
               "`SOURCE_UNVERIFIED` means the limit's authority is not on file, which is not the same as the "
               "rule being wrong: it means nobody can check it. A `HEURISTIC` may never be a blocker; where "
               "one is doing a blocker's work today it is written as a screen under the principle it screens for."), ""]
    for dom in R.DOMAINS:
        rs = [r for r in reg["rules"] if r["domain"] == dom]
        if not rs: continue
        L.append("## %s\n" % dom.replace("_", " ").title())
        for r in rs:
            c = cov.get(r["id"]) or {}
            L.append("### %s  %s\n" % (r["id"], r["short_name"]))
            L.append(_wrap(r["requirement"]) + "\n")
            L.append("| | |\n|---|---|")
            L.append("| classification | %s |" % r["classification"])
            L.append("| applies | %s%s |" % (r["applicability"].replace("_", " ").lower(),
                                             ("" if r["applicability"] == "UNIVERSAL_FOR_THIS_PROJECT"
                                              else "; boards " + ", ".join(str(b) for b in (r["boards_affected"] or [])))))
            L.append("| release effect | **%s** |" % r["release_effect"])
            L.append("| risk | %s |" % ", ".join(r["risk_class"] if isinstance(r["risk_class"], list) else [r["risk_class"]]))
            L.append("| verified by | %s at %s (%s) |" % (", ".join(r["verification_method"] if isinstance(r["verification_method"], list) else [r["verification_method"]]),
                                                          r["verification_phase"], r["automation_feasibility"].replace("_", " ").lower()))
            L.append("| source | %s |" % r["source_status"])
            for s in (r.get("sources") or []):
                L.append("| | %s, %s%s%s |" % (s.get("title", ""), s.get("issuer", ""),
                                               (", " + s["clause"]) if s.get("clause") else "",
                                               " -- " + s.get("url_or_path", "")))
            L.append("| implementation | %s |" % (c.get("implementation") or r.get("implementation_location")))
            # the coverage map owns the live maturity; the registry keeps only what Phase A assessed before the
            # gate implementations were opened, and the two are printed as the different things they are
            L.append("| maturity | **%s** |  (at writing: %s)" % (c.get("maturity", "UNASSESSED"), r.get("maturity_at_writing", "UNASSESSED")))
            L.append("| owner | %s |" % r["owner"])
            w = r.get("waiver_policy") or {}
            L.append("| waiver | %s |" % ("not waivable" if not w.get("allowed") else
                                          "by %s, scope %s, expires %s" % (w.get("authority"), w.get("scope"), w.get("expiry"))))
            L.append("")
            L.append("**Accept when** " + _wrap(r["acceptance_criteria"]).lstrip() + "\n")
            L.append("**Why** " + _wrap(r["rationale"]).lstrip() + "\n")
            L.append("**If violated** " + _wrap(r["failure_mode"]).lstrip() + "\n")
            if c.get("note"): L.append("**Today** " + _wrap(c["note"]).lstrip() + "\n")
    return "\n".join(L) + "\n"


def coverage_doc(reg, cov):
    by = {r["id"]: r for r in reg["rules"]}
    L = [HEAD, "# Rule coverage\n",
         _wrap("Where each rule is generated, where it is verified, and what that verification is worth. "
               "ENFORCED means an executable gate with a machine-readable verdict and behavioural fixtures; "
               "everything else is a gap and appears in the gap register."), "",
         "| rule | domain | effect | implementation | verification | fixtures | maturity |",
         "|---|---|---|---|---|---|---|"]
    for rid in sorted(cov):
        r = by.get(rid, {}); c = cov[rid]; v = c.get("verification") or {}
        L.append("| %s | %s | %s | %s | %s | %s | **%s** |"
                 % (rid, r.get("domain", ""), r.get("release_effect", ""), c.get("implementation", ""),
                    v.get("tool", "none") + ((" -> " + v["verdict"]) if v.get("verdict") else ""),
                    v.get("fixtures", ""), c.get("maturity", "")))
    counts = {}
    for c in cov.values(): counts[c.get("maturity")] = counts.get(c.get("maturity"), 0) + 1
    L += ["", "## Maturity", "", "| maturity | rules |", "|---|---|"]
    for k in R.MATURITY:
        if counts.get(k): L.append("| %s | %d |" % (k, counts[k]))
    return "\n".join(L) + "\n"


def gap_register(reg, cov):
    by = {r["id"]: r for r in reg["rules"]}
    L = [HEAD, "# Gap register\n",
         _wrap("Every applicable rule this project does not yet verify, by the category of the gap, with what "
               "closing it needs, who decides and the effort estimate. A gap is not a failure of the board: it "
               "is a question nobody has answered yet, made visible so it cannot be forgotten."), ""]
    tot = sum(1 for c in cov.values() if c.get("gap_category") not in (None, "NONE"))
    L.append("**%d of %d rules carry a gap.**\n" % (tot, len(cov)))
    for cat in GAP_ORDER:
        rs = [rid for rid in sorted(cov) if (cov[rid].get("gap_category") or "NONE") == cat]
        if not rs or cat == "NONE": continue
        L.append("## %s (%d)\n" % (cat.replace("_", " ").lower(), len(rs)))
        for rid in rs:
            c = cov[rid]; r = by.get(rid, {}); rem = c.get("remediation") or {}
            L.append("**%s %s** (%s, %s)  " % (rid, r.get("short_name", ""), r.get("release_effect", ""), c.get("maturity", "")))
            L.append(_wrap(c.get("note", ""), indent="") + "  ")
            if rem:
                L.append("*Close it by* %s. Owner **%s**%s. Effort P50 %sh, P80 %sh.\n"
                         % (rem.get("action", ""), rem.get("owner", ""),
                            (", after " + ", ".join(rem.get("depends_on") or [])) if rem.get("depends_on") else "",
                            rem.get("p50_h", "?"), rem.get("p80_h", "?")))
            else: L.append("")
    covered = [rid for rid in sorted(cov) if (cov[rid].get("gap_category") or "NONE") == "NONE"]
    L.append("## covered (%d)\n" % len(covered))
    L.append(_wrap("These rules have an executable gate, a machine-readable verdict and behavioural fixtures: "
                   + ", ".join(covered)) + "\n")
    return "\n".join(L) + "\n"


def board_doc(letter, st, reg, cov):
    m = S.manifest()
    L = [HEAD, "# Rule status: board %s\n" % letter.upper(),
         "Manifest **%s**, rule set **%s**, evidence epoch **%s**.\n"
         % (st.get("manifest_version"), st.get("rule_set_fingerprint"), st.get("evidence_epoch")),
         "**Readiness: %s**\n" % S.gate_state(st["rows"], m),
         # AND THE BOARD THESE NUMBERS ARE ABOUT (17 September 2026). A percentage with no subject is the
         # defect of this whole night one level up: every verdict names the board it was taken on and the page
         # that adds them up named none. Boards A, B and P are judged on a board older than the phase they
         # declare, which is honest evidence about the board this tree holds and unreadable without saying so.
         "Measured on %s.\n" % S.subject_line(st.get("subject") or S.subject(letter, m))]
    hold = R.board_holds().get(letter.lower())
    if hold:
        L += ["> **HELD BY OWNER DECISION %s.** %s" % (hold["decision"], R.hold_banner(hold)), ">",
              "> " + " ".join(str(hold.get("why", "")).split()), ">",
              "> Permitted while held: %s." % " ".join(str(hold.get("permitted", "nothing")).split()), ">",
              "> Forbidden while held: %s." % " ".join(str(hold.get("forbidden", "promotion")).split()), ">",
              "> This lifts when %s." % " ".join(str(hold.get("lifts_when", "the decision is ruled")).split()), ""]
    c = S.counts(st["rows"])
    L += ["| result | rules | percent |", "|---|---|---|"]
    for k in ("PASS", "FAIL", "INCONCLUSIVE", "WAIVED"):
        L.append("| %s | %d | %.1f |" % (k, c[k], c[k.lower() + "_percent"]))
    L += ["| **denominator** | **%d** | 100.0 |" % c["denominator"], "",
          "| rule | effect | phase | result | why |", "|---|---|---|---|---|"]
    for r in st["rows"]:
        L.append("| %s %s | %s | %s | **%s** | %s |" % (r["rule"], r["short_name"], r["release_effect"],
                                                        r["verification_phase"], r["result"],
                                                        " ".join(str(r["why"]).split())[:150]))
    return "\n".join(L) + "\n"


def prototype_doc(reg, cov):
    """SGN-002: the properties that cannot be decided before hardware exists, generated from the registry so
    the list cannot quietly shrink. A prototype-only unknown that is not named reads exactly like a pass."""
    L = [HEAD, "# Prototype-only unknowns\n",
         _wrap("Generated from the registry: every rule verified at the prototype, or whose verification needs a "
               "physical measurement, together with what will decide it. Nothing on this page can be closed by "
               "any amount of work on the boards; each one needs hardware that does not exist yet."), "",
         "| rule | what is unknown | what decides it | owner |", "|---|---|---|---|"]
    n = 0
    for r in reg["rules"]:
        meths = r["verification_method"] if isinstance(r["verification_method"], list) else [r["verification_method"]]
        if r["verification_phase"] != "PROTOTYPE" and "PROTOTYPE_MEASUREMENT" not in meths: continue
        n += 1
        c = cov.get(r["id"]) or {}
        rem = (c.get("remediation") or {}).get("action", "")
        L.append("| %s %s | %s | %s | %s |" % (r["id"], r["short_name"], " ".join(r["failure_mode"].split())[:110],
                                               " ".join(str(rem).split())[:110] or "a measurement on the built board", r["owner"]))
    L += ["", _wrap("%d rule(s) of %d wait on hardware. Nothing has been fabricated or powered, so each of these "
                    "is UNKNOWN rather than passing or failing, and the readiness state says so."
                    % (n, len(reg["rules"]))), ""]
    return "\n".join(L) + "\n"


def bringup_doc(reg, cov):
    """TST-001: how each board is brought up the first time, generated from what the boards themselves declare.

    Nothing here has been fabricated or powered. The first time any of these boards has current through it, the
    order it is brought up in decides whether a wiring error costs a resistor or the board. The sheet is
    GENERATED from each board's intent file, so it cannot describe a rail the board does not have and cannot
    miss one the board does.

    THE ORDER IS BY DEPENDENCY AND NOT BY VOLTAGE. A first draft of this page sorted by voltage ascending, which
    would have had a bench supply put 3.3 V onto board A's logic rail before the 14.4 V pack node that FEEDS the
    converter making it. A derived rail is not applied at all: it appears when its converter is enabled, and the
    step for it is a measurement.

    It is a procedure and not a verification: it says what to do and what to expect, and a person does it.
    """
    ECAD = os.path.dirname(HERE)
    L = [HEAD, "# Bring-up, board by board\n",
         _wrap("Generated from each board's own intent file. NOTHING HERE HAS BEEN FABRICATED OR POWERED: this is "
               "the procedure for the first time, written before there is anything to do it to."), "",
         _wrap("AN INPUT IS APPLIED. A DERIVED RAIL APPEARS. Every input below is brought up from a bench supply "
               "current-limited to the figure in its row, which is the rail's own typical current and not its "
               "peak: a board that draws its peak on the first power-up is telling you something, and a step that "
               "trips the limit is a short until proved otherwise. A derived rail is never applied from the "
               "bench; its step is a measurement at the point named, and a reading outside the tolerance stops "
               "the sequence there."), "",
         _wrap("Tolerance for a first power-up: plus or minus 5 percent of the declared voltage, or the part's "
               "own stated range where that is tighter. A rail that reads zero means its converter is not "
               "enabled, which is a different fault from one that reads low."), ""]
    boards = (R.load().get("manifest") or {}).get("boards", [])
    facts = R.board_facts()
    n_boards = 0
    for letter in boards:
        f = facts.get(letter) or {}
        proj = (f.get("project") or "")
        it = None
        for d in sorted(glob.glob(os.path.join(ECAD, proj + "*", "out", "*-intent.json"))):
            try: it = json.load(open(d)); break
            except ValueError: continue
        L.append("## Board %s" % letter.upper())
        if not it or not it.get("rails"):
            L += ["", _wrap("No intent file in this tree for board %s, so no rail can be listed. This section is "
                            "empty because the data is missing, not because the board has no rails." % letter.upper()), ""]
            continue
        n_boards += 1
        rails = it["rails"]

        def kind(r):
            """input, derived, or ASK: what a rail's declared source says about where it comes from.

            A connector or a fuse is an input; the board receives that rail. A part is a converter output; the
            board makes it. AN INDUCTOR OR A FERRITE IS NEITHER, and pretending otherwise is how a first draft
            of this page told a bench supply to put 3.3 V onto board A's logic rail: L7 is a buck's OUTPUT
            inductor there, and L2 on board E is a filter choke on the incoming 12 V. The tool cannot tell those
            apart from the declaration, so it says so instead of choosing.
            """
            src = str((r or {}).get("source") or "")
            if not src: return "input"
            if src.startswith("J"): return "input"
            if re.match(r"^F\d", src): return "input"
            if re.match(r"^(L|FB)\d", src): return "ask"
            return "derived"

        by = {"input": [], "derived": [], "ask": []}
        for k, v in rails.items(): by[kind(v)].append((k, v))
        for g in by.values(): g.sort(key=lambda kv: float((kv[1] or {}).get("volts") or 0))
        inputs, derived, ask = by["input"], by["derived"], by["ask"]
        L += ["", "**Applied, in this order.**", "",
              "| step | rail | apply | current limit | at | what it feeds |", "|---|---|---|---|---|---|"]
        for n, (net, r) in enumerate(inputs, 1):
            loads = ", ".join(sorted((r.get("loads") or {}).keys())[:6]) or "nothing declared"
            L.append("| %d | %s | %.2f V | %.2f A | %s | %s |"
                     % (n, net.lstrip("/"), float(r.get("volts") or 0), float(r.get("amps_typ") or 0),
                        r.get("source") or "another board or the pack", loads))
        if not inputs:
            L.append("| | | | | | this board receives no rail of its own: it is powered entirely from another board |")
        L += ["", "**Measured, in this order, after the inputs are up.**", "",
              "| step | rail | expect | at | what it feeds |", "|---|---|---|---|---|"]
        for n, (net, r) in enumerate(derived, 1):
            loads = ", ".join(sorted((r.get("loads") or {}).keys())[:6]) or "nothing declared"
            v = float(r.get("volts") or 0)
            L.append("| %d | %s | %.2f V (%.2f to %.2f) | %s | %s |"
                     % (n, net.lstrip("/"), v, v * 0.95, v * 1.05, r.get("source") or "?", loads))
        if not derived:
            L.append("| | | | | this board makes no rail of its own |")
        if ask:
            L += ["", "**Decide before powering: the declared source is an inductor or a ferrite, which is a "
                      "filter on an incoming feed on some boards and a converter's output on others.**", "",
                  "| rail | volts | current | source | what it feeds |", "|---|---|---|---|---|"]
            for net, r in ask:
                loads = ", ".join(sorted((r.get("loads") or {}).keys())[:6]) or "nothing declared"
                L.append("| %s | %.2f V | %.2f A | %s | %s |"
                         % (net.lstrip("/"), float(r.get("volts") or 0), float(r.get("amps_typ") or 0),
                            r.get("source"), loads))
        L.append("")
    L += ["", _wrap("%d board(s) have an intent file in this tree and are listed. Every number here is a DESIGN "
                    "figure from the board's own declaration and not a measurement: there is nothing to measure "
                    "yet." % n_boards), ""]
    return "\n".join(L) + "\n"


# Documents that are a pure function of the registry and the coverage map, with no board evidence in them.
# rules_status reads this to judge a VERIFIED_MANUALLY rule whose evidence IS one of these pages: it can
# rebuild the page in memory and compare, which is what makes "the list has not quietly shrunk" a fact rather
# than a habit. The board pages are deliberately absent: they are generated FROM the status, so asking the
# status to check them would be a circle.
SELF_CONTAINED = {"PCB-PROTOTYPE-UNKNOWNS.md": prototype_doc,
                  "PCB-BRING-UP.md": bringup_doc,
                  "PCB-GOLDEN-RULES.md": rulebook,
                  "PCB-RULE-COVERAGE.md": coverage_doc,
                  "PCB-GAP-REGISTER.md": gap_register}


def eta_doc():
    import rules_eta as E
    m = E.model(); items = E.open_items()
    L = [HEAD, "# ETA, computed\n",
         _wrap("Derived from the gap register's remediation entries and the route durations measured in this "
               "tree's own journals. It is regenerated, never typed: change an estimate in the coverage map "
               "and this page changes with it."), "",
         "## Effort, which is not a date\n",
         "| | P50 | P80 |", "|---|---|---|",
         "| engineering effort, one worker | %.0f h | %.0f h |" % (m["engineering_hours"]["p50"], m["engineering_hours"]["p80"]),
         "| the same at %.0f hours a day | %.1f days | %.1f days |" % (m["hours_per_day"], m["engineering_days"]["p50"], m["engineering_days"]["p80"]),
         "| critical path through the dependencies | %.0f h | %.0f h |" % (m["critical_path_hours"]["p50"], m["critical_path_hours"]["p80"]),
         "",
         _wrap("Read the table above as WORK REMAINING and never as a delivery date. The two are different "
               "questions: a rented box runs a route through the night while this session sleeps, several "
               "items that share no file run beside each other, and an owner's ruling takes as long as it "
               "takes whatever else is happening. The elapsed figures are below."), "",
         "## How the open work executes\n",
         "| class | items | P50 | P80 | what it means |", "|---|---|---|---|---|"]
    for c, v in sorted(m["by_execution"].items(), key=lambda kv: -kv[1]["p50_h"]):
        if not v["items"]: continue
        L.append("| %s | %d | %.0f h | %.0f h | %s |" % (c, v["items"], v["p50_h"], v["p80_h"], E.EXECUTION[c]))
    L += ["",
         "## Elapsed, at %d session worker(s) and %d rented box(es)\n" % (m["width"]["agents"], m["width"]["boxes"]),
         "| | P50 | P80 |", "|---|---|---|",
         "| session pool | %.1f days | %.1f days |" % (m["pools"]["p50"]["session_pool_days"], m["pools"]["p80"]["session_pool_days"]),
         "| fleet pool | %.1f days | %.1f days |" % (m["pools"]["p50"]["box_pool_days"], m["pools"]["p80"]["box_pool_days"]),
         "| longest dependency chain | %.1f days | %.1f days |" % (m["critical_path_days"]["p50"], m["critical_path_days"]["p80"]),
         "| **design package ready for prototype** | **%.1f days** | **%.1f days** |" % (m["design_package_days"]["p50"], m["design_package_days"]["p80"]),
         "",
         "## The programme, cumulative elapsed days from the day this page was generated\n",
         "| milestone | P50 | P80 | where the number comes from |", "|---|---|---|---|"]
    for st in m["milestones"]:
        L.append("| %s | %.0f days | %.0f days | %s |" % (st["stage"], st["cumulative_p50_days"],
                                                          st["cumulative_p80_days"], st["source"]))
    L += ["",
         _wrap("Only the first milestone is computed from this project's own register. Every stage after it is "
               "a vendor's published figure or this session's declared estimate, and NONE of them has been "
               "measured here, because nothing has been ordered. The basis of each is in "
               "`v2/ecad/tools/pcb_programme_stages.yaml` beside its number."), "",
         _wrap("%d open item(s): %d are work and %d are waits on the owner, a vendor or a standard. "
               "Waits are not engineering time and are listed separately below." % (m["open_items"], m["session_items"], m["wait_items"])), "",
         "## Waits, which no amount of engineering shortens\n",
         "| rule | what it needs | owner |", "|---|---|---|"]
    for w in m["owner_waits"]:
        L.append("| %s | %s | %s |" % (w["rule"], w["action"], next((i["owner"] for i in items if i["rule"] == w["rule"]), "")))
    L += ["", "## Measured route history\n",
          _wrap("Route durations this tree has recorded, in minutes per attempt: median %s, worst %s, over %d board(s). "
                "A board's re-route is elapsed time, not engineering time, and several run at once on the rented box."
                % (m["route_history"]["median_minutes"], m["route_history"]["worst_minutes"], len(m["route_history"]["boards"]))), "",
          "## Assumptions\n"]
    for a in m["assumptions"]: L.append("- " + a)
    L += ["", _wrap("This estimate covers making every applicable rule verified. It does not cover prototype "
                    "manufacture, assembly or physical validation, none of which can start before the set is "
                    "ordered, and it is separate from the question of when the seven boards pass the gates that "
                    "exist today."), ""]
    return "\n".join(L) + "\n"


def render(out_dir=None, board_docs=True, generated=True):
    """The documents, as a path -> body map.

    TWO GROUPS, and the split is not cosmetic. The generated documents are rendered from the registry alone.
    The per-board status pages are rendered from `out/rule-audit/<L>.json`, which `rules_status.py` wrote, and
    two of the rules that audit decides (TST-001 and SGN-002) judge a GENERATED document. So a single pass that
    rewrites a stale bring-up page and renders the status pages in the same breath reports the stale answer:
    the audit it read was taken before the page existed in its current form. `main` writes group one, refreshes
    the audit when group one changed, and only then renders group two."""
    reg = R.load(); cov = S.coverage(); docs = out_dir or DOCS
    files = {} if not generated else {os.path.join(docs, "PCB-GOLDEN-RULES.md"): rulebook(reg, cov),
             os.path.join(docs, "PCB-RULE-COVERAGE.md"): coverage_doc(reg, cov),
             os.path.join(docs, "PCB-GAP-REGISTER.md"): gap_register(reg, cov),
             os.path.join(docs, "PCB-ETA.md"): eta_doc(),
             os.path.join(docs, "PCB-PROTOTYPE-UNKNOWNS.md"): prototype_doc(reg, cov),
             os.path.join(docs, "PCB-BRING-UP.md"): bringup_doc(reg, cov)}
    audit = os.path.join(os.path.dirname(HERE), "out", "rule-audit")
    for f in (sorted(glob.glob(os.path.join(audit, "*.json"))) if board_docs else []):
        letter = os.path.basename(f)[:-5]
        if letter == "summary": continue
        try: st = json.load(open(f))
        except ValueError: continue
        if "rows" not in st: continue          # summary.json and any other non-board artefact in the audit dir
        files[os.path.join(docs, "PCB-RULE-STATUS-%s.md" % letter.upper())] = board_doc(letter, st, reg, cov)
    return files


def _write(files):
    """Write each body, return the paths that actually changed."""
    changed = []
    for p, body in sorted(files.items()):
        old = open(p, encoding="utf-8").read() if os.path.exists(p) else None
        if old == body: continue
        os.makedirs(os.path.dirname(p), exist_ok=True)
        open(p, "w", encoding="utf-8").write(body)
        print("rules_render: wrote %s (%d lines)" % (os.path.relpath(p), body.count("\n")))
        changed.append(p)
    return changed


def _refresh_audit():
    """Re-run the readiness computation so the status pages read an audit taken AFTER the pages it judges.

    It is the same call a sweep makes, with its stdout put aside: this is a rendering step, not a second
    opinion, and printing a whole readiness table in the middle of a document run would read as one."""
    import io, contextlib
    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf): S.main([])
        return True
    except BaseException as e:                     # a SystemExit here is a failure to refresh, not a refusal
        print("rules_render: the audit could not be refreshed (%s: %s); the status pages below are rendered "
              "from the audit as it stands" % (type(e).__name__, str(e)[:80]))
        return False


def main(argv):
    if "--check" in argv:
        files = render()
        bad = [p for p, body in files.items() if not os.path.exists(p) or open(p).read() != body]
        for p in bad: print("rules_render: %s differs from what the registry renders" % os.path.relpath(p))
        print("rules_render: %d document(s), %d out of date" % (len(files), len(bad)))
        return 1 if bad else 0
    # Group one: the documents the registry alone decides, two of which rules judge.
    changed = _write(render(board_docs=False))
    # Group two: the per-board status pages, from an audit taken after group one was written.
    if changed and "--no-refresh" not in argv: _refresh_audit()
    _write(render(generated=False))
    return 0


if __name__ == "__main__": sys.exit(main(sys.argv[1:]))
