#!/usr/bin/env python3
"""Compute each board's result for every rule that applies to it, and the readiness state of the set
(MESHSAT-862, 16 September 2026; owner instruction of 16 September 00:30).

Every applicable rule-board pair gets exactly one of PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE, and
the rule that makes this worth reading is: **absence is never a pass**. A missing verdict file, a verdict
older than the evidence epoch, a verdict taken under a different rule-set fingerprint or a different board,
a rule with no implementation, a rule whose authority is unverified, a rule whose owner decision is open:
each of those is INCONCLUSIVE, and an INCONCLUSIVE blocker keeps the set out of READY_FOR_PROTOTYPE.

Where a result comes from:
  * the registry says whether the rule applies to this board (rules_lib.rules_for);
  * the coverage map says which tool verifies it and which verdict file carries the evidence;
  * the verdict file, if it exists in the board's project `out/` or its `routed/` snapshot, carries the
    result, the denominator and its own inputs;
  * the readiness manifest says what evidence is current (the epoch) and whether promotion is frozen.

Percentages: four numbers over ONE denominator (the applicable rule-board pairs required at the phase being
reported), summing to 100 subject to rounding. The gate state is printed BEFORE them, and the WITH_WAIVERS
qualifier cannot be hidden by any of them. The project aggregate sums rule-board pairs; it never averages
board percentages.

Usage:
  rules_status.py [--board <letter>] [--phase <SCHEMATIC|PLACED_BOARD|ROUTED_BOARD|RELEASE_PACKAGE>]
                  [--out-dir out/rule-audit] [--json]

The per-board markdown is generated by rules_render.py from the JSON this writes; this tool computes and
never formats a document.
"""
import os, sys, re, json, glob, time, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import verdict as _v

ECAD = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "readiness_manifest.json")
COVERAGE = os.path.join(HERE, "pcb_rules_coverage.yaml")
PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE = "PASS", "FAIL", "INCONCLUSIVE", "WAIVED", "NOT_APPLICABLE"
PHASE_ORDER = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE", "ASSEMBLY", "PROTOTYPE")
PRE_FAB = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE")


def manifest(path=None):
    return json.load(open(path or MANIFEST))


def coverage(path=None):
    return (R._yaml().safe_load(open(path or COVERAGE)) or {}).get("coverage", {})


def _project_dirs(letter, m):
    """Where a board's evidence can be: its phase directory's out/ and routed/, plus the SET-LEVEL out/ where
    the across-the-set gates write (the final gate, the contracts and the parts certification judge the whole
    manifest at once, and their verdict is evidence for every board in it).

    THE PHASE DIRECTORY, NOT EVERY DIRECTORY WHOSE NAME BEGINS WITH THE PROJECT'S (26 September 2026, MESHSAT-1357,
    found by the regeneration parity run of 25 September). This globbed `<project>*`, so board A's evidence included `pcb-a-power/` (the A18 board of
    the generation before) beside `pcb-a-power-a23/`, and every legacy directory of every board was read. No
    verdict sat in one on that day (613 tracked and 784 in the main checkout were read), so no reading moved; the
    directory is now the one the board's routeflow profile names, which `_phase_dir` already reads."""
    d = _phase_dir(letter, m)
    out = [os.path.join(d, "out"), os.path.join(d, "routed"), os.path.join(ECAD, "out")]
    return [x for x in out if os.path.isdir(x)]


_FP_NOW = [None]


def _fingerprint_now():
    """The rule set this tree carries, read once. Used to keep a verdict taken under an older one from
    standing in front of a current reading."""
    if _FP_NOW[0] is None:
        try: _FP_NOW[0] = R.fingerprint(R.load()) or ""
        except BaseException: _FP_NOW[0] = ""
    return _FP_NOW[0]


# Every time a reading that declares a missing input is preferred over one that HAD its input, because its
# rule-set fingerprint is current and the other's is not. Reported at the end of a run; it decides nothing.
_DISPLACED = []


def _had_its_input(rec):
    """Did this verdict have the thing it judges? `verdict.write(missing_input=...)` is a tool saying it did
    not: no rotation table in this tree, no order folder, no netlist."""
    return not (rec.get("missing_input") or "")


def _current_reading(rec):
    """Is this verdict taken under the rule versions this tree carries NOW? True, False, or None when the
    tree cannot say at all because its own registry will not load.

    ASKED RULE BY RULE WHERE THE VERDICT ALLOWS IT, which is how `_fresh` has judged freshness since 17
    September and how the selection above it did NOT ask until now (19 September 2026). A verdict names the
    rules it decides and carries a digest of each of them; the SET fingerprint moves whenever anything
    anywhere in the registry does, so a measurement whose own rules never changed was reading as history at
    the moment two verdicts were compared, and could lose its place to a newer reading that declares it had
    no input at all. That is not a hypothetical: board A's ANA-001 is measured at FAIL 15 of 24 under a
    superseded SET fingerprint while carrying the CURRENT digest of ANA-001, and five of the seven boards'
    sensitive-node readings are in exactly that state tonight.

    A verdict with NO per-rule digest is judged by the set fingerprint exactly as before, which is every
    verdict written before 17 September; so is one whose named rules have all left the registry, because a
    digest of a rule that no longer exists answers nothing. A verdict is current only if EVERY rule it names
    is current, because this answer is given once for a reading that several rules will read."""
    _fp = _fingerprint_now()
    if not _fp: return None
    _per = ((rec.get("policy") or {}).get("rule_fingerprints") or {})
    _asked = [(rid, d) for rid, d in _per.items() if _rule_digest(rid)]
    if _asked: return all(d == _rule_digest(rid) for rid, d in _asked)
    return (((rec.get("policy") or {}).get("rule_set_fingerprint")) or "") == _fp


def _supersedes(new, old):
    """Does `new` replace `old` as this board's reading of that tool?

    Newest wins, with ONE exception, which is this project's own rule written where every tool meets it: A
    READING TAKEN WITH LESS INPUT NEVER REPLACES ONE TAKEN WITH MORE. A verdict that declares its input absent
    is a statement about the tree it ran in and not about the boards, and the only reason it ever won was its
    timestamp: a sweep tree carries no `v2/release/revA/order/`, so `doc_provenance` there reads 0 documents of
    0 folders and writes an INCONCLUSIVE that is newer than the runner's reading of the seven real ones. It
    stood in front of it on boards D, E, E5 and P, which read "nobody has checked" about documents that are
    sitting on this disk being untraceable (17 September 2026).

    It can never turn a failure into a pass: the reading it protects is whatever was measured, pass or fail,
    and it is still judged for freshness, fingerprint and board identity afterwards like any other."""
    # HISTORY NEVER STANDS IN FRONT OF A CURRENT READING (17 September 2026). The rule above protects a
    # reading that HAD its input, and on 17 September it protected a stale one: board A's parts were last
    # certified under rule set 8087c341, before the applicability correction, from a folder of a board this
    # tree does not hold; the fresh reading says so with `missing_input` and was refused for saying it. A
    # verdict taken under a superseded rule set is not evidence at all (`_fresh` refuses it wherever it is
    # read), so it cannot be the thing that keeps a current reading out. Fingerprint first, then input.
    _n_ok, _o_ok = _current_reading(new), _current_reading(old)
    if _n_ok is not None and _n_ok != _o_ok:
        # AND IT SAYS SO WHEN IT DOES THIS, because the page can otherwise change under the reader with
        # nothing on it to show why (19 September 2026). A gate run by hand on a host without pcbnew wrote a
        # reading with its missing input declared and the CURRENT fingerprint; board A's measured ANA-001,
        # taken under a superseded SET fingerprint while carrying the current digest of ANA-001 itself, lost
        # to it by this branch and the readiness page went from FAIL 15 of 24 to INCONCLUSIVE with nothing
        # said. The question is asked rule by rule now (`_current_reading`), which is what closes that case;
        # the announcement stays, because the ladder can still prefer a no-input reading over a measured one
        # whose own rules really did move, and a reader is owed the sentence when it does.
        if _n_ok and not _had_its_input(new) and _had_its_input(old):
            _DISPLACED.append((str(new.get("name") or new.get("tool") or "?"),
                               " ".join(str(new.get("missing_input") or "").split())[:120],
                               str((old.get("policy") or {}).get("rule_set_fingerprint") or "")[:16]))
        return _n_ok
    if _had_its_input(old) and not _had_its_input(new): return False
    if _had_its_input(new) and not _had_its_input(old): return True
    return str(new.get("ts", "")) >= str(old.get("ts", ""))


def _verdicts(letter, m):
    """{name: record} of every verdict file the board has, newest wins (see _supersedes for the one exception)."""
    found = {}
    for d in _project_dirs(letter, m):
        for f in sorted(glob.glob(os.path.join(d, "*.verdict.json"))):
            try: rec = json.load(open(f))
            except ValueError: continue
            name = rec.get("name") or os.path.basename(f)[:-len(".verdict.json")]
            prev = found.get(name)
            if prev is None or _supersedes(rec, prev): rec["_path"] = f; found[name] = rec
    return found


def _instant(s):
    """One instant from either clock. A verdict writes UTC without an offset and the manifest's epoch carries
    one: comparing the two as strings made a verdict written at 23:16 UTC look older than an epoch of
    00:35+02:00, which is the same moment as 22:35 UTC (found 16 September 2026, the first time the status
    was asked to read current evidence). Times are compared as instants here, never as text."""
    import datetime as _dt
    t = (s or "").strip().replace("Z", "+00:00")
    try: d = _dt.datetime.fromisoformat(t)
    except ValueError:
        try: d = _dt.datetime.fromisoformat(t[:19])
        except ValueError: return None
    if d.tzinfo is None: d = d.replace(tzinfo=_dt.timezone.utc)   # a verdict writes UTC without saying so
    return d


def _board_identities(letter, m):
    """{sha256_16} of every board file this letter's project directories hold, plus the letter itself.

    A verdict says which board it was taken on. Nothing compared it with the board being judged, so a verdict
    about ANOTHER board counted as this board's evidence: board A's `fab_limits` and board E's `port_protect`
    are both sitting in the SET-LEVEL out/, which every board reads, and only their timestamps kept the right
    one winning (16 September 2026). Identity is cheap and does not depend on who wrote a file where.
    """
    out = {str(letter).lower()}
    # The board file is NAMED, never searched for: one project directory holds one board and its name is the
    # project's, so the path is constructed. A tool that globs a directory for a board is the 11 September
    # trap (it takes whichever board ran last), and this collects identities rather than picking one, but the
    # rule that forbids the glob is right to make no exception it cannot see.
    name = ((R.board_facts().get(letter) or {}).get("project") or "")
    if not name: return out
    # A RETIRED BOARD IS NOT AN IDENTITY (26 September 2026, MESHSAT-1357). The phase directory's own board is one. A
    # board saved in its out/ or routed/ is one only when its silk carries the phase the board DECLARES: the E9
    # board still sits in pcb-e1-dock-e7/routed/ while board E declares E17, and it was an identity, so a verdict
    # taken on E9 would have read as current evidence for E17. Before this, every `<project>*` directory's board
    # was one too (see _project_dirs).
    d = _phase_dir(letter, m)
    try: raw = open(os.path.join(d, name + ".kicad_pcb"), "rb").read(); out.add(hashlib.sha256(raw).hexdigest()[:16])
    except OSError: pass
    decl = _declared_phase(letter)
    for f in (os.path.join(d, "routed", name + ".kicad_pcb"), os.path.join(d, "out", name + ".kicad_pcb")):
        try: raw = open(f, "rb").read()
        except OSError: continue
        if decl and decl.upper() in _legend_phases(raw.decode("utf-8", "replace"), letter):
            out.add(hashlib.sha256(raw).hexdigest()[:16])
    return out


def _declared_phase(letter):
    """The phase the board table declares for this letter, or None."""
    try: return (json.load(open(os.path.join(HERE, "boards", "%s.json" % letter), encoding="utf-8")) or {}).get("phase")
    except (OSError, ValueError): return None


def _legend_phases(text, letter):
    """Every phase token (the board's letter and one to three digits) in a board file's silk legends."""
    tok = re.compile(r"\b(%s\d{1,3})\b" % re.escape(letter.upper()[0]))
    seen = set()
    for t in _LEGEND.findall(text): seen |= set(tok.findall(t))
    return seen


_LEGEND = re.compile(r'\(gr_text "([^"]*)"')


def _phase_dir(letter, m):
    """The project directory of the phase this board declares, read from the letter's routeflow profile the
    way `check_contracts.netlist_path` reads it, never guessed from a timestamp."""
    stem = (m["boards"].get(letter) or {}).get("project", "")
    for pf in sorted(glob.glob(os.path.join(HERE, "routeflow", "*.json"))):
        try: p = json.load(open(pf, encoding="utf-8"))
        except ValueError: continue
        if p.get("board") != stem: continue
        d = os.path.join(ECAD, os.path.basename(str(p.get("project", "")).rstrip("/")))
        if os.path.isdir(d): return d
    return os.path.join(ECAD, stem)


def subject(letter, m=None):
    """WHICH BOARD IS THIS COLUMN ABOUT (17 September 2026).

    A percentage with no subject is the shape of defect this whole night has been about, one level up: every
    verdict now names the board it was taken on, and the STATUS that adds them up named none. Board A reads
    28 of 50 verified and the board in its phase directory carries the legend A32, four phases behind the A36
    its own declaration names and behind the A40 and A41 that are routing tonight; board B reads 14 and its
    board is B19, the design whose missing PCIe coupling capacitors are the reason B21 exists. Both are honest
    readings OF THE BOARD THIS TREE HOLDS, and a reader could not tell which board that was.

    The phase is read from the board's own silk, which is where `silk_fix_all.py` stamps it and where
    `verify_deliverable` reads it to refuse a folder stamped with a sibling's phase. A board that carries no
    phase legend says so rather than being assumed current."""
    m = m or manifest()
    stem = (m["boards"].get(letter) or {}).get("project", "")
    decl = None
    try: decl = (json.load(open(os.path.join(HERE, "boards", "%s.json" % letter), encoding="utf-8")) or {}).get("phase")
    except (OSError, ValueError): pass
    d = _phase_dir(letter, m)
    f = os.path.join(d, stem + ".kicad_pcb")
    out = {"dir": os.path.relpath(d, ECAD), "board": None, "sha256_16": None, "legend_phase": None,
           "declared_phase": decl, "agrees": None}
    try: raw = open(f, "rb").read()
    except OSError: return out
    out["board"] = os.path.relpath(f, ECAD)
    out["sha256_16"] = hashlib.sha256(raw).hexdigest()[:16]
    tok = re.compile(r"\b(%s\d{1,3})\b" % re.escape(letter.upper()[0]))
    seen = set()
    for t in _LEGEND.findall(raw.decode("utf-8", "replace")): seen |= set(tok.findall(t))
    if decl and decl.upper() in seen: out["legend_phase"] = decl.upper()
    elif seen: out["legend_phase"] = sorted(seen)[-1]
    out["agrees"] = (None if not seen or not decl else (decl.upper() in seen))
    return out


def subject_line(su):
    """One clause for the per-board line and the generated page."""
    if not su.get("board"): return "no board file in %s" % su.get("dir")
    who = su.get("legend_phase") or "no phase legend"
    s = "board %s (%s, %s)" % (who, su["dir"], su["sha256_16"])
    if su.get("declared_phase"):
        s += ", declares %s" % su["declared_phase"]
        if su.get("agrees") is False:
            s += ": THIS TREE HOLDS NO BOARD AT THE DECLARED PHASE"
    return s


def _named_board(rec):
    """What board does this verdict say it was taken on, if it says at all? Either a {path, sha256_16} block
    or a bare string; a verdict that names none is judged on its other properties."""
    b = (rec.get("inputs") or {}).get("board")
    if isinstance(b, dict): return b.get("sha256_16")
    if isinstance(b, str) and b.strip(): return b.strip().lower()
    return None


_RULE_FPS = [None]


def _rule_digest(rid):
    """Today's digest of one rule's demands, or "" if the registry cannot be read."""
    if _RULE_FPS[0] is None:
        try:
            import rules_lib as _r; _RULE_FPS[0] = _r.rule_fingerprints()
        except BaseException: _RULE_FPS[0] = {}
    return (_RULE_FPS[0] or {}).get(rid, "")


def _fresh(rec, m, fingerprint, identities=None, rule=None):
    """(ok, why): is this verdict current evidence? The epoch, the rule's own demands and the BOARD are the
    identity; a verdict from before the audit, or about a different board, is history rather than a decision.

    RULE BY RULE WHERE THE VERDICT ALLOWS IT (17 September 2026). A verdict names the rules it decides and now
    carries a digest of each of them, so a reading is stale when THE RULE IT DECIDES changed rather than when
    anything anywhere in the registry did. Correcting ten board lists this afternoon marked three hundred
    readings stale and fifteen of them were about the rules that moved. A verdict with no per-rule digest is
    judged by the set fingerprint exactly as before, which is every verdict written before this change."""
    ts = str(rec.get("ts", ""))
    epoch_s = str(m.get("evidence", {}).get("epoch", ""))
    if not ts: return False, "the verdict carries no timestamp"
    t, e = _instant(ts), _instant(epoch_s)
    if t is None: return False, "the verdict's timestamp %r cannot be read" % ts[:25]
    if e is not None and t < e: return False, "PRE_AUDIT: taken %s, before the evidence epoch %s" % (ts[:19], epoch_s[:19])
    got = (rec.get("policy") or {}).get("rule_set_fingerprint") or rec.get("rule_set_fingerprint")
    rid = (rule or {}).get("id")
    mine = ((rec.get("policy") or {}).get("rule_fingerprints") or {}).get(rid) if rid else None
    if mine:
        now_d = _rule_digest(rid)
        if now_d and mine != now_d:
            return False, "taken under a different version of %s (%s, current is %s)" % (rid, mine, now_d)
        if now_d:
            if identities and _named_board(rec) and _named_board(rec) not in identities:
                return False, "taken on board %s, which is not a board this project directory holds" % str(_named_board(rec))[:20]
            return True, "current"
    if fingerprint and got and got != fingerprint: return False, "taken under rule set %s, current is %s" % (got, fingerprint)
    if fingerprint and not got: return False, "the verdict does not name the rule set it was taken under"
    nb = _named_board(rec)
    if identities and nb and nb not in identities:
        return False, "taken on board %s, which is not a board this project directory holds" % str(nb)[:20]
    return True, "current"


_DOC_CACHE = {}


def _document_current(rel, sha=None):
    """A document is evidence only while it is still the one that was verified.

    A GENERATED page is rebuilt in memory from the registry and compared with the file. A hand edit, a rule
    added to the registry after the page was last written, or a deleted row all read as INCONCLUSIVE, because
    a list of unknowns that has quietly shrunk looks exactly like a list of unknowns that is complete.

    A HAND-WRITTEN RECORD cannot be rebuilt, and until 21 September 2026 that meant it could never be current:
    the manual-verification path answered "not a document this tool can rebuild, so it cannot be checked" and
    ENV-001 stayed INCONCLUSIVE on all seven boards the hour its envelope was adopted, which is a rule refusing
    the only kind of evidence its own maturity is named for. Such a record is pinned by CONTENT instead: the
    coverage entry carries `verified_sha`, the sha256 of the file as it was when a person verified it, and any
    later edit takes the verification away rather than inheriting it. A record with no pin is still not
    evidence, because "somebody read it once" is not a record.
    """
    key = (rel, sha)
    if key in _DOC_CACHE: return _DOC_CACHE[key]
    name = os.path.basename(rel)
    path = os.path.join(ECAD, "..", "docs", name)
    try:
        import rules_render as RR                       # imported here: rules_render imports this module
        fn = RR.SELF_CONTAINED.get(name)
        if fn is None:
            if not os.path.exists(path):
                out = (False, "the record %s does not exist" % name)
            elif not sha:
                out = (False, "%s is a hand-written record and the coverage map pins no verified_sha for it, "
                              "so nothing says WHICH text was verified" % name)
            else:
                import hashlib
                got = hashlib.sha256(open(path, "rb").read()).hexdigest()
                out = ((True, "%s is the record that was verified (sha %s)" % (name, got[:16])) if got == sha
                       else (False, "%s has CHANGED since it was verified (pinned %s, now %s): re-verify it or "
                                    "put the pin back" % (name, str(sha)[:16], got[:16])))
        elif not os.path.exists(path):
            out = (False, "the record %s does not exist" % name)
        else:
            want = fn(R.load(), coverage())
            have = open(path, errors="replace").read()
            out = ((True, "%s is current with the registry" % name) if want == have
                   else (False, "%s differs from the registry it is generated from: regenerate it" % name))
    except Exception as e:
        # A DOCUMENT THAT REFUSES TO RENDER HERE NAMES ITS MISSING INPUT rather than hiding behind a type name:
        # `PCB-BRING-UP.md` is generated from each board's untracked intent file and cannot be rebuilt on a host
        # that has none. It is not a pass either way, which is the point (18 September 2026).
        out = (False, "%s could not be checked (%s%s)" % (name, type(e).__name__,
                                                          ": " + str(e) if type(e).__name__ == "MissingInput" else ""))
    _DOC_CACHE[key] = out
    return out


# The verdict that says whether a board IS routed. A rule verified at ROUTED_BOARD is judged on the board this
# tree holds, and for a board still in its route that board is the PLACED one.
ROUTE_GATE = "hardset-routed-board-gate"


def _unrouted(vs, m=None, fingerprint=None, identities=None):
    """(n, why) from the routed-board gate's own count, or (0, "") when it has not run or is not current.

    A BOARD THAT IS NOT ROUTED HAS NOT FAILED THE RULES THAT NEED A ROUTED BOARD (17 September 2026). Board B
    is mid-route: the board committed in its phase directory is the placed one, 499 connections open and every
    one of its six zones carrying zero filled area, because the fill happens in the finish. Judged against it,
    the return-path rule read 214 nets of 566 without a reference (the same tool on the same board, with the
    zones filled in memory, reads ONE net over by 0.6 mm), the return-via rule read 204 signal vias without a
    ground via, and the via-current rule read 19 rails over their barrels. None of those is a property of the
    design. They are what a board looks like before it is finished, reported as defects, on the board of the
    set that most needs an honest reading.

    So a ROUTED_BOARD rule on an unrouted board is INCONCLUSIVE, which still blocks promotion: absence is never
    a pass, and neither is prematurity a failure. The rules that measure the ROUTE ITSELF keep their result,
    because "nothing unrouted" is exactly what they are there to say."""
    rec = vs.get(ROUTE_GATE)
    if not rec: return 0, ""
    # AND IT HAS TO BE CURRENT EVIDENCE ITSELF. A stale routed-board gate, taken on a board this phase no
    # longer holds, would otherwise suppress every routed-board rule on a board that IS routed: the guard is
    # only allowed to speak when the reading it speaks from is one this computation would accept anywhere else.
    if m is not None:
        ok, _why = _fresh(rec, m, fingerprint, identities)
        if not ok: return 0, ""
    n = (rec.get("counts") or {}).get("unrouted")
    if not n: return 0, ""
    return n, ("the board this tree holds for this phase is not routed (%s reports %d unrouted connection(s)), "
               "so a rule verified on a routed board has nothing current to be judged against" % (ROUTE_GATE, n))


def result_for(rule, letter, cov, vs, m, fingerprint, phase=None, identities=None):
    """One rule on one board. Everything that is not a positive, current PASS is INCONCLUSIVE or FAIL."""
    rid = rule["id"]; c = cov.get(rid) or {}
    if phase and rule["verification_phase"] not in _phases_up_to(phase):
        return dict(result=NOT_APPLICABLE, why="verified at %s, later than the phase being reported" % rule["verification_phase"], evidence=None)
    w = (c.get("waiver") or {})
    if w.get("active"):
        return dict(result=WAIVED, why="waived by %s until %s: %s" % (w.get("authority"), w.get("expiry"), w.get("reason", "")), evidence=w.get("evidence"))
    if c.get("maturity") in ("OPEN", "DOCUMENTED_ONLY"):
        return dict(result=INCONCLUSIVE, why="no verification: %s" % c.get("note", "")[:160], evidence=None)
    if c.get("maturity") == "SOURCE_UNVERIFIED":
        return dict(result=INCONCLUSIVE, why="the authority behind this rule's limit is not established: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "OWNER_DECISION_REQUIRED":
        return dict(result=INCONCLUSIVE, why="an owner decision is open: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "VERIFIED_MANUALLY":
        doc = (c.get("verification") or {}).get("document")
        if not doc:
            return dict(result=INCONCLUSIVE, why="a manual verification with no record is not evidence", evidence=None)
        ok, why = _document_current(doc, c.get("verified_sha"))
        return (dict(result=PASS, why=why, evidence=doc) if ok
                else dict(result=INCONCLUSIVE, why=why, evidence=doc))
    if c.get("maturity") == "GENERATED_ONLY":
        return dict(result=INCONCLUSIVE, why="generation intends to comply and nothing verifies it: %s" % c.get("note", "")[:140], evidence=None)
    raw = (c.get("verification") or {}).get("verdict")
    if not raw:
        return dict(result=INCONCLUSIVE, why="the coverage map names no verdict for an enforced rule", evidence=None)
    # A RULE MAY BE VERIFIED BY MORE THAN ONE TOOL, and several are: a placement is judged both by the DRC on
    # the placed board and by the escape-fan predictor, and a part is judged both by the code the BOM carries
    # and by asking the fabricator whether that code is the part. Where a rule names several, the WORST result
    # decides, because a rule is satisfied only when every tool that verifies it says so.
    names = [n.strip().replace("<letter>", letter) for n in str(raw).split(",") if n.strip()]
    if rule["verification_phase"] == "ROUTED_BOARD" and ROUTE_GATE not in names:
        n_un, why_un = _unrouted(vs, m, fingerprint, identities)
        if n_un: return dict(result=INCONCLUSIVE, why=why_un, evidence=(vs.get(ROUTE_GATE) or {}).get("_path"))
    worst = None
    for name in names:
        rec = vs.get(name)
        if rec is None:
            r = dict(result=INCONCLUSIVE, why="no %s verdict for this board" % name, evidence=None)
        else:
            ok, why = _fresh(rec, m, fingerprint, identities, rule)
            if ok:
                ok, why = _after_meaning_changed(rec, name, c, letter)
            if not ok:
                r = dict(result=INCONCLUSIVE, why=why, evidence=rec.get("_path"))
            elif rec.get("applicable") is False:
                # THE GATE SAYING THE QUESTION CANNOT ARISE HERE IS AN ANSWER, AND NOTHING READ IT (17 September
                # 2026). `clock_check` writes "this board carries no crystal, so CLK-001 has nothing on it to
                # judge" with applicable false, and it was written on 16 September precisely so that a reader
                # could tell "not applicable" from "could not judge"; this reader never looked at the field, so
                # board A's CLK-001 counted as an unanswered question about a crystal it does not have. The
                # registry's condition says a rule COULD apply to a board; a current verdict from the tool that
                # looked says whether the thing it is about is there. The pair leaves the denominator, which is
                # what NOT_APPLICABLE means everywhere else in this file, and the note travels with it.
                r = dict(result=NOT_APPLICABLE, why=(rec.get("note") or "the gate reports that this rule does "
                                                     "not apply to this board"), evidence=rec.get("_path"))
            else:
                res = rec.get("result") or rec.get("verdict")
                # AN ADVISORY VERDICT IS A MEASUREMENT AND NOT A BAR (16 September 2026). The verdict channel
                # has carried the flag since 15 September and this reader did not look at it, so a tool whose
                # own author had marked it "not a bar" would still have failed its rule on every board. A
                # measurement counts as no verification at all here, which is the honest reading: the rule is
                # unverified until something decides it.
                if rec.get("advisory"):
                    r = dict(result=INCONCLUSIVE, why="%s is advisory: a measurement for the record, not a bar (%s)"
                             % (name, str(rec.get("counts"))[:90]), evidence=rec.get("_path"))
                elif res == "PASS": r = dict(result=PASS, why="%s PASS of %s" % (name, rec.get("denominator")), evidence=rec.get("_path"))
                elif res == "FAIL": r = dict(result=FAIL, why="%s FAIL: %s" % (name, str(rec.get("counts"))[:120]), evidence=rec.get("_path"))
                else:
                    # AN INCONCLUSIVE READING EXPLAINS ITSELF AND THIS READER THREW THE EXPLANATION AWAY (19
                    # September 2026). Every gate writes a note saying WHY it could not judge, and thirteen
                    # rule-board pairs on the readiness pages read "assembly_set INCONCLUSIVE", which is the
                    # tool's name and its verdict and not one word about the cause; the sentence "no
                    # single-ended controlled line was found to judge, and this board does not declare that it
                    # has none" was sitting in the verdict file the whole time. A gate that names what it hit
                    # is a law here (16 September) and a reader that drops the name breaks it just as surely.
                    note = " ".join(str(rec.get("note") or "").split())
                    mi = " ".join(str(rec.get("missing_input") or "").split())
                    tail = (": " + (mi or note)[:160]) if (mi or note) else ""
                    r = dict(result=INCONCLUSIVE, why="%s %s%s" % (name, res, tail), evidence=rec.get("_path"))
        order = {FAIL: 0, INCONCLUSIVE: 1, PASS: 2}
        if worst is None or order[r["result"]] < order[worst["result"]]: worst = r
    return worst


def _after_meaning_changed(rec, name, c, letter):
    """(ok, why): was this verdict taken after its tool last changed what the verdict MEANS for this rule?

    26 September 2026 (MESHSAT-1357). A rule's digest moves when the RULE's demands change and a verdict's epoch
    when the audit restarts; neither moves when the TOOL is corrected to measure what the rule always demanded.
    jlc_certify was: until that day CERTIFIED did not establish that the part was the one the row or its land
    names (the tracked per-board verdicts of boards C and P read PASS over C2089, a TO-92-3 part, certified as sixteen panel
    LEDs and XSD's C4661 on the Keystone 3568 fuse-holder land). A coverage row names, per verdict, the instant
    its tool's meaning changed (`evidence_not_before`, `<letter>` expanded), and a reading taken before it is not
    current evidence for that rule until it is re-taken. A floor that cannot be read is not a floor: it refuses."""
    floors = c.get("evidence_not_before") or {}
    if not isinstance(floors, dict):
        return False, "the coverage map's evidence_not_before is not a map of verdict to instant (%r)" % (str(floors)[:40],)
    for pat, since in floors.items():
        if str(pat).replace("<letter>", letter) != name:
            continue
        e = _instant(str(since))
        if e is None:
            return False, "the coverage map's evidence_not_before for %s cannot be read (%r)" % (name, str(since)[:30])
        t = _instant(str(rec.get("ts", "")))
        if t is None or t < e:
            return False, ("%s was taken %s, before %s, when its tool changed what the verdict means; re-take it"
                           % (name, str(rec.get("ts") or "at no stated time")[:19], str(since)[:25]))
    return True, "current"


def _phases_up_to(phase):
    i = PHASE_ORDER.index(phase)
    return PHASE_ORDER[:i + 1]


def board_status(letter, reg=None, facts=None, cov=None, m=None, fingerprint=None, phase=None):
    reg = reg or R.load(); facts = facts if facts is not None else R.facts(); cov = cov if cov is not None else coverage()
    m = m or manifest(); fingerprint = fingerprint or R.fingerprint(reg)
    vs = _verdicts(letter, m)
    ident = _board_identities(letter, m)
    rows = []
    for rule, why in R.rules_for(letter, reg, facts):
        r = result_for(rule, letter, cov, vs, m, fingerprint, phase, ident)
        rows.append(dict(rule=rule["id"], domain=rule["domain"], short_name=rule["short_name"],
                         release_effect=rule["release_effect"], verification_phase=rule["verification_phase"],
                         maturity=(cov.get(rule["id"]) or {}).get("maturity", "UNASSESSED"),
                         applies_because=why, **r))
    return dict(board=letter, rule_set_fingerprint=fingerprint, manifest_version=m.get("manifest_version"),
                evidence_epoch=m.get("evidence", {}).get("epoch"), verdicts_seen=len(vs),
                subject=subject(letter, m), rows=rows)


def counts(rows, required_only=True):
    rs = [r for r in rows if r["result"] != NOT_APPLICABLE]
    if required_only: rs = [r for r in rs if r["release_effect"] in ("BLOCKER", "MUST_JUSTIFY")]
    d = len(rs) or 1
    c = {k: sum(1 for r in rs if r["result"] == k) for k in (PASS, FAIL, INCONCLUSIVE, WAIVED)}
    pct = {k.lower() + "_percent": round(100.0 * v / d, 1) for k, v in c.items()}
    return dict(denominator=len(rs), **c, **pct)


def gate_state(rows, m):
    """Reported BEFORE any percentage. A blocker that fails, or a board or deliverable the manifest expects
    and does not have, is NOT_READY; a blocker with no current evidence is INCONCLUSIVE; anything else with
    every pre-fabrication blocker satisfied is READY_FOR_PROTOTYPE."""
    blockers = [r for r in rows if r["release_effect"] == "BLOCKER" and r["result"] != NOT_APPLICABLE]
    pre = [r for r in blockers if r["verification_phase"] in PRE_FAB]
    state = "READY_FOR_PROTOTYPE"
    if any(r["result"] == FAIL for r in blockers): state = "NOT_READY"
    elif any(r["result"] == INCONCLUSIVE for r in pre): state = "INCONCLUSIVE"
    if m.get("promotion", {}).get("frozen") and state == "READY_FOR_PROTOTYPE": state = "INCONCLUSIVE"
    if any(r["result"] == WAIVED for r in blockers): state += " WITH_WAIVERS"
    return state


def main(argv):
    reg = R.load(); facts = R.facts(); cov = coverage(); m = manifest(); fp = R.fingerprint(reg)
    phase = _v.opt(argv, "--phase", None)
    only = [argv[argv.index("--board") + 1]] if "--board" in argv else list(m["boards"])
    out_dir = _v.opt(argv, "--out-dir", os.path.join(ECAD, "out", "rule-audit"))
    os.makedirs(out_dir, exist_ok=True)
    all_rows, per_board = [], {}
    for letter in only:
        st = board_status(letter, reg, facts, cov, m, fp, phase)
        per_board[letter] = st; all_rows += st["rows"]
        json.dump(st, open(os.path.join(out_dir, "%s.json" % letter), "w"), indent=1)
        c = counts(st["rows"])
        print("%-3s %-28s %s" % (letter.upper(), gate_state(st["rows"], m),
                                 "PASS %d  FAIL %d  INCONCLUSIVE %d  WAIVED %d  of %d required rule(s)"
                                 % (c[PASS], c[FAIL], c[INCONCLUSIVE], c[WAIVED], c["denominator"])))
        # AND WHICH BOARD THOSE NUMBERS ARE ABOUT, on the line that carries them.
        print("    %s" % subject_line(st["subject"]))
    # SGN-001, and it is a DIFFERENT question from readiness: not "does this board pass" but "did every rule
    # that applies to it reach a decision at all". A rule that applies and produces nothing is the failure this
    # whole registry exists to make impossible, and it would otherwise be invisible, since a rule missing from
    # the table looks exactly like a rule that is not applicable.
    # It is written at the END of a run and read by the NEXT one, like every other gate's verdict: a tool does
    # not read its own answer while producing it. So SGN-001 reports on the previous computation, which is what
    # evidence is, and a first run on a fresh tree leaves it INCONCLUSIVE rather than assuming itself correct.
    unresolved = [r for r in all_rows if r["result"] not in R.RESULTS]
    val, _warn = R.validate(reg)          # (errors, warnings): a warning is not a missing decision
    no_cov = sorted({r["rule"] for r in all_rows if r["rule"] not in cov})
    complete = not (unresolved or val or no_cov)
    # A PARTIAL RUN CANNOT ANSWER THE SET'S QUESTION, AND THIS ONE ANSWERED IT ANYWAY (17 September 2026).
    # `rules_status.py --board p` judges forty-two pairs and wrote the SET-LEVEL completeness verdict from
    # them, denominator and all, over the reading taken on all 301. SGN-001 is a BLOCKER on every one of the
    # seven boards and it is decided by that single file, so one scoped run silently narrowed what every
    # board's page then claimed to have checked: the generated pages read "rules_complete PASS of 42" on
    # boards the run never looked at. It is the `missing_input` doctrine one level up, and here the honest
    # move is not to take the reading at all: a run that was asked about one board has nothing to say about
    # the set, says so on its own line, and leaves the set's evidence alone. Staleness is already handled,
    # because the epoch and the rule-set fingerprint refuse an old verdict wherever it is read.
    scoped = [w for w in ("--board", "--phase") if w in argv]
    if scoped:
        print("scoped run (%s): the set-level completeness verdict SGN-001 was NOT written. This run judged "
              "%d rule-board pair(s) on %d of %d board(s), which cannot answer for the set; the verdict on "
              "disk stands until a full run replaces it."
              % (" ".join(scoped), len(all_rows), len(only), len(m["boards"])))
        return _finish(argv, all_rows, per_board, m, fp, phase, out_dir)
    _v.write("rules_complete", _v.PASS if complete else _v.FAIL,
             counts={"pairs": len(all_rows), "unresolved": len(unresolved),
                     "registry_errors": len(val), "rules_without_coverage": len(no_cov)},
             denominator=len(all_rows),
             evidence=([str(x)[:110] for x in val[:10]]
                       + ["%s on %s produced %r" % (r["rule"], r.get("board", "?"), r["result"]) for r in unresolved[:10]]
                       + ["%s has no coverage entry" % x for x in no_cov[:10]]),
             inputs={"manifest_version": m.get("manifest_version"), "rule_set_fingerprint": fp},
             note=("every applicable rule reached one of the five results on every board in the manifest"
                   if complete else "a rule that applies reached no result, which is what the registry exists to prevent"),
             # A SET-LEVEL verdict, so it goes where the set-level gates write and every board can read it,
             # UNLESS the caller said where to write (18 September 2026). `--out-dir` redirected the board
             # pages and the audit but not this one, so a run told to keep its output somewhere else still
             # wrote into the tree: the suite's own completeness test does exactly that, and on the runner it
             # is invisible because the numbers match what was there. Run on a box in a checkout without the
             # untracked evidence it rewrote the tree's readiness with a reading taken with LESS input (188
             # PASS against 211), which is the one thing this project's verdicts are not allowed to do. The
             # guard in `tests/run.py` caught it, which is what that guard is for. An option that says where
             # to write must write all of it there.
             out_dir=(_explicit_out(argv) or os.path.join(ECAD, "out")), quiet=True)
    return _finish(argv, all_rows, per_board, m, fp, phase, out_dir)


def _explicit_out(argv):
    """The directory the caller named, or None. A set-level verdict belongs beside the set's own gates; a run
    told to write elsewhere is a run that must leave the tree exactly as it found it."""
    return _v.opt(argv, "--out-dir", None)


def _finish(argv, all_rows, per_board, m, fp, phase, out_dir):
    """The run's own summary and its readiness verdict. Split out of `main` so that a scoped run reaches
    exactly this and nothing else: the set-level completeness verdict above it is written only by a run that
    saw the whole set."""
    agg = counts(all_rows); state = gate_state(all_rows, m)
    summary = dict(manifest_version=m.get("manifest_version"), rule_set_fingerprint=fp,
                   promotion_frozen=bool(m.get("promotion", {}).get("frozen")), phase=phase or "ALL",
                   gate_state=state, counts=agg, boards={k: counts(v["rows"]) for k, v in per_board.items()})
    json.dump(summary, open(os.path.join(out_dir, "summary.json"), "w"), indent=1)
    print("\nreadiness: %s   (manifest %s, rule set %s%s)" % (state, m.get("manifest_version"), fp,
          ", promotion frozen" if m.get("promotion", {}).get("frozen") else ""))
    print("verified %.1f%%  waived %.1f%%  failed %.1f%%  inconclusive %.1f%%  of %d applicable required rule-board pair(s)"
          % (agg["pass_percent"], agg["waived_percent"], agg["fail_percent"], agg["inconclusive_percent"], agg["denominator"]))
    if _DISPLACED:
        # A reading that declares it lacked its input stood in front of one that had it, because its rule-set
        # fingerprint is current and the other's is not. It is legal by the order in `_supersedes` and it is
        # exactly how a page can change under the reader with nothing on it to show why (19 September 2026).
        seen = []
        for _n, _mi, _ofp in _DISPLACED:
            if (_n, _mi, _ofp) in seen: continue
            seen.append((_n, _mi, _ofp))
        print("\nNOTE: %d reading(s) that declare a MISSING INPUT stand in front of a measured one, because the "
              "measured one was taken under a superseded version of the rule it decides (asked rule by rule "
              "where the verdict carries its digests, and by the set fingerprint where it does not). Re-take "
              "those on the board, where the tool has its input (retake_gate.sh), rather than reading the "
              "page as an answer:" % len(seen))
        for _n, _mi, _ofp in seen[:8]:
            print("  %-22s displaces a reading taken under %s; it lacked: %s" % (_n, _ofp or "(no fingerprint)", _mi or "(unsaid)"))
    if "--json" in argv: print(json.dumps(summary, indent=1, sort_keys=True))
    res = _v.PASS if state.startswith("READY") else (_v.FAIL if state.startswith("NOT_READY") else _v.INCONCLUSIVE)
    return _v.write("rules_status", res, counts=agg, denominator=agg["denominator"],
                    evidence=["%s %s %s" % (r["rule"], r["result"], r["why"][:80]) for r in all_rows if r["result"] in (FAIL, INCONCLUSIVE)][:40],
                    inputs={"manifest_version": m.get("manifest_version"), "rule_set_fingerprint": fp},
                    note="gate state %s; %s" % (state, "promotion frozen" if m.get("promotion", {}).get("frozen") else "promotion open"),
                    out_dir=out_dir)


if __name__ == "__main__":
    # the coverage map names this tool as a rule's verification, so a crash here has to leave a reading
    # too (18 September 2026; the rule that finds this one reads the coverage map rather than a list)
    sys.exit(_v.guard("rules_status", main, sys.argv[1:]))