#!/usr/bin/env python3
"""Compute each board's result for every rule that applies to it, and the readiness state of the set
(MESHSAT-862, 16 September 2026; owner instruction of 16 September 00:30).

Every applicable rule-board pair gets exactly one of PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE, and
the rule that makes this worth reading is: **absence is never a pass**. A missing verdict file, a verdict
older than the evidence epoch, a verdict taken under a different rule-set fingerprint or a different board,
a rule with no implementation, a rule whose authority is unverified, a rule whose owner decision is open:
each of those is INCONCLUSIVE, and an INCONCLUSIVE blocker keeps the set out of READY_FOR_PROTOTYPE.

Where a result comes from:
  * the registry says whether the rule applies to this board (rules_lib.rules_for);
  * the coverage map says which tool verifies it and which verdict file carries the evidence;
  * the verdict file, if it exists in the board's project `out/` or its `routed/` snapshot, carries the
    result, the denominator and its own inputs;
  * the readiness manifest says what evidence is current (the epoch) and whether promotion is frozen.

Percentages: four numbers over ONE denominator (the applicable rule-board pairs required at the phase being
reported), summing to 100 subject to rounding. The gate state is printed BEFORE them, and the WITH_WAIVERS
qualifier cannot be hidden by any of them. The project aggregate sums rule-board pairs; it never averages
board percentages.

Usage:
  rules_status.py [--board <letter>] [--phase <SCHEMATIC|PLACED_BOARD|ROUTED_BOARD|RELEASE_PACKAGE>]
                  [--out-dir out/rule-audit] [--json]

The per-board markdown is generated by rules_render.py from the JSON this writes; this tool computes and
never formats a document.
"""
import os, sys, json, glob, time, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import verdict as _v

ECAD = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "readiness_manifest.json")
COVERAGE = os.path.join(HERE, "pcb_rules_coverage.yaml")
PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE = "PASS", "FAIL", "INCONCLUSIVE", "WAIVED", "NOT_APPLICABLE"
PHASE_ORDER = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE", "ASSEMBLY", "PROTOTYPE")
PRE_FAB = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE")


def manifest(path=None):
    return json.load(open(path or MANIFEST))


def coverage(path=None):
    return (R._yaml().safe_load(open(path or COVERAGE)) or {}).get("coverage", {})


def _project_dirs(letter, m):
    """Where a board's evidence can be: its phase directory's out/ and routed/, and the plain project dir."""
    proj = (m["boards"].get(letter) or {}).get("project", "")
    out = []
    for d in sorted(glob.glob(os.path.join(ECAD, proj + "*"))):
        out += [os.path.join(d, "out"), os.path.join(d, "routed")]
    return [d for d in out if os.path.isdir(d)]


def _verdicts(letter, m):
    """{name: record} of every verdict file the board has, newest wins."""
    found = {}
    for d in _project_dirs(letter, m):
        for f in sorted(glob.glob(os.path.join(d, "*.verdict.json"))):
            try: rec = json.load(open(f))
            except ValueError: continue
            name = rec.get("name") or os.path.basename(f)[:-len(".verdict.json")]
            prev = found.get(name)
            if prev is None or str(rec.get("ts", "")) >= str(prev.get("ts", "")): rec["_path"] = f; found[name] = rec
    return found


def _fresh(rec, m, fingerprint):
    """(ok, why): is this verdict current evidence? The epoch and the rule-set fingerprint are the identity;
    a verdict from before the audit is history, not a decision."""
    ts = str(rec.get("ts", ""))
    epoch = str(m.get("evidence", {}).get("epoch", ""))[:19].replace("T", " ")
    if not ts: return False, "the verdict carries no timestamp"
    if ts[:19].replace("T", " ") < epoch: return False, "PRE_AUDIT: taken %s, before the evidence epoch %s" % (ts[:19], epoch[:19])
    got = (rec.get("policy") or {}).get("rule_set_fingerprint") or rec.get("rule_set_fingerprint")
    if fingerprint and got and got != fingerprint: return False, "taken under rule set %s, current is %s" % (got, fingerprint)
    if fingerprint and not got: return False, "the verdict does not name the rule set it was taken under"
    return True, "current"


def result_for(rule, letter, cov, vs, m, fingerprint, phase=None):
    """One rule on one board. Everything that is not a positive, current PASS is INCONCLUSIVE or FAIL."""
    rid = rule["id"]; c = cov.get(rid) or {}
    if phase and rule["verification_phase"] not in _phases_up_to(phase):
        return dict(result=NOT_APPLICABLE, why="verified at %s, later than the phase being reported" % rule["verification_phase"], evidence=None)
    w = (c.get("waiver") or {})
    if w.get("active"):
        return dict(result=WAIVED, why="waived by %s until %s: %s" % (w.get("authority"), w.get("expiry"), w.get("reason", "")), evidence=w.get("evidence"))
    if c.get("maturity") in ("OPEN", "DOCUMENTED_ONLY"):
        return dict(result=INCONCLUSIVE, why="no verification: %s" % c.get("note", "")[:160], evidence=None)
    if c.get("maturity") == "SOURCE_UNVERIFIED":
        return dict(result=INCONCLUSIVE, why="the authority behind this rule's limit is not established: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "OWNER_DECISION_REQUIRED":
        return dict(result=INCONCLUSIVE, why="an owner decision is open: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "GENERATED_ONLY":
        return dict(result=INCONCLUSIVE, why="generation intends to comply and nothing verifies it: %s" % c.get("note", "")[:140], evidence=None)
    name = (c.get("verification") or {}).get("verdict")
    if not name:
        return dict(result=INCONCLUSIVE, why="the coverage map names no verdict for an enforced rule", evidence=None)
    name = name.replace("<letter>", letter)
    rec = vs.get(name)
    if rec is None:
        return dict(result=INCONCLUSIVE, why="no %s verdict for this board" % name, evidence=None)
    ok, why = _fresh(rec, m, fingerprint)
    if not ok:
        return dict(result=INCONCLUSIVE, why=why, evidence=rec.get("_path"))
    res = rec.get("result") or rec.get("verdict")
    if res == "PASS": return dict(result=PASS, why="%s PASS of %s" % (name, rec.get("denominator")), evidence=rec.get("_path"))
    if res == "FAIL": return dict(result=FAIL, why="%s FAIL: %s" % (name, str(rec.get("counts"))[:120]), evidence=rec.get("_path"))
    return dict(result=INCONCLUSIVE, why="%s %s" % (name, res), evidence=rec.get("_path"))


def _phases_up_to(phase):
    i = PHASE_ORDER.index(phase)
    return PHASE_ORDER[:i + 1]


def board_status(letter, reg=None, facts=None, cov=None, m=None, fingerprint=None, phase=None):
    reg = reg or R.load(); facts = facts if facts is not None else R.facts(); cov = cov if cov is not None else coverage()
    m = m or manifest(); fingerprint = fingerprint or R.fingerprint(reg)
    vs = _verdicts(letter, m)
    rows = []
    for rule, why in R.rules_for(letter, reg, facts):
        r = result_for(rule, letter, cov, vs, m, fingerprint, phase)
        rows.append(dict(rule=rule["id"], domain=rule["domain"], short_name=rule["short_name"],
                         release_effect=rule["release_effect"], verification_phase=rule["verification_phase"],
                         maturity=(cov.get(rule["id"]) or {}).get("maturity", "UNASSESSED"),
                         applies_because=why, **r))
    return dict(board=letter, rule_set_fingerprint=fingerprint, manifest_version=m.get("manifest_version"),
                evidence_epoch=m.get("evidence", {}).get("epoch"), verdicts_seen=len(vs), rows=rows)


def counts(rows, required_only=True):
    rs = [r for r in rows if r["result"] != NOT_APPLICABLE]
    if required_only: rs = [r for r in rs if r["release_effect"] in ("BLOCKER", "MUST_JUSTIFY")]
    d = len(rs) or 1
    c = {k: sum(1 for r in rs if r["result"] == k) for k in (PASS, FAIL, INCONCLUSIVE, WAIVED)}
    pct = {k.lower() + "_percent": round(100.0 * v / d, 1) for k, v in c.items()}
    return dict(denominator=len(rs), **c, **pct)


def gate_state(rows, m):
    """Reported BEFORE any percentage. A blocker that fails, or a board or deliverable the manifest expects
    and does not have, is NOT_READY; a blocker with no current evidence is INCONCLUSIVE; anything else with
    every pre-fabrication blocker satisfied is READY_FOR_PROTOTYPE."""
    blockers = [r for r in rows if r["release_effect"] == "BLOCKER" and r["result"] != NOT_APPLICABLE]
    pre = [r for r in blockers if r["verification_phase"] in PRE_FAB]
    state = "READY_FOR_PROTOTYPE"
    if any(r["result"] == FAIL for r in blockers): state = "NOT_READY"
    elif any(r["result"] == INCONCLUSIVE for r in pre): state = "INCONCLUSIVE"
    if m.get("promotion", {}).get("frozen") and state == "READY_FOR_PROTOTYPE": state = "INCONCLUSIVE"
    if any(r["result"] == WAIVED for r in blockers): state += " WITH_WAIVERS"
    return state


def main(argv):
    reg = R.load(); facts = R.facts(); cov = coverage(); m = manifest(); fp = R.fingerprint(reg)
    phase = argv[argv.index("--phase") + 1] if "--phase" in argv else None
    only = [argv[argv.index("--board") + 1]] if "--board" in argv else list(m["boards"])
    out_dir = argv[argv.index("--out-dir") + 1] if "--out-dir" in argv else os.path.join(ECAD, "out", "rule-audit")
    os.makedirs(out_dir, exist_ok=True)
    all_rows, per_board = [], {}
    for letter in only:
        st = board_status(letter, reg, facts, cov, m, fp, phase)
        per_board[letter] = st; all_rows += st["rows"]
        json.dump(st, open(os.path.join(out_dir, "%s.json" % letter), "w"), indent=1)
        c = counts(st["rows"])
        print("%-3s %-28s %s" % (letter.upper(), gate_state(st["rows"], m),
                                 "PASS %d  FAIL %d  INCONCLUSIVE %d  WAIVED %d  of %d required rule(s)"
                                 % (c[PASS], c[FAIL], c[INCONCLUSIVE], c[WAIVED], c["denominator"])))
    agg = counts(all_rows); state = gate_state(all_rows, m)
    summary = dict(manifest_version=m.get("manifest_version"), rule_set_fingerprint=fp,
                   promotion_frozen=bool(m.get("promotion", {}).get("frozen")), phase=phase or "ALL",
                   gate_state=state, counts=agg, boards={k: counts(v["rows"]) for k, v in per_board.items()})
    json.dump(summary, open(os.path.join(out_dir, "summary.json"), "w"), indent=1)
    print("\nreadiness: %s   (manifest %s, rule set %s%s)" % (state, m.get("manifest_version"), fp,
          ", promotion frozen" if m.get("promotion", {}).get("frozen") else ""))
    print("verified %.1f%%  waived %.1f%%  failed %.1f%%  inconclusive %.1f%%  of %d applicable required rule-board pair(s)"
          % (agg["pass_percent"], agg["waived_percent"], agg["fail_percent"], agg["inconclusive_percent"], agg["denominator"]))
    if "--json" in argv: print(json.dumps(summary, indent=1, sort_keys=True))
    res = _v.PASS if state.startswith("READY") else (_v.FAIL if state.startswith("NOT_READY") else _v.INCONCLUSIVE)
    return _v.write("rules_status", res, counts=agg, denominator=agg["denominator"],
                    evidence=["%s %s %s" % (r["rule"], r["result"], r["why"][:80]) for r in all_rows if r["result"] in (FAIL, INCONCLUSIVE)][:40],
                    inputs={"manifest_version": m.get("manifest_version"), "rule_set_fingerprint": fp},
                    note="gate state %s; %s" % (state, "promotion frozen" if m.get("promotion", {}).get("frozen") else "promotion open"),
                    out_dir=out_dir)


if __name__ == "__main__": sys.exit(main(sys.argv[1:]))
