#!/usr/bin/env python3
"""Generate every rule document from the canonical registry (MESHSAT-862, 16 September 2026).

`pcb_rules.yaml` and `pcb_rules_coverage.yaml` are the authorities; the documents under v2/docs/ are their
rendering. Nothing here is hand-maintained: `--check` regenerates into memory and refuses a file on disk that
differs, which is what keeps a reader's document and the machine's registry the same thing.

  rules_render.py            write the documents
  rules_render.py --check    refuse if any document on disk differs from what the registry renders (exit 1)

Documents:
  v2/docs/PCB-GOLDEN-RULES.md      the rulebook, by domain
  v2/docs/PCB-RULE-COVERAGE.md     rule -> implementation, verification, fixtures, maturity
  v2/docs/PCB-GAP-REGISTER.md      the gaps, by category, with remediation, owner and effort
  v2/docs/PCB-ETA.md               the computed ETA from those remediations and the measured run history
  v2/docs/PCB-PROTOTYPE-UNKNOWNS.md what only hardware can decide, so it never reads as a pass
  v2/docs/PCB-RULE-STATUS-<L>.md   per board, from out/rule-audit/<L>.json when it exists
"""
import os, sys, json, glob

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import rules_status as S

DOCS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "v2", "docs")
if not os.path.isdir(DOCS): DOCS = os.path.join(os.path.dirname(os.path.dirname(HERE)), "docs")
GAP_ORDER = ("ABSENT", "GENERATED_ONLY", "PROSE_ONLY", "NO_BEHAVIOURAL_TEST", "NO_PROTOCOL",
             "DUPLICATED_OR_STALE", "HEURISTIC_AS_LAW", "SOURCE_OR_APPLICABILITY_UNRESOLVED",
             "CROSS_BOARD_INCONSISTENT", "NONE")
HEAD = ("<!-- GENERATED by tools/rules_render.py from tools/pcb_rules.yaml and tools/pcb_rules_coverage.yaml.\n"
        "     Do not edit: `python3 tools/rules_render.py --check` refuses a hand-edited copy, and the suite runs it. -->\n")


def _wrap(s, width=110, indent=""):
    words = " ".join(str(s or "").split()); out, line = [], indent
    for w in words.split(" "):
        if len(line) + len(w) + 1 > width: out.append(line.rstrip()); line = indent
        line += w + " "
    out.append(line.rstrip())
    return "\n".join(x for x in out if x.strip())


def rulebook(reg, cov):
    L = [HEAD, "# The PCB golden rules\n",
         _wrap("Every rule this project holds a board to, with its authority, its applicability, how it is "
               "verified and what its verification is currently worth. Generated from the registry: the "
               "registry is the authority and this page is its rendering."), "",
         "Registry version **%s**, fingerprint **%s**, %d rules over %d domains.\n"
         % (reg.get("registry_version"), R.fingerprint(reg), len(reg["rules"]), len({r["domain"] for r in reg["rules"]})),
         "## How to read a rule\n",
         _wrap("`BLOCKER` stops a release, `MUST_JUSTIFY` needs a written reason, `ADVISORY` informs. "
               "`SOURCE_UNVERIFIED` means the limit's authority is not on file, which is not the same as the "
               "rule being wrong: it means nobody can check it. A `HEURISTIC` may never be a blocker; where "
               "one is doing a blocker's work today it is written as a screen under the principle it screens for."), ""]
    for dom in R.DOMAINS:
        rs = [r for r in reg["rules"] if r["domain"] == dom]
        if not rs: continue
        L.append("## %s\n" % dom.replace("_", " ").title())
        for r in rs:
            c = cov.get(r["id"]) or {}
            L.append("### %s  %s\n" % (r["id"], r["short_name"]))
            L.append(_wrap(r["requirement"]) + "\n")
            L.append("| | |\n|---|---|")
            L.append("| classification | %s |" % r["classification"])
            L.append("| applies | %s%s |" % (r["applicability"].replace("_", " ").lower(),
                                             ("" if r["applicability"] == "UNIVERSAL_FOR_THIS_PROJECT"
                                              else "; boards " + ", ".join(str(b) for b in (r["boards_affected"] or [])))))
            L.append("| release effect | **%s** |" % r["release_effect"])
            L.append("| risk | %s |" % ", ".join(r["risk_class"] if isinstance(r["risk_class"], list) else [r["risk_class"]]))
            L.append("| verified by | %s at %s (%s) |" % (", ".join(r["verification_method"] if isinstance(r["verification_method"], list) else [r["verification_method"]]),
                                                          r["verification_phase"], r["automation_feasibility"].replace("_", " ").lower()))
            L.append("| source | %s |" % r["source_status"])
            for s in (r.get("sources") or []):
                L.append("| | %s, %s%s%s |" % (s.get("title", ""), s.get("issuer", ""),
                                               (", " + s["clause"]) if s.get("clause") else "",
                                               " -- " + s.get("url_or_path", "")))
            L.append("| implementation | %s |" % (c.get("implementation") or r.get("implementation_location")))
            L.append("| maturity | **%s** |" % c.get("maturity", r.get("maturity")))
            L.append("| owner | %s |" % r["owner"])
            w = r.get("waiver_policy") or {}
            L.append("| waiver | %s |" % ("not waivable" if not w.get("allowed") else
                                          "by %s, scope %s, expires %s" % (w.get("authority"), w.get("scope"), w.get("expiry"))))
            L.append("")
            L.append("**Accept when** " + _wrap(r["acceptance_criteria"]).lstrip() + "\n")
            L.append("**Why** " + _wrap(r["rationale"]).lstrip() + "\n")
            L.append("**If violated** " + _wrap(r["failure_mode"]).lstrip() + "\n")
            if c.get("note"): L.append("**Today** " + _wrap(c["note"]).lstrip() + "\n")
    return "\n".join(L) + "\n"


def coverage_doc(reg, cov):
    by = {r["id"]: r for r in reg["rules"]}
    L = [HEAD, "# Rule coverage\n",
         _wrap("Where each rule is generated, where it is verified, and what that verification is worth. "
               "ENFORCED means an executable gate with a machine-readable verdict and behavioural fixtures; "
               "everything else is a gap and appears in the gap register."), "",
         "| rule | domain | effect | implementation | verification | fixtures | maturity |",
         "|---|---|---|---|---|---|---|"]
    for rid in sorted(cov):
        r = by.get(rid, {}); c = cov[rid]; v = c.get("verification") or {}
        L.append("| %s | %s | %s | %s | %s | %s | **%s** |"
                 % (rid, r.get("domain", ""), r.get("release_effect", ""), c.get("implementation", ""),
                    v.get("tool", "none") + ((" -> " + v["verdict"]) if v.get("verdict") else ""),
                    v.get("fixtures", ""), c.get("maturity", "")))
    counts = {}
    for c in cov.values(): counts[c.get("maturity")] = counts.get(c.get("maturity"), 0) + 1
    L += ["", "## Maturity", "", "| maturity | rules |", "|---|---|"]
    for k in R.MATURITY:
        if counts.get(k): L.append("| %s | %d |" % (k, counts[k]))
    return "\n".join(L) + "\n"


def gap_register(reg, cov):
    by = {r["id"]: r for r in reg["rules"]}
    L = [HEAD, "# Gap register\n",
         _wrap("Every applicable rule this project does not yet verify, by the category of the gap, with what "
               "closing it needs, who decides and the effort estimate. A gap is not a failure of the board: it "
               "is a question nobody has answered yet, made visible so it cannot be forgotten."), ""]
    tot = sum(1 for c in cov.values() if c.get("gap_category") not in (None, "NONE"))
    L.append("**%d of %d rules carry a gap.**\n" % (tot, len(cov)))
    for cat in GAP_ORDER:
        rs = [rid for rid in sorted(cov) if (cov[rid].get("gap_category") or "NONE") == cat]
        if not rs or cat == "NONE": continue
        L.append("## %s (%d)\n" % (cat.replace("_", " ").lower(), len(rs)))
        for rid in rs:
            c = cov[rid]; r = by.get(rid, {}); rem = c.get("remediation") or {}
            L.append("**%s %s** (%s, %s)  " % (rid, r.get("short_name", ""), r.get("release_effect", ""), c.get("maturity", "")))
            L.append(_wrap(c.get("note", ""), indent="") + "  ")
            if rem:
                L.append("*Close it by* %s. Owner **%s**%s. Effort P50 %sh, P80 %sh.\n"
                         % (rem.get("action", ""), rem.get("owner", ""),
                            (", after " + ", ".join(rem.get("depends_on") or [])) if rem.get("depends_on") else "",
                            rem.get("p50_h", "?"), rem.get("p80_h", "?")))
            else: L.append("")
    covered = [rid for rid in sorted(cov) if (cov[rid].get("gap_category") or "NONE") == "NONE"]
    L.append("## covered (%d)\n" % len(covered))
    L.append(_wrap("These rules have an executable gate, a machine-readable verdict and behavioural fixtures: "
                   + ", ".join(covered)) + "\n")
    return "\n".join(L) + "\n"


def board_doc(letter, st, reg, cov):
    m = S.manifest()
    L = [HEAD, "# Rule status: board %s\n" % letter.upper(),
         "Manifest **%s**, rule set **%s**, evidence epoch **%s**.\n"
         % (st.get("manifest_version"), st.get("rule_set_fingerprint"), st.get("evidence_epoch")),
         "**Readiness: %s**\n" % S.gate_state(st["rows"], m)]
    c = S.counts(st["rows"])
    L += ["| result | rules | percent |", "|---|---|---|"]
    for k in ("PASS", "FAIL", "INCONCLUSIVE", "WAIVED"):
        L.append("| %s | %d | %.1f |" % (k, c[k], c[k.lower() + "_percent"]))
    L += ["| **denominator** | **%d** | 100.0 |" % c["denominator"], "",
          "| rule | effect | phase | result | why |", "|---|---|---|---|---|"]
    for r in st["rows"]:
        L.append("| %s %s | %s | %s | **%s** | %s |" % (r["rule"], r["short_name"], r["release_effect"],
                                                        r["verification_phase"], r["result"],
                                                        " ".join(str(r["why"]).split())[:150]))
    return "\n".join(L) + "\n"


def prototype_doc(reg, cov):
    """SGN-002: the properties that cannot be decided before hardware exists, generated from the registry so
    the list cannot quietly shrink. A prototype-only unknown that is not named reads exactly like a pass."""
    L = [HEAD, "# Prototype-only unknowns\n",
         _wrap("Generated from the registry: every rule verified at the prototype, or whose verification needs a "
               "physical measurement, together with what will decide it. Nothing on this page can be closed by "
               "any amount of work on the boards; each one needs hardware that does not exist yet."), "",
         "| rule | what is unknown | what decides it | owner |", "|---|---|---|---|"]
    n = 0
    for r in reg["rules"]:
        meths = r["verification_method"] if isinstance(r["verification_method"], list) else [r["verification_method"]]
        if r["verification_phase"] != "PROTOTYPE" and "PROTOTYPE_MEASUREMENT" not in meths: continue
        n += 1
        c = cov.get(r["id"]) or {}
        rem = (c.get("remediation") or {}).get("action", "")
        L.append("| %s %s | %s | %s | %s |" % (r["id"], r["short_name"], " ".join(r["failure_mode"].split())[:110],
                                               " ".join(str(rem).split())[:110] or "a measurement on the built board", r["owner"]))
    L += ["", _wrap("%d rule(s) of %d wait on hardware. Nothing has been fabricated or powered, so each of these "
                    "is UNKNOWN rather than passing or failing, and the readiness state says so."
                    % (n, len(reg["rules"]))), ""]
    return "\n".join(L) + "\n"


# Documents that are a pure function of the registry and the coverage map, with no board evidence in them.
# rules_status reads this to judge a VERIFIED_MANUALLY rule whose evidence IS one of these pages: it can
# rebuild the page in memory and compare, which is what makes "the list has not quietly shrunk" a fact rather
# than a habit. The board pages are deliberately absent: they are generated FROM the status, so asking the
# status to check them would be a circle.
SELF_CONTAINED = {"PCB-PROTOTYPE-UNKNOWNS.md": prototype_doc,
                  "PCB-GOLDEN-RULES.md": rulebook,
                  "PCB-RULE-COVERAGE.md": coverage_doc,
                  "PCB-GAP-REGISTER.md": gap_register}


def eta_doc():
    import rules_eta as E
    m = E.model(); items = E.open_items()
    L = [HEAD, "# ETA, computed\n",
         _wrap("Derived from the gap register's remediation entries and the route durations measured in this "
               "tree's own journals. It is regenerated, never typed: change an estimate in the coverage map "
               "and this page changes with it."), "",
         "| | P50 | P80 |", "|---|---|---|",
         "| engineering effort, one worker | %.0f h | %.0f h |" % (m["engineering_hours"]["p50"], m["engineering_hours"]["p80"]),
         "| critical path through the dependencies | %.0f h | %.0f h |" % (m["critical_path_hours"]["p50"], m["critical_path_hours"]["p80"]),
         "| at %.0f engineering hours a day | %.1f days | %.1f days |" % (m["hours_per_day"], m["calendar_days"]["p50"], m["calendar_days"]["p80"]),
         "",
         _wrap("%d open item(s): %d are this session's work and %d are waits on the owner, a vendor or a lab. "
               "Waits are not engineering time and are listed separately below." % (m["open_items"], m["session_items"], m["wait_items"])), "",
         "## Waits, which no amount of engineering shortens\n",
         "| rule | what it needs | owner |", "|---|---|---|"]
    for w in m["owner_waits"]:
        L.append("| %s | %s | %s |" % (w["rule"], w["action"], next((i["owner"] for i in items if i["rule"] == w["rule"]), "")))
    L += ["", "## Measured route history\n",
          _wrap("Route durations this tree has recorded, in minutes per attempt: median %s, worst %s, over %d board(s). "
                "A board's re-route is elapsed time, not engineering time, and several run at once on the rented box."
                % (m["route_history"]["median_minutes"], m["route_history"]["worst_minutes"], len(m["route_history"]["boards"]))), "",
          "## Assumptions\n"]
    for a in m["assumptions"]: L.append("- " + a)
    L += ["", _wrap("This estimate covers making every applicable rule verified. It does not cover prototype "
                    "manufacture, assembly or physical validation, none of which can start before the set is "
                    "ordered, and it is separate from the question of when the seven boards pass the gates that "
                    "exist today."), ""]
    return "\n".join(L) + "\n"


def render(out_dir=None):
    reg = R.load(); cov = S.coverage(); docs = out_dir or DOCS
    files = {os.path.join(docs, "PCB-GOLDEN-RULES.md"): rulebook(reg, cov),
             os.path.join(docs, "PCB-RULE-COVERAGE.md"): coverage_doc(reg, cov),
             os.path.join(docs, "PCB-GAP-REGISTER.md"): gap_register(reg, cov),
             os.path.join(docs, "PCB-ETA.md"): eta_doc(),
             os.path.join(docs, "PCB-PROTOTYPE-UNKNOWNS.md"): prototype_doc(reg, cov)}
    audit = os.path.join(os.path.dirname(HERE), "out", "rule-audit")
    for f in sorted(glob.glob(os.path.join(audit, "*.json"))):
        letter = os.path.basename(f)[:-5]
        if letter == "summary": continue
        try: st = json.load(open(f))
        except ValueError: continue
        if "rows" not in st: continue          # summary.json and any other non-board artefact in the audit dir
        files[os.path.join(docs, "PCB-RULE-STATUS-%s.md" % letter.upper())] = board_doc(letter, st, reg, cov)
    return files


def main(argv):
    files = render()
    if "--check" in argv:
        bad = [p for p, body in files.items() if not os.path.exists(p) or open(p).read() != body]
        for p in bad: print("rules_render: %s differs from what the registry renders" % os.path.relpath(p))
        print("rules_render: %d document(s), %d out of date" % (len(files), len(bad)))
        return 1 if bad else 0
    for p, body in files.items():
        os.makedirs(os.path.dirname(p), exist_ok=True); open(p, "w").write(body)
        print("rules_render: wrote %s (%d lines)" % (os.path.relpath(p), body.count("\n")))
    return 0


if __name__ == "__main__": sys.exit(main(sys.argv[1:]))
