#!/usr/bin/env python3
"""Compute each board's result for every rule that applies to it, and the readiness state of the set
(MESHSAT-862, 16 September 2026; owner instruction of 16 September 00:30).

Every applicable rule-board pair gets exactly one of PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE, and
the rule that makes this worth reading is: **absence is never a pass**. A missing verdict file, a verdict
older than the evidence epoch, a verdict taken under a different rule-set fingerprint or a different board,
a rule with no implementation, a rule whose authority is unverified, a rule whose owner decision is open:
each of those is INCONCLUSIVE, and an INCONCLUSIVE blocker keeps the set out of READY_FOR_PROTOTYPE.

Where a result comes from:
  * the registry says whether the rule applies to this board (rules_lib.rules_for);
  * the coverage map says which tool verifies it and which verdict file carries the evidence;
  * the verdict file, if it exists in the board's project `out/` or its `routed/` snapshot, carries the
    result, the denominator and its own inputs;
  * the readiness manifest says what evidence is current (the epoch) and whether promotion is frozen.

Percentages: four numbers over ONE denominator (the applicable rule-board pairs required at the phase being
reported), summing to 100 subject to rounding. The gate state is printed BEFORE them, and the WITH_WAIVERS
qualifier cannot be hidden by any of them. The project aggregate sums rule-board pairs; it never averages
board percentages.

Usage:
  rules_status.py [--board <letter>] [--phase <SCHEMATIC|PLACED_BOARD|ROUTED_BOARD|RELEASE_PACKAGE>]
                  [--out-dir out/rule-audit] [--json]

The per-board markdown is generated by rules_render.py from the JSON this writes; this tool computes and
never formats a document.
"""
import os, sys, json, glob, time, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import rules_lib as R
import verdict as _v

ECAD = os.path.dirname(HERE)
MANIFEST = os.path.join(HERE, "readiness_manifest.json")
COVERAGE = os.path.join(HERE, "pcb_rules_coverage.yaml")
PASS, FAIL, INCONCLUSIVE, WAIVED, NOT_APPLICABLE = "PASS", "FAIL", "INCONCLUSIVE", "WAIVED", "NOT_APPLICABLE"
PHASE_ORDER = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE", "ASSEMBLY", "PROTOTYPE")
PRE_FAB = ("SCHEMATIC", "PLACED_BOARD", "ROUTED_BOARD", "RELEASE_PACKAGE")


def manifest(path=None):
    return json.load(open(path or MANIFEST))


def coverage(path=None):
    return (R._yaml().safe_load(open(path or COVERAGE)) or {}).get("coverage", {})


def _project_dirs(letter, m):
    """Where a board's evidence can be: its phase directory's out/ and routed/, plus the SET-LEVEL out/ where
    the across-the-set gates write (the final gate, the contracts and the parts certification judge the whole
    manifest at once, and their verdict is evidence for every board in it)."""
    proj = (m["boards"].get(letter) or {}).get("project", "")
    out = []
    for d in sorted(glob.glob(os.path.join(ECAD, proj + "*"))):
        out += [os.path.join(d, "out"), os.path.join(d, "routed")]
    out.append(os.path.join(ECAD, "out"))
    return [d for d in out if os.path.isdir(d)]


def _verdicts(letter, m):
    """{name: record} of every verdict file the board has, newest wins."""
    found = {}
    for d in _project_dirs(letter, m):
        for f in sorted(glob.glob(os.path.join(d, "*.verdict.json"))):
            try: rec = json.load(open(f))
            except ValueError: continue
            name = rec.get("name") or os.path.basename(f)[:-len(".verdict.json")]
            prev = found.get(name)
            if prev is None or str(rec.get("ts", "")) >= str(prev.get("ts", "")): rec["_path"] = f; found[name] = rec
    return found


def _instant(s):
    """One instant from either clock. A verdict writes UTC without an offset and the manifest's epoch carries
    one: comparing the two as strings made a verdict written at 23:16 UTC look older than an epoch of
    00:35+02:00, which is the same moment as 22:35 UTC (found 16 September 2026, the first time the status
    was asked to read current evidence). Times are compared as instants here, never as text."""
    import datetime as _dt
    t = (s or "").strip().replace("Z", "+00:00")
    try: d = _dt.datetime.fromisoformat(t)
    except ValueError:
        try: d = _dt.datetime.fromisoformat(t[:19])
        except ValueError: return None
    if d.tzinfo is None: d = d.replace(tzinfo=_dt.timezone.utc)   # a verdict writes UTC without saying so
    return d


def _fresh(rec, m, fingerprint):
    """(ok, why): is this verdict current evidence? The epoch and the rule-set fingerprint are the identity;
    a verdict from before the audit is history, not a decision."""
    ts = str(rec.get("ts", ""))
    epoch_s = str(m.get("evidence", {}).get("epoch", ""))
    if not ts: return False, "the verdict carries no timestamp"
    t, e = _instant(ts), _instant(epoch_s)
    if t is None: return False, "the verdict's timestamp %r cannot be read" % ts[:25]
    if e is not None and t < e: return False, "PRE_AUDIT: taken %s, before the evidence epoch %s" % (ts[:19], epoch_s[:19])
    got = (rec.get("policy") or {}).get("rule_set_fingerprint") or rec.get("rule_set_fingerprint")
    if fingerprint and got and got != fingerprint: return False, "taken under rule set %s, current is %s" % (got, fingerprint)
    if fingerprint and not got: return False, "the verdict does not name the rule set it was taken under"
    return True, "current"


_DOC_CACHE = {}


def _document_current(rel):
    """A generated document is evidence only while it still matches the registry it claims to come from.

    The page is rebuilt in memory from the registry and compared with the file. A hand edit, a rule added to
    the registry after the page was last written, or a deleted row all read as INCONCLUSIVE, because a list of
    unknowns that has quietly shrunk looks exactly like a list of unknowns that is complete.
    """
    if rel in _DOC_CACHE: return _DOC_CACHE[rel]
    name = os.path.basename(rel)
    path = os.path.join(ECAD, "..", "docs", name)
    try:
        import rules_render as RR                       # imported here: rules_render imports this module
        fn = RR.SELF_CONTAINED.get(name)
        if fn is None:
            out = (False, "%s is not a document this tool can rebuild, so it cannot be checked" % name)
        elif not os.path.exists(path):
            out = (False, "the record %s does not exist" % name)
        else:
            want = fn(R.load(), coverage())
            have = open(path, errors="replace").read()
            out = ((True, "%s is current with the registry" % name) if want == have
                   else (False, "%s differs from the registry it is generated from: regenerate it" % name))
    except Exception as e:
        out = (False, "%s could not be checked (%s)" % (name, type(e).__name__))
    _DOC_CACHE[rel] = out
    return out


def result_for(rule, letter, cov, vs, m, fingerprint, phase=None):
    """One rule on one board. Everything that is not a positive, current PASS is INCONCLUSIVE or FAIL."""
    rid = rule["id"]; c = cov.get(rid) or {}
    if phase and rule["verification_phase"] not in _phases_up_to(phase):
        return dict(result=NOT_APPLICABLE, why="verified at %s, later than the phase being reported" % rule["verification_phase"], evidence=None)
    w = (c.get("waiver") or {})
    if w.get("active"):
        return dict(result=WAIVED, why="waived by %s until %s: %s" % (w.get("authority"), w.get("expiry"), w.get("reason", "")), evidence=w.get("evidence"))
    if c.get("maturity") in ("OPEN", "DOCUMENTED_ONLY"):
        return dict(result=INCONCLUSIVE, why="no verification: %s" % c.get("note", "")[:160], evidence=None)
    if c.get("maturity") == "SOURCE_UNVERIFIED":
        return dict(result=INCONCLUSIVE, why="the authority behind this rule's limit is not established: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "OWNER_DECISION_REQUIRED":
        return dict(result=INCONCLUSIVE, why="an owner decision is open: %s" % c.get("note", "")[:140], evidence=None)
    if c.get("maturity") == "VERIFIED_MANUALLY":
        doc = (c.get("verification") or {}).get("document")
        if not doc:
            return dict(result=INCONCLUSIVE, why="a manual verification with no record is not evidence", evidence=None)
        ok, why = _document_current(doc)
        return (dict(result=PASS, why=why, evidence=doc) if ok
                else dict(result=INCONCLUSIVE, why=why, evidence=doc))
    if c.get("maturity") == "GENERATED_ONLY":
        return dict(result=INCONCLUSIVE, why="generation intends to comply and nothing verifies it: %s" % c.get("note", "")[:140], evidence=None)
    raw = (c.get("verification") or {}).get("verdict")
    if not raw:
        return dict(result=INCONCLUSIVE, why="the coverage map names no verdict for an enforced rule", evidence=None)
    # A RULE MAY BE VERIFIED BY MORE THAN ONE TOOL, and several are: a placement is judged both by the DRC on
    # the placed board and by the escape-fan predictor, and a part is judged both by the code the BOM carries
    # and by asking the fabricator whether that code is the part. Where a rule names several, the WORST result
    # decides, because a rule is satisfied only when every tool that verifies it says so.
    names = [n.strip().replace("<letter>", letter) for n in str(raw).split(",") if n.strip()]
    worst = None
    for name in names:
        rec = vs.get(name)
        if rec is None:
            r = dict(result=INCONCLUSIVE, why="no %s verdict for this board" % name, evidence=None)
        else:
            ok, why = _fresh(rec, m, fingerprint)
            if not ok:
                r = dict(result=INCONCLUSIVE, why=why, evidence=rec.get("_path"))
            else:
                res = rec.get("result") or rec.get("verdict")
                if res == "PASS": r = dict(result=PASS, why="%s PASS of %s" % (name, rec.get("denominator")), evidence=rec.get("_path"))
                elif res == "FAIL": r = dict(result=FAIL, why="%s FAIL: %s" % (name, str(rec.get("counts"))[:120]), evidence=rec.get("_path"))
                else: r = dict(result=INCONCLUSIVE, why="%s %s" % (name, res), evidence=rec.get("_path"))
        order = {FAIL: 0, INCONCLUSIVE: 1, PASS: 2}
        if worst is None or order[r["result"]] < order[worst["result"]]: worst = r
    return worst


def _phases_up_to(phase):
    i = PHASE_ORDER.index(phase)
    return PHASE_ORDER[:i + 1]


def board_status(letter, reg=None, facts=None, cov=None, m=None, fingerprint=None, phase=None):
    reg = reg or R.load(); facts = facts if facts is not None else R.facts(); cov = cov if cov is not None else coverage()
    m = m or manifest(); fingerprint = fingerprint or R.fingerprint(reg)
    vs = _verdicts(letter, m)
    rows = []
    for rule, why in R.rules_for(letter, reg, facts):
        r = result_for(rule, letter, cov, vs, m, fingerprint, phase)
        rows.append(dict(rule=rule["id"], domain=rule["domain"], short_name=rule["short_name"],
                         release_effect=rule["release_effect"], verification_phase=rule["verification_phase"],
                         maturity=(cov.get(rule["id"]) or {}).get("maturity", "UNASSESSED"),
                         applies_because=why, **r))
    return dict(board=letter, rule_set_fingerprint=fingerprint, manifest_version=m.get("manifest_version"),
                evidence_epoch=m.get("evidence", {}).get("epoch"), verdicts_seen=len(vs), rows=rows)


def counts(rows, required_only=True):
    rs = [r for r in rows if r["result"] != NOT_APPLICABLE]
    if required_only: rs = [r for r in rs if r["release_effect"] in ("BLOCKER", "MUST_JUSTIFY")]
    d = len(rs) or 1
    c = {k: sum(1 for r in rs if r["result"] == k) for k in (PASS, FAIL, INCONCLUSIVE, WAIVED)}
    pct = {k.lower() + "_percent": round(100.0 * v / d, 1) for k, v in c.items()}
    return dict(denominator=len(rs), **c, **pct)


def gate_state(rows, m):
    """Reported BEFORE any percentage. A blocker that fails, or a board or deliverable the manifest expects
    and does not have, is NOT_READY; a blocker with no current evidence is INCONCLUSIVE; anything else with
    every pre-fabrication blocker satisfied is READY_FOR_PROTOTYPE."""
    blockers = [r for r in rows if r["release_effect"] == "BLOCKER" and r["result"] != NOT_APPLICABLE]
    pre = [r for r in blockers if r["verification_phase"] in PRE_FAB]
    state = "READY_FOR_PROTOTYPE"
    if any(r["result"] == FAIL for r in blockers): state = "NOT_READY"
    elif any(r["result"] == INCONCLUSIVE for r in pre): state = "INCONCLUSIVE"
    if m.get("promotion", {}).get("frozen") and state == "READY_FOR_PROTOTYPE": state = "INCONCLUSIVE"
    if any(r["result"] == WAIVED for r in blockers): state += " WITH_WAIVERS"
    return state


def main(argv):
    reg = R.load(); facts = R.facts(); cov = coverage(); m = manifest(); fp = R.fingerprint(reg)
    phase = argv[argv.index("--phase") + 1] if "--phase" in argv else None
    only = [argv[argv.index("--board") + 1]] if "--board" in argv else list(m["boards"])
    out_dir = argv[argv.index("--out-dir") + 1] if "--out-dir" in argv else os.path.join(ECAD, "out", "rule-audit")
    os.makedirs(out_dir, exist_ok=True)
    all_rows, per_board = [], {}
    for letter in only:
        st = board_status(letter, reg, facts, cov, m, fp, phase)
        per_board[letter] = st; all_rows += st["rows"]
        json.dump(st, open(os.path.join(out_dir, "%s.json" % letter), "w"), indent=1)
        c = counts(st["rows"])
        print("%-3s %-28s %s" % (letter.upper(), gate_state(st["rows"], m),
                                 "PASS %d  FAIL %d  INCONCLUSIVE %d  WAIVED %d  of %d required rule(s)"
                                 % (c[PASS], c[FAIL], c[INCONCLUSIVE], c[WAIVED], c["denominator"])))
    # SGN-001, and it is a DIFFERENT question from readiness: not "does this board pass" but "did every rule
    # that applies to it reach a decision at all". A rule that applies and produces nothing is the failure this
    # whole registry exists to make impossible, and it would otherwise be invisible, since a rule missing from
    # the table looks exactly like a rule that is not applicable.
    # It is written at the END of a run and read by the NEXT one, like every other gate's verdict: a tool does
    # not read its own answer while producing it. So SGN-001 reports on the previous computation, which is what
    # evidence is, and a first run on a fresh tree leaves it INCONCLUSIVE rather than assuming itself correct.
    unresolved = [r for r in all_rows if r["result"] not in R.RESULTS]
    val, _warn = R.validate(reg)          # (errors, warnings): a warning is not a missing decision
    no_cov = sorted({r["rule"] for r in all_rows if r["rule"] not in cov})
    complete = not (unresolved or val or no_cov)
    _v.write("rules_complete", _v.PASS if complete else _v.FAIL,
             counts={"pairs": len(all_rows), "unresolved": len(unresolved),
                     "registry_errors": len(val), "rules_without_coverage": len(no_cov)},
             denominator=len(all_rows),
             evidence=([str(x)[:110] for x in val[:10]]
                       + ["%s on %s produced %r" % (r["rule"], r.get("board", "?"), r["result"]) for r in unresolved[:10]]
                       + ["%s has no coverage entry" % x for x in no_cov[:10]]),
             inputs={"manifest_version": m.get("manifest_version"), "rule_set_fingerprint": fp},
             note=("every applicable rule reached one of the five results on every board in the manifest"
                   if complete else "a rule that applies reached no result, which is what the registry exists to prevent"),
             # a SET-LEVEL verdict, so it goes where the set-level gates write and every board can read it
             out_dir=os.path.join(ECAD, "out"), quiet=True)
    agg = counts(all_rows); state = gate_state(all_rows, m)
    summary = dict(manifest_version=m.get("manifest_version"), rule_set_fingerprint=fp,
                   promotion_frozen=bool(m.get("promotion", {}).get("frozen")), phase=phase or "ALL",
                   gate_state=state, counts=agg, boards={k: counts(v["rows"]) for k, v in per_board.items()})
    json.dump(summary, open(os.path.join(out_dir, "summary.json"), "w"), indent=1)
    print("\nreadiness: %s   (manifest %s, rule set %s%s)" % (state, m.get("manifest_version"), fp,
          ", promotion frozen" if m.get("promotion", {}).get("frozen") else ""))
    print("verified %.1f%%  waived %.1f%%  failed %.1f%%  inconclusive %.1f%%  of %d applicable required rule-board pair(s)"
          % (agg["pass_percent"], agg["waived_percent"], agg["fail_percent"], agg["inconclusive_percent"], agg["denominator"]))
    if "--json" in argv: print(json.dumps(summary, indent=1, sort_keys=True))
    res = _v.PASS if state.startswith("READY") else (_v.FAIL if state.startswith("NOT_READY") else _v.INCONCLUSIVE)
    return _v.write("rules_status", res, counts=agg, denominator=agg["denominator"],
                    evidence=["%s %s %s" % (r["rule"], r["result"], r["why"][:80]) for r in all_rows if r["result"] in (FAIL, INCONCLUSIVE)][:40],
                    inputs={"manifest_version": m.get("manifest_version"), "rule_set_fingerprint": fp},
                    note="gate state %s; %s" % (state, "promotion frozen" if m.get("promotion", {}).get("frozen") else "promotion open"),
                    out_dir=out_dir)


if __name__ == "__main__": sys.exit(main(sys.argv[1:]))
