#!/usr/bin/env python3
"""Render the FAILOVER-FABRIC.md map tables from fabmap.json (read-only; MESHSAT-1357 stream FAB, 26 Sep 2026).

Usage: render.py <out_dir>/fabmap.json > tables.md
Every cell is read from the candidate netlist's row; the last column says whether the committed B21 netlist agrees.
"""
import json
import re
import sys

d = json.load(open(sys.argv[1]))
rows = d['rows']


def short(v):
    # a part value here often carries its reason in brackets; keep "REF value" and drop the reason
    out, i = [], 0
    while i < len(v):
        m = re.match(r'([A-Z]+\d+)\(', v[i:])
        if not m:
            out.append(v[i]); i += 1; continue
        ref = m.group(1); j = i + m.end(); depth = 1; k = j
        while k < len(v) and depth:
            depth += {'(': 1, ')': -1}.get(v[k], 0); k += 1
        val = v[j:k - 1].split(' (')[0]
        out.append('%s %s' % (ref, val)); i = k
    txt = ''.join(out)
    return re.sub(r' \((?:HCSL|PCIe|REFCLK|IREF|REXT|break)[^)]*\)', '', txt)


def series(c):
    out = []
    for p in c['paths']:
        m = re.match(r'(.*?) ?-> ', p)
        via = m.group(1) if m else ''
        out.append(short(via) if via else 'direct')
    s = sorted(set(out))
    return '; '.join(s) if s else '-'


def far(c):
    fs = []
    for p in c['paths']:
        m = re.search(r'-> (\S+ .*)$', p)
        fs.append(m.group(1) if m else p)
    return '; '.join(fs) if fs else '(none)'


def shunts(c):
    return '; '.join(short(s) for s in c['shunts']) or '-'


def b21(r):
    c, o = r['cand'], r['b21']
    if c['net'] == o['net'] and c['paths'] == o['paths'] and c['shunts'] == o['shunts']:
        return 'same'
    if o['check'] == 'MISMATCH':
        return '**differs: %s** (%s)' % (far(o), o['net'])
    return 'differs: %s; %s' % (series(o) + ' to ' + far(o), shunts(o))


def table(kind, cols, pick, filt=None):
    print('| ' + ' | '.join(cols) + ' |')
    print('|' + '---|' * len(cols))
    for r in rows:
        if r['kind'] != kind or (filt and not filt(r)):
            continue
        print('| ' + ' | '.join(pick(r)) + ' |')
    print()


def pin(r):
    return '%s.%s %s' % (r['ref'], r['pin'], r['cand']['fn'])


print('<!-- generated by render.py from fabmap.json; candidate %s, B21 %s -->' % (d['meta']['candidate_sha256'][:16], d['meta']['b21_sha256'][:16]))
for kind, title in (('pcie-up', 'PCIe upstream'), ('pcie-ctl', 'PCIe control and the module clock'),
                    ('refclk', 'reference clock tree'), ('pcie-dn', 'PCIe downstream'), ('strap', 'switch test straps'),
                    ('usb-home', 'USB home host (USB3-0)'), ('usb-fail', 'USB failover host (USB3-1)'),
                    ('usb-ctl', 'USB control pins'), ('bank', 'bank side'), ('hdmi', 'HDMI0'), ('hdmi-ctl', 'HDMI switch control and output'),
                    ('eth', 'Ethernet'), ('hb', 'heartbeat')):
    print('#### %s' % title)
    print()
    table(kind, ['Slot/bank', 'Signal', 'Start pin', 'Net (candidate)', 'In series', 'Far end', 'Shunt', 'Check', 'B21 (main)'],
          lambda r: [str(r['slot']), r['label'], pin(r), r['cand']['net'] or '-', series(r['cand']), far(r['cand']),
                     shunts(r['cand']), r['cand']['check'], b21(r)])
