#!/usr/bin/env python3
"""The regeneration parity comparator: what is noise, and that nothing else is (MESHSAT-1357, 26 September 2026).

`regen_compare.py` is the instrument behind the owner's condition 5 ("generator is current" needs parity). W7 ran
it on the KiCad box on 25 September (box 52646493, commit 82dd1e4d) and validated it against the six real boards
with positive and negative controls (its validate.json, sha16 afa316ed906e6630): an all-dates copy of every
schematic read PARITY_AFTER_NOISE, and a date or a value inside a placed part, a lib_symbols body or a wire read
DIFFERENT with the right bucket. The committed copy reproduces that draft's output on all 48 of those real-file
comparisons (checked on 26 September against the draft, sha16 8099a3df2ba7b5c2). These fixtures carry the same
controls on small synthetic files, so they run anywhere and cannot drift with the boards.

The round-1 comparator had no N2 (the page-frame date); the round-1 challenger showed a date-only change then read
DIFFERENT. `t_a_comparator_without_the_page_frame_date_is_caught_by_these_fixtures` keeps that defect findable.
"""
import os, sys, json, re, shutil, subprocess, tempfile

TOOLS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, TOOLS)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from harness import Skip
import regen_compare as RC


def _sch(date="2026-09-20", label="X7", value="10k", lib_body='(pin passive line (at 0 3.81 270) (length 1.27))',
         wire_x="50.80"):
    frame = lambda k: ('\t(text "page %d of 2   MeshSat field kit V2, CERN-OHL-S-2.0   PROTOTYPE, nothing built   %s" '
                       '(exclude_from_sim no) (at 400 290 0) (effects (font (size 1.27 1.27))) (uuid "f%d"))\n' % (k, date, k))
    head = lambda k: '\t(text "PCB-X TEST BOARD   %s" (exclude_from_sim no) (at 10 10 0) (uuid "h%d"))\n' % (label, k)
    return ('(kicad_sch (version 20250114) (generator "eeschema")\n'
            '\t(paper "User" 838.2 297.18)\n'
            '\t(title_block (title "MeshSat Field Kit carrier - PCB-X TEST") (date "%s") (rev "A") (company "MeshSat") '
            '(comment 1 "Phase %s schematic, generated by tools/gen_sch_x.py"))\n'
            '\t(lib_symbols\n\t\t(symbol "Device:R" (in_bom yes) (on_board yes)\n\t\t\t%s\n\t\t)\n\t)\n'
            '\t(symbol (lib_id "Device:R") (at 50.8 35.56 0) (unit 1) (in_bom yes) (on_board yes) (uuid "u1")\n'
            '\t\t(property "Reference" "R1" (at 0 0 0))\n\t\t(property "Value" "%s" (at 0 0 0))\n'
            '\t\t(property "Footprint" "Resistor_SMD:R_0603_1608Metric" (at 0 0 0))\n\t)\n'
            '\t(wire (pts (xy %s 30.48) (xy 60.96 30.48)) (stroke (width 0) (type default)) (uuid "w1"))\n'
            % (date, label, lib_body, value, wire_x)) + frame(1) + frame(2) + head(1) + head(2) + ")\n"


def _net(date="2026-09-20T12:00:00+0000", tdate="2026-09-20", label="X7", pin="1", tool="Eeschema 9.0.9", order=("R1", "R2"),
         tstamp="t1"):
    comp = {"R1": '    (comp (ref "R1")\n      (value "10k")\n      (footprint "Resistor_SMD:R_0603_1608Metric")\n'
                  '      (libsource (lib "Device") (part "R") (description "Resistor"))\n      (tstamps "%s"))\n' % tstamp,
            "R2": '    (comp (ref "R2")\n      (value "1k")\n      (footprint "Resistor_SMD:R_0603_1608Metric")\n'
                  '      (libsource (lib "Device") (part "R") (description "Resistor"))\n      (tstamps "t2"))\n'}
    return ('(export (version "E")\n  (design\n    (source "/root/x/pcb-x.kicad_sch")\n    (date "%s")\n    (tool "%s")\n'
            '    (sheet (number "1") (name "/") (tstamps "/")\n      (title_block\n        (title "MeshSat Field Kit carrier - PCB-X TEST")\n'
            '        (company "MeshSat")\n        (rev "A")\n        (date "%s")\n        (source "pcb-x.kicad_sch")\n'
            '        (comment (number "1") (value "Phase %s schematic")))))\n  (components\n%s  )\n  (nets\n'
            '    (net (code "1") (name "/SIG")\n      (node (ref "R1") (pin "%s") (pintype "passive"))\n'
            '      (node (ref "R2") (pin "1") (pintype "passive")))\n  )\n)\n'
            % (date, tool, tdate, label, "".join(comp[r] for r in order), pin))


def _put(d, name, text):
    p = os.path.join(d, name); open(p, "w").write(text); return p


def _dir():
    return tempfile.mkdtemp(prefix="rc-")


# ---------------------------------------------------------------- schematic
def t_every_date_the_generator_writes_is_noise_and_nothing_else_is():
    d = _dir(); a = _put(d, "a.kicad_sch", _sch())
    r = RC.cmp_sch(a, a); assert r["result"] == "PARITY", r
    r = RC.cmp_sch(a, _put(d, "b.kicad_sch", _sch(date="2027-01-02")))           # ACCEPTABLE: title and both frames
    assert r["result"] == "PARITY_AFTER_NOISE", r
    assert r["noise_removed"][1]["N1_title_date"] == 1 and r["noise_removed"][1]["N2_page_frame_date"] == 2, r["noise_removed"]
    r = RC.cmp_sch(a, _put(d, "c.kicad_sch", _sch(date="2027-01-02", label="ZZ9")))
    assert r["result"] == "PARITY_AFTER_NOISE" and r.get("labels_differ") and r["phase_labels"] == [["X7"], ["ZZ9"]], r


def t_a_date_or_a_value_in_a_placed_part_is_a_parts_difference():
    d = _dir(); a = _put(d, "a.kicad_sch", _sch())
    for v in ("2026-09-20 10k", "10kX"):                                          # DEFECTIVE: not on the noise list
        r = RC.cmp_sch(a, _put(d, "v.kicad_sch", _sch(value=v)))
        assert r["result"] == "DIFFERENT" and r["bucket_hint"] == "PARTS", r
        assert r["parts_changed"][0][0] == "R1", r["parts_changed"]


def t_a_library_body_and_a_moved_wire_are_their_own_buckets():
    d = _dir(); a = _put(d, "a.kicad_sch", _sch())
    r = RC.cmp_sch(a, _put(d, "l.kicad_sch", _sch(lib_body='(pin passive line (at 0 3.81 270) (length 2.54))')))
    assert r["result"] == "DIFFERENT" and r["bucket_hint"] == "LIBRARY" and r["lib_symbols_changed"] == ["Device:R"], r
    r = RC.cmp_sch(a, _put(d, "w.kicad_sch", _sch(wire_x="52.07")))
    assert r["result"] == "DIFFERENT" and r["bucket_hint"] == "DRAWING_ONLY" and r["changed_lines"] == 2, r


def t_a_comparator_without_the_page_frame_date_is_caught_by_these_fixtures():
    """The round-1 defect as a negative control: with N2 switched off, the acceptable all-dates fixture reads
    DIFFERENT, which is the failure the round-1 challenger found."""
    d = _dir(); a = _put(d, "a.kicad_sch", _sch()); b = _put(d, "b.kicad_sch", _sch(date="2027-01-02"))
    saved = RC._N2; RC._N2 = re.compile(r"(?!x)x(x)(x)(x)")   # never matches, three groups like N2
    try: r = RC.cmp_sch(a, b)
    finally: RC._N2 = saved
    assert r["result"] == "DIFFERENT", "a comparator without N2 passed a date-only change: the fixture does not bite"


# ---------------------------------------------------------------- netlist
def t_the_export_header_is_noise_and_the_content_hash_says_so():
    d = _dir(); a = _put(d, "a.net", _net())
    r = RC.cmp_net(a, _put(d, "b.net", _net(date="2027-01-02T00:00:00+0000", tdate="2027-01-02", tool="Eeschema 9.0.99")))
    assert r["result"] == "PARITY_AFTER_NOISE", r
    assert r["content_hash"][0] == r["content_hash"][1], r["content_hash"]
    assert r["noise_removed"][1]["N3_design_source_date_tool"] == 1 and r["noise_removed"][1]["N4_title_date"] == 1, r


def t_a_moved_node_is_a_netlist_difference():
    d = _dir(); a = _put(d, "a.net", _net())
    r = RC.cmp_net(a, _put(d, "b.net", _net(pin="2")))                            # DEFECTIVE
    assert r["result"] == "DIFFERENT" and r["nets_changed"][0][0] == "/SIG", r
    assert r["content_hash"][0] != r["content_hash"][1]


def t_an_export_order_is_not_a_design_difference_and_a_uuid_shift_is_counted():
    d = _dir(); a = _put(d, "a.net", _net())
    r = RC.cmp_net(a, _put(d, "b.net", _net(order=("R2", "R1"))))
    assert r["result"] == "DIFFERENT_TEXT_SAME_CONTENT", r
    r = RC.cmp_net(a, _put(d, "c.net", _net(tstamp="t9")))
    assert r["result"] == "DIFFERENT" and r["comps_uuid_shifted"] == 1 and not r["comps_changed"], r


# ---------------------------------------------------------------- sidecars, BOM, ERC
def t_the_provenance_sidecar_moves_only_with_its_schematic():
    import hashlib
    d = _dir(); sa = _put(d, "a.kicad_sch", _sch()); sb = _put(d, "b.kicad_sch", _sch(date="2027-01-02"))
    h = lambda p: hashlib.sha256(open(p, "rb").read()).hexdigest()[:32]
    pa = _put(d, "a.prov.json", json.dumps({"generator_sha": "g", "schematic_sha256": h(sa), "taken": "1"}))
    pb = _put(d, "b.prov.json", json.dumps({"generator_sha": "g", "schematic_sha256": h(sb), "taken": "2"}))
    r = RC.cmp_prov(pa, pb, sa, sb, RC.cmp_sch(sa, sb)["result"])
    assert r["result"] == "PARITY_AFTER_NOISE" and r["sidecar_self_consistent"] == [True, True], r
    liar = _put(d, "c.prov.json", json.dumps({"generator_sha": "g", "schematic_sha256": "0" * 32, "taken": "2"}))
    r = RC.cmp_prov(pa, liar, sa, sb, "PARITY_AFTER_NOISE")                       # DEFECTIVE: not self-consistent
    assert r["result"] == "DIFFERENT", r
    r = RC.cmp_json(_put(d, "i1.json", '{"written": "1", "rails": 2}'), _put(d, "i2.json", '{"written": "2", "rails": 2}'), "intent", ("written",))
    assert r["result"] == "PARITY_AFTER_NOISE", r
    r = RC.cmp_json(_put(d, "i3.json", '{"written": "1", "rails": 2}'), _put(d, "i4.json", '{"written": "1", "rails": 3}'), "intent", ("written",))
    assert r["result"] == "DIFFERENT" and r["keys_changed"] == ["rails"], r


def t_a_bom_is_a_row_set_and_an_erc_is_a_multiset_of_findings():
    d = _dir()
    a = _put(d, "a.csv", "Reference,Value\nR1,10k\nR2,1k\n")
    assert RC.cmp_bom(a, _put(d, "b.csv", "Reference,Value\nR2,1k\nR1,10k\n"))["result"] == "PARITY_AFTER_NOISE"
    assert RC.cmp_bom(a, _put(d, "c.csv", "Reference,Value\nR1,10k\nR2,2k\n"))["result"] == "DIFFERENT"
    v = lambda x, extra=False: json.dumps({"sheets": [{"violations": [
        {"severity": "warning", "type": "pin_not_connected", "description": "Pin not connected",
         "items": [{"description": "Symbol R1 Pin 2", "pos": {"x": x, "y": 1}, "uuid": "u%s" % x}]}]
        + ([{"severity": "error", "type": "pin_to_pin", "description": "x", "items": []}] if extra else [])}]})
    e1 = _put(d, "e1.json", v(1.0))
    assert RC.cmp_erc(e1, _put(d, "e2.json", v(9.0)))["result"] == "PARITY_AFTER_NOISE"   # a position is not a finding
    assert RC.cmp_erc(e1, _put(d, "e3.json", v(1.0, extra=True)))["result"] == "DIFFERENT"


def t_the_board_against_its_netlist_is_read_by_sch002_s_companion():
    import test_netlist_parts as NPT
    d = _dir()
    n = _put(d, "b.net", NPT._netlist(NPT.D12_NET)); b = _put(d, "b.kicad_pcb", NPT._board(NPT.D12_PCB))
    r = RC.board_vs_net(b, n)
    assert r["result"] == "DIFFERENT" and len(r["value"]) == 5 and len(r["footprint"]) == 2, r
    b2 = _put(d, "c.kicad_pcb", NPT._board([(x, v, f.split(":")[-1]) for x, v, f in NPT.D12_NET]))
    assert RC.board_vs_net(b2, n)["result"] == "PARITY"


def t_a_reference_on_one_side_only_is_a_parity_difference():
    """DEFECTIVE: board E's D9 and D10 are in the netlist and not on the committed E17 board. The draft of 25
    September read that DIFFERENT; the first committed copy counted values and lands alone and read PARITY.
    ACCEPTABLE: a board-only mounting hole or test point is netlist_board's declared exception, not a difference."""
    import test_netlist_parts as NPT
    d = _dir()
    net = NPT.D12_NET + [("D9", "SMCJ40A", "Diode_SMD:D_SMC"), ("D10", "USBLC6-2SC6", "Package_TO_SOT_SMD:SOT-23-6")]
    same = [(x, v, f.split(":")[-1]) for x, v, f in NPT.D12_NET]
    n = _put(d, "e.net", NPT._netlist(net))
    r = RC.board_vs_net(_put(d, "e.kicad_pcb", NPT._board(same)), n)
    assert r["result"] == "DIFFERENT" and r["only_netlist"] == ["D10", "D9"], r
    n2 = _put(d, "e2.net", NPT._netlist(NPT.D12_NET))
    r = RC.board_vs_net(_put(d, "e2.kicad_pcb", NPT._board(same + [("H1", "MountingHole", "MountingHole_3.2mm_M3"),
                                                                  ("TP1", "TP", "TestPoint_Pad_D1.0mm")])), n2)
    assert r["result"] == "PARITY" and r["only_board_declared_bench"] == ["H1", "TP1"], r
    r = RC.board_vs_net(_put(d, "e3.kicad_pcb", NPT._board(same + [("U99", "X", "SOT-23")])), n2)
    assert r["result"] == "DIFFERENT" and r["only_board"] == ["U99"], r


# ---------------------------------------------------------------- the box run
def t_the_box_run_reads_the_board_directories_from_the_clone_and_judges_every_artefact():
    """End to end on a throwaway clone: the committed files come from HEAD, the regenerated ones differ only by
    noise, and every row reads PARITY or PARITY_AFTER_NOISE; a board whose regeneration is absent reads
    MISSING_INPUT, which is not a pass."""
    if not shutil.which("git"): raise Skip("no git here")
    repo = _dir(); ecad = os.path.join(repo, "v2", "ecad"); tools = os.path.join(ecad, "tools")
    os.makedirs(os.path.join(tools, "routeflow")); os.makedirs(os.path.join(ecad, "pcb-x-x7", "out"))
    json.dump({"board": "pcb-x", "project": "v2/ecad/pcb-x-x7"}, open(os.path.join(tools, "routeflow", "x.json"), "w"))
    json.dump({"board": "pcb-y", "project": "v2/ecad/pcb-y"}, open(os.path.join(tools, "routeflow", "y.json"), "w"))
    open(os.path.join(tools, "gen_sch_x.py"), "w").write("# generator\n")      # y has none, so it is not a board here
    import test_netlist_parts as NPT
    parts = [("R1", "10k", "Resistor_SMD:R_0603_1608Metric"), ("R2", "1k", "Resistor_SMD:R_0603_1608Metric")]
    base = os.path.join(ecad, "pcb-x-x7")
    _put(base, "pcb-x.kicad_sch", _sch()); _put(base, "pcb-x.kicad_pcb", NPT._board([(r, v, f.split(":")[-1]) for r, v, f in parts]))
    _put(os.path.join(base, "out"), "pcb-x.net", _net())
    _put(os.path.join(base, "out"), "pcb-x-intent.json", '{"written": "1", "rails": 2}')
    _put(os.path.join(base, "out"), "pcb-x.net.prov.json", '{"generator_sha": "g", "taken": "1"}')
    g = ["git", "-C", repo, "-c", "user.name=fixture", "-c", "user.email=fixture@example.invalid"]
    subprocess.run(g + ["init", "-q"], check=True); subprocess.run(g + ["add", "-A"], check=True)
    subprocess.run(g + ["commit", "-q", "-m", "fixture"], check=True)
    assert RC.boards_of(repo) == {"x": ("pcb-x-x7", "pcb-x")}, RC.boards_of(repo)
    out = _dir(); o = os.path.join(out, "x")
    for sub in ("ref", "regen"): os.makedirs(os.path.join(o, sub))
    _put(os.path.join(o, "ref"), "pcb-x.net", _net(date="2027-01-02T00:00:00+0000"))
    _put(os.path.join(o, "ref"), "pcb-x-bom.csv", "Reference,Value\nR1,10k\nR2,1k\n")
    _put(os.path.join(o, "ref"), "pcb-x-erc.json", '{"sheets": []}')
    _put(os.path.join(o, "regen"), "pcb-x.kicad_sch", _sch(date="2027-01-02"))
    _put(os.path.join(o, "regen"), "pcb-x.net", _net(date="2027-01-02T00:00:00+0000", tdate="2027-01-02"))
    _put(os.path.join(o, "regen"), "pcb-x-intent.json", '{"written": "2", "rails": 2}')
    _put(os.path.join(o, "regen"), "pcb-x.net.prov.json", '{"generator_sha": "g", "taken": "2"}')
    _put(os.path.join(o, "regen"), "pcb-x-bom.csv", "Reference,Value\nR2,1k\nR1,10k\n")
    _put(os.path.join(o, "regen"), "pcb-x-erc.json", '{"sheets": []}')
    res = RC.box(repo, out)
    bad = {k: v["result"] for k, v in res["x"].items() if not str(v["result"]).startswith("PARITY")}
    assert not bad, bad
    # a netlist_board verdict beside the run is reported and does not decide the exit code: it reads PASS, never
    # PARITY, and counting it made every clean run exit 1 (the draft's behaviour, carried into the first copy)
    os.makedirs(os.path.join(o, "v-committed"))
    json.dump({"tool": "netlist_board", "verdict": "PASS", "counts": {}}, open(os.path.join(o, "v-committed", "netlist_board.verdict.json"), "w"))
    rc = RC.main(["box", repo, out])
    assert rc == 0, "a clean run with a netlist_board PASS beside it exited %s" % rc
    assert json.load(open(os.path.join(out, "parity.json")))["x"]["sch002_v-committed"]["result"] == "PASS"
    os.remove(os.path.join(o, "regen", "pcb-x-bom.csv"))
    res = RC.box(repo, out)
    assert res["x"]["bom_export_committed_vs_regen"]["result"] == "MISSING_INPUT", res["x"]["bom_export_committed_vs_regen"]
