#!/usr/bin/env python3
"""Every order note opens with its board's own readiness, so no order folder reads as an approved package
(owner decision 41, ruled 25 September 2026 at the recommendation; executed 26 September 2026, MESHSAT-1357).

WHY. `v2/release/revA/order/` is the one artefact of this pipeline that travels to the fabricator with a board,
and a current-looking order folder is a more convincing package than a stale one while promotion is frozen. The
owner's ruling rebuilds the set and quarantines it in the same commit: every ORDER-NOTES.txt carries the board's
readiness at the top, in the four fields the owner named on 16 September 2026 for board E's hold
(ROUTING_STATUS, ELECTRICAL_PROTECTION_STATUS, FAB_READINESS, PUBLICATION_STATUS).

WHERE THE FOUR VALUES COME FROM, and none of them is typed:

  * a board HELD by an open decision (`pcb_board_holds.yaml`) carries the hold's four fields verbatim, because
    they are the owner's words and are carried verbatim wherever the board is reported (rules_lib.HOLD_FIELDS);
  * any other board's values are computed from the rule registry, exactly as the status pages are:
      ROUTING_STATUS                the board's ROUTING rules (RTE-001, RTE-002),
      ELECTRICAL_PROTECTION_STATUS  its TRANSIENT_PROTECTION and ENERGY_STORAGE rules (TRN-001, BAT-001, BAT-002
                                    where they apply),
      FAB_READINESS                 the readiness gate state (`rules_status.gate_state`); anything short of
                                    READY_FOR_PROTOTYPE is NOT_READY,
      PUBLICATION_STATUS            NOT_RELEASED while promotion is frozen or the board is not ready; releasing
                                    a board is the owner's and never this tool's.
    Each of the first two reads PASS only when every applicable required rule of its domains is PASS or WAIVED,
    FAIL when any FAILs, INCONCLUSIVE otherwise, and NOT_APPLICABLE when no such rule applies to the board.

WHAT IT DOES NOT DO. It never changes a byte of the note below the block: the provenance lines DOC-002 reads, the
bench-fit lists and the fabrication notes stay exactly as `make_handoff.py` wrote them. And the numbers it writes
are a dated reading: the block names the day and the rule set it was computed under, and a later run replaces it.

Usage: order_readiness.py [<release dir>]            re-stamp every order folder's note and the order README
       order_readiness.py [<release dir>] --check    exit 1 if a note in the order set carries no complete block
"""
import os, re, sys, json, glob, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

FIELDS = ("ROUTING_STATUS", "ELECTRICAL_PROTECTION_STATUS", "FAB_READINESS", "PUBLICATION_STATUS")
HEAD = "READINESS OF THIS FOLDER: QUARANTINED, NOT_FOR_FAB"
TAIL = "END OF READINESS"
README_BEGIN = "<!-- readiness:begin (generated by tools/order_readiness.py; do not edit) -->"
README_END = "<!-- readiness:end -->"
ROUTING_DOMAINS = ("ROUTING",)
PROTECTION_DOMAINS = ("TRANSIENT_PROTECTION", "ENERGY_STORAGE")
REQUIRED = ("BLOCKER", "MUST_JUSTIFY")
PART_RULES = ("CMP-002", "SUP-001")
FOLDER = re.compile(r"^(PCB-[A-Z0-9]+-[A-Z0-9]+)-([A-Z]+\d+)$")


def release_dir():
    return os.path.join(os.path.dirname(os.path.dirname(HERE)), "release", os.environ.get("MESHSAT_FK_REV", "revA"))


def folder_board(name, m):
    """(letter, stem, folder phase) of an order folder name such as PCB-C-DISPLAY-C24, or None when the name is
    not a board's order folder. The stem is matched against the manifest, never guessed from the letters."""
    f = FOLDER.match(name or "")
    if not f: return None
    stem = f.group(1).lower()
    for letter, b in (m.get("boards") or {}).items():
        if (b or {}).get("project") == stem:
            return letter, stem, f.group(2)
    return None


def _domain_state(rows, domains):
    """(value, n_applicable, counts) over the required rules of the named domains."""
    rs = [r for r in rows if r["domain"] in domains and r["release_effect"] in REQUIRED and r["result"] != "NOT_APPLICABLE"]
    if not rs: return "NOT_APPLICABLE", [], {}
    c = {}
    for r in rs: c[r["result"]] = c.get(r["result"], 0) + 1
    if c.get("FAIL"): v = "FAIL"
    elif all(r["result"] in ("PASS", "WAIVED") for r in rs): v = "PASS"
    else: v = "INCONCLUSIVE"
    return v, rs, c


def _count_text(rs, c):
    return "%s (%s)" % (", ".join("%s %s" % (r["rule"], r["result"]) for r in rs),
                        ", ".join("%d %s" % (c[k], k) for k in sorted(c)))


class _Ctx:
    """The registry, the facts, the manifest and the holds, read once per run."""
    def __init__(self):
        import rules_lib as R
        import rules_status as S
        self.R, self.S = R, S
        self.m = S.manifest()
        self.reg = R.load()
        self.facts = R.facts()
        self.cov = S.coverage()
        self.fp = R.fingerprint(self.reg)
        self.holds = R.board_holds()
        self._st = {}
        self._dec = None

    def decision(self, n):
        """One entry of pcb_decisions.yaml by number, or None."""
        if self._dec is None:
            try:
                import yaml
                self._dec = {str(d.get("n")): d for d in (yaml.safe_load(open(os.path.join(HERE, "pcb_decisions.yaml"),
                                                                                   encoding="utf-8")) or {}).get("decisions", [])}
            except Exception:
                self._dec = {}
        return self._dec.get(str(n))

    def status(self, letter):
        if letter not in self._st:
            self._st[letter] = self.S.board_status(letter, self.reg, self.facts, self.cov, self.m, self.fp)
        return self._st[letter]


def fields(letter, ctx):
    """{field: value} and the lines that explain each, for one board as this tree holds it."""
    st = ctx.status(letter)
    rows = st["rows"]
    gate = ctx.S.gate_state(rows, ctx.m)
    cnt = ctx.S.counts(rows)
    rv, rrs, rc = _domain_state(rows, ROUTING_DOMAINS)
    pv, prs, pc = _domain_state(rows, PROTECTION_DOMAINS)
    failing = sorted({r["rule"] for r in rows if r["release_effect"] == "BLOCKER" and r["result"] == "FAIL"})
    frozen = bool((ctx.m.get("promotion") or {}).get("frozen"))
    computed = {
        "ROUTING_STATUS": rv,
        "ELECTRICAL_PROTECTION_STATUS": pv,
        "FAB_READINESS": gate if gate.startswith("READY") else "NOT_READY",
        "PUBLICATION_STATUS": "NOT_RELEASED" if (frozen or not gate.startswith("READY")) else "OWNER_TO_RELEASE",
    }
    why = {
        "ROUTING_STATUS": "the board's routing rules read %s" % (_count_text(rrs, rc) if rrs else "nothing: none applies"),
        "ELECTRICAL_PROTECTION_STATUS": "the board's protection rules read %s" % (_count_text(prs, pc) if prs else "nothing: none applies"),
        "FAB_READINESS": "the readiness gate reads %s over %d required rule-board pairs: %d PASS, %d FAIL, %d INCONCLUSIVE, %d WAIVED%s"
                         % (gate, cnt["denominator"], cnt["PASS"], cnt["FAIL"], cnt["INCONCLUSIVE"], cnt["WAIVED"],
                            ("; blockers failing: %s" % ", ".join(failing[:14]) + (" and %d more" % (len(failing) - 14) if len(failing) > 14 else "")) if failing else ""),
        "PUBLICATION_STATUS": ("board promotion has been frozen by the owner since %s (readiness manifest), so no folder here is released; "
                               "this set was rebuilt under owner decision 41 of 25 September 2026 as a quarantined record. Nothing is "
                               "ordered from it and no cart line was touched" % str((ctx.m.get("promotion") or {}).get("frozen_at", ""))[:10])
                              if frozen else "a board is released only by the owner",
    }
    # THE PARTS, NAMED, where the order-code rules fail: this note travels with the BOM, and "CMP-002 FAIL" does not
    # tell the person holding it which line is wrong. Read from the verdict that decided the rule, never re-derived.
    parts = []
    for r in rows:
        if r["rule"] in PART_RULES and r["result"] == "FAIL" and isinstance(r.get("evidence"), str):
            try: ev = json.load(open(r["evidence"], encoding="utf-8")).get("evidence") or []
            except (OSError, ValueError): ev = []
            for e in ev:
                e = " ".join(str(e).split())
                if e not in parts: parts.append(e)
    if parts:
        why["FAB_READINESS"] += "; the order-code rules name %s" % "; ".join(parts[:6]) + (" and %d more" % (len(parts) - 6) if len(parts) > 6 else "")
    h = ctx.holds.get(letter)
    if h:
        # The owner's words, verbatim; the registry's own reading follows as context and decides nothing here.
        vals = {k: str(h[k]) for k in FIELDS}
        why = {k: "the hold's value; the registry today: %s" % why[k] for k in FIELDS}
        held = "Board %s is held by decision %s (%s). Forbidden while it holds: %s. Lifts when: %s" % (
            letter.upper(), h.get("decision"), h.get("title", ""), " ".join(str(h.get("forbidden", "")).split()),
            " ".join(str(h.get("lifts_when", "")).split()))
        d = ctx.decision(h.get("decision"))
        if d and str(d.get("status")) != "open":
            # A HOLD WHOSE DECISION IS RULED IS STILL A HOLD UNTIL ITS ENTRY IS DELETED, and a reader is owed both
            # facts: the register says the question is answered, and the hold file says the board is still held.
            # Lifting it is a data edit with the ruling quoted, never something this tool does.
            held += ("; the decision register records decision %s as %s on %s by %s, and this hold entry has not "
                     "been lifted" % (h.get("decision"), d.get("status"), d.get("ruled_on") or "an unstated date",
                                      d.get("ruled_by") or d.get("authority") or "an unstated authority"))
        return vals, why, gate, held, st
    return computed, why, gate, None, st


def block(folder, ctx, today=None):
    """The readiness block for one order folder, as lines."""
    fb = folder_board(folder, ctx.m)
    if not fb:
        raise ValueError("%s is not a board's order folder (PCB-<name>-<phase> for a board of the manifest)" % folder)
    letter, stem, phase = fb
    vals, why, gate, held, st = fields(letter, ctx)
    su = st.get("subject") or {}
    decl = str(su.get("declared_phase") or "").upper()
    L = [HEAD,
         "This folder is not an approved fabrication package and nothing may be ordered from it (owner decision 41,",
         "25 September 2026: the order set is rebuilt and quarantined; promotion, publication and money are the owner's).", ""]
    L += ["%s = %s" % (k, vals[k]) for k in FIELDS]
    L.append("")
    if decl and decl == phase.upper():
        L.append("- Board %s declares %s and this folder is cut from the %s deliverable folder; the readiness above is that board's." % (letter.upper(), decl, phase))
    else:
        L.append("- This folder holds %s and board %s declares %s. Its gerbers, BOM and CPL are an older phase than the board this project "
                 "is building, it was not rebuilt because no deliverable folder exists at %s, and the readiness above is board %s at %s, "
                 "not a judgement of the files in this folder." % (phase, letter.upper(), decl or "no phase", decl or "a declared phase",
                                                                   letter.upper(), decl or "its declared phase"))
    if held:
        L.append("- " + held.rstrip(".") + ".")
    for k in FIELDS:
        L.append("- %s: %s." % (k, why[k]))
    L.append("- Computed %s by tools/order_readiness.py under rule set %s (manifest %s). The full reading is "
             "v2/docs/PCB-RULE-STATUS-%s.md." % (today or datetime.date.today().isoformat(), ctx.fp, ctx.m.get("manifest_version"), letter.upper()))
    L += [TAIL, ""]
    return L


def strip_block(text):
    """The note without a block this tool wrote earlier. Only a block that starts on the first line and ends at
    its own closing line is removed; anything else is the note and is left alone."""
    lines = text.split("\n")
    if not lines or not lines[0].startswith(HEAD): return text
    try: end = lines.index(TAIL)
    except ValueError:
        raise ValueError("a readiness block opens on the first line and never closes; refusing to guess where the note starts")
    rest = lines[end + 1:]
    while rest and not rest[0].strip(): rest = rest[1:]
    return "\n".join(rest)


def parse(text):
    """{field: value} of the block at the top of a note, or {} when there is none."""
    if not text.startswith(HEAD): return {}
    head = text.split("\n" + TAIL, 1)[0]
    out = {}
    for ln in head.split("\n"):
        mm = re.match(r"^([A-Z_]+) = (\S+)$", ln)
        if mm and mm.group(1) in FIELDS: out[mm.group(1)] = mm.group(2)
    return out


def order_folders(rel):
    """Every board order folder of the set: order/<folder>/ORDER-NOTES.txt, never superseded/."""
    out = []
    for d in sorted(glob.glob(os.path.join(rel, "order", "*"))):
        n = os.path.basename(d)
        if n == "superseded" or not os.path.isdir(d): continue
        if os.path.exists(os.path.join(d, "ORDER-NOTES.txt")): out.append(d)
    return out


def stamp(note_path, ctx, today=None):
    """Put the folder's block at the top of its note, replacing an earlier one. Returns the block's fields."""
    folder = os.path.basename(os.path.dirname(os.path.abspath(note_path)))
    body = strip_block(open(note_path, encoding="utf-8").read())
    L = block(folder, ctx, today)
    text = "\n".join(L) + "\n" + body
    if parse(text) and set(parse(text)) != set(FIELDS):
        raise AssertionError("the block for %s lost a field" % folder)
    open(note_path, "w", encoding="utf-8").write(text)
    return parse(text)


def readme_rows(rel, ctx):
    rows = []
    for d in order_folders(rel):
        name = os.path.basename(d)
        fb = folder_board(name, ctx.m)
        if not fb: continue
        got = parse(open(os.path.join(d, "ORDER-NOTES.txt"), encoding="utf-8").read())
        decl = str((ctx.status(fb[0]).get("subject") or {}).get("declared_phase") or "").upper()
        rows.append("| `%s/` | %s | %s | %s | %s | %s | %s | %s |" % (
            name, fb[0].upper(), fb[2], decl or "-", *[got.get(k, "MISSING") for k in FIELDS]))
    return rows


def stamp_readme(rel, ctx):
    p = os.path.join(rel, "order", "README.md")
    if not os.path.exists(p): return False
    text = open(p, encoding="utf-8").read()
    if README_BEGIN in text:
        pre, rest = text.split(README_BEGIN, 1)
        post = rest.split(README_END, 1)[1] if README_END in rest else ""
        pre = pre.rstrip("\n") + "\n\n"
        post = post.lstrip("\n")
    else:
        # after the title line, before everything else
        first, _, after = text.partition("\n")
        pre, post = first + "\n\n", after.lstrip("\n")
    blk = [README_BEGIN,
           "**QUARANTINED: nothing in this folder is an approved fabrication package, and nothing is ordered from it** "
           "(owner decision 41, 25 September 2026). Every `ORDER-NOTES.txt` opens with its board's readiness in the four "
           "fields below; read it before anything else. A folder whose phase is not the phase its board declares is an "
           "older board than the one this project is building.", "",
           "| Folder | Board | Folder phase | Board declares | %s |" % " | ".join(FIELDS),
           "|---|---|---|---|---|---|---|---|"] + readme_rows(rel, ctx) + [README_END, ""]
    open(p, "w", encoding="utf-8").write(pre + "\n".join(blk) + "\n" + post)
    return True


def stamp_all(rel=None, today=None, ctx=None):
    rel = rel or release_dir()
    ctx = ctx or _Ctx()
    done = []
    for d in order_folders(rel):
        name = os.path.basename(d)
        if not folder_board(name, ctx.m): continue
        vals = stamp(os.path.join(d, "ORDER-NOTES.txt"), ctx, today)
        done.append((name, vals))
    stamp_readme(rel, ctx)
    return done


def check(rel=None):
    """Structure only: every board note of the set opens with a complete block and none reads as released.
    The VALUES are a dated reading and are never compared with a live computation here."""
    rel = rel or release_dir()
    bad = []
    for d in order_folders(rel):
        name = os.path.basename(d)
        if not FOLDER.match(name): continue
        text = open(os.path.join(d, "ORDER-NOTES.txt"), encoding="utf-8").read()
        got = parse(text)
        if not text.startswith(HEAD):
            bad.append("%s: ORDER-NOTES.txt does not open with the readiness block" % name); continue
        miss = [k for k in FIELDS if k not in got]
        if miss: bad.append("%s: the block carries no %s" % (name, ", ".join(miss)))
        if ("\n" + TAIL + "\n") not in text: bad.append("%s: the block never closes" % name)
    return bad


def main(argv):
    rel = argv[0] if argv and not argv[0].startswith("--") else release_dir()
    if "--check" in argv:
        bad = check(rel)
        for b in bad: print("order_readiness: " + b)
        print("order_readiness: %d order note(s), %d without a complete readiness block" % (len(order_folders(rel)), len(bad)))
        return 1 if bad else 0
    done = stamp_all(rel)
    for name, vals in done:
        print("order_readiness: %-22s %s" % (name, "  ".join("%s=%s" % (k, vals.get(k)) for k in FIELDS)))
    print("order_readiness: %d order note(s) stamped, and the order README's readiness table" % len(done))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
