"""The cut list of the definition-baseline restructure (branch fnd/defstab, MESHSAT-1357, 27 September 2026).

Each cut is (id, file, start anchor, end anchor, destination, section, category, why). The cut runs from the first
character of the unique occurrence of `start` to the last character of the first occurrence of `end` at or after it.
A start anchor that begins with a space or a newline takes that separator with the cut, so the kept text closes up
exactly; the moved text is the cut stripped of surrounding whitespace. Every anchor must occur exactly once.

Destinations: "appendix" = the same file's 'Appendix: review and status history (not part of the baseline)';
"status" = v2/docs/handover/DEFINITION-STATUS.md.
Categories: "review-history" (the baseline attempts, the review gate, the revision notes of the document itself);
"implementation-status" (transmitter counts, circuit revisions, feasibility-blocker counts, reading results,
commit-by-commit status).
"""

BRIEF = "v2/docs/PRODUCT-BRIEF.md"
CONOPS = "v2/docs/CONOPS.md"

CUTS = [
    # ------------------------------------------------------------------ PRODUCT-BRIEF.md
    ("B-H1", BRIEF, "**Status: BASELINED as layer 1 of the foundation baseline",
     "and the exclusions\nthe handover audit found missing.\n", "appendix", "the head (the status paragraph)", "review-history",
     "the status line and the history of the baseline attempts (Review A passes, release checks, the targeted fix, "
     "the narrow verification, EQ-27's re-read rule)"),
    ("B-S1", BRIEF, " What the design has and has not shown\ntoday is `CURRENT-EVIDENCE.md`",
     "0 boards ready for layout; 0\nphysically verified.\"**", "status", "the head (the framing paragraph)",
     "implementation-status", "the evidence headline's counts, quoted"),
    ("B-H2", BRIEF, "## How this brief answers layer 1\n", "| The review | \"Review A, layer 1\" below |\n\n",
     "appendix", "the section \"How this brief answers layer 1\"", "review-history",
     "the map of the layer 1 review criteria to this brief"),
    ("B-S2", BRIEF, " As generated at `45bde541` the line is drawn to remove the supply of the",
     "`CONOPS.md` section 4b).", "status", "the section \"What the V2 kit is\" (emission and light discipline)",
     "implementation-status", "what the EMCON line is drawn to do as generated, with board B's round 8"),
    ("B-S3", BRIEF, " Read transmitter by\n  transmitter against that",
     "and no row is shown to meet the latency.", "status", "the section \"What the V2 kit is\" (emission and light discipline)",
     "implementation-status", "the transmitter counts (17, 15 of 17 local, 0 of 17 end to end) and their open rows"),
    ("B-S4", BRIEF, "No row has been shown on a bench; EMCON is feasibility blocker FEA-002",
     "(`feasibility/EMCON.md` section 0; `PANEL.md` section 3, GPIO 8). ", "status",
     "the section \"What the V2 kit is\" (emission and light discipline)", "implementation-status",
     "the bench state and the lamps as drawn (D22, the TX lamp's supply)"),
    ("B-S5", BRIEF, " The case generators carry C1 to C6\n  since `c351115d`",
     "eleven coupler sites at 88 mm, which is history.", "status", "the section \"What the V2 kit is\" (antenna entries)",
     "implementation-status", "which commit's generators and release folders carry the case choices"),
    ("B-S6", BRIEF, " No board of the set is ready for layout, and no layout of boards A, B, C, D, E",
     "(`CURRENT-EVIDENCE.md`, the candidate table).", "status", "the section \"What it is not, today\" (not ready for layout)",
     "implementation-status", "board readiness and the circuit corrections the deliverable folders predate"),
    ("B-S7", BRIEF, " The current PROVISIONAL model\n  gives an aged pack 2.5 h",
     "since the layer 2 merge (`95e078a1`).", "status", "the section \"What it is not, today\" (runtime)",
     "implementation-status", "the power model's current runtime figures and the commit that aligned CONOPS"),
    ("B-S8", BRIEF, " Seven feasibility blockers on the core are not closed",
     "(`EXECUTION-PLAN.md`, stage gates).", "status", "the section \"What the first prototype has to show\"",
     "implementation-status", "the count of open feasibility blockers on the core"),
    ("B-H3", BRIEF, "## Open items that bear on this brief, and why layer 1 can close with them open\n",
     "No route is claimed; establishing one is a bounded item before any carriage. |\n\n", "appendix",
     "the section \"Open items that bear on this brief, and why layer 1 can close with them open\"", "review-history",
     "the closing argument of layer 1 at its baseline, with each open item's state at that time"),
    ("B-H4", BRIEF, "## Review A, layer 1\n", "is held the same way by its own fresh reviewer.\n", "appendix",
     "the section \"Review A, layer 1\"", "review-history", "the definition of the review gate layer 1 closed through"),

    # ------------------------------------------------------------------ CONOPS.md
    ("C-H1", CONOPS, "**Status: BASELINED as layer 2 of the foundation baseline",
     "are marked as the session's (section 7).\n\n", "appendix", "the head (the status paragraph)", "review-history",
     "the status line and the revision history of 25 to 27 September 2026 (passes 1 to 3)"),
    ("C-H2", CONOPS, "**Review A, the gate this layer closes through",
     "this document was a DRAFT for Review A. ", "appendix", "the head (the Review A paragraph)", "review-history",
     "the definition of Review A for layer 2 and the record of its passes and release checks"),
    ("C-H3", CONOPS, "NEED-18 and NEED-19 were added in the revision of 25 September 2026",
     "but neither had a need to trace to.\n\n", "appendix", "section 2 (the paragraph under the needs table)", "review-history",
     "when two needs were added (the needs table itself is unchanged)"),
    ("C-H4", CONOPS, " **Corrected 26 September 2026:** this paragraph first called the two",
     "and SC-02\nsettles it as above.", "appendix", "section 2a (which peripherals NEED-03 protects)", "review-history",
     "a correction note of the document itself"),
    ("C-S1", CONOPS, " As\ngenerated since `458b2873` the two gaps this mission first named",
     "and no row has been shown on a bench.", "status", "section 3, mission M4", "implementation-status",
     "the gaps as generated, board B's round 8 and the transmitter counts"),
    ("C-H5", CONOPS, "\nThe table has eighteen rows: the fourteen of the first draft",
     "(added later that day, pass 3).", "appendix", "section 4 (its introduction)", "review-history",
     "when the mode rows were added"),
    ("C-H6", CONOPS, " **Corrected 26 September 2026:** this cell had stated a road route",
     "before, whether it was powered was TBD", "appendix", "section 4, the Transport row", "review-history",
     "two correction notes of the document itself"),
    ("C-H7", CONOPS, " **Changed 27 September 2026 after Review A (B2):** this cell had the panel controller",
     "only when the lid was closed, which it cannot sense", "appendix", "section 4, the Startup row",
     "review-history", "a correction note of the document itself"),
    ("C-H8", CONOPS, " **Corrected 26 September 2026 (S-07):** this row said the kit's loads sat",
     "the strap selected 2S, the circuit before `458b2873`", "appendix", "section 4, the Charging row",
     "review-history", "a correction note of the document itself"),
    ("C-H9", CONOPS, " **Corrected 26 September 2026 (S-07):** this row said the module radios were off the line",
     "had only their disable pin, the circuit before `458b2873`", "appendix", "section 4, the EMCON row",
     "review-history", "a correction note of the document itself"),
    ("C-H10", CONOPS, " **Changed 27 September 2026:** this row had the pack out;",
     "so storage keeps it fitted (section 7a).", "appendix", "section 4, the Storage row", "review-history",
     "a correction note of the document itself (its reason stands in section 7a's storage and transport row)"),
    ("C-H11", CONOPS, " The figures this table carried until then were the W2 model's",
     "and PS-TYP from 60.1 to 63.0 W.", "appendix", "section 4a (the paragraph under its heading)", "review-history",
     "which model the table's figures replaced"),
    ("C-H12", CONOPS, "**What the table does not carry any more (27 September 2026).**",
     "which is why this table's figure is lower.\n\n", "appendix", "section 4a (the paragraph under its table)", "review-history",
     "the rows and columns the table dropped on 27 September 2026"),
    ("C-S2", CONOPS, " Read transmitter by transmitter\n(`feasibility/EMCON.md` section 0a, sixth revision)",
     "none\nof which can use the kit's own SDR, whose supply EMCON removes).", "status",
     "section 4b (the D-05 paragraph)", "implementation-status",
     "the transmitter counts, board B's round 8 and the open shared items"),
    ("C-S3", CONOPS, " The WiFi cards' converter enables are drawn since `458b2873`",
     "(SD-EMC-1r8, EMCON.md section 4b).", "status", "section 4b (its closing paragraph)", "implementation-status",
     "the commits that drew the two switches"),
    ("C-H13", CONOPS, " **Corrected 26 September 2026 (S-07):** this section described the circuit before",
     "had only their disable pin.", "appendix", "section 4b (its closing paragraph)", "review-history",
     "a correction note of the document itself"),
    ("C-S4", CONOPS, " **State at this revision:** this is a requirement on the design (REQ-071)",
     "so 0 of 17 close end to end).", "status", "section 4b.1 (what the operator does with it)", "implementation-status",
     "the transmitter counts against REQ-071"),
    ("C-H14", CONOPS, " Those three documents follow this section since 27 September 2026",
     "(FW-C13, FW-C14, FW-E10).", "appendix", "section 4c (which modules can host what)", "review-history",
     "the answer to finding B4 of the release check of layer 2: three other documents brought into line"),
    ("C-S5", CONOPS, " **Until HOT-R1 is in both generators the hot stop's requirement reads FAIL",
     "and falls back to the `TMP117` elsewhere.", "status", "section 4c (HOT-R1)", "implementation-status",
     "the hot stop requirement's reading on the generated boards"),
    ("C-S6", CONOPS, " **Until BANK-R1 is in board B's generator,",
     "reported to the owner at the next checkpoint, not asked.", "status", "section 4c (BANK-R1)",
     "implementation-status", "REQ-052's reading on board B as generated"),
    ("C-S7", CONOPS, " These close S-37 and REQ-003's latency TBD for the kit's part.",
     "for the kit's part.", "status", "section 4c (the recovery and delivery targets)", "implementation-status",
     "the registry items the targets closed"),
    ("C-H15", CONOPS, " **Corrected 26 September 2026 (S-07):** this paragraph said the PoE and USB-C",
     "the circuit before `458b2873`.", "appendix", "section 5 (the rule the hardware is designed to)", "review-history",
     "a correction note of the document itself"),
    ("C-H16", CONOPS, " Corrected 27 September 2026: this cell said \"key-down for minutes\"",
     "this cell said \"key-down for minutes\"", "appendix", "section 5 (the load table, the row of APRS with the 30 W PA)",
     "review-history", "a correction note of the document itself"),
    ("C-H17", CONOPS, "These replace the W2 model's 4.2 and 3.4 h",
     "before the loads were sourced (section 4a).\n\n", "appendix", "section 6 (the paragraph under its list)", "review-history",
     "which model's runtimes these replaced"),
    ("C-H18", CONOPS, "| Review A | one fresh reviewer, recorded under `v2/docs/reviews/`",
     "| the status paragraph at the top |\n", "appendix", "section 7a (the Review A row)", "review-history",
     "the review gate's own choice row, which points at the status paragraph that moved with it"),
]
