#!/usr/bin/env python3
"""Render layer 3's second issue (L3-R2) from the requirements registry (MESHSAT-1357, 30 September 2026).

  render_l3r2.py            write REQUIREMENTS-L3-R2.md, OWNER-DECISIONS-L3.md and L3-RECONCILIATION.md beside this file
  render_l3r2.py --check    refuse (exit 1) if any of the three on disk differs from what the inputs render
                            (with --out-dir DIR, the copies in DIR are checked, so a test damages a copy, never the tree's)
  render_l3r2.py --registry PATH --out-dir DIR   render another registry (a dry run of a decision) elsewhere
  render_l3r2.py --freeze   write h3_registry_digest.json from v2/release/handover/H3.zip (once; the H3 release is read,
                            never modified), so the change record renders in a tree that does not carry the ZIP

Inputs, and nothing else: v2/ecad/tools/pcb_requirements.yaml (the registry, validated first: a registry that does not
validate renders nothing), l3r2.yaml (beside this file: what the registry has no field for), h3_registry_digest.json
(H3's registry as released), v2/ecad/tools/pcb_envelope.yaml (the envelope's numbers), and v2/docs/TEST-PLAN.md,
v2/docs/CONOPS.md and v2/docs/PRODUCT-BRIEF.md (read for the trace to test rows and for the passages a decision
changes; none is edited). A decision's state is read from the registry: the conditional script that applies the owner's
answer records a ruling with `decides: <row>:<option>`. Every page is generated; a hand edit is refused by --check,
which the suite runs (v2/ecad/tools/tests/test_l3r2.py).

Style: one Markdown paragraph per line (claims_check.py screens sentence by sentence within a line), no dash character.
Python 3.11 with PyYAML, as rules_render.py.
"""
import hashlib
import json
import os
import re
import sys
import zipfile

import yaml

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
TOOLS = os.path.join(ROOT, "v2", "ecad", "tools")
sys.path.insert(0, TOOLS)
import rules_lib as R  # noqa: E402

DATA = os.path.join(HERE, "l3r2.yaml")
DIGEST = os.path.join(HERE, "h3_registry_digest.json")
PAGES = {"spec": "REQUIREMENTS-L3-R2.md", "decisions": "OWNER-DECISIONS-L3.md", "recon": "L3-RECONCILIATION.md"}
BASE_FIELDS = ("kind", "parent", "statement", "acceptance", "allocated_to", "verification_method", "verification_phase",
               "final_phase", "prototype_1", "prototype_1_basis", "release_effect", "status")
DIGEST_FIELDS = BASE_FIELDS + ("evidence_result", "rulings", "choices", "waits_on")
HEAD = ("<!-- GENERATED by v2/docs/handover/layer3/render_l3r2.py from v2/ecad/tools/pcb_requirements.yaml, "
        "v2/docs/handover/layer3/l3r2.yaml and H3's registry (h3_registry_digest.json).\n     Do not edit: "
        "`python3 v2/docs/handover/layer3/render_l3r2.py --check` refuses a hand-edited copy, and the suite runs it. -->\n")
LAYERS = ("4", "5", "6", "7", "8", "9")
DASHES = ("\u2013", "\u2014")
# The rows that set the target configuration (the gate's first condition); row L3-OD5 closes CFL-017 alone.
TARGET = ("L3-OD7", "L3-OD1", "L3-OD2", "L3-OD3", "L3-OD4", "L3-OD6")
# D-27: rows whose prepared restatements state M1's 72 hours; none is asked before row L3-OD7 is answered, and after its
# answers other than 72-required each is restated from the runtime comparison first.
RUNTIME_ROWS = ("L3-OD1", "L3-OD2", "L3-OD4", "L3-OD6")
CHECKED_KEYS = ("energy_basis", "power_path_check", "runtime_comparison")
LINK = re.compile(r"\]\(([^)#\s]+)(?:#[^)]*)?\)")


class RenderError(Exception):
    pass


def p(s):
    return " ".join(str(s if s is not None else "").split())


def cell(s):
    return p(s).replace("|", "/")


def rel(path):
    return os.path.relpath(path, ROOT).replace(os.sep, "/")


def sha16_bytes(b):
    return hashlib.sha256(b).hexdigest()[:16]


def load_data():
    return yaml.safe_load(open(DATA, encoding="utf-8"))


# ------------------------------------------------------------------------------------------------ H3's registry
def freeze(data):
    z = os.path.join(ROOT, data["h3"]["zip"])
    raw = zipfile.ZipFile(z).read(data["h3"]["member"])
    h3 = yaml.safe_load(raw)
    out = {"source": "%s!%s" % (data["h3"]["zip"], data["h3"]["member"]), "member_sha256": hashlib.sha256(raw).hexdigest(),
           "baseline_state": h3.get("baseline_state"), "needs_document_sha256": h3.get("needs_document_sha256"),
           "owner_rulings": [x["id"] for x in h3["owner_rulings"]],
           "session_choices": [x["id"] for x in h3["session_choices"]],
           "open_items": [x["id"] for x in h3["open_items"]], "closed_items": [x["id"] for x in h3["closed_items"]],
           "records": {r["id"]: {k: r.get(k) for k in DIGEST_FIELDS} for r in h3["records"]},
           "evidence_counts": {r["id"]: len(r.get("evidence") or []) for r in h3["records"]}}
    return json.dumps(out, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def load_h3():
    if not os.path.exists(DIGEST): raise RenderError("h3_registry_digest.json is absent: run render_l3r2.py --freeze")
    return json.load(open(DIGEST, encoding="utf-8"))


# ------------------------------------------------------------------------------------------------ what the tree says
def decided(req, data):
    """{row: (option, ruling id, date, words)} from rulings carrying `decides: <row>:<option>`."""
    out = {}
    for r in req.get("owner_rulings") or []:
        d = str(r.get("decides") or "")
        if ":" in d:
            row, opt = d.split(":", 1)
            out[row] = (opt, r["id"], str(r.get("ruled_on")), p(r.get("words") or ""),
                        {"share": r.get("weather_share"), "build": r.get("weather_build")})
    rows = {d["id"]: d for d in data["decisions"]}
    for row, v in out.items():
        opt, rid = v[0], v[1]
        if row not in rows: raise RenderError("ruling %s decides %s, which l3r2.yaml does not list" % (rid, row))
        if opt not in [o["id"] for o in rows[row]["options"]]:
            raise RenderError("ruling %s decides %s with option %s, which the row does not offer" % (rid, row, opt))
    return out


def testplan_refs(root):
    """{record id: [places in TEST-PLAN.md that name it]}: a table row by its first cell, a paragraph by its section."""
    path = os.path.join(root, "v2", "docs", "TEST-PLAN.md")
    out = {}
    if not os.path.exists(path): return out
    sec = "head"
    for line in open(path, encoding="utf-8"):
        m = re.match(r"^##\s+(\d+[a-z]?)\.", line)
        if m: sec = "section " + m.group(1)
        ids = set(re.findall(r"\b((?:REQ|CON|ASM|CHO|CFL|FEA)-\d{3})\b", line))
        if not ids: continue
        where = sec
        if line.startswith("|"):
            first = line.split("|")[1].strip().strip("*").strip()
            if first and len(first) <= 12: where = "%s row %s" % (sec, first)
        for i in ids:
            out.setdefault(i, [])
            if where not in out[i]: out[i].append(where)
    return out


def passages(data, root):
    out = []
    for ps in data.get("passages") or []:
        path = os.path.join(root, ps["file"])
        hits = []
        if os.path.exists(path):
            for n, line in enumerate(open(path, encoding="utf-8"), 1):
                if re.search(ps["pattern"], line): hits.append(n)
        out.append((ps, hits))
    return out


TBD_PAT = re.compile(r"\b(TBD|TBC|owed|not yet stated|exists? yet|is open|are open|stays? open|remains? open|open until|"
                     r"not yet (?:known|settled|decided|set|measured))\b", re.I)


def tbd_mentions(req):
    """Every 'TBD', 'TBC', 'owed', 'not yet stated', 'exists yet' and 'open' state sentence in a live record's statement,
    acceptance or notes (CHECK-1, minor 10: REQ-045's 'no coordination study exists yet', REQ-024's 'open')."""
    out = []
    for r in req["records"]:
        if r["kind"] == "superseded": continue
        for f in ("statement", "acceptance", "notes"):
            t = p(r.get(f))
            for m in TBD_PAT.finditer(t):
                a, b = max(0, m.start() - 90), min(len(t), m.end() + 60)
                out.append((r["id"], f, t[a:b]))
    return out


def filed(data, key):
    """The l3r2.yaml entry `key` if it names a file this tree holds at its sha; None if not filed; a refusal if it names
    a file the tree does not hold."""
    v = data.get(key)
    if not v: return None
    for e in (v if isinstance(v, list) else [v]):
        for rk, sk in (("record", "sha16"), ("check", "check_sha16")):
            if e.get(rk) is None: continue
            fp = os.path.join(ROOT, str(e[rk]))
            if not os.path.isfile(fp) or sha16_bytes(open(fp, "rb").read()) != str(e.get(sk)):
                raise RenderError("l3r2.yaml's %s names %s at %s, which this tree does not hold" % (key, e[rk], e.get(sk)))
    return v


def handover_checks(data):
    """The filed checks of L3-R2 (l3r2.yaml `independent_check`), each verdict verified against its record's first line:
    ACCEPTED only over 'accepted: yes' and NOT_ACCEPTED only over a first line that says no ('accepted: no', or CHECK-2's
    'accepted-so-far: no'); any other pairing is refused (CHECK-3 of L3-R2, B1: a check is verified, never trusted)."""
    chks = filed(data, "independent_check") or []
    for c in chks:
        first = open(os.path.join(ROOT, str(c["record"])), encoding="utf-8").readline().strip().lower()
        v = str(c.get("verdict")).upper()
        ok = first == "accepted: yes" if v == "ACCEPTED" else (
            v == "NOT_ACCEPTED" and first in ("accepted: no", "accepted-so-far: no"))
        if not ok:
            raise RenderError("l3r2.yaml's independent_check reads %s for %s, whose first line is %r" %
                              (c.get("verdict"), c["record"], first))
    return chks


def handover_accepted(data):
    chks = handover_checks(data)
    return bool(chks) and str(chks[-1].get("verdict")).upper() == "ACCEPTED"


def basis_ok(data, key="energy_basis", root=None):
    """(True, '') when `key` (energy_basis, or power_path_check of D-24) names its record, outputs and check, every file
    held at its sha256/16 and byte identical to the file of that path at the tip its accepted check checked, and the check
    reads 'accepted: yes' and names that tip (v2/docs/records/l3r2/basis_binding.py; CHECK-2 of L3-R2 B3, CHECK-3 B1: a
    check is verified, never trusted, and bound to what it checked)."""
    v = data.get(key)
    if not v: return False, "not filed (S-127)" if key == "energy_basis" else "not filed"
    sys.path.insert(0, os.path.join(ROOT, "v2", "docs", "records", "l3r2"))
    import basis_binding as BB
    return BB.verify(v, root or ROOT, ROOT, need_outputs=(key == "energy_basis"))


def reissue_ok(req, data, dec):
    """(True, '') when definition_reissue names a file this tree holds at its sha that differs from the baselined text,
    approved by an owner ruling that decides it (`decides: definition_reissue`) dated on or after every row's ruling
    (CHECK-2 of L3-R2, B3: D-21 or any other ruling does not qualify)."""
    dr = filed(data, "definition_reissue")
    if not dr: return False, "not filed"
    base = data.get("baseline_definition") or {}
    if str(dr.get("sha16")) in {str(v) for v in base.values()}: return False, "it names the baselined text unchanged"
    r = next((x for x in req["owner_rulings"] if x["id"] == str(dr.get("approved_by"))), None)
    if r is None: return False, "its approving ruling %s is not in the registry" % dr.get("approved_by")
    if str(r.get("decides")) != "definition_reissue": return False, "%s does not decide the re-issue" % r["id"]
    late = [x[1] for x in dec.values() if str(x[2]) > str(r.get("ruled_on"))]
    if late: return False, "%s is dated before the rulings %s" % (r["id"], ", ".join(late))
    return True, ""


def held(row, dec, data):
    """A row is HELD (D-22, D-23) while it is undecided and a file it waits on is not filed (the energy basis: with an
    accepted check)."""
    d = next(x for x in data["decisions"] if x["id"] == row)
    return row not in dec and (bool(runtime_wait(row, dec)) or any(
        not (basis_ok(data, k)[0] if k in CHECKED_KEYS else filed(data, k)) for k in (d.get("held_until") or [])))


def runtime_wait(row, dec):
    """Why a row waits on row L3-OD7 (D-27), or '': it is not asked before row L3-OD7 is answered, and after an answer
    other than 72-required its prepared restatement (72 hours) is restated from the runtime comparison first."""
    if row not in RUNTIME_ROWS or row in dec: return ""
    if "L3-OD7" not in dec: return "not asked until row L3-OD7, M1's runtime, is answered"
    if dec["L3-OD7"][0] != "72-required":
        return ("row L3-OD7 answered `%s` (%s): restated from the runtime comparison before it is asked (L3-C56)"
                % (dec["L3-OD7"][0], dec["L3-OD7"][1]))
    return ""


LID = {"qmx-out": "qmx-out", "qmx-outside": "qmx-out", "tablet-out": "tablet-out", "both-kept": "both-kept"}


def od6_row(data, option, share, build):
    q = next(x for x in data["decisions"] if x["id"] == "L3-OD6")["quantified"]["rows"]
    want = "mean-day" if option == "mean-day" else str(share)
    return next((r for r in q if r.get("option") == option and str(r.get("build")) == str(build) and
                 ("mean-day" if r.get("option") == "mean-day" else str(r.get("share"))) == want), None)


def coherent(dec, data=None):
    """([], True) when no two decided rows set requirements that cannot both hold (l3r2.yaml `contradictions`, D-26: the
    owner's reviewer, "Retain rejection of genuinely contradictory requirements"). A target the studied candidate does
    not meet is NOT a contradiction: it is valid and records a feasibility item (feasibility()). Every rule here is one
    l3r2.yaml states, and nothing else is claimed (L3-C32)."""
    data = data or load_data()
    why = []
    opt = lambda r: dec.get(r, ("",))[0]
    if "L3-OD7" in dec and opt("L3-OD7") != "72-required" and [r for r in RUNTIME_ROWS if r in dec]:
        why.append("row L3-OD7 answered %s while rows %s stand on prepared restatements for 72 hours (D-27)" % (
            opt("L3-OD7"), ", ".join(r for r in RUNTIME_ROWS if r in dec)))
    if opt("L3-OD1") == "reject" and "L3-OD2" in dec:
        why.append("row L3-OD2 answered %s while row L3-OD1 stands rejected: every option of row L3-OD2 sets a lid pack, "
                   "and a reject keeps D-06's one pack" % opt("L3-OD2"))
    return why, not why


def not_applicable(row, dec):
    """Row L3-OD2 does not apply after row L3-OD1's reject (the first contradiction rule)."""
    return row == "L3-OD2" and dec.get("L3-OD1", ("",))[0] == "reject"


def settled(row, dec):
    return row in dec or not_applicable(row, dec)


def feasibility(req, dec, data):
    """[(FI id, the feasibility record's id or None, disposition kind)]: the items the registry records for the decided
    answers (feasibility records whose blocker id is an FI id of l3r2.yaml), each with the disposition l3r2.yaml gives."""
    items = {x["id"]: x for x in data.get("feasibility_items") or []}
    out = []
    for r in req["records"]:
        if r.get("kind") != "feasibility": continue
        for b in r.get("blocker_ids") or []:
            if str(b) in items: out.append((str(b), r["id"], items[str(b)]["disposition"]["kind"]))
    return sorted(out)


def dispositions(req, dec, data):
    """[(row, option, kind)] of every decided row's option, and the recorded feasibility items' kinds."""
    out = []
    for d in data["decisions"]:
        if d["id"] in dec:
            o = next(x for x in d["options"] if x["id"] == dec[d["id"]][0])
            out.append((d["id"], o["id"], (o.get("disposition") or {}).get("kind")))
    return out


def status_level(req, dec, data, h3, g=None):
    """The reviewer's status level that holds (D-26), read from the gate and the rulings: (id or None, sentence)."""
    lv = {x["id"]: x for x in data.get("status_levels") or []}
    g = g or gate(req, dec, data, h3)
    rows = [d["id"] for d in data["decisions"]]
    drafted = all(settled(r, dec) for r in rows) and basis_ok(data, "feasibility_basis")[0]
    accepted = any(str(r.get("decides")) == "layer3_baseline" for r in req["owner_rulings"])
    if drafted and all(x[1] for x in g) and accepted:
        return "VALIDATED", "**%s** holds: %s." % (lv["VALIDATED"]["name"], lv["VALIDATED"]["means"])
    if drafted:
        return "DRAFTED", ("**%s** holds (%s); **%s** does not yet: %s." % (
            lv["DRAFTED"]["name"], lv["DRAFTED"]["means"], lv["VALIDATED"]["name"], lv["VALIDATED"]["holds_when"]))
    return None, ("None of the three levels holds yet. **%s** needs %s; **%s** needs %s; **%s** is %s." % (
        lv["DRAFTED"]["name"], lv["DRAFTED"]["holds_when"], lv["VALIDATED"]["name"], lv["VALIDATED"]["holds_when"],
        lv["COMPLIANT"]["name"], lv["COMPLIANT"]["holds_when"]))


def row_state(row, dec, data):
    if not_applicable(row, dec) and row not in dec:
        return "NOT APPLICABLE: row L3-OD1 rejected (every option sets a lid pack; a contradiction rule)"
    if row in dec:
        f = dec[row][4] if len(dec[row]) > 4 else {}
        extra = ", ".join("%s %s" % (k, v) for k, v in (("build", f.get("build")), ("share", f.get("share"))) if v is not None)
        return "DECIDED: `%s`%s (%s, %s)" % (dec[row][0], (" " + extra) if extra else "", dec[row][1], dec[row][2])
    d = next(x for x in data["decisions"] if x["id"] == row)
    if runtime_wait(row, dec): return "HELD (D-27): %s" % runtime_wait(row, dec)
    return ("HELD (%s)" % d.get("held_by", "D-22")) if held(row, dec, data) else "AWAITING"


def baseline_changes(req, h3, data):
    """[(id, 'added' or 'changed', [fields])] for records whose baseline fields differ from H3's registry."""
    out = []
    for r in req["records"]:
        old = h3["records"].get(r["id"])
        if old is None: out.append((r["id"], "added", list(BASE_FIELDS))); continue
        f = [k for k in BASE_FIELDS if r.get(k) != old.get(k)]
        if f: out.append((r["id"], "changed", f))
    missing = [i for i, _, _ in out if i not in (data.get("impacts") or {})]
    if missing: raise RenderError("records changed since H3 with no impacts entry in l3r2.yaml: %s" % ", ".join(missing))
    return out


def closure_state(item, req, dec, data):
    """The live state of a closure item where the registry or a filed file decides it; the data's state otherwise."""
    recs = {r["id"]: r for r in req["records"]}
    open_ids = {x["id"] for x in req["open_items"]}
    closed_ids = {x["id"] for x in req["closed_items"]}
    rulings = {r["id"] for r in req["owner_rulings"]}
    iid, st = item["id"], item["state"]
    rows = [d["id"] for d in data["decisions"]]
    if iid == "L3-C01":
        return "CLOSED" if all(settled(r, dec) for r in TARGET) and coherent(dec, data)[1] and basis_ok(data)[0] and \
            basis_ok(data, "power_path_check")[0] else st
    if iid == "L3-C45": return "CLOSED" if basis_ok(data, "power_path_check")[0] else st
    if iid == "L3-C09": return "CLOSED" if (recs.get("CFL-017") or {}).get("status") == "CONFLICT_RESOLVED" else st
    if iid == "L3-C16":
        return "CLOSED" if ("S-122" in closed_ids or (recs.get("CFL-016") or {}).get("evidence_result") == "PASS") else st
    if iid == "L3-C17": return "CLOSED" if "S-114" in closed_ids else "OPEN"
    if iid == "L3-C18": return "CLOSED" if "M-02" in closed_ids else st
    if iid == "L3-C20":
        cls = data.get("tbd_mentions") or {}
        unc = [m[0] for m in tbd_mentions(req) if m[0] not in cls]
        return "CLOSED" if not unc and not any(r.get("status") == "TBD" for r in recs.values()) else "OPEN"
    if iid == "L3-C23":
        return "OPEN" if [i for i in open_ids if i not in (data.get("open_items_layer") or {})] else st
    if iid == "L3-C26":
        if reissue_ok(req, data, dec)[0]: return "CLOSED"
        return "OPEN (the session prepares the re-issue for the owner's approval)" if all(r in dec for r in rows) else st
    if iid == "L3-C27":
        chks = handover_checks(data)
        stale = bool(dec) and bool(chks) and "decisions pending" in str(chks[-1].get("scope") or "")
        return ("OPEN (the decided issue is checked again)" if stale else "CLOSED") if handover_accepted(data) else st
    if iid == "L3-C28": return "CLOSED" if {"D-21", "D-23", "D-24", "D-25", "D-26", "D-27"} <= rulings else st
    if iid == "L3-C56":
        if "L3-OD7" not in dec: return st
        if not basis_ok(data, "runtime_comparison")[0]: return "OPEN (row L3-OD7 decided; the runtime comparison is not filed)"
        return "CLOSED (decided)" if dec["L3-OD7"][0] == "72-required" else "OPEN (the four rows restated from the comparison next)"
    if iid == "L3-C57":
        rp = (data.get("runtime_provenance") or {}).get("record")
        return "CLOSED" if rp and basis_ok(data, "runtime_comparison")[0] else st
    if iid == "L3-C55": return "CLOSED" if basis_ok(data, "feasibility_basis")[0] else st
    if iid == "L3-C54":
        rows = [d["id"] for d in data["decisions"]]
        disp = dispositions(req, dec, data)
        fis = feasibility(req, dec, data)
        ok = all(settled(r, dec) for r in rows) and not [1 for x in disp if not x[2] or x[2] == "OWED"] and \
            not [1 for x in fis if x[2] == "OWED"]
        return "CLOSED" if ok else st
    if iid == "L3-C30": return "CLOSED" if basis_ok(data)[0] else "OPEN (the checked basis is not filed)"
    if iid == "L3-C31":
        return "CLOSED" if basis_ok(data)[0] and "S-127" in closed_ids else (
            "OPEN (the basis is filed and bound to its checked tip; S-127 is closed in the registry next)" if basis_ok(data)[0] else st)
    if iid == "L3-C32": return st if coherent(dec, data)[1] else "OPEN (%s)" % "; ".join(coherent(dec, data)[0])
    needed = [r for r in rows if r in str(item.get("closes_by"))]
    if st in ("AWAITING_OWNER", "HELD") and needed and all(r in dec for r in needed): return "CLOSED (decided)"
    return st


def gate(req, dec, data, h3):
    recs = {r["id"]: r for r in req["records"]}
    rulings = {r["id"] for r in req["owner_rulings"]}
    rows = [d["id"] for d in data["decisions"]]
    why, ok = coherent(dec, data)
    basis, basis_why = basis_ok(data)
    power, power_why = basis_ok(data, "power_path_check")
    g1 = all(settled(r, dec) for r in TARGET) and ok and bool(basis) and bool(power)
    g2 = all(settled(r, dec) for r in rows)
    down = data.get("resolved_fail_downstream") or {}
    open_cfl = [r["id"] for r in recs.values() if r.get("status") == "CONFLICT_OPEN"]
    fail_cfl = [r["id"] for r in recs.values() if r.get("kind") == "conflict" and r.get("status") == "CONFLICT_RESOLVED"
                and r.get("evidence_result") == "FAIL" and r["id"] not in down]
    tbd = [r["id"] for r in recs.values() if r.get("status") == "TBD"]
    cls = data.get("tbd_mentions") or {}
    unc = sorted({m[0] for m in tbd_mentions(req) if m[0] not in cls})
    reissued, reissue_why = reissue_ok(req, data, dec)
    ran = {"D-21", "D-23", "D-24", "D-25", "D-26", "D-27"} <= rulings
    g3 = not open_cfl and not fail_cfl and not tbd and not unc and reissued and ran
    chks = handover_checks(data)
    # An acceptance of the handover as prepared, with the decisions pending, does not cover the decided issue (D-26:
    # "BLOCKED for blanket approval"): once any row is decided, the decided issue is checked again.
    stale = bool(dec) and bool(chks) and "decisions pending" in str(chks[-1].get("scope") or "")
    g4 = handover_accepted(data) and not stale
    disp = dispositions(req, dec, data)
    fis = feasibility(req, dec, data)
    owed = ["%s %s" % (r, o) for r, o, k in disp if not k or k == "OWED"] + ["%s (%s)" % (i, rid) for i, rid, k in fis if k == "OWED"]
    fok, fwhy = basis_ok(data, "feasibility_basis")
    g5 = g2 and not owed and fok
    return [
        ("Target unambiguous", g1, "rows L3-OD7, L3-OD1 to L3-OD4 and L3-OD6 decided on a combination whose requirements do not "
         "contradict (row L3-OD2 not applicable after a reject), the energy basis filed: decided %s; contradictions %s; "
         "energy basis %s" % (
             ", ".join("%s %s (%s)" % (r, dec[r][0], dec[r][1]) for r in rows if r in dec) or "none",
             "none" if ok else "FOUND (%s)" % "; ".join(why), "filed with an accepted check" if basis else basis_why) +
         "; the power path at Option A(i)'s currents (D-24): %s" % ("filed with an accepted check" if power else power_why)),
        ("Requirement-changing owner decisions resolved", g2, "%d of %d rows decided%s; rows held (D-22 to D-24, D-27): %s" % (
            sum(1 for r in rows if r in dec), len(rows),
            "" if not any(not_applicable(r, dec) for r in rows) else ", row L3-OD2 not applicable after the reject",
            ", ".join(r for r in rows if held(r, dec, data)) or "none")),
        ("Contradictions and requirement-level TBDs closed", g3,
         "open conflicts: %s; resolved conflicts reading FAIL on a requirement-level source: %s (downstream, listed in "
         "l3r2.yaml: %s); records reading TBD: %s; unclassified TBD mentions: %s; the definition documents re-issued and "
         "approved by a ruling that decides it (L3-C26): %s; the session's scripts run on the set (L3-C28): %s" % (
             ", ".join(open_cfl) or "none", ", ".join(fail_cfl) or "none", ", ".join(sorted(down)) or "none",
             ", ".join(tbd) or "none", ", ".join(unc) or "none", "yes" if reissued else "no (%s)" % reissue_why,
             "yes" if ran else "no")),
        ("An independent check accepts the handover", g4,
         ("; ".join("%s (%s%s)" % (c.get("record"), c.get("verdict"), ", " + p(c["scope"]) if c.get("scope") else "")
                    for c in chks) if chks else "not held yet (closure item L3-C27)") +
         ("; the last acceptance covers the handover with the decisions pending, and rows are now decided: the decided "
          "issue is checked again" if stale else "")),
        ("Every recorded target has a feasibility disposition (D-26)", g5,
         "a credible route, inconclusive with the evidence named, or no route with a quantified trade-off returned to the "
         "owner, for each decided row's option and each feasibility item its answer records (L3-C54): %s; feasibility items "
         "recorded: %s; owed: %s" % (
             "; ".join("%s `%s` %s" % (r, o, k) for r, o, k in disp) or "no row decided",
             ", ".join("%s as %s (%s)" % (i, rid, k) for i, rid, k in fis) or "none",
             ", ".join(owed) or ("none" if g2 else "the undecided rows' dispositions")) +
         "; the feasibility record they rest on: %s" % ("bound to its checked tip" if fok else "NOT BOUND (%s)" % fwhy)),
    ]


def target_lines(req, data, dec, g1, heading):
    """Section (a) or 3: the decided target once the gate's first condition holds, the approved target, the
    contradiction and the proposed configuration before (CHECK-1, B6)."""
    rulings = {r["id"]: r for r in req["owner_rulings"]}
    if g1:
        L = ["**The decided target.** " + p(data["target"]["approved"]).split(";")[0] + ", as the owner's rulings on the "
             "rows set it:", ""]
        for row in [d["id"] for d in data["decisions"]]:
            if row in dec: L.append("- %s, `%s` (%s): %s" % (row, dec[row][0], dec[row][1], p(rulings[dec[row][1]]["ruling"])))
        return L + [""]
    L = ["**Approved today.** " + p(data["target"]["approved"]), "",
         "**Why it is not yet unambiguous.** " + p(data["target"]["contradiction"]), "",
         "**%s** " % heading + p(data["target"]["proposed"]), ""]
    return L + findings_lines(data)


def item_state(req, iid):
    """('closed', commit) when the registry's closed_items holds `iid`, ('open', '') when its open_items does, else
    ('absent', '')."""
    for x in req.get("closed_items") or []:
        if x["id"] == iid: return "closed", str(x.get("closed_by", "")).replace("commit ", "")[:8]
    if any(x["id"] == iid for x in req.get("open_items") or []): return "open", ""
    return "absent", ""


def m1_figures_clause(req, data):
    """The M1 figures' state, rendered from the files and the registry (CHECK-5 of L3-R2, minor 1): HELD for S-127 while
    the basis or its check is not filed and bound, else the checked basis's, bound to its tip, with S-127's closure."""
    st, by = item_state(req, "S-127")
    if basis_ok(data)[0] and basis_ok(data, "power_path_check")[0]:
        v = data["energy_basis"]
        return ("every M1 energy figure on these pages is the checked basis's, bound to the tip `%s` its accepted check "
                "names (`%s`)%s" % (str(v["tip"])[:12], v["check"],
                                    "; S-127 is closed (commit %s)" % by if st == "closed" else "; S-127 reads %s" % st.upper()))
    return "every M1 energy figure stays HELD for the checked second round (S-127)"


def l3_open_clause(req, lay):
    """Which open items belong to layer 3, from open_items_layer and the registry's open_items."""
    ids = [("the owner's " if it.get("class") == "OWNER_ACTION" else "") + it["id"] for it in req["open_items"]
           if str((lay.get(it["id"]) or {}).get("layer")) == "3"]
    return "Layer 3 holds %s" % (("only " + ", ".join(ids)) if ids else "no open item")


def s127_clause(req, data):
    """The energy basis's item stated from the registry and the files (CHECK-5 of L3-R2, minor 1)."""
    st, by = item_state(req, "S-127")
    if st == "closed":
        return ("the energy basis S-127 is closed (commit %s)%s" %
                (by, " and no row is held for it" if not any(held(d["id"], {}, data) for d in data["decisions"])
                 else ", yet a row still reads HELD"))
    return "the energy basis S-127 is layer 4's engineering input that rows L3-OD1, L3-OD2 and L3-OD4 wait on (D-22)"


def facts_lines(data, req):
    """The facts the first check of the energy basis confirmed (l3r2.yaml `facts`), with the checks filed."""
    chks = filed(data, "energy_basis_checks") or []
    if not data.get("facts"): return []
    L = [p("**Facts confirmed by the check of the energy basis** (%s). Used now; none is a figure of the cases the "
           "check did not accept, and %s." %
           ("; ".join("[%s](%s), of %s, %s" % (os.path.basename(os.path.dirname(c["record"])) + "/" + os.path.basename(c["record"]),
                                             os.path.relpath(os.path.join(ROOT, c["record"]), HERE).replace(os.sep, "/"),
                                             c.get("of"), c.get("verdict")) for c in chks), m1_figures_clause(req, data))), ""]
    for f in data["facts"]:
        L += ["- **%s, %s.** %s (%s)" % (f["id"], p(f["title"]), p(f["text"]), "; ".join(p(s) for s in f.get("source") or []))]
    return L + [""]


def basis_figures_lines(data):
    """The figures fill_l3r2_from_basis.py read from the filed basis by exact keys; HELD while it has not run."""
    B = data.get("basis_figures")
    if not B:
        return [p("**The checked energy basis's figures:** HELD. `energy_basis` is not named with an accepted check, so "
                  "`fill_l3r2_from_basis.py` has read nothing (`v2/docs/records/l3r2/README.md`, the fill procedure)."), ""]
    src = B["source"]
    lk = lambda s: "[%s](%s)" % (os.path.basename(s["path"]), os.path.relpath(os.path.join(ROOT, s["path"]), HERE).replace(os.sep, "/"))
    L = [p("**The checked energy basis's figures**, read by exact keys from %s (sha256/16 `%s`) and %s (`%s`) of the "
           "basis at `%s`. Model results; nothing is measured." % (lk(src["energy_basis"]), src["energy_basis"]["sha16"],
                                                                   lk(src["weather_basis"]), src["weather_basis"]["sha16"],
                                                                   src.get("tip"))), "",
         "SC-37's reference plane (40/0), both starts: the lowest store of both packs in Wh (the base's, the lid's), or the "
         "energy unserved; COMB/EACH as the basis defines them (energy_basis.out 5):", "",
         "| Lid | Case | TYP | COMB/EACH | WAB | COMB/EACH |", "|---|---|---|---|---|---|"]
    for k, v in B["reference_plane"].items():
        lid, case = k.split("|")
        L.append("| %s | %s | %s | %s | %s | %s |" % (lid, case, v["TYP"], v["TYP_lines"], v["WAB"], v["WAB_lines"]))
    L += ["", "Modelled historical coverage of the 864 September windows, not a probability of success (weather_basis.out A):", "",
          "| Lid | Case | No STOP | COMB above the floor | EACH above the floor |", "|---|---|---|---|---|"]
    for k, v in B["coverage"].items():
        lid, case = k.split("|")
        L.append("| %s | %s | %s | %s | %s |" % (lid, case, v["STOP"], v["COMB"], v["EACH"]))
    L += ["", "The lids' stores at WE on the mean day and the allowances from nominal to usable (weather_basis.out B):", ""]
    for k, v in B["stores"].items():
        L.append("- %s: %s cells, %s Wh nominal, %s Wh usable (%s of nominal)." % (k, v["cells"], v["nominal_wh"], v["usable_wh"], v["fraction"]))
    for v in B["allowances"]:
        L.append("- the %s pack %s at %s, %s A a cell: %s of nominal, %s Wh usable." % (v["pack"], v["block"], v["at"], v["a_cell"], v["fraction"], v["usable_wh"]))
    return L + [""]


CASE_LABEL = {"a": "AS DRAWN", "a'": "DERATED VARIANT (U3 at {s} A): current-limit coordination only",
              "b": "RESISTOR-ONLY, lower bound: INCONCLUSIVE between this and (c)",
              "c": "HYPOTHETICAL corrected path, not demonstrated (WE also CONDITIONAL on three undocumented efficiencies)"}
LID_SHORT = {"4S9P both kept": "4S9P", "4S14P tablet out": "4S14P", "4S15P QMX out": "4S15P"}


def pp_state(data):
    """Where the findings list stands: restated from the checked record once power_path_check is filed, provisional before."""
    if basis_ok(data, "power_path_check")[0] and any(str(c.get("id")) == "A-1" for c in data.get("power_path_corrections") or []):
        v = data["power_path_check"]
        return ("The list is restated from stream r11dep's record at the tip `%s` its accepted check names (`%s`): A-1 and "
                "A-2, existing defects of the circuit as drawn; B-1 to B-5, defects the resistor-only proposal introduces; "
                "C-1 to C-9, missing evidence, not failures." % (str(v["tip"])[:12], v["check"]))
    return ("PROVISIONAL: the list is stream r11dep's first issue; it is restated from the checked classes once "
            "l3r2.yaml's power_path_check is filed and verified (restate_power_path.py).")


def derated_text(data):
    F = data.get("four_cases")
    return ("%s A (three_cases.out 1)" % F["derated_setting"]) if F else "4.05 A or less"


def four_cell(F, case):
    """Row L3-OD1's cell for one front-end case from four_cases (three_cases.out 2), by exact key."""
    out = [CASE_LABEL[case].format(s=F["derated_setting"]) + "."]
    for inp in ("NOM", "WE"):
        parts = []
        for lid in ("4S14P tablet out", "4S15P QMX out", "4S9P both kept"):
            v = F["reference_day"]["%s|%s|%s" % (case, inp, lid)]
            parts.append("%s TYP %s (%s), WAB %s (%s)" % (LID_SHORT[lid], v["TYP"], v["TYP_lines"], v["WAB"], v["WAB_lines"]))
        out.append("%s: %s." % (inp, "; ".join(parts)))
    return " ".join(out)


def four_cases_lines(data):
    F = data.get("four_cases")
    if not F:
        return [p("**Board A's front end in four cases, the figures:** HELD. `fill_l3r2_from_basis.py` has not read "
                  "`three_cases.out`, which it does only from a basis filed with an accepted check of its tip."), ""]
    src = F["source"]
    L = [p("**Board A's front end in four cases** (D-24, D-25), read by exact keys from [%s](%s) (sha256/16 `%s`, tip "
           "`%s`). SC-37's reference day at 40/0, both starts: the lowest store of both packs in Wh (the base's, the lid's), or "
           "the energy unserved. No figure here is demonstrated capability." % (
               os.path.basename(src["path"]), os.path.relpath(os.path.join(ROOT, src["path"]), HERE).replace(os.sep, "/"),
               src["sha16"], src.get("tip"))), "",
         "| Case | Inputs | Lid | TYP | COMB/EACH | WAB | COMB/EACH |", "|---|---|---|---|---|---|---|"]
    for k, v in F["reference_day"].items():
        case, inp, lid = k.split("|")
        L.append("| %s | %s | %s | %s | %s | %s | %s |" % (cell(CASE_LABEL[case].format(s=F["derated_setting"])), inp, lid,
                                                         v["TYP"], v["TYP_lines"], v["WAB"], v["WAB_lines"]))
    L += ["", "Modelled historical coverage of the 864 September windows in the TYP build, not a probability of success "
          "(three_cases.out 3):", "", "| Case | Inputs | Lid | No STOP | COMB | EACH |", "|---|---|---|---|---|---|"]
    for k, v in F["coverage"].items():
        case, inp, lid = k.split("|")
        L.append("| %s | %s | %s | %s | %s | %s |" % (cell(CASE_LABEL[case].format(s=F["derated_setting"])), inp, lid,
                                                    v["STOP"], v["COMB"], v["EACH"]))
    return L + [""]


def option_cell(d, dec):
    out = []
    for o in d["options"]:
        s = "`%s`: %s" % (o["id"], p(o["label"]))
        if o.get("status"): s += ". **The studied candidate: %s.**" % p(o["status"])
        if o.get("flag"): s += " %s" % p(o["flag"])
        if o.get("disposition"): s += ". *Feasibility disposition: %s.* %s" % (o["disposition"]["kind"], p(o["disposition"]["text"]))
        if o.get("held_until"): s += " (also held until l3r2.yaml %s filed)" % ", ".join("`%s`" % k for k in o["held_until"])
        out.append(s)
    return cell(" ; ".join(out)).replace(" ; ", "<br>")


def recommendation(d, dec):
    """A row's recommendation; while it waits on row L3-OD7 (D-27) it is stated as conditional on that answer and asks
    nothing: no function removed and no deployment condition accepted before row L3-OD7 is answered."""
    w = runtime_wait(d["id"], dec)
    if not w: return d["recommendation"]
    return ("**HELD (D-27): %s.** Stated for the case row L3-OD7 is answered `72-required`, as prepared: %s"
            % (w, d["recommendation"]))


def check_links(name, body):
    """Every relative link on a page resolves to a file in this tree (the evidence the table links to)."""
    for m in LINK.finditer(body):
        target = m.group(1)
        if re.match(r"^[a-z]+:", target): continue
        if not os.path.exists(os.path.normpath(os.path.join(HERE, target))):
            raise RenderError("%s links to %s, which this tree does not hold" % (name, target))


# ------------------------------------------------------------------------------------------------ pages
def held_sentence(data):
    """The rows' hold, stated from the files: held (D-22, D-23, D-24) until both checked files are filed, then the checked
    basis named with its tip."""
    if basis_ok(data)[0] and basis_ok(data, "power_path_check")[0]:
        v = data["energy_basis"]
        return ("Rows L3-OD1, L3-OD2, L3-OD4 and L3-OD6 were held by the owner's review (D-22), his instruction on this "
                "table (D-23) and his addendum (D-24) until the checked energy basis and the checked power path were filed. "
                "Both are, bound to the tip `%s` of stream l3plane that their accepted check names (`%s`), and every figure "
                "on these rows is that basis's, linked to its section. Every result on board A's front end is stated in four "
                "cases (D-24, D-25), and every case is named by its exact weather and operating assumptions: SC-37's mean "
                "day at Leiden, the input sets NOM and WE, and the array builds TYP and WAB on the same day, neither a "
                "weather case." % (str(v["tip"])[:12], v["check"]))
    return ("Rows L3-OD1, L3-OD2 and L3-OD4 are HELD by the owner's review of the draft table (D-22), and row L3-OD6's "
            "recommendation and figures by his instruction on this table (D-23), until the corrected, independently "
            "checked energy comparison is filed (open item S-127) and, by his addendum (D-24), the power path at Option "
            "A(i)'s currents is independently checked (closure item L3-C45); their energy cells state no figure before "
            "them, every result on board A's front end is stated in four cases (D-24, D-25), and no "
            "case is called typical or adverse until the basis names each by its exact weather and operating assumptions.")


def rows_heading(data):
    if basis_ok(data)[0] and basis_ok(data, "power_path_check")[0]:
        return "What the rows propose (AWAITING the owner; their figures are the checked basis's)."
    return "What the rows propose (AWAITING the owner; rows L3-OD1, L3-OD2, L3-OD4 and L3-OD6 HELD, D-22, D-23 and D-24)."


def page_decisions(req, data, dec):
    L = [HEAD, "# Owner decisions needed to close layer 3 (L3-R2)", "",
         p("MESHSAT-1357, %s. The only decisions layer 3 still needs from the owner, one row each, from "
           "`v2/docs/handover/layer3/l3r2.yaml`; every figure is a model or desk result of the records named on "
           "`L3-RECONCILIATION.md`, not a measurement, and nothing here is drawn, built or tested. A recommendation is the "
           "session's and is not an approval (D-21): each row stays AWAITING until the owner's own words decide it. "
           "%s Each row gives its options, the session's recommendation, quantified consequences with their evidence "
           "linked, and its dependencies (D-23). An answer records the owner's REQUIREMENT TARGET; beside each option "
           "stands the studied candidate's status (PASS on a named case, FAIL by how much, INCONCLUSIVE with what is "
           "missing, CONDITIONAL on which corrections) and its feasibility disposition. A target the candidate does not "
           "meet is valid and records a feasibility item; only requirements that cannot both hold are refused (D-26, the "
           "owner's reviewer). Row L3-OD7, M1's runtime, comes first (D-27, the owner: \"Evaluate alternatives before "
           "asking me to sacrifice functions or accept restrictive deployment conditions.\"): rows %s are not asked "
           "before it is answered, their scripts refuse until it is, and its figures are held for the bounded runtime and "
           "battery comparison of stream l3batt, which comes with its check." % (
               data["written_text"], held_sentence(data), ", ".join(RUNTIME_ROWS[:-1]) + " and " + RUNTIME_ROWS[-1])), "",
         p(data.get("proposal_only") or ""), "",
         "| Row | Question | Why it is the owner's: the requirement it changes, quantified (D-25) | Options | Recommendation | "
         "Quantified consequences | Dependencies | Affected | State |",
         "|---|---|---|---|---|---|---|---|---|"]
    for d in data["decisions"]:
        L.append("| %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            d["id"], cell(d["question"]), cell(d["owner_test"]), option_cell(d, dec), cell(recommendation(d, dec)),
            cell(d["consequences"]), cell(d["dependencies"]), cell(d["affected"]), row_state(d["id"], dec, data)))
    L += review_lines(req, data, dec)
    L += ["", "## Board A's front end in four cases: as drawn, derated, the resistor-only proposal and a hypothetical corrected power path", "",
          p("Every Option A(i) energy result depends on board A's front end (fact CF-02 of `L3-RECONCILIATION.md`). Each "
            "row's result is stated in four cases, never merged (D-24, D-25): (a) the circuit as drawn; (a') a DERATED "
            "VARIANT, U3's input limit at %s, which fixes current-limit coordination only and establishes "
            "neither that the other findings are resolved nor that M1 is met; (b) the resistor-only proposal, which is not a "
            "sufficient solution and reads CONDITIONAL or INCONCLUSIVE until the electrical check (l3r2.yaml's "
            "power_path_check) says otherwise; (c) a HYPOTHETICAL corrected power path, whose figures are feasibility "
            "figures, never demonstrated capability, and rest on the requirements and corrections listed after this table."
            % derated_text(data)), "",
          "| Row | (a) The circuit as drawn: R11 10 mOhm | (a') Derated variant: U3 at %s | (b) The resistor-only proposal: R11 6.2 mOhm | (c) A hypothetical corrected power path |" % derated_text(data),
          "|---|---|---|---|---|"]
    F = data.get("four_cases")
    for d in data["decisions"]:
        if not d.get("r11"): continue
        if F and d["id"] == "L3-OD1":                   # filled by exact keys from three_cases.out 2 (CHECK-3 of L3-R2)
            L.append("| %s | %s | %s | %s | %s |" % (d["id"], cell(four_cell(F, "a")), cell(four_cell(F, "a'")),
                                                     cell(four_cell(F, "b")), cell(four_cell(F, "c"))))
        else:
            L.append("| %s | %s | %s | %s | %s |" % (d["id"], cell(d["r11"]["held"]), cell(d["r11"]["derated"]),
                                                     cell(d["r11"]["resistor"]), cell(d["r11"]["corrected"])))
    L += ["", "**The findings case (c) assumes closed.** Engineering tasks with measurable criteria, tracked downstream as "
          "closure items, not owner decisions and not layer 3 prerequisites (D-24, D-25); a row reaches the owner only where "
          "a remedy would change a mission condition, charging time, a function, a deployment condition, an enclosure "
          "constraint or an approved resource, naming the requirement and the consequence. %s" % pp_state(data), "",
          "| Id | Correction | Measurable criterion | Layer | Closure item | Source |", "|---|---|---|---|---|---|"]
    for c in data.get("power_path_corrections") or []:
        L.append("| %s | %s | %s | %s | %s | %s |" % (c["id"], cell(c["item"]), cell(c["criterion"]), c["layer"], c["closure"], cell(c["source"])))
    if data.get("conditional_owner_cases"):
        L += ["", "**Remedies that would change a requirement, if an engineer chose them instead of the engineering form.** None "
              "is asked now (D-25): each correction above has an engineering form that changes no requirement. Each case names "
              "the requirement and its consequence.", "", "| Remedy | Requirement it changes | Consequence |", "|---|---|---|"]
        for c in data["conditional_owner_cases"]:
            L.append("| %s | %s | %s |" % (cell(c["remedy"]), cell(c["requirement"]), cell(c["consequence"])))
    q = next((d for d in data["decisions"] if d.get("quantified")), None)
    if q:
        Q = q["quantified"]
        L += ["", "## Row %s's options, quantified" % q["id"], "", p(Q.get("note") or ""), "",
              "| Option | Build | What it asks | Limitations | Usable energy required (Wh) | Lid block | Cells | Nominal (Wh) | "
              "Cells' mass (kg) | Cells' volume, cylinders / footprint (l) | Times the 4S21P kit: Wh; cells | "
              "4S14P lid (tablet out) | 4S15P lid (QMX out or outside) | 4S9P lid (both kept) | Evidence |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        H = "HELD (S-127)"
        for r in Q["rows"]:
            f = lambda k: H if r.get(k) is None else cell(r[k])
            vol = H if r.get("volume_cyl_l") is None else "%s / %s" % (r["volume_cyl_l"], r["volume_box_l"])
            mult = H if r.get("x_wh") is None else "%s; %s" % (r["x_wh"], r["x_cells"])
            lids = []
            for lid in ("tablet-out", "qmx-out", "both-kept"):
                if r.get("fits") is None: lids.append(H)
                elif lid in r["fits"]: lids.append("carries it")
                else: lids.append("**NO: the studied lid does not carry it** (a feasibility item, D-26)")
            ev = "the checked basis, not filed (S-127)" if not r.get("evidence") else cell(r["evidence"])
            L.append("| `%s`%s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
                r["option"], (" %s percent" % r["share"]) if r.get("share") else "", r["build"], cell(r["asks"]),
                cell(r["limits"]), f("usable_wh"), f("lid_block"), f("cells"), f("nominal_wh"), f("mass_kg"), vol, mult,
                lids[0], lids[1], lids[2], ev))
        L += ["", "The array build cases, exactly (neither is a weather case):", ""]
        for k, v in (Q.get("builds") or {}).items():
            L.append("- **%s:** %s." % (k, p(v)))
    L += ["", "## Applying an answer", "",
          p("Each row has a prepared registry restatement, not applied: `python3 %s/<script> --option <option> --words "
            "\"<the owner's words>\" --date <YYYY-MM-DD>` records his answer as an owner ruling that names the row and "
            "applies the exact registry change; `--check` does the same in memory and writes nothing. A row whose "
            "`requires` is not met is refused. After a script: `rules_lib.py requirements`, `rules_render.py "
            "--requirements` and this renderer." % data["scripts"]["conditional_dir"]), "",
          "| Row | Script | Options | Requires | Held until |", "|---|---|---|---|---|"]
    for d in data["decisions"]:
        L.append("| %s | `%s` | %s | %s | %s |" % (d["id"], d["script"], "; ".join("`%s`%s" % (o["id"], (" (also held until `%s`)" % ", ".join(o["held_until"])) if o.get("held_until") else "") for o in d["options"]),
                                                  ", ".join(d.get("requires") or []) or "none",
                                                  ", ".join("l3r2.yaml `%s` filed" % k for k in (d.get("held_until") or [])) or "nothing"))
    L += ["", "## Requirements that cannot both hold: the only answers refused (D-26)", "",
          p("The prepared scripts refuse an answer only where two rulings would set requirements that cannot both hold, "
            "and the completion gate reads the target unambiguous only when none does. A combination whose studied "
            "candidate fails is not among them: it records a feasibility item (the owner's reviewer: \"A combination can "
            "be a valid target and have a FAIL or INCONCLUSIVE implementation\")."), "", "| Rule | Why |", "|---|---|"]
    for c in data.get("contradictions") or []:
        L.append("| %s | %s |" % (cell(c["rule"]), cell(c["why"])))
    return "\n".join(L) + "\n"


def review_lines(req, data, dec):
    """The review's sections (D-26): the status level, the acceptance definitions, the feasibility items and the
    reviewer's directions, each from l3r2.yaml."""
    rv = data.get("review") or {}
    lvl, sentence = status_level(req, dec, data, load_h3())
    L = ["", "## Where layer 3 stands: the reviewer's three status levels (D-26)", "",
         p("The owner's reviewer reviewed the decision brief %s: \"%s\". No owner answer is recorded yet unless a row above "
           "reads DECIDED." % (rv.get("brief", ""), rv.get("verdict", ""))), "",
         "| Level | What it means | When it holds here |", "|---|---|---|"]
    for x in data.get("status_levels") or []:
        L.append("| %s%s | %s | %s |" % (x["name"], " (HOLDS)" if x["id"] == lvl else "", cell(x["means"]), cell(x["holds_when"])))
    fb = data.get("feasibility_basis") or {}
    fok, fwhy = basis_ok(data, "feasibility_basis")
    chk = filed(data, "feasibility_checks") or []
    L += ["", p(sentence), "", "## The acceptance definitions (D-26)", "",
          p("Each is written into the prepared restatement named, so that the requirement an answer records states its "
            "own pass line. Definitions 1b and 3, and feasibility items FI-02 and FI-06, rest on the bounded feasibility "
            "record [%s](%s) of stream l3feas at `%s`: %s. Its checks, filed byte for byte: %s." % (
                os.path.basename(str(fb.get("record"))), os.path.relpath(os.path.join(ROOT, str(fb.get("record"))), HERE).replace(os.sep, "/"),
                str(fb.get("tip"))[:12],
                "bound to that tip and accepted by its check `%s`, every file byte identical to the tip's" % fb.get("check")
                if fok else "NOT BOUND (%s): the definitions resting on it read pending" % fwhy,
                "; ".join("[%s](%s), of %s, %s" % (os.path.basename(c["record"]),
                                                  os.path.relpath(os.path.join(ROOT, c["record"]), HERE).replace(os.sep, "/"),
                                                  c.get("of"), c.get("verdict")) for c in chk) or "none"))]
    for a in data.get("acceptance_definitions") or []:
        L += ["", "**%s. %s** (row %s, %s; `%s`)%s" % (a["label"], a["title"][0].upper() + a["title"][1:], a["row"],
                                                        a["requirement"], a["script"],
                                                        " PENDING: its feasibility record is not bound" if a["row"] in ("L3-OD1", "L3-OD3") and
                                                        not fok else ""),
              "", p(a["text"])]
        if a.get("table"):
            L += ["", "| Mode | Environment | Functions available | Source |", "|---|---|---|---|"]
            for t in a["table"]:
                L.append("| %s | %s | %s | %s |" % (cell(t["mode"]), cell(t["environment"]), cell(t["functions"]), cell(t["source"])))
        if a.get("consequence"): L += ["", p("**The operational consequence, which the owner's acceptance covers:** " + a["consequence"])]
        if a.get("choice"): L += ["", p("**The owner's choice:** " + a["choice"])]
    L += ["", "## The feasibility items an answer records (D-26)", "",
          p("A target the studied candidate does not meet is recorded with its feasibility item, a feasibility record in "
            "the requirements registry whose page is this one (FEASIBILITY_OPEN, a BLOCKER on the core, reading FAIL or "
            "INCONCLUSIVE, never PASS). The candidate statements are scoped to the studied architecture and its "
            "established arrangements, never a proof about every architecture. Recorded now: %s." % (
                ", ".join("%s as %s" % (i, rid) for i, rid, k in feasibility(req, dec, data)) or "none, since no row is "
                "decided")), "",
          "| Item | Recorded when | What | The owner's target | The studied candidate | Disposition | Blocks |",
          "|---|---|---|---|---|---|---|"]
    for x in data.get("feasibility_items") or []:
        L.append("| %s | %s | %s | %s | %s | %s: %s | %s |" % (x["id"], cell(x["trigger"]), cell(x["title"]), cell(x["target"]),
                                                             cell(x["candidate"]), x["disposition"]["kind"],
                                                             cell(x["disposition"]["text"]), ", ".join(x["blocks"])))
    L += ["", "## The owner's reviewer's directions (D-26), recorded as the reviewer's, not as approvals", "",
          p("Each direction is one of the review's passages quoted word for word in `OWNER-INSTRUCTION-2026-09-30.md` and "
            "recorded as owner ruling D-26; it binds how the rows are presented and applied, and it answers no row."), "",
          "| Passage | Rows | Direction |", "|---|---|---|"]
    for r in data.get("reviewer_directions") or []:
        L.append("| %d | %s | %s |" % (r["passage"], ", ".join(r["rows"]) or "the gate", cell(r["text"])))
    return L


def page_recon(req, data, dec, h3, root):
    recs = {r["id"]: r for r in req["records"]}
    L = [HEAD, "# Layer 3 reconciliation for the current target (L3-R2)", "",
         p("MESHSAT-1357, %s, on the owner's instruction of that day (`%s`, owner ruling D-21). Prototype design: no V2 "
           "board has been fabricated, ordered, assembled or powered, and no kit has been field deployed. This page "
           "reconciles the requirements handover H3 accepted (registry %s) with the owner's decisions since and the "
           "proposals made since, and lists what closes layer 3. Its companions: `OWNER-DECISIONS-L3.md` (the owner's "
           "rows) and `REQUIREMENTS-L3-R2.md` (the consolidated specification). All three are generated from the "
           "registry and `l3r2.yaml`." % (data["written_text"], data["instruction"], data["h3"]["baseline"])), "",
         "## (a) The current target configuration", ""]
    g1 = gate(req, dec, data, h3)[0][1]
    L += target_lines(req, data, dec, g1, rows_heading(data))
    L += facts_lines(data, req)
    L += basis_figures_lines(data)
    L += four_cases_lines(data)
    L += ["**Under the other answers of each row:**", ""]
    for a in data["target"]["alternatives"]:
        L.append("- %s, option `%s`: %s" % (a["row"], a["option"], p(a["text"])))
    if dec:
        L += ["", "**Decided so far:** " + "; ".join("%s `%s` by %s (%s)" % (r, v[0], v[1], v[2]) for r, v in sorted(dec.items())) + "."]
    else:
        L += ["", "**Decided so far:** none of the %d rows." % len(data["decisions"])]
    L += ["", "## (b) Every requirement-changing proposal since H3", "",
          p("Status APPROVED or REJECTED only on the owner's words, cited; a session proposal is AWAITING (D-21); "
            "WITHDRAWN is a session's own text it reverted; NOT_A_REQUIREMENT_CHANGE is an implementation choice or a "
            "record, listed so that nothing is missed. " + p(data.get("proposal_only") or "")), "",
          "| Id | Proposal | Source | What it would change | Status | Basis | Records | Row |", "|---|---|---|---|---|---|---|---|"]
    for pr in data["proposals"]:
        st = pr["status"]
        row = pr.get("decision")
        if row and row in dec: st = "%s (now DECIDED: %s, %s)" % (st, dec[row][0], dec[row][1])
        L.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
            pr["id"], cell(pr["title"]), cell("; ".join(pr["source"])), cell(pr["changes"]), st, cell(pr["basis"]),
            ", ".join(pr.get("affects") or []) or "none", row or ""))
    L += ["", "The owner questions of `v2/docs/EXECUTION-PLAN.md` (29 September 2026), which the rows replace:", "",
          "| Question | Row | What changed |", "|---|---|---|"]
    for q in data.get("execution_plan_questions") or []:
        L.append("| %s | %s | %s |" % (q["q"], q["row"], cell(q["note"])))
    L += ["", "## (c) Requirement or implementation", "",
          "| Item | Level | Where it lives |", "|---|---|---|"]
    for c in data["classification"]:
        lvl = c["level"] + ((" (layer %s)" % c["layer"]) if c.get("layer") else " (layer 3)")
        L.append("| %s | %s | %s |" % (cell(c["item"]), lvl, cell(c["where"])))
    L += ["", "## (d) The layer 3 closure list", "",
          p("Each item with whose it is, what closes it and its state, the state read live from the registry where the "
            "registry or a filed file decides it: CLOSED, CLOSED (decided) once the owner's row is applied, AWAITING_OWNER, "
            "HELD (D-22 to D-24, waiting on the checked files), DOWNSTREAM (a later layer's, holding no layer 3 statement) or OPEN."), "",
          "| Id | Item | Whose | Closes by | State | Registry now |", "|---|---|---|---|---|---|"]
    for it in data["closure"]:
        live = ""
        if it.get("record") and it["record"] in recs:
            r = recs[it["record"]]
            live = "%s %s, %s" % (it["record"], r.get("status"), r.get("evidence_result"))
        L.append("| %s | %s | %s | %s | %s | %s |" % (it["id"], cell(it["item"]), it["whose"], cell(it["closes_by"]),
                                                     closure_state(it, req, dec, data), live))
    if data.get("carried_items"):
        L += ["", "### Carried items: minors of the checks kept in the record, not reopened", "",
              "| Id | From | Item | Where it is carried |", "|---|---|---|---|"]
        for c in data["carried_items"]:
            L.append("| %s | %s | %s | %s |" % (c["id"], cell(c["from"]), cell(c["item"]), cell(c["where"])))
    # requirement-level TBD mentions
    L += ["", "### Requirement-level TBDs: every 'TBD', 'TBC', 'owed', 'not yet stated', 'exists yet' and 'open' state sentence in a statement, acceptance or note", "",
          "| Record | Field | Text around it | Classification |", "|---|---|---|---|"]
    cls = data.get("tbd_mentions") or {}
    for rid, f, snip in tbd_mentions(req):
        L.append("| %s | %s | %s | %s |" % (rid, f, cell(snip), cell(cls.get(rid, "UNCLASSIFIED: add it to l3r2.yaml tbd_mentions"))))
    L += ["", p("Records whose status is TBD: %s." % (", ".join(r["id"] for r in req["records"] if r.get("status") == "TBD") or "none"))]
    # open items by layer
    lay = data.get("open_items_layer") or {}
    waited = {}
    for r in req["records"]:
        for w in r.get("waits_on") or []: waited.setdefault(w, []).append(r["id"])
    L += ["", "### Open items, by the layer each belongs to", "",
          p("%d open items. %s; %s; everything else is downstream work, an outside step or tooling, and holds no "
            "requirement's statement." % (len(req["open_items"]), l3_open_clause(req, lay), s127_clause(req, data))), "",
          "| Item | Class | Layer | Why | Records waiting on it | Disposition |", "|---|---|---|---|---|---|"]
    for it in sorted(req["open_items"], key=lambda x: (str((lay.get(x["id"]) or {}).get("layer", "?")), x["id"])):
        e = lay.get(it["id"]) or {}
        L.append("| %s | %s | %s | %s | %s | %s |" % (it["id"], it.get("class"), e.get("layer", "UNCLASSIFIED"), cell(e.get("why", "")),
                                                     ", ".join(waited.get(it["id"], [])) or "none",
                                                     cell(it.get("disposition") or "")))
    orphans = [it["id"] for it in req["open_items"] if it["id"] not in waited]
    L += ["", p("Acceptance item 3.15: %d open items are in no record's `waits_on` (%s); each carries a disposition with its "
                "reason, which the validator enforces." % (len(orphans), ", ".join(orphans) or "none"))]
    # passages
    L += ["", "### Baselined passages a decided row changes (re-issued through layers 1 and 2, never edited here)", "",
          "| Row | File | Lines matching today | Why |", "|---|---|---|---|"]
    for ps, hits in passages(data, root):
        L.append("| %s | `%s` | %s | %s |" % (ps["row"], ps["file"], ", ".join(map(str, hits)) or "none", cell(ps["why"])))
    return "\n".join(L) + "\n"


def findings_lines(data):
    L = []
    for f in data.get("findings") or []:
        L += ["**Feasibility finding %s for the owner: %s.** %s" % (f["id"], p(f["title"]), p(f["text"])), ""]
    return L


def need_title(req):
    return {n["id"]: p(n["statement"]) for n in req["needs"]}


def page_spec(req, data, dec, h3, root):
    recs = req["records"]
    byid = {r["id"]: r for r in recs}
    rulings = {r["id"]: r for r in req["owner_rulings"]}
    choices = {c["id"]: c for c in req["session_choices"]}
    lay = data.get("open_items_layer") or {}
    tp = testplan_refs(root)
    changes = baseline_changes(req, h3, data)
    changed = {i: f for i, _, f in changes}
    pend = {}
    for d in data["decisions"]:
        for i in re.findall(r"\b((?:REQ|CON|CFL|SPD)-\d{3})\b", d["affected"]):
            pend.setdefault(i, []).append(d["id"])
    env = yaml.safe_load(open(os.path.join(TOOLS, "pcb_envelope.yaml"), encoding="utf-8"))
    reg_sha = data["_registry_sha16"]
    L = [HEAD, "# %s (%s)" % (data["title"], data["version"]), "",
         p("MESHSAT-1357, issue %s of %s, generated from the requirements registry `v2/ecad/tools/pcb_requirements.yaml` "
           "(sha256/16 `%s`, registry state `%s`) and `v2/docs/handover/layer3/l3r2.yaml`. **Prototype design: no V2 board "
           "has been fabricated, ordered, assembled or powered, and no kit has been field deployed.** Every statement below "
           "is a requirement, what the kit is to do, and every acceptance is how success will be judged; a planned test is "
           "never marked passed, and a reading is a desk reading of named files unless it says otherwise. The original H3 "
           "release (`v2/release/handover/H3.zip`, registry %s) is preserved and unchanged." % (
               data["version"], data["written_text"], reg_sha, req.get("baseline_state"), data["h3"]["baseline"])), "",
         "## 1. How to read this document", "",
         "- **Ids are stable.** REQ requirement, CON derived constraint, ASM assumption, CHO implementation choice, CFL conflict between sources, FEA architecture feasibility blocker, SPD superseded statement; D-nn an owner ruling, SC-nn a session choice (the session's, reversible), S-nn, M-nn, L-nn open items. An id is never reused.",
         "- **Sources.** Each record names the need it serves (quoted from `v2/docs/CONOPS.md` section 2, pinned by sha256), the owner rulings and session choices that set it, and its source files. Only an owner ruling is an approval; a session choice is recorded as the session's under the owner's standing rule of 26 September 2026 and can be reversed.",
         "- **Applicability.** `core` records are what prototype 1 is accepted on (owner ruling D-01); `deferred` records are designed and fitted where copper exists and reported NOT_YET_TESTED, never as a pass.",
         "- **Acceptance and verification.** The acceptance is the pass line; the method and the earliest phase at which it can be judged, and the final phase where a later measurement is owed. A record's current reading is its own desk reading; rule verdicts live on `v2/docs/REQUIREMENTS-TRACE.md` and the board status pages.",
         "- **Pending owner decisions** are shown inline where they apply (section 3 lists them). Until one is decided, the record reads as the registry states it today.",
         ""]
    # status and gate
    g = gate(req, dec, data, h3)
    L += ["## 2. Status of this issue and the completion gate", "",
          p("Layer 3 reaches completion only when all four conditions of the owner's instruction of 30 September 2026 (D-21) "
            "hold. Completed circuits and physical tests belong to later verification stages and are not conditions here."), "",
          "| Condition | Met | State |", "|---|---|---|"]
    for name, ok, st in g:
        L.append("| %s | %s | %s |" % (name, "MET" if ok else "NOT MET", cell(st)))
    L += ["", p("**Status of L3-R2: %s.**" % ("COMPLETE" if all(x[1] for x in g) else
                                               "IN_PROGRESS (the conditions above that read NOT MET)")), "",
          p("**Status level (the owner's reviewer's three, D-26):** " + status_level(req, dec, data, h3, g)[1] +
            " The fifth condition joins the gate with D-26: a recorded target may have a FAIL or INCONCLUSIVE "
            "candidate, but not an owed disposition."), ""]
    # target
    L += ["## 3. The target configuration and the pending owner decisions", "",
          ] + target_lines(req, data, dec, g[0][1], rows_heading(data)) + facts_lines(data, req) + [
          "| Row | Question | Options | Recommendation | State |", "|---|---|---|---|---|"]
    for d in data["decisions"]:
        L.append("| %s | %s | %s | %s | %s |" % (d["id"], cell(d["question"]), option_cell(d, dec), cell(d["recommendation"]),
                                               row_state(d["id"], dec, data)))
    L += ["", p("The quantified consequences, the dependencies, board A's front end in four cases with the corrections, row L3-OD6's options table "
                "and the scripts that apply each answer: `OWNER-DECISIONS-L3.md`. The proposals behind them, with their "
                "status and sources: `L3-RECONCILIATION.md` (b). " + p(data.get("proposal_only") or "")), ""]
    # operating conditions
    amb = env.get("ambient_c") or {}
    L += ["## 4. Operating conditions", "",
          "| Condition | Value | Source |", "|---|---|---|",
          "| Ambient in use | %s to %s C | `pcb_envelope.yaml` (ENV-001), `v2/docs/OPERATING-ENVELOPE.md` section 4 |" % (amb["in_use"]["min"], amb["in_use"]["max"]),
          "| Storage, up to three months | %s to %s C | the same |" % (amb["storage_3_months"]["min"], amb["storage_3_months"]["max"]),
          "| Storage, up to a year | %s to %s C | the same |" % (amb["storage_1_year"]["min"], amb["storage_1_year"]["max"])]
    for rid in ("D-02a", "D-02b", "D-02c", "D-02d", "D-02e", "D-04", "D-16", "D-20", "D-21", "D-22"):
        r = rulings.get(rid)
        if r: L.append("| %s (owner, %s) | %s | owner ruling %s |" % (cell(r["title"]), r["ruled_on"], cell(r["ruling"]), rid))
    for cid in ("SC-21", "SC-37"):
        c = choices.get(cid)
        if c: L.append("| %s (session, %s) | %s | session choice %s |" % (cell(c["question"]), c["taken_on"], cell(c["taken"]), cid))
    L += ["", p("**Mission M1's conditions, in one place.** 72 hours (SC-21, preserved by D-20, approved by D-21) in "
                "PS-IDLE-SPEC (42.8 W at the pack terminals, `feasibility/POWER-THERMAL.md` section 4) on the kit's own "
                "store and its solar input, battery and solar mandatory and an external DC source never the basis (D-20, "
                "D-21, D-22), from a full aged store, lid open and the kit shaded (D-02e), judged on the reference day of "
                "SC-37 (September at Leiden, 4.0 kWh/m2 a day on the optimally inclined plane, 40 degrees facing south). "
                "M1 carries no season (CONOPS section 3): the reference day is the verification condition of REQ-072's desk "
                "acceptance, not a restriction on where or when the kit is used, and a month with less sun asks more of the "
                "array (SC-37). Any M1 energy claim holds across the kit's supply range, with every limit that must hold a "
                "load at its minimum (D-22: 'If 19.08 V is permitted, mission claims must account for it'); the range and "
                "its effect on the calculation are the energy basis (fact CF-01). **Pending (L3-OD4):** the open kit's "
                "ground slope and operator push, as narrower operating conditions for the owner's approval; no plane band "
                "exists at the supply range's low end with U3's 6.0 A bracket, so none is proposed. **Pending (L3-OD6):** "
                "M1's weather basis, a quantified choice between the average-day benchmark (SC-37's reference day as "
                "REQ-072 states it today; one site and one month's mean day repeated, a mean day is not a cloudy day, and "
                "it states no share of real weather in which M1 holds) and historical-coverage targets on the September "
                "record of fact CF-03, each with the store it needs and whether that fits the case (no coverage target "
                "fits it). Every M1 figure that meets rests on the hypothetical corrected power path (finding F-01)."), ""]
    # the requirements by need
    L += ["## 5. The requirements, by need", "",
          p("Every live record, grouped by the need it serves. For each: statement; applicability; acceptance; "
            "verification; allocation; its sources; the rules and decisions that judge or settle part of it; the TEST-PLAN "
            "places that name it; its current reading; what it waits on, with the layer of each item; and any owner decision "
            "pending on it or change since H3."), ""]
    needs = need_title(req)
    for nid in sorted(needs):
        rs = [r for r in recs if r.get("parent") == nid and r["kind"] != "superseded"]
        L += ["### %s: %s" % (nid, needs[nid]), "",
              p("Prototype 1 core need: %s." % ("yes" if nid in set(R.core_needs(req)) else "no")), ""]
        for r in sorted(rs, key=lambda x: x["id"]):
            L += spec_record(r, byid, rulings, choices, lay, tp, pend, changed, dec, data)
    sup = [r for r in recs if r["kind"] == "superseded"]
    L += ["### Superseded statements (kept so nobody re-opens them)", ""]
    for r in sorted(sup, key=lambda x: x["id"]):
        L.append("- **%s** (%s): %s Superseded by: %s" % (r["id"], r.get("parent"), p(r["statement"]), p(r.get("superseded_by"))))
    L.append("")
    # change record
    L += change_record(req, h3, data, changes)
    # impacts by layer
    L += ["## 7. Downstream impacts by layer", "",
          p("For each record changed since H3, and for each change a pending decision would make, what it moves in layers 4 "
            "to 9 (from `l3r2.yaml` impacts; a changed record with no entry is refused by the renderer)."), "",
          "| Layer | Record | Why | Impact |", "|---|---|---|---|"]
    imp = data.get("impacts") or {}
    for layer in LAYERS:
        for rid in sorted(imp):
            v = (imp[rid].get("layers") or {}).get(int(layer)) or (imp[rid].get("layers") or {}).get(layer)
            if v and p(v) != "none":
                applied = "applied" if rid in changed else "if decided"
                L.append("| %s | %s (%s) | %s | %s |" % (layer, rid, applied, cell(imp[rid]["why"]), cell(v)))
    L += ["", "## 8. Traceability summary", "",
          "| Need | Core | Records | Rules named | TEST-PLAN places |", "|---|---|---|---|---|"]
    for nid in sorted(needs):
        rs = [r for r in recs if r.get("parent") == nid and r["kind"] != "superseded"]
        rules = sorted({x for r in rs for x in ((r.get("satisfied_by") or {}).get("rules") or [])})
        tps = sorted({x for r in rs for x in tp.get(r["id"], [])})
        L.append("| %s | %s | %s | %s | %s |" % (nid, "yes" if nid in set(R.core_needs(req)) else "no",
                                                 ", ".join(r["id"] for r in sorted(rs, key=lambda x: x["id"])),
                                                 ", ".join(rules) or "none", "; ".join(tps) or "none"))
    untraced = [r["id"] for r in recs if r["kind"] not in ("superseded",) and r.get("final_phase") == "PROTOTYPE"
                and not tp.get(r["id"])]
    L += ["", p("Records whose final phase is PROTOTYPE and that no TEST-PLAN line names by id: %d (%s). Each is verified "
                "by the method its entry states; a TEST-PLAN row for it is a layer 9 and test-plan item, not a requirement "
                "change." % (len(untraced), ", ".join(untraced) or "none")), ""]
    return "\n".join(L) + "\n"


def spec_record(r, byid, rulings, choices, lay, tp, pend, changed, dec, data):
    rid = r["id"]
    sb = r.get("satisfied_by") or {}
    src = []
    for x in r.get("rulings") or []: src.append("%s (owner, %s)" % (x, rulings[x]["ruled_on"]) if x in rulings else x)
    for x in r.get("choices") or []: src.append("%s (session, %s)" % (x, choices[x]["taken_on"]) if x in choices else x)
    files = [s for s in (r.get("source") or []) if not str(s).startswith(("owner ruling", "session choice"))]
    appl = "%s (%s%s)" % (r.get("prototype_1") or "n/a", r.get("prototype_1_basis") or "",
                          (": " + p(r.get("prototype_1_why"))) if r.get("prototype_1_why") else "")
    ver = "%s at %s" % (", ".join(r.get("verification_method") or []), r.get("verification_phase"))
    if r.get("final_phase") and r.get("final_phase") != r.get("verification_phase"): ver += ", final %s" % r["final_phase"]
    reading = "%s%s%s" % (r.get("evidence_result"), (" at " + r["evidence_phase"]) if r.get("evidence_phase") else "",
                          (", " + r["evidence_class"]) if r.get("evidence_class") else "")
    waits = ["%s (layer %s)" % (w, (lay.get(w) or {}).get("layer", "?")) for w in (r.get("waits_on") or [])]
    L = ["#### %s (%s, %s, %s)" % (rid, r["kind"], r.get("status"), r.get("release_effect")), "",
         "- **Statement:** " + p(r["statement"]),
         "- **Applicability:** " + appl,
         "- **Acceptance:** " + p(r["acceptance"]),
         "- **Verification:** " + ver + "; allocated to " + ", ".join(r.get("allocated_to") or []),
         "- **Sources:** need %s; %s%s" % (r.get("parent"), "; ".join(src) or "no ruling or choice",
                                             ("; files: " + "; ".join(p(f) for f in files)) if files else ""),
         "- **Judged or settled by:** rules %s (coverage %s); decisions %s" % (
             ", ".join(sb.get("rules") or []) or "none", r.get("rule_coverage"), ", ".join(map(str, sb.get("decisions") or [])) or "none"),
         "- **TEST-PLAN:** " + ("; ".join(tp.get(rid, [])) or "not named by id"),
         "- **Current reading:** " + reading + (" (%d evidence entries; `REQUIREMENTS-TRACE.md` lists them)" % len(r.get("evidence") or []) if r.get("evidence") else ""),
         "- **Waits on:** " + (", ".join(waits) or "nothing")]
    if r.get("resolved_by"): L.append("- **Resolved by:** " + p(r["resolved_by"]))
    if r.get("tbd_effect"): L.append("- **TBD effect:** " + p(r["tbd_effect"]))
    for row in pend.get(rid, []):
        st = row_state(row, dec, data)
        L.append("- **Pending owner decision %s:** %s; the restatement it applies is prepared, not applied." % (row, st))
    if rid in changed: L.append("- **Changed since H3:** %s (section 6)." % ", ".join(changed[rid]))
    L.append("")
    return L


def change_record(req, h3, data, changes):
    L = ["## 6. Change record since H3", "",
         p("Computed from H3's registry as released (`%s`, member sha256/16 `%s`, %s) against this registry. A change to a "
           "statement, acceptance, applicability, allocation, verification, release effect, kind, parent or status is a "
           "change to the baseline and is listed with its downstream impact; readings, bindings and open items move "
           "without a review of the baseline and are counted." % (h3["source"], h3["member_sha256"][:16], h3["baseline_state"])), "",
         "### 6.1 Baseline changes", "", "| Record | Change | Fields | Why | Layers affected |", "|---|---|---|---|---|"]
    imp = data.get("impacts") or {}
    for rid, kind, f in changes:
        lay = ", ".join(str(k) for k, v in sorted((imp[rid].get("layers") or {}).items(), key=lambda x: str(x[0])) if p(v) != "none")
        L.append("| %s | %s | %s | %s | %s |" % (rid, kind, ", ".join(f), cell(imp[rid]["why"]), lay or "none"))
    if not changes: L.append("| none | | | | |")
    cur = {r["id"]: r for r in req["records"]}
    rd = [(i, h3["records"][i].get("evidence_result"), r.get("evidence_result")) for i, r in cur.items()
          if i in h3["records"] and h3["records"][i].get("evidence_result") != r.get("evidence_result")]
    nev = sum(1 for i, r in cur.items() if len(r.get("evidence") or []) != h3["evidence_counts"].get(i, 0))
    add = lambda k: sorted(set(x["id"] for x in req[k]) - set(h3[k]), key=lambda s: (len(s), s))
    gone = lambda k: sorted(set(h3[k]) - set(x["id"] for x in req[k]), key=lambda s: (len(s), s))
    L += ["", "### 6.2 Rulings, choices, items and readings", "",
          "- **Owner rulings added:** " + (", ".join("%s (%s, %s)" % (x["id"], x["ruled_on"], p(x["title"])) for x in req["owner_rulings"] if x["id"] in add("owner_rulings")) or "none"),
          "- **Session choices added:** " + (", ".join(add("session_choices")) or "none"),
          "- **Open items added:** " + (", ".join(add("open_items")) or "none"),
          "- **Open items closed:** " + (", ".join(add("closed_items")) or "none"),
          "- **Readings that changed result:** " + (", ".join("%s %s to %s" % x for x in sorted(rd)) or "none"),
          "- **Records whose evidence list changed:** %d" % nev,
          "- **The needs document's pin:** %s" % ("unchanged" if h3["needs_document_sha256"] == req["needs_document_sha256"] else
                                                   "re-taken, `%s` to `%s` (CONOPS re-stamped and restored; its needs table unchanged, which the validator checks)"
                                                   % (h3["needs_document_sha256"][:16], req["needs_document_sha256"][:16])),
          ""]
    return L


def render_all(root=ROOT, registry=None):
    data = load_data()
    req = R.load_requirements(registry)
    data["_registry_sha16"] = sha16_bytes(open(registry or R.REQUIREMENTS, "rb").read())
    errs, _w = R.validate_requirements(req, root=root, citing=())
    if errs: raise RenderError("the registry does not validate (%d errors): %s" % (len(errs), "; ".join(errs[:3])))
    h3 = load_h3()
    dec = decided(req, data)
    out = {PAGES["decisions"]: page_decisions(req, data, dec),
           PAGES["recon"]: page_recon(req, data, dec, h3, root),
           PAGES["spec"]: page_spec(req, data, dec, h3, root)}
    for name, body in out.items():
        for d in DASHES:
            if d in body: raise RenderError("%s would carry a dash character" % name)
        check_links(name, body)
    return out


def main(argv):
    if "--freeze" in argv:
        body = freeze(load_data())
        open(DIGEST, "w", encoding="utf-8").write(body)
        print("render_l3r2: wrote %s" % rel(DIGEST)); return 0
    reg = argv[argv.index("--registry") + 1] if "--registry" in argv else None
    out = argv[argv.index("--out-dir") + 1] if "--out-dir" in argv else HERE
    try: pages = render_all(registry=reg)
    except RenderError as e:
        print("render_l3r2: REFUSED: %s" % e); return 1
    if "--check" in argv:
        bad = [n for n, b in pages.items() if not os.path.exists(os.path.join(out, n)) or open(os.path.join(out, n), encoding="utf-8").read() != b]
        for n in bad: print("render_l3r2: %s differs from what the inputs render" % n)
        print("render_l3r2: %d page(s), %d out of date" % (len(pages), len(bad)))
        return 1 if bad else 0
    for n, b in pages.items():
        open(os.path.join(out, n), "w", encoding="utf-8").write(b)
        print("render_l3r2: wrote %s (%d lines)" % (n, b.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
