#!/usr/bin/env python3
"""S-119's closure in the requirements registry (stream s119, MESHSAT-1357, 29 September 2026; second round after the
stream's independent check). DRAFT for the integrator, run AFTER apply_decision_s119.py.

  close <commit>  refuses unless
                  (1) every file of the restated chain is tracked, carries no uncommitted change, and has the same content
                      at <commit> as in the working tree (the rows, the drawn U3B and the re-run outputs are committed);
                  (2) the two rows read as restated: energy_inputs.yaml's U3 row (YAML reader) equals
                      records/s117/efficiency.out section 7's figures (its table parsed), and energy_two_pack.py's eta_u3b
                      and its bracket (ast) equal records/s119/u3b_hourly.out's carried figure and bracket (parsed);
                  (3) every sha256 pin along the chain names the committed file (read with ast from each script);
                  (4) unless --no-rerun, every script of the chain re-run now prints its committed output byte for byte
                      (about three minutes of pure Python on this host);
                  (5) reconcile_s119.out reads the failing case NOT MET everywhere ("the instrument discriminates");
                  (6) the session decision "(S-119 U3B)" is ruled in tools/pcb_decisions.yaml (apply_decision_s119.py);
                  (7) records/a1elec/TOPOLOGY.md 3b's parts table (parsed as a table, by its first cell) draws U3B on the
                      400 kHz row: Q7B and Q9B CSD17578Q5A, Q8B and Q10B CSD17577Q5A, L2B XAL1010-472ME, 191 k, R16B 10 mOhm.
                  Then: S-119 moves to closed_items (closed by <commit>, its closing evidence with every figure read here
                  from the outputs); U3B's FET finding is filed as the closed SESSION item S-121 (the number the
                  integrator reserved for it; the script refuses if S-121 is already in the registry), closed by the same
                  commit, the decision's number read from the register; REQ-072 leaves S-119 in its
                  waits_on and gains one evidence entry; its statement, acceptance and evidence_result (FAIL) do not move.

Every new text passes int7's screen (no claim word, no dash); the registry is re-parsed and only what is named may move;
a second run refuses. --check validates in memory and writes nothing.
Usage (anywhere in the tree): python3 apply_registry_s119.py close <commit> [--check] [--no-rerun]"""
import ast
import hashlib
import os
import re
import subprocess
import sys

import yaml

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
TOP = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=HERE, capture_output=True, check=True).stdout.decode().strip()
REG = os.path.join(TOP, "v2/ecad/tools/pcb_requirements.yaml")
DEC = os.path.join(TOP, "v2/ecad/tools/pcb_decisions.yaml")
sys.path.insert(0, os.path.join(TOP, "v2/docs/records/int7"))
sys.path.insert(0, os.path.join(TOP, "v2/ecad/tools"))
import apply_check1_answers as A  # noqa: E402

R = "v2/docs/records/"
# (script, its output); each output is regenerated by its script from the repository root
CHAIN = [(R + "energy/energy_budget.py", R + "energy/energy_budget.out"),
         (R + "energy/energy_architecture.py", R + "energy/energy_architecture.out"),
         (R + "energy/energy_4s6p.py", R + "energy/energy_4s6p.out"),
         (R + "energy/night_bounds.py", R + "energy/night_bounds.out"),
         (R + "energy/packfit_west.py", R + "energy/packfit_west.out"),
         (R + "energy/checks/recompute.py", R + "energy/checks/recompute.out"),
         (R + "a1elec/energy_two_pack.py", R + "a1elec/energy_two_pack.out"),
         (R + "a1elec/checks/recheck_two_pack.py", R + "a1elec/checks/recheck_two_pack.out"),
         (R + "s117/efficiency.py", R + "s117/efficiency.out"),
         (R + "s119/u3b_hourly.py", R + "s119/u3b_hourly.out"),
         (R + "s119/inductor_u3b.py", R + "s119/inductor_u3b.out"),
         (R + "a1solar/array_calc.py", R + "a1solar/array_calc.out"),
         (R + "a1solar/energy_runs.py", R + "a1solar/energy_runs.out"),
         (R + "a1int/reconcile_lid.py", R + "a1int/reconcile_lid.out"),
         (R + "a1int/reconcile_lid_panel.py", R + "a1int/reconcile_lid_panel.out"),
         (R + "s119/reconcile_s119.py", R + "s119/reconcile_s119.out")]
FILES = [R + "energy/energy_inputs.yaml", R + "a1elec/TOPOLOGY.md", R + "a1elec/CHARGER.md"] + [f for pair in CHAIN for f in pair]
MARK_U3B = "(stream s119, S-119's U3B finding)"
U3B_ID = "S-121"   # reserved by the integrator for this item (29 September 2026); S-122 is another stream's
EV_MARK = "v2/docs/records/s119/README.md (stream s119"
DRAWN = {"Q7B": "CSD17578Q5A", "Q8B": "CSD17577Q5A", "Q9B": "CSD17578Q5A", "Q10B": "CSD17577Q5A",
         "L2B": "XAL1010-472ME", "R_IADPT_B": "191 k", "R16B": "10 mOhm"}


def refuse(m):
    print("apply_registry_s119: REFUSED: %s" % m)
    sys.exit(2)


def sha(rel):
    return hashlib.sha256(open(os.path.join(TOP, rel), "rb").read()).hexdigest()


def git(*a):
    return subprocess.run(["git", "-C", TOP] + list(a), capture_output=True, text=True)


def consts(rel):
    """Module-level string constants and dicts of string constants of a script, read with ast."""
    tree = ast.parse(open(os.path.join(TOP, rel), encoding="utf-8").read())
    out = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            v = node.value
            if isinstance(v, ast.Constant) and isinstance(v.value, str):
                out[node.targets[0].id] = v.value
            elif isinstance(v, ast.Dict) and all(isinstance(k, ast.Constant) for k in v.keys):
                out[node.targets[0].id] = {k.value: (x.value if isinstance(x, ast.Constant) else None) for k, x in zip(v.keys, v.values)}
    return out


def par(key):
    tree = ast.parse(open(os.path.join(TOP, R + "a1elec/energy_two_pack.py"), encoding="utf-8").read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "PAR" for t in node.targets):
            for k, v in zip(node.value.keys, node.value.values):
                if isinstance(k, ast.Constant) and k.value == key:
                    return v.elts[0].value
    refuse("energy_two_pack.py has no PAR[%r]" % key)


def eff_u3():
    sec = open(os.path.join(TOP, R + "s117/efficiency.out"), encoding="utf-8").read().split("7. WHAT THE ENERGY MODEL SHOULD CARRY", 1)[1].split("\n8. ", 1)[0]
    for line in sec.split("\n"):
        m = re.match(r"\s{3}U3, chosen FETs, day at E2\s+(0\.\d{3})\s+(0\.\d{3})\s+(0\.\d{3})\s+(0\.\d{3})", line)
        if m:
            return tuple(float(m.group(i)) for i in (1, 2, 3))
    refuse("efficiency.out section 7 has no chosen-FET row for U3")


def hourly_u3b():
    text = " ".join(open(os.path.join(TOP, R + "s119/u3b_hourly.out"), encoding="utf-8").read().split())
    m = re.search(r"rounded down, (0\.\d{3}) \(range (0\.\d{4}) to (0\.\d{4})\); bracket (0\.\d{3}) \(the lowest at the "
                  r"makers' maxima\) to (0\.\d{3})", text)
    if not m:
        refuse("u3b_hourly.out's carried figure not found")
    return float(m.group(4)), float(m.group(1)), float(m.group(5))


def panel_rows(rel):
    """(lid, ratio, U3 case) to (verdict, both Wh) from a reconcile_lid_panel-format output."""
    out, lid = {}, None
    for line in open(os.path.join(TOP, rel), encoding="utf-8").read().split("\n"):
        m = re.match(r"4S(\d+)P lid:", line)
        if m:
            lid = int(m.group(1))
            continue
        m = re.match(r"\s+([ABC]), U3 (\w+)\s+[\d.]+ A, at [\d.]+ C: (MEETS|NOT MET)\s.*?both\s+([\d.]+) Wh", line)
        if m and lid is not None:
            out[(lid, m.group(1), m.group(2))] = (m.group(3), float(m.group(4)))
    return out


def hourly_rows():
    """reconcile_s119.out section 3: (lid, ratio) to the hourly TI cell's lowest store, parsed from its table."""
    sec = open(os.path.join(TOP, R + "s119/reconcile_s119.out"), encoding="utf-8").read().split("3. U3B HOUR BY HOUR", 1)[1].split("\n4. ", 1)[0]
    out = {}
    for line in sec.split("\n"):
        m = re.match(r"\s+4S(\d+)P, ratio ([BC])\s+(MEETS\s+[\d.]+|NOT MET)\s+(MEETS\s+([\d.]+)|NOT MET)", line)
        if m:
            out[(int(m.group(1)), m.group(2))] = float(m.group(5)) if m.group(5) else None
    return out


def parts_table():
    """TOPOLOGY.md's U3B parts table, read as a markdown table by its first cell."""
    rows = {}
    for l in open(os.path.join(TOP, R + "a1elec/TOPOLOGY.md"), encoding="utf-8").read().split("\n"):
        s = l.strip()
        if s.startswith("|") and s.endswith("|"):
            c = [x.strip() for x in s[1:-1].split("|")]
            if len(c) == 3 and c[0] in DRAWN:
                rows[c[0]] = c[1]
    return rows


def preconditions(commit, rerun):
    # (1) committed
    for f in FILES:
        if git("ls-files", "--error-unmatch", f).returncode:
            refuse("%s is not tracked" % f)
    if git("diff", "--quiet", "HEAD", "--", *FILES).returncode:
        refuse("the chain carries uncommitted changes")
    for f in FILES:
        shown = subprocess.run(["git", "-C", TOP, "show", "%s:%s" % (commit, f)], capture_output=True).stdout
        if shown != open(os.path.join(TOP, f), "rb").read():
            refuse("%s at %s is not the working tree's file" % (f, commit[:8]))
    # (2) the rows
    y = yaml.safe_load(open(os.path.join(TOP, R + "energy/energy_inputs.yaml"), encoding="utf-8"))
    c = y["solar"]["chain"][2]
    u3 = eff_u3()
    if (c["low"], c["eta"], c["high"]) != u3:
        refuse("energy_inputs.yaml's U3 row %s is not efficiency.out's %s" % ((c["low"], c["eta"], c["high"]), u3))
    if abs(y["solar"]["vehicle_entry"]["chain_eta"]["value"] - round(y["solar"]["chain"][1]["eta"] * c["eta"], 4)) > 1e-9:
        refuse("chain_eta is not the front end times the charger row")
    u3b = hourly_u3b()
    if (par("eta_u3b_lo"), par("eta_u3b"), par("eta_u3b_hi")) != u3b:
        refuse("energy_two_pack.py's U3B row is not u3b_hourly.out's %s" % (u3b,))
    # (3) the pins
    pins = [(R + "energy/energy_budget.py", "INPUTS_SHA256", R + "energy/energy_inputs.yaml"),
            (R + "energy/energy_architecture.py", "EB_SHA256", R + "energy/energy_budget.py"),
            (R + "a1elec/energy_two_pack.py", "EB_SHA256", R + "energy/energy_budget.py"),
            (R + "a1solar/energy_runs.py", "EA_SHA", R + "energy/energy_architecture.py"),
            (R + "a1solar/energy_runs.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "a1int/reconcile_lid.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "a1int/reconcile_lid_panel.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "s117/efficiency.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "s119/u3b_hourly.py", "PIN_EFF", R + "s117/efficiency.py"),
            (R + "s119/u3b_hourly.py", "PIN_TP", R + "a1elec/energy_two_pack.py"),
            (R + "s119/inductor_u3b.py", "PIN_EFF", R + "s117/efficiency.py")]
    for script, name, target in pins:
        if consts(script).get(name) != sha(target):
            refuse("%s's %s does not name the committed %s" % (script, name, target))
    dicts = ((R + "energy/energy_4s6p.py", "PINS", {R + "energy/energy_budget.py": R + "energy/energy_budget.py",
                                                     R + "energy/energy_inputs.yaml": R + "energy/energy_inputs.yaml"}),
             (R + "energy/checks/recompute.py", "PINS", {"energy_budget.py": R + "energy/energy_budget.py",
                                                         "energy_inputs.yaml": R + "energy/energy_inputs.yaml"}),
             (R + "a1elec/checks/recheck_two_pack.py", "PINS", {"energy_budget.py": R + "energy/energy_budget.py",
                                                                "energy_inputs.yaml": R + "energy/energy_inputs.yaml"}),
             (R + "s119/reconcile_s119.py", "PINS", {"a1elec/energy_two_pack.py": R + "a1elec/energy_two_pack.py",
                                                     "a1solar/energy_runs.py": R + "a1solar/energy_runs.py",
                                                     "s119/u3b_hourly.py": R + "s119/u3b_hourly.py"}))
    for script, name, keymap in dicts:
        d = consts(script).get(name) or {}
        for k, target in keymap.items():
            if d.get(k) != sha(target):
                refuse("%s's %s[%s] does not name the committed %s" % (script, name, k, target))
    # (4) the outputs reproduce
    if rerun:
        for script, out in CHAIN:
            r = subprocess.run([sys.executable, script], cwd=TOP, capture_output=True)
            if r.returncode != 0 or r.stdout != open(os.path.join(TOP, out), "rb").read():
                refuse("%s does not reproduce %s (exit %d)" % (script, out, r.returncode))
    # (5) the failing case
    if "every case NOT MET: the instrument discriminates" not in open(os.path.join(TOP, R + "s119/reconcile_s119.out"), encoding="utf-8").read():
        refuse("reconcile_s119.out does not read the failing case NOT MET everywhere")
    # (6) the decision
    dd = yaml.safe_load(open(DEC, encoding="utf-8"))
    hit = [x for x in dd["decisions"] if "(S-119 U3B)" in str(x.get("title", ""))]
    if len(hit) != 1 or hit[0].get("status") != "ruled" or hit[0].get("authority") != "SESSION":
        refuse("the session decision (S-119 U3B) is not ruled in pcb_decisions.yaml; run apply_decision_s119.py first")
    # (7) the drawn parts
    tab = parts_table()
    for ref, want in DRAWN.items():
        if want not in tab.get(ref, ""):
            refuse("TOPOLOGY.md 3b's parts table does not draw %s as %s (reads %r)" % (ref, want, tab.get(ref)))
    return u3, u3b, int(hit[0]["n"])


def main(argv):
    check = "--check" in argv
    rerun = "--no-rerun" not in argv
    args = [x for x in argv[1:] if not x.startswith("--")]
    if len(args) != 2 or args[0] != "close":
        refuse("usage: apply_registry_s119.py close <commit> [--check] [--no-rerun]")
    commit = args[1]
    if not re.match(r"^[0-9a-f]{8,40}$", commit):
        refuse("give the commit that carries the restated chain")
    if git("cat-file", "-e", commit + "^{commit}").returncode:
        refuse("%s is not in this history" % commit)
    t = open(REG, encoding="utf-8").read()
    d = yaml.safe_load(t)
    if any(x["id"] == "S-119" for x in d["closed_items"]) or MARK_U3B in t or EV_MARK in t:
        refuse("S-119 is already closed or the s119 texts are present (a second run)")
    if not any(x["id"] == "S-119" for x in d["open_items"]):
        refuse("S-119 is not an open item")
    req = [r for r in d["records"] if r["id"] == "REQ-072"][0]
    if "S-119" not in (req.get("waits_on") or []) or req["evidence_result"] != "FAIL":
        refuse("REQ-072 does not wait on S-119 or is not FAIL")
    u3, u3b, dec_n = preconditions(commit, rerun)
    pr = panel_rows(R + "a1int/reconcile_lid_panel.out")
    hr = hourly_rows()
    b14, c14, b15, c15 = pr[(14, "B", "minimum")], pr[(14, "C", "minimum")], pr[(15, "B", "minimum")], pr[(15, "C", "minimum")]
    n9 = [pr[(9, k, "minimum")][0] for k in "BC"]
    if any(v[0] != "MEETS" for v in (b14, c14, b15, c15)) or any(v != "NOT MET" for v in n9) or any(hr.get(k) is None for k in ((14, "B"), (14, "C"), (15, "B"), (15, "C"))):
        refuse("the reconciliation outputs do not read as this closure states")
    ids = [x["id"] for sec in ("open_items", "closed_items") for x in d.get(sec) or []]
    if U3B_ID in ids or re.search(r"(?m)^  - id: %s\s*$" % re.escape(U3B_ID), t):
        refuse("%s, reserved for U3B's FET item, is already in the registry" % U3B_ID)
    new_id = U3B_ID
    ev = ("The charger rows restated from the FETs' losses by TI's SLUSE66A Equations 6 to 22 (printed pages 86 to 88), each "
          "with its sense resistors inside and the inductors' core loss excluded (Coilcraft Document 804-1 prints none; every "
          "figure is high by it): U3 in v2/docs/records/energy/energy_inputs.yaml at %.3f (%.3f to %.3f, the reference day "
          "weighted by energy at entry E2, decision 57's FETs; was 0.98) with chain_eta 0.9105, equal to "
          "v2/docs/records/s117/efficiency.out section 7; U3B in v2/docs/records/a1elec/energy_two_pack.py at %.3f (%.3f to "
          "%.3f; was 0.975) on U3's 400 kHz row, which decision %d draws for it, weighted by energy over the model's own hours "
          "(v2/docs/records/s119/u3b_hourly.out), with its 6.2 A input limit and the charge loop at 23 mOhm. Every script of "
          "the chain re-issued with its pins moved and its output regenerated%s, committed by %s. The lid reconciliation "
          "re-run with U3 at its 6.1 A minimum on the 40 degree south plane: the tablet-out lid (4S14P) %.1f Wh typical and "
          "%.1f Wh adverse at the lowest (was 93.7 and 87.4; %.1f and %.1f Wh with U3B's efficiency taken hour by hour), the "
          "QMX-out lid (4S15P) %.1f and %.1f Wh (was 125.2 and 118.5; %.1f and %.1f hour by hour), both functions kept (4S9P) "
          "not met; with the chargers at the FETs first drawn and drafted (U3 0.939, U3B 0.802) every case reads NOT MET "
          "(v2/docs/records/s119/reconcile_s119.out, with the sensitivity, the room for the core loss and the deployment "
          "rule's planes). Model results on the reference day; U3B's FET finding is %s."
          % (u3[1], u3[0], u3[2], u3b[1], u3b[0], u3b[2], dec_n,
             ", each reproduced byte for byte when this closure was applied" if rerun else "", commit,
             b14[1], c14[1], hr[(14, "B")], hr[(14, "C")], b15[1], c15[1], hr[(15, "B")], hr[(15, "C")], new_id))
    title_u3b = ("%s U3B, Option A(i)'s drafted lid charger, was drawn in v2/docs/records/a1elec/TOPOLOGY.md 3b with Q7B to Q10B "
                 "CSD18510Q5B on an 800 kHz row, which its 6 V REGN cannot drive (120 mA in buck mode and 240 mA in buck-boost "
                 "against IREGN_LIM's 50 mA minimum, SLUSE66A 8.5, printed page 11) and with which it reads 0.802 by TI's "
                 "method; with that figure the adverse case of both lid options reads NOT MET even with U3 as drawn "
                 "(v2/docs/records/s119/reconcile_s119.out section 4). Owner: Option A(i)'s electrical writer. Closed when "
                 "U3B's draft carries FETs its REGN can drive and the energy chain carries their figure." % MARK_U3B)
    ev_u3b = ("Decision %d (SESSION) draws U3B on U3's 400 kHz row and v2/docs/records/a1elec/TOPOLOGY.md 3b and CHARGER.md "
              "carry it at %s: Q7B and Q9B CSD17578Q5A, Q8B and Q10B CSD17577Q5A, L2B XAL1010-472ME, 191 k on IADPT, Table "
              "9-5's 400 kHz compensation, R16B 10 mOhm, IIN_HOST 6.2 A. REGN then supplies 32.6 mA at the makers' maxima "
              "in buck-boost against its 50 mA minimum limit (v2/docs/records/s117/efficiency.out section 5); U3B reads "
              "%.3f over the model's hours, which energy_two_pack.py carries; the inductor at 400 kHz peaks at 9.74 A "
              "against Isat 25.4 A and runs at most 8.00 A RMS against 17.5 A for a 20 C rise (Coilcraft 804-1 page 1; "
              "v2/docs/records/s119/inductor_u3b.out). A draft closed on its page: U3B is on no generator, and its switch "
              "node, loop, REGN current and temperatures are bench items." % (dec_n, commit, u3b[1]))
    note = ("v2/docs/records/s119/README.md (stream s119, S-119, 29 September 2026, two rounds): the energy chain's charger "
            "rows restated from the FETs' losses (U3 0.98 to 0.979, decision 57's FETs on board A; U3B 0.975 to 0.972 on U3's "
            "400 kHz row, decision %d, weighted over the model's hours; core loss excluded) and every script of the chain "
            "re-issued with its output regenerated. The single-pack balance of ENERGY-RECONCILIATION.md moves by about 0.1 "
            "percent: 320 and 90 Wh a day at the node, the stops at hours 8 and 2, the 483 Wh night and the 8.4 W stand as "
            "quoted above, the pack that would carry M1 alone is 2121 Wh (was 2120). Option A(i), not adopted, meets M1 on "
            "the model with the tablet-out lid at %.1f Wh typical and %.1f Wh adverse at the lowest (was 87.4; %.1f hour by "
            "hour) and the QMX-out lid at %.1f and %.1f Wh (was 118.5; %.1f hour by hour), both functions kept not met; the "
            "chargers at the FETs first drawn and drafted read NOT MET in every case. This entry changes no result, "
            "statement or acceptance: the verdict stays FAIL." % (dec_n, b14[1], c14[1], hr[(14, "C")], b15[1], c15[1], hr[(15, "C")]))
    for s, w in ((ev, "the closing evidence"), (title_u3b, "the U3B item's title"), (ev_u3b, "the U3B item's evidence"), (note, "REQ-072's entry")):
        A.screen(s, w)
    # 1. S-119 out of open_items
    i, j = A.span(t, "S-119")
    blk = t[i:j]
    tm = re.search(r"(?m)^    title: >-\n", blk)
    if not tm:
        refuse("S-119's title is not a folded block")
    s119_title = blk[tm.end():].rstrip("\n")
    out = t[:i] + t[j:]
    # 2. S-119 and the U3B finding at the end of closed_items (before records)
    k = out.index("\nrecords:\n")
    out = (out[:k + 1]
           + "  - id: S-119\n    closed_by: commit %s\n    closing_evidence: >-\n%s    title: >-\n%s\n" % (commit, A.fold(ev, 6, 120), s119_title)
           + "  - id: %s\n    closed_by: commit %s\n    closing_evidence: >-\n%s    title: >-\n%s" % (new_id, commit, A.fold(ev_u3b, 6, 120), A.fold(title_u3b, 6, 120))
           + out[k + 1:])
    # 3. REQ-072: waits_on without S-119, and one evidence entry
    ri, rj = A.span(out, "REQ-072")
    rb = out[ri:rj]
    old_w = "    waits_on: [%s]\n" % ", ".join(req["waits_on"])
    if rb.count(old_w) != 1:
        refuse("REQ-072's waits_on line is not as parsed")
    left = [x for x in req["waits_on"] if x != "S-119"]
    rb = rb.replace(old_w, "    waits_on: [%s]\n" % ", ".join(left))
    anchor = "\n    evidence_bound_to:\n"
    if rb.count(anchor) != 1:
        refuse("REQ-072's evidence_bound_to is not found once")
    p = rb.index(anchor) + 1
    rb = rb[:p] + "      - >-\n" + A.fold(note, 10, 120) + rb[p:]
    out = out[:ri] + rb + out[rj:]
    # re-parse and compare
    after = yaml.safe_load(out)
    if [x["id"] for x in after["open_items"]] != [x["id"] for x in d["open_items"] if x["id"] != "S-119"]:
        refuse("open items changed beyond S-119")
    if [x["id"] for x in after["closed_items"]] != [x["id"] for x in d["closed_items"]] + ["S-119", new_id]:
        refuse("closed items changed beyond S-119 and %s" % new_id)
    s_old = [x for x in d["open_items"] if x["id"] == "S-119"][0]
    if after["closed_items"][-2] != {"id": "S-119", "closed_by": "commit %s" % commit, "closing_evidence": ev, "title": s_old["title"]}:
        refuse("S-119 does not read as closed with its title kept")
    if after["closed_items"][-1] != {"id": new_id, "closed_by": "commit %s" % commit, "closing_evidence": ev_u3b, "title": title_u3b}:
        refuse("%s does not read as written" % new_id)
    rb_, ra_ = {r["id"]: r for r in d["records"]}, {r["id"]: r for r in after["records"]}
    for k2 in rb_:
        diff = {f for f in set(rb_[k2]) | set(ra_[k2]) if rb_[k2].get(f) != ra_[k2].get(f)}
        if diff and not (k2 == "REQ-072" and diff == {"waits_on", "evidence"}):
            refuse("%s moved in %s" % (k2, diff))
    a72 = ra_["REQ-072"]
    if a72["evidence"] != rb_["REQ-072"]["evidence"] + [note] or a72["evidence_result"] != "FAIL" or a72["waits_on"] != left:
        refuse("REQ-072 did not move exactly as named, or its result moved")
    for sec in d:
        if sec not in ("open_items", "closed_items", "records") and d[sec] != after[sec]:
            refuse("section %s changed" % sec)
    print("apply_registry_s119 close: S-119 closed by commit %s; %s filed closed (U3B's FET finding, decision %d); REQ-072 "
          "waits on %s and gained one evidence entry, its result FAIL" % (commit[:8], new_id, dec_n, ", ".join(left)))
    if check:
        print("CHECK ONLY: pcb_requirements.yaml not written.")
        return 0
    open(REG, "w", encoding="utf-8").write(out)
    if yaml.safe_load(open(REG, encoding="utf-8").read()) != after:
        refuse("re-parse differs")
    print("APPLIED. Next: python3 v2/ecad/tools/rules_lib.py requirements, then rules_render.py --requirements")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
