#!/usr/bin/env python3
"""S-119's closure in the requirements registry (stream s119, MESHSAT-1357, 29 September 2026). DRAFT for the integrator.

  close <commit>  AFTER the stream's commits are on the integrating line: refuses unless
                  (1) every file of the restated chain is tracked and carries no uncommitted change, and each has the
                      same content at <commit> as in the working tree (the rows and the re-run outputs are committed);
                  (2) the two rows read as restated: energy_inputs.yaml's U3 row (YAML reader) and energy_two_pack.py's
                      eta_u3b (ast) equal records/s117/efficiency.out section 7's figures (parsed from its table);
                  (3) every sha256 pin along the chain names the committed file (read with ast from each script);
                  (4) unless --no-rerun, every script of the chain re-run now prints its committed output byte for byte
                      (about a minute of pure Python on this host);
                  (5) reconcile_s119.out reads the failing case NOT MET everywhere ("the instrument discriminates").
                  Then: S-119 moves to closed_items (closed by <commit>, its closing evidence with every figure read here
                  from the outputs); a SESSION item opens with the next free S number for U3B's drafted FETs (TOPOLOGY.md
                  3b still names CSD18510Q5B, with which the adverse case is NOT MET); REQ-072 waits on it in S-119's place
                  and gains one evidence entry; REQ-072's statement, acceptance and evidence_result (FAIL) do not move.

Every new text passes int7's screen (no claim word, no dash); the registry is re-parsed and only what is named may move;
a second run refuses. --check validates in memory and writes nothing.
Usage (anywhere in the tree): python3 apply_registry_s119.py close <commit> [--check] [--no-rerun]"""
import ast
import hashlib
import os
import re
import subprocess
import sys

import yaml

sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
TOP = subprocess.run(["git", "rev-parse", "--show-toplevel"], cwd=HERE, capture_output=True, check=True).stdout.decode().strip()
REG = os.path.join(TOP, "v2/ecad/tools/pcb_requirements.yaml")
sys.path.insert(0, os.path.join(TOP, "v2/docs/records/int7"))
sys.path.insert(0, os.path.join(TOP, "v2/ecad/tools"))
import apply_check1_answers as A  # noqa: E402

R = "v2/docs/records/"
# (script, its output); the output is regenerated by the script from the repository root
CHAIN = [(R + "energy/energy_budget.py", R + "energy/energy_budget.out"),
         (R + "energy/energy_architecture.py", R + "energy/energy_architecture.out"),
         (R + "energy/energy_4s6p.py", R + "energy/energy_4s6p.out"),
         (R + "energy/night_bounds.py", R + "energy/night_bounds.out"),
         (R + "energy/packfit_west.py", R + "energy/packfit_west.out"),
         (R + "energy/checks/recompute.py", R + "energy/checks/recompute.out"),
         (R + "a1elec/energy_two_pack.py", R + "a1elec/energy_two_pack.out"),
         (R + "a1elec/checks/recheck_two_pack.py", R + "a1elec/checks/recheck_two_pack.out"),
         (R + "a1solar/array_calc.py", R + "a1solar/array_calc.out"),
         (R + "a1solar/energy_runs.py", R + "a1solar/energy_runs.out"),
         (R + "a1int/reconcile_lid.py", R + "a1int/reconcile_lid.out"),
         (R + "a1int/reconcile_lid_panel.py", R + "a1int/reconcile_lid_panel.out"),
         (R + "s119/reconcile_s119.py", R + "s119/reconcile_s119.out")]
FILES = [R + "energy/energy_inputs.yaml", R + "s117/efficiency.out"] + [f for pair in CHAIN for f in pair]
MARK_NEW = "(stream s119, S-119's remainder)"
EV_MARK = "v2/docs/records/s119/README.md (stream s119"


def refuse(m):
    print("apply_registry_s119: REFUSED: %s" % m)
    sys.exit(2)


def sha(rel):
    return hashlib.sha256(open(os.path.join(TOP, rel), "rb").read()).hexdigest()


def git(*a):
    return subprocess.run(["git", "-C", TOP] + list(a), capture_output=True, text=True)


def consts(rel):
    """Module-level string constants and dicts of string constants of a script, read with ast."""
    tree = ast.parse(open(os.path.join(TOP, rel), encoding="utf-8").read())
    out = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            v = node.value
            if isinstance(v, ast.Constant) and isinstance(v.value, str):
                out[node.targets[0].id] = v.value
            elif isinstance(v, ast.Dict) and all(isinstance(k, ast.Constant) for k in v.keys):
                out[node.targets[0].id] = {k.value: (x.value if isinstance(x, ast.Constant) else None) for k, x in zip(v.keys, v.values)}
    return out


def eta_u3b():
    tree = ast.parse(open(os.path.join(TOP, R + "a1elec/energy_two_pack.py"), encoding="utf-8").read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "PAR" for t in node.targets):
            for k, v in zip(node.value.keys, node.value.values):
                if isinstance(k, ast.Constant) and k.value == "eta_u3b":
                    return v.elts[0].value
    refuse("energy_two_pack.py has no PAR['eta_u3b']")


def eff_rows():
    text = open(os.path.join(TOP, R + "s117/efficiency.out"), encoding="utf-8").read()
    sec = text.split("7. WHAT THE ENERGY MODEL SHOULD CARRY", 1)[1].split("\n8. ", 1)[0]
    rows = {}
    for line in sec.split("\n"):
        m = re.match(r"\s{3}(U3B?[ ,].*?)\s+(0\.\d{3})\s+(0\.\d{3})\s+(0\.\d{3})\s+(0\.\d{3})", line)
        if m:
            rows[m.group(1).strip()] = tuple(float(m.group(i)) for i in (2, 3, 4))
    return rows


def panel_rows(rel):
    """(lid, ratio, U3 case) -> (verdict, both Wh, threshold C or None) from a reconcile_lid_panel-format output."""
    out, lid = {}, None
    lines = open(os.path.join(TOP, rel), encoding="utf-8").read().split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"4S(\d+)P lid:", line)
        if m:
            lid = int(m.group(1))
            continue
        m = re.match(r"\s+([ABC]), U3 (\w+)\s+[\d.]+ A, at [\d.]+ C: (MEETS|NOT MET)\s.*?both\s+([\d.]+) Wh", line)
        if m and lid is not None:
            t = re.search(r"meets M1: ([+-][\d.]+) C", lines[i + 1])
            out[(lid, m.group(1), m.group(2))] = (m.group(3), float(m.group(4)), float(t.group(1)) if t else None)
    return out


def preconditions(commit, rerun):
    # (1) committed
    for f in FILES:
        if git("ls-files", "--error-unmatch", f).returncode:
            refuse("%s is not tracked" % f)
    if git("diff", "--quiet", "HEAD", "--", *FILES).returncode:
        refuse("the chain carries uncommitted changes")
    for f in FILES:
        shown = subprocess.run(["git", "-C", TOP, "show", "%s:%s" % (commit, f)], capture_output=True).stdout
        if shown != open(os.path.join(TOP, f), "rb").read():
            refuse("%s at %s is not the working tree's file" % (f, commit[:8]))
    # (2) the rows
    y = yaml.safe_load(open(os.path.join(TOP, R + "energy/energy_inputs.yaml"), encoding="utf-8"))
    c = y["solar"]["chain"][2]
    e = eff_rows()
    u3, u3b = e.get("U3, chosen FETs, day at E2"), e.get("U3B, CSD17578Q5A x 4, 800 kHz")
    if (c["low"], c["eta"], c["high"]) != u3:
        refuse("energy_inputs.yaml's U3 row %s is not efficiency.out's %s" % ((c["low"], c["eta"], c["high"]), u3))
    if abs(y["solar"]["vehicle_entry"]["chain_eta"]["value"] - round(y["solar"]["chain"][1]["eta"] * c["eta"], 4)) > 1e-9:
        refuse("chain_eta is not the front end times the charger row")
    if eta_u3b() != u3b[1]:
        refuse("energy_two_pack.py's eta_u3b %s is not efficiency.out's %s" % (eta_u3b(), u3b[1]))
    # (3) the pins
    pins = [(R + "energy/energy_budget.py", "INPUTS_SHA256", R + "energy/energy_inputs.yaml"),
            (R + "energy/energy_architecture.py", "EB_SHA256", R + "energy/energy_budget.py"),
            (R + "a1elec/energy_two_pack.py", "EB_SHA256", R + "energy/energy_budget.py"),
            (R + "a1solar/energy_runs.py", "EA_SHA", R + "energy/energy_architecture.py"),
            (R + "a1solar/energy_runs.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "a1int/reconcile_lid.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "a1int/reconcile_lid_panel.py", "TP_SHA", R + "a1elec/energy_two_pack.py"),
            (R + "s119/reconcile_s119.py", "TP_SHA", R + "a1elec/energy_two_pack.py")]
    for script, name, target in pins:
        if consts(script).get(name) != sha(target):
            refuse("%s's %s does not name the committed %s" % (script, name, target))
    for script, name, keymap in ((R + "energy/energy_4s6p.py", "PINS", {R + "energy/energy_budget.py": R + "energy/energy_budget.py",
                                                                         R + "energy/energy_inputs.yaml": R + "energy/energy_inputs.yaml"}),
                                 (R + "energy/checks/recompute.py", "PINS", {"energy_budget.py": R + "energy/energy_budget.py",
                                                                             "energy_inputs.yaml": R + "energy/energy_inputs.yaml"})):
        d = consts(script).get(name) or {}
        for k, target in keymap.items():
            if d.get(k) != sha(target):
                refuse("%s's %s[%s] does not name the committed %s" % (script, name, k, target))
    # (4) the outputs reproduce
    if rerun:
        for script, out in CHAIN:
            r = subprocess.run([sys.executable, script], cwd=TOP, capture_output=True)
            if r.returncode != 0 or r.stdout != open(os.path.join(TOP, out), "rb").read():
                refuse("%s does not reproduce %s (exit %d)" % (script, out, r.returncode))
    # (5) the failing case
    s119 = open(os.path.join(TOP, R + "s119/reconcile_s119.out"), encoding="utf-8").read()
    if "every case NOT MET: the instrument discriminates" not in s119:
        refuse("reconcile_s119.out does not read the failing case NOT MET everywhere")
    return u3, u3b


def main(argv):
    check = "--check" in argv
    rerun = "--no-rerun" not in argv
    args = [x for x in argv[1:] if not x.startswith("--")]
    if len(args) != 2 or args[0] != "close":
        refuse("usage: apply_registry_s119.py close <commit> [--check] [--no-rerun]")
    commit = args[1]
    if not re.match(r"^[0-9a-f]{8,40}$", commit):
        refuse("give the commit that carries the restated chain")
    if git("cat-file", "-e", commit + "^{commit}").returncode:
        refuse("%s is not in this history" % commit)
    t = open(REG, encoding="utf-8").read()
    d = yaml.safe_load(t)
    if any(x["id"] == "S-119" for x in d["closed_items"]) or MARK_NEW in t or EV_MARK in t:
        refuse("S-119 is already closed or the s119 texts are present (a second run)")
    if not any(x["id"] == "S-119" for x in d["open_items"]):
        refuse("S-119 is not an open item")
    req = [r for r in d["records"] if r["id"] == "REQ-072"][0]
    if "S-119" not in (req.get("waits_on") or []) or req["evidence_result"] != "FAIL":
        refuse("REQ-072 does not wait on S-119 or is not FAIL")
    u3, u3b = preconditions(commit, rerun)
    pr = panel_rows(R + "a1int/reconcile_lid_panel.out")
    b14, c14, b15, c15 = pr[(14, "B", "minimum")], pr[(14, "C", "minimum")], pr[(15, "B", "minimum")], pr[(15, "C", "minimum")]
    n9 = [pr[(9, k, "minimum")][0] for k in "BC"]
    if any(v[0] != "MEETS" for v in (b14, c14, b15, c15)) or any(v != "NOT MET" for v in n9):
        refuse("reconcile_lid_panel.out does not read as this closure states")
    ids = [x["id"] for sec in ("open_items", "closed_items") for x in d.get(sec) or []]
    new_id = "S-%d" % (max(int(m.group(1)) for i in ids for m in [re.match(r"^S-(\d+)$", str(i))] if m) + 1)
    ev = ("The charger rows restated from the drawn and drafted FETs' losses by TI's SLUSE66A Equations 6 to 22 (printed "
          "pages 86 to 88), R16 and R17 counted, the inductor's core loss excluded (Coilcraft Document 804-1 prints none; "
          "every figure is high by it): U3 in v2/docs/records/energy/energy_inputs.yaml at %.3f (%.3f to %.3f, the "
          "reference day weighted by energy at entry E2, decision 57's FETs; was 0.98) with chain_eta 0.9105, and U3B in "
          "v2/docs/records/a1elec/energy_two_pack.py at %.3f (%.3f to %.3f, CSD17578Q5A in all four positions on its "
          "drafted 800 kHz row, the worst mode at the peak hour; was 0.975), both equal to "
          "v2/docs/records/s117/efficiency.out section 7. Every script of the chain re-issued with its pins moved and its "
          "output regenerated%s (energy_budget, energy_architecture, energy_4s6p and the "
          "section 9 recompute; energy_two_pack and its closed-form re-check, which agrees on every figure; energy_runs; "
          "reconcile_lid and reconcile_lid_panel), committed by %s. The lid reconciliation re-run with U3 at its 6.1 A "
          "minimum on the 40 degree south plane: the tablet-out lid (4S14P) %.1f Wh typical and %.1f Wh adverse at the "
          "lowest (was 93.7 and 87.4), the QMX-out lid (4S15P) %.1f and %.1f Wh (was 125.2 and 118.5), both functions kept "
          "(4S9P) not met; with the chargers at the FETs first drawn and drafted (U3 0.939, U3B 0.802) every case reads "
          "NOT MET (v2/docs/records/s119/reconcile_s119.out section 3, with the sensitivity, the margins and the deployment "
          "rule's planes). Model results on the reference day; U3B's drafted FETs are %s."
          % (u3[1], u3[0], u3[2], u3b[1], u3b[0], u3b[2],
             ", each reproduced byte for byte when this closure was applied" if rerun else "", commit,
             b14[1], c14[1], b15[1], c15[1], new_id))
    title = ("%s U3B, Option A(i)'s drafted lid charger, is carried in the energy chain at 0.961 (TI's SLUSE66A Equations "
             "6 to 22 with CSD17578Q5A in all four positions on its drafted 800 kHz row, v2/docs/records/s117/U3B-NOTE.md "
             "way (a); REGN 33.0 mA typical and 49.9 mA at the makers' maxima in buck-boost against its 50 mA minimum "
             "limit, SLUSE66A 8.5, printed page 11), but v2/docs/records/a1elec/TOPOLOGY.md 3b still draws Q7B to Q10B as "
             "CSD18510Q5B, which REGN cannot drive (120 mA in buck mode, 240 mA in buck-boost) and with which U3B reads "
             "0.802; with that figure the adverse case of both lid options reads NOT MET even with U3 as drawn "
             "(v2/docs/records/s119/reconcile_s119.out section 3). The 400 kHz row (way (b): U3's inductor, IADPT resistor, "
             "compensation and FET pair, a 10 mOhm input sense and IIN_HOST at most 6.35 A; the model's largest U3B input is "
             "4.08 A) reads 0.974 with REGN at 32.6 mA. Owner: Option A(i)'s electrical writer. Closed when TOPOLOGY.md 3b "
             "and CHARGER.md draw U3B on one of the two ways with its figures, or eta_u3b is restated from the FETs drawn "
             "and the lid reconciliation re-run." % MARK_NEW)
    note = ("v2/docs/records/s119/README.md (stream s119, S-119, 29 September 2026): the energy chain's charger rows "
            "restated from the drawn and drafted FETs' losses (U3 0.98 to 0.979, decision 57's FETs on board A; U3B 0.975 "
            "to 0.961, CSD17578Q5A on its drafted 800 kHz row; core loss excluded) and every script of the chain re-issued "
            "with its output regenerated. The single-pack balance of ENERGY-RECONCILIATION.md moves by about 0.1 percent: "
            "320 and 90 Wh a day at the node, the stops at hours 8 and 2, the 483 Wh night and the 8.4 W stand as quoted "
            "above, the pack that would carry M1 alone is 2121 Wh (was 2120). Option A(i), not adopted, meets M1 on the "
            "model with the tablet-out lid at %.1f Wh typical and %.1f Wh adverse at the lowest (was 87.4) and the QMX-out "
            "lid at %.1f and %.1f Wh (was 118.5), both functions kept not met; the chargers at the FETs first drawn and "
            "drafted read NOT MET in every case; U3B's drafted FETs are %s. This entry changes no result, statement or "
            "acceptance: the verdict stays FAIL." % (b14[1], c14[1], b15[1], c15[1], new_id))
    for s, w in ((ev, "the closing evidence"), (title, "the new item's title"), (note, "REQ-072's entry")):
        A.screen(s, w)
    # 1. S-119 out of open_items, into closed_items
    i, j = A.span(t, "S-119")
    blk = t[i:j]
    tm = re.search(r"(?m)^    title: >-\n", blk)
    if not tm:
        refuse("S-119's title is not a folded block")
    s119_title = blk[tm.end():].rstrip("\n")
    out = t[:i] + t[j:]
    # 2. the new item after the last open item (before closed_items)
    k = out.index("\nclosed_items:\n")
    out = out[:k + 1] + "  - id: %s\n    class: SESSION\n    status: OPEN\n    title: >-\n%s" % (new_id, A.fold(title, 6, 120)) + out[k + 1:]
    k = out.index("\nrecords:\n")
    out = out[:k + 1] + "  - id: S-119\n    closed_by: commit %s\n    closing_evidence: >-\n%s    title: >-\n%s\n" % (
        commit, A.fold(ev, 6, 120), s119_title) + out[k + 1:]
    # 3. REQ-072: waits_on and one evidence entry
    ri, rj = A.span(out, "REQ-072")
    rb = out[ri:rj]
    old_w = "    waits_on: [%s]\n" % ", ".join(req["waits_on"])
    if rb.count(old_w) != 1:
        refuse("REQ-072's waits_on line is not as parsed")
    rb = rb.replace(old_w, "    waits_on: [%s]\n" % ", ".join(new_id if x == "S-119" else x for x in req["waits_on"]))
    anchor = "\n    evidence_bound_to:\n"
    if rb.count(anchor) != 1:
        refuse("REQ-072's evidence_bound_to is not found once")
    p = rb.index(anchor) + 1
    rb = rb[:p] + "      - >-\n" + A.fold(note, 10, 120) + rb[p:]
    out = out[:ri] + rb + out[rj:]
    # re-parse and compare
    after = yaml.safe_load(out)
    if [x["id"] for x in after["open_items"]] != [x["id"] for x in d["open_items"] if x["id"] != "S-119"] + [new_id]:
        refuse("open items changed beyond S-119 and %s" % new_id)
    if [x["id"] for x in after["closed_items"]] != [x["id"] for x in d["closed_items"]] + ["S-119"]:
        refuse("closed items changed beyond S-119")
    s_old = [x for x in d["open_items"] if x["id"] == "S-119"][0]
    s_new = after["closed_items"][-1]
    if s_new != {"id": "S-119", "closed_by": "commit %s" % commit, "closing_evidence": ev, "title": s_old["title"]}:
        refuse("S-119 does not read as closed with its title kept")
    if after["open_items"][-1] != {"id": new_id, "class": "SESSION", "status": "OPEN", "title": title}:
        refuse("%s does not read as written" % new_id)
    rb_, ra_ = {r["id"]: r for r in d["records"]}, {r["id"]: r for r in after["records"]}
    for k2 in rb_:
        diff = {f for f in set(rb_[k2]) | set(ra_[k2]) if rb_[k2].get(f) != ra_[k2].get(f)}
        if diff and not (k2 == "REQ-072" and diff == {"waits_on", "evidence"}):
            refuse("%s moved in %s" % (k2, diff))
    a72 = ra_["REQ-072"]
    if a72["evidence"] != rb_["REQ-072"]["evidence"] + [note] or a72["evidence_result"] != "FAIL":
        refuse("REQ-072's evidence did not gain exactly the one entry, or its result moved")
    for sec in d:
        if sec not in ("open_items", "closed_items", "records") and d[sec] != after[sec]:
            refuse("section %s changed" % sec)
    print("apply_registry_s119 close: S-119 closed by commit %s; %s opened (U3B's drafted FETs); REQ-072 waits on %s and "
          "gained one evidence entry, its result FAIL" % (commit[:8], new_id, ", ".join(a72["waits_on"])))
    if check:
        print("CHECK ONLY: pcb_requirements.yaml not written.")
        return 0
    open(REG, "w", encoding="utf-8").write(out)
    if yaml.safe_load(open(REG, encoding="utf-8").read()) != after:
        refuse("re-parse differs")
    print("APPLIED. Next: python3 v2/ecad/tools/rules_lib.py requirements, then rules_render.py --requirements")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
