"""r8int5: ARCHITECTURE.md's stale VIN_RAW lines after EQ-16 (w3de check 2's note; lines 246, 328 and 1138 at 38dcd764,
246, 328 and 1176 on main 953f5658), and the power tree's dock edge (line 282), which says the same. Run from the root."""
import os, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'common'))
from edlib import once
P = 'v2/docs/ARCHITECTURE.md'
once(P, '''  E5 -->|"IF-AE-DOCK: 4 x VIN_RAW (12.31 A declared), 4 x CELL+, pre-charge, USB, SHORE_INHIBIT"| A''',
        '''  E5 -->|"IF-AE-DOCK: 4 x VIN_RAW 9 A pins (14.10 A declared, EQ-16), 4 x CELL+, pre-charge, USB, SHORE_INHIBIT"| A''',
     marker="4 x VIN_RAW 9 A pins (14.10 A declared, EQ-16)")
once(P, '''  VR -->|"dock pins 1 to 4, 12.31 A declared"| FE''',
        '''  VR -->|"4 x 9 A dock pins J_VR1 to J_VR4, 14.10 A declared"| FE''', marker="J_VR1 to J_VR4, 14.10 A declared")
once(P, '''| VIN_RAW at the dock | the vehicle entry and the tracker together | **12.31 A declared** on board A (6.15 + 6.16 A), each of the four Preci-Dip 813 contacts at 3.08 A of its 3.5 A with even sharing (R4A-N13); board E's own VIN_RAW declares 14.10 A since round 8 (R4A-N12): both feeds, L2 and Q2, limited by board A's front end at its ISNS limit from a 9.0 V bus (5.7 A at 20.7 V over 0.93), the tracker's own TRK_OUT 10.33 A (the panel's 93 W at 9 V); above board A's 12.31 A, so the four contacts read 3.53 A each with even sharing (R8E-N01, open) | `gen_sch_a.py:49-66`; `gen_sch_e.py:93-138` | VERIFIED (re-read); the contact margin is IF-AE-DOCK's |''',
        '''| VIN_RAW at the dock | the vehicle entry and the tracker together | **14.10 A declared** at both ends since set 5 (`fnd/r8int5`, 27 September 2026; R8E-N01 answered by EQ-16): both feeds, L2 and Q2, limited by board A's front end at its ISNS limit from a 9.0 V bus (5.7 A at 20.7 V over 0.93), the tracker's own TRK_OUT 10.33 A (the panel's 93 W at 9 V) (R4A-N12). VIN_RAW crosses on four Mill-Max 0858-class power pins (A J_VR1 to J_VR4, with J_VN1 to J_VN4 for its return, to E's P_VR and P_VN), 3.53 A each with even sharing (39 percent of 9 A) and 4.70 A with one open; the four Preci-Dip 813 contacts that carried it (3.53 A each at 14.10 A, 101 percent of their 3.5 A; 3.08 A at the old 12.31 A) are ground since EQ-16 | `gen_sch_a.py:69-70` and `:235-237`; `gen_sch_e.py` (VIN_RAW's derivation, J_BLK, P_VR, P_VN) | VERIFIED (re-read); the contact margin and the ground return (W3DE-DOCK-R1) are IF-AE-DOCK's |''',
     marker="**14.10 A declared** at both ends since set 5")
once(P, '''| IF-AE-DOCK | A J_DOCK and pack pins, E5, E J_BLK, P_CP, P_CN | VIN_RAW, CELL+, pre-charge, USB, SHORE_INHIBIT; lifted only by the D-14 procedure, with a cap over E5 | sections 4 and 5; `block_contract.py` needs pcbnew | the VIN_RAW contacts: 12.31 A declared on A gives 3.08 A of 3.5 A per contact with even sharing and no margin for one open (R4A-N13); board E's round 8 declares 14.10 A, 3.53 A each, over the rating at nominal (R8E-N01); A04-D2 on the A32 board; BAT-F06 (stated, section 4.4) |''',
        '''| IF-AE-DOCK | A J_DOCK, the pack pins and the VIN_RAW pins J_VR1-4, J_VN1-4, E5, E J_BLK, P_CP, P_CN, P_VR, P_VN | VIN_RAW, CELL+, pre-charge, USB, SHORE_INHIBIT; lifted only by the D-14 procedure, with a cap over E5 | sections 4, 5 and 5a (the EQ-16 dock checks); `block_contract.py` needs pcbnew | the VIN_RAW pins: 14.10 A declared at both ends since set 5 (EQ-16, R8E-N01 answered) on four Mill-Max 9 A pins, 3.53 A each with even sharing and 4.70 A with one open, the 813 contacts 1 to 4 ground; the ground current's share on the 813 ground contacts (W3DE-DOCK-R1, a bench measurement owed); E5's eight new targets and two 12 AWG holes are layer 7's; A04-D2 on the A32 board; BAT-F06 (stated, section 4.4) |''',
     marker="the VIN_RAW pins: 14.10 A declared at both ends since set 5")
print("architecture_r8int5: applied")
