#!/usr/bin/env python3
"""Drawing set A1-1 to A1-6 of the Option A(i) mechanical work package (MESHSAT-1357, stream a1mech): the lid module in plan and section,
the arrangements for the owner's decision, the hinge harness, the mass and stability, the base pockets. Every figure is taken from
v2/cad/lid_pack_a1.py (imported), so the sheets and lid_pack_a1.out cannot disagree. matplotlib only (no CAD import).
Usage: lid_pack_a1_drawing.py <out.pdf>. Prototype design, AI review: nothing built, bought or fitted."""
import math, os, sys
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.patches import Rectangle, Circle, Arc, FancyArrowPatch, Polygon

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import lid_pack_a1 as L

plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 6.0, "axes.linewidth": 0.5})
A3 = (16.54, 11.69)
INK, GREY, LIGHT = "#111111", "#777777", "#bbbbbb"
REVISION = os.environ.get("A1_REV", "fnd/a1mech")


def frame(fig, num, title, notes):
    fig.text(0.015, 0.975, "MeshSat field kit V2, Option A(i) lid pack: sheet %s  %s" % (num, title), fontsize=10, weight="bold", va="top")
    fig.text(0.015, 0.948, "MESHSAT-1357, stream a1mech, 29 Sep 2026. Case frame: X east, Y toward the hinge (back) wall, Z up from the base floor, lid closed. "
             "mm. Prototype design, AI review: nothing built, bought or fitted; analytical success is not physical verification.", fontsize=6.4, va="top")
    fig.text(0.015, 0.02, "Generated by v2/cad/lid_pack_a1_drawing.py from v2/cad/lid_pack_a1.py (%s). " % REVISION + notes, fontsize=5.6, va="bottom", wrap=True)


def rect(ax, r, **kw):
    ax.add_patch(Rectangle((r[0], r[1]), r[2] - r[0], r[3] - r[1], **kw))


def dim_h(ax, x0, x1, y, text, off=0.0):
    ax.annotate("", (x0, y), (x1, y), arrowprops=dict(arrowstyle="<->", lw=0.4, color=INK, shrinkA=0, shrinkB=0))
    ax.text((x0 + x1) / 2, y + 1.5 + off, text, ha="center", va="bottom", fontsize=5.2)


def dim_v(ax, x, y0, y1, text):
    ax.annotate("", (x, y0), (x, y1), arrowprops=dict(arrowstyle="<->", lw=0.4, color=INK, shrinkA=0, shrinkB=0))
    ax.text(x + 1.5, (y0 + y1) / 2, text, ha="left", va="center", fontsize=5.2, rotation=90)


def lid_outline(ax):
    fx, fy = L.CEIL_FLAT
    rect(ax, (-fx, -fy, fx, fy), fill=False, lw=0.6, ec=INK)
    wx, wy = L.LID_WALL_AT_PART
    rect(ax, (-wx, -wy, wx, wy), fill=False, lw=0.4, ec=GREY, ls="--")
    ax.text(-fx + 2, fy - 4, "flat ceiling 346.16 x 231.86 (STEP #736)", fontsize=5, color=INK)
    ax.text(-wx + 2, -wy + 2, "lid cavity at the parting plane 373.88 x 261.87 (dashed); R 16.26 fillets between", fontsize=5, color=GREY)


def face_parts(ax, label=True):
    for ref, r, h, src in L.FACE:
        if ref.startswith("PLATE_SCREW"):
            ax.add_patch(Circle(((r[0] + r[2]) / 2, (r[1] + r[3]) / 2), 3.43, fill=False, lw=0.3, ec=GREY)); continue
        col = "#cc3333" if L.one_layer_fails(h) else GREY
        rect(ax, r, fill=False, lw=0.35, ec=col, ls=":" if h is not None and h < 1.0 else "-")
        if label and not ref.startswith("D") or ref in ("D1", "D12"):
            t = ref.replace("_GUARD", " guard").replace("_PLATE", "")
            if ref.endswith("_PLATE"): continue
            ax.text((r[0] + r[2]) / 2, (r[1] + r[3]) / 2, "%s\nh %s" % (t, "TBD" if h is None else "%.2f" % h), fontsize=3.8,
                    ha="center", va="center", color=col)


def qmx(ax):
    rect(ax, L.QMX["rect"], fill=True, fc="#e8e8f8", ec="#333399", lw=0.6)
    r = L.QMX["rect"]
    ax.text((r[0] + r[2]) / 2, (r[1] + r[3]) / 2, "QMX set r2 (HF, 16a)\n%.1f..%.1f x %.1f..%.1f\ndepth 29.30 unit, 40.90 knobs" % (r[0], r[2], r[1], r[3]),
            ha="center", va="center", fontsize=4.6, color="#333399")


def cells(ax, a, lw=0.25):
    for c in a["cells"]:
        y0 = c["yc"] - L.CELL_D / 2
        if c["layer"] == 1:
            rect(ax, (c["x0"], y0 + 0.4, c["x1"], y0 + L.CELL_D - 0.4), fill=True, fc="#f3e3c3", ec="#8a6a2a", lw=max(lw, 0.3))
        else:
            rect(ax, (c["x0"] + 4, y0 + 3, c["x1"] - 4, y0 + L.CELL_D - 3), fill=False, ec="#6a4a0a", lw=lw, hatch="////")
    rect(ax, (a["x_w"], a["y_s"], a["x_e"], a["y_n"]), fill=False, ec="#8a6a2a", lw=0.7)
    rect(ax, a["p2_rect"], fill=True, fc="#c8e8c8", ec="#2a6a2a", lw=0.6)
    p = a["p2_rect"]
    ax.text((p[0] + p[2]) / 2, (p[1] + p[3]) / 2, "P2 %.0f x %.0f\n(ASSUMPTION)" % (p[2] - p[0], p[3] - p[1]), ha="center", va="center", fontsize=4.6, color="#2a6a2a")
    if a["tablet_rect"]:
        rect(ax, a["tablet_rect"], fill=False, ec="#1a6a9a", lw=0.9, ls="--")
        t = a["tablet_rect"]
        ax.text(t[0] + 3, t[3] - 3, "tablet bracket %.0f x %.0f (%s), depth %.2f" % (t[2] - t[0], t[3] - t[1], a["tablet"]["name"], L.tablet_depth(a["tablet"])),
                fontsize=4.8, color="#1a6a9a", va="top")


def plan_ax(fig, box, lim=(-200, 200, -140, 140)):
    ax = fig.add_axes(box)
    ax.set_aspect("equal"); ax.set_xlim(lim[0], lim[1]); ax.set_ylim(lim[2], lim[3])
    ax.tick_params(labelsize=4.5, length=2, width=0.3)
    ax.grid(True, lw=0.15, color="#dddddd")
    return ax


def sheet1(pdf, arr):
    a = arr["B"]
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-1", "arrangement B in plan: the lid module, the QMX set and every face part under the lid",
          "Face parts in red stand taller than a one-layer module allows (the toggle guards, 28.00) or have no height (U-174/U jacks, TBD); "
          "dotted: 1.0 or less. Pale cells layer 1; hatched cells layer 2, nested in the grooves 16.065 further from the ceiling (toward the face). Every clearance is a row of lid_pack_a1.out section 2.")
    ax = plan_ax(fig, (0.03, 0.09, 0.66, 0.83))
    lid_outline(ax); face_parts(ax); qmx(ax); cells(ax, a)
    dim_h(ax, a["x_w"], a["x_e"], 124, "module X %.2f .. %.2f (%.2f): 3 slices of 65.25 + 4 joints of 1.0 + two 7.0 bays" % (a["x_w"], a["x_e"], a["x_e"] - a["x_w"]))
    dim_h(ax, a["x_e"], L.QMX["rect"][0], 112, "%.2f" % (L.QMX["rect"][0] - a["x_e"]), off=-6)
    dim_v(ax, a["x_w"] - 12, a["south"][0][2], a["y_n"], "west slice %.2f .. %.2f" % (a["south"][0][2], a["y_n"]))
    dim_v(ax, 70, a["south"][1][2], a["y_n"], "slices 1, 2 from %.2f" % a["south"][1][2])
    for (x0, x1, ys, j) in a["south"]:
        ax.text((x0 + x1) / 2, ys - 4, "%d across" % j, ha="center", fontsize=4.8)
    ax.plot([p[0] for p in L.DC_ROUTE], [p[1] for p in L.DC_ROUTE], color="#aa5500", lw=1.0)
    ax.text(160, -105, "QMX DC lead, re-routed east (R 20)", fontsize=4.6, color="#aa5500", ha="center")
    ax.set_title("Plan, looking down onto the face through the closed lid (not to a print scale: read the dimensions)", fontsize=6)
    tx = fig.add_axes((0.71, 0.09, 0.28, 0.83)); tx.axis("off")
    n = len(a["cells"])
    lines = ["ARRANGEMENT B (HF kept, no tablet in the lid)",
             "cells %d: layer 1 %d, layer 2 %d; 4S%dP (48 used as instructed, %d spare places)" % (n, sum(1 for c in a["cells"] if c["layer"] == 1),
                                                                                           sum(1 for c in a["cells"] if c["layer"] == 2), n // 4, n - 48),
             "",
             "CELL  Samsung INR18650-35E: d 18.55 max, L 65.25 max, 50 g max",
             "      (spec Ver. 1.1, 3.10 and drawing)",
             "BLOCK A06's construction (the ruled base block): cells touching,",
             "      wrap 0.5 a side, joints 1.0 at each cell end along X",
             "      (nickel strip and fish paper), layer 2 nested in the grooves",
             "HOLD  the block bonded to the lid plate (cell glue and a fillet,",
             "      adhesive TBD); the cover on 8 M3 standoffs in the end bays",
             "      presses a PORON 4701-30 pad 1.0; the plate bonded to the",
             "      lid's ceiling with DP8005 as the r2 set (no hole in the case)",
             "VENT  every cell end faces its 1.0 joint; the end bays are open",
             "      slots; the case relieves through Peli's pressure valve",
             "",
             "STACK FROM THE CEILING               nominal",
             "  DP8005 bond                          %.2f" % L.BOND,
             "  5052-H32 lid plate                   %.2f" % L.PLATE,
             "  block, one layer / two layers    %.2f / %.2f" % (L.CELL_D + 2 * L.WRAP, L.CELL_D + L.NEST_DZ + 2 * L.WRAP),
             "  PORON pad (compressed)               %.2f" % L.PAD,
             "  cover 1.0 + insulation 0.25          %.2f" % L.COVER,
             "  module depth, one / two layers   %.2f / %.2f" % (L.DEPTH1, L.DEPTH2),
             "  P2 on 2.5 standoffs (ASSUMPTION)     %.2f" % L.P2_DEPTH,
             "",
             "ROOM face top to ceiling: %.2f nominal, %.2f worst," % (L.ROOM_NOM, L.ROOM_WORST),
             "     %.2f sensitivity (frame_seat.out, r2 record B)" % L.ROOM_X2,
             "",
             "TIGHTEST ROWS (worst, x2; min 1.0)",
             "  two layers over the Xenarc window 0.80: 3.10, 0.39 OPEN",
             "  two layers over the LED bar 1.50:     2.40, -0.31 OPEN",
             "  two layers over the e-paper lens:     3.85, 1.14 MET",
             "  one layer over the XFRAME screws:    15.96, 13.25 MET",
             "  layer 2 refused over XFRAME_1 and _3 (4.00): -0.10 worst",
             "",
             "PLAN  module to the QMX tray %.2f; inside the flat ceiling" % (L.QMX["rect"][0] - a["x_e"]),
             "      1.00 in Y (the fillets begin at +-115.93)",
             "      west edge 1.0 beyond the guard caps and the allowance",
             "      west slice stops north of the headset jacks (TBD)",
             "",
             "OPEN AT THE MOCK-UP: T9 (chalk on the module's cover and the",
             "face parts, lid closed), T8 (pull test of a bonded plate on",
             "Peli's polypropylene), T-A1-1 to T-A1-4 of the README."]
    tx.text(0, 1, "\n".join(lines), family="DejaVu Sans Mono", fontsize=5.6, va="top")
    pdf.savefig(fig); plt.close(fig)


def sheet2(pdf, arr):
    a = arr["B"]
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-2", "sections: the module under the ceiling over the face, at the worst room",
          "Z of the ceiling and the face top at nominal; the worst room 44.39 is marked. Section Y-Z at X -34 (slice 1), section X-Z at Y 0.")
    ax = fig.add_axes((0.04, 0.52, 0.92, 0.38)); ax.set_aspect("equal")
    cz, fz = L.CEIL_Z_NOM, L.FACE_Z_NOM
    ax.set_xlim(-140, 140); ax.set_ylim(95, 165)
    ax.plot([-131, 131], [cz, cz], color=INK, lw=0.8); ax.text(-128, cz + 1, "lid ceiling Z %.2f nominal (152.66 worst)" % cz, fontsize=5)
    ax.plot([-131, 131], [fz, fz], color=INK, lw=0.8); ax.text(-128, fz - 3.5, "face top Z %.2f nominal (108.27 worst)" % fz, fontsize=5)
    ax.plot([-131, 131], [L.P.PELI["rim_z"]] * 2, color=GREY, lw=0.4, ls="--"); ax.text(95, L.P.PELI["rim_z"] + 0.8, "parting plane 108.97", fontsize=4.6, color=GREY)
    # fillets at the long walls
    for sgn in (-1, 1):
        th = [math.radians(t) for t in range(0, 91, 5)]
        ys = [sgn * (L.CEIL_FLAT[1] + L.CEIL_FILLET_R * math.sin(t)) for t in th]
        zs = [cz - L.CEIL_FILLET_R + L.CEIL_FILLET_R * math.cos(t) for t in th]
        ax.plot(ys, zs, color=INK, lw=0.6)
    ax.plot([-130.9, -130.9], [L.P.PELI["rim_z"], cz - 14], color=INK, lw=0.6); ax.plot([130.9, 130.9], [L.P.PELI["rim_z"], cz - 14], color=INK, lw=0.6)
    # module in Y-Z for slice 1
    ax.add_patch(Rectangle((a["south"][1][2], cz - L.BOND - L.PLATE), a["y_n"] - a["south"][1][2], L.PLATE, fc="#cccccc", ec=INK, lw=0.4))
    z1 = cz - L.BOND - L.PLATE - L.WRAP - L.CELL_D / 2
    for c in a["cells"]:
        if c["s"] != 1: continue
        z = z1 - (L.NEST_DZ if c["layer"] == 2 else 0.0)
        ax.add_patch(Circle((c["yc"], z), L.CELL_D / 2, fc="#f3e3c3" if c["layer"] == 1 else "#d9a441", ec="#6a4a0a", lw=0.3))
    ax.plot([a["south"][1][2], a["y_n"]], [cz - L.DEPTH2] * 2, color="#8a6a2a", lw=0.6)
    ax.text(a["south"][1][2] + 2, cz - L.DEPTH2 - 3, "cover underside at %.2f below the ceiling (two layers)" % L.DEPTH2, fontsize=4.8, color="#8a6a2a")
    ax.annotate("", (120, cz), (120, cz - L.ROOM_NOM), arrowprops=dict(arrowstyle="<->", lw=0.4))
    ax.text(121, cz - L.ROOM_NOM / 2, "room %.2f nom\n%.2f worst\n%.2f x2" % (L.ROOM_NOM, L.ROOM_WORST, L.ROOM_X2), fontsize=4.8, va="center")
    ax.annotate("", (-120, cz), (-120, cz - L.DEPTH2), arrowprops=dict(arrowstyle="<->", lw=0.4))
    ax.text(-119, cz - L.DEPTH2 / 2, "%.2f" % L.DEPTH2, fontsize=4.8, va="center")
    ax.add_patch(Rectangle((-94.0, fz), 140.0, 0.8, fc="#aaaacc", ec="none")); ax.text(-40, fz + 1.2, "Xenarc window (up to 0.8 proud)", fontsize=4.4)
    ax.set_title("Section Y-Z through slice 1 (X -67.75 .. -0.50): worst margin over the window 3.10 (OPEN at the sensitivity reading, 0.39)", fontsize=6)
    ax.tick_params(labelsize=4.5)
    # X-Z section
    bx = fig.add_axes((0.04, 0.09, 0.92, 0.36)); bx.set_aspect("equal")
    bx.set_xlim(-180, 180); bx.set_ylim(95, 165)
    bx.plot([-173.08, 173.08], [cz, cz], color=INK, lw=0.8); bx.plot([-176, 176], [fz, fz], color=INK, lw=0.8)
    bx.add_patch(Rectangle((a["x_w"], cz - L.BOND - L.PLATE), a["x_e"] - a["x_w"], L.PLATE, fc="#cccccc", ec=INK, lw=0.4))
    for s, (x0, x1, ys, j) in enumerate(a["south"]):
        bx.add_patch(Rectangle((x0 + 1, cz - L.BOND - L.PLATE - L.WRAP - L.CELL_D), 65.25, L.CELL_D, fc="#f3e3c3", ec="#6a4a0a", lw=0.3))
        bx.add_patch(Rectangle((x0 + 1, cz - L.BOND - L.PLATE - L.WRAP - L.CELL_D - L.NEST_DZ), 65.25, L.CELL_D, fc="#d9a441", ec="#6a4a0a", lw=0.3, alpha=0.6))
        bx.text((x0 + x1) / 2, cz - 12, "slice %d" % s, ha="center", fontsize=5)
    for xb in (a["x_w"], a["x_e"] - L.BAY):
        bx.add_patch(Rectangle((xb, cz - L.DEPTH2), L.BAY, L.DEPTH2 - L.BOND - L.PLATE, fc="none", ec="#8a6a2a", lw=0.4, hatch="////"))
    bx.text(a["x_w"], cz - L.DEPTH2 - 4, "7.0 end bays: 4 M3 standoffs each, the cover's flange, the group links and taps; open vent slots", fontsize=4.8)
    rq = L.QMX["rect"]
    bx.add_patch(Rectangle((rq[0], cz - L.QMX["frame"]), rq[2] - rq[0], L.QMX["frame"], fc="#e8e8f8", ec="#333399", lw=0.5))
    bx.text((rq[0] + rq[2]) / 2, cz - 16, "QMX set r2\n(frame 32.30, knobs 40.90)", ha="center", fontsize=4.8, color="#333399")
    for ref, r, h, _s in L.FACE:
        if h and h > 3.0 and abs((r[1] + r[3]) / 2) < 70:
            bx.add_patch(Rectangle((r[0], fz), r[2] - r[0], h, fc="#f0c0c0", ec="#cc3333", lw=0.3))
    bx.text(-150, fz + 30, "toggle guards 28.00\n(red: no lid item over them)", fontsize=4.6, color="#cc3333", ha="center")
    bx.set_title("Section X-Z at Y 0, looking north: 3 slices end to end, layer 2 behind; the QMX set east; the guards west", fontsize=6)
    bx.tick_params(labelsize=4.5)
    pdf.savefig(fig); plt.close(fig)


def sheet3(pdf, arr):
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-3", "the arrangements that fit, and the owner decision",
          "Each arrangement is the generator's best: the tablet's band searched in 1 mm steps, P2 at the corner costing fewest cells. "
          "4SnP counts whole groups of four; the totals add the base pockets' 4S6P of section 8.")
    boxes = [(0.03, 0.52, 0.30, 0.38), (0.35, 0.52, 0.30, 0.38), (0.67, 0.52, 0.30, 0.38), (0.03, 0.09, 0.30, 0.38), (0.35, 0.09, 0.30, 0.38)]
    for key, box in zip(("A", "B", "C", "C10", "D"), boxes):
        a = arr.get(key)
        if not a: continue
        ax = plan_ax(fig, box)
        lid_outline(ax); face_parts(ax, label=False)
        if a["qmx"]: qmx(ax)
        cells(ax, a, lw=0.15)
        n = len(a["cells"])
        ax.set_title("%s\n%d cells: 4S%dP in the lid, 4S%dP with the base" % (a["name"], n, n // 4, n // 4 + 6), fontsize=6)
    tx = fig.add_axes((0.67, 0.09, 0.31, 0.38)); tx.axis("off")
    A, B, C, C10, D = (len(arr[k]["cells"]) if k in arr else 0 for k in ("A", "B", "C", "C10", "D"))
    lines = ["THE OWNER DECISION (the session does not take it:",
             "it removes an owner-approved function, 6 Sep 2026)",
             "",
             "48 cells (4S12P) in the lid with BOTH the QMX HF set",
             "(16a) and the tablet bracket (16d): DOES NOT FIT.",
             "At the worst room the lid holds %d places with both," % A,
             "4S%dP, 4S%dP in all (the check's B1)." % (A // 4, A // 4 + 6),
             "",
             "What fits 4S12P (each with every row of sheet A1-1",
             "at or above its minimum at the worst):",
             " 1. HF kept, tablet bracket out of the lid:",
             "    %d places (4S%dP); the tablet goes out of the case." % (B, B // 4),
             " 2. 8 inch tablet kept, HF (QMX) out of the lid:",
             "    %d places (4S%dP); HF inside (16a) is lost: the base" % (C, C // 4),
             "    has no volume for the QMX set",
             " 3. Both kept, lid pack 4S%dP (4S%dP in all): not" % (A // 4, A // 4 + 6),
             "    Option A(i). The coordinator's two-pack run",
             "    (Sept. reference day, 200 W stage): lid at its",
             "    13.23 C basis NOT MET at 400, 650, 1000 Wp; lid",
             "    at +20 C NOT MET at 400 Wp, met at 650 (2.0 Wh",
             "    left) and 1000 Wp (29.4 Wh left)",
             "",
             "10 inch tablet: only with HF out: %d places (4S%dP)." % (C10, C10 // 4),
             "Both out: %d places (4S%dP)." % (D, D // 4),
             "",
             "Session's recommendation (engineering view only):",
             "option 1, which keeps a radio bearer and gives",
             "8 spare places; the tablet works from outside the",
             "case on the kit's WiFi and USB-C outlet.",
             "",
             "D-01 already defers HF, the tablet bracket and a",
             "second pack from prototype 1: Option A(i) reopens",
             "D-01 whichever option is taken."]
    tx.text(0, 1, "\n".join(lines), family="DejaVu Sans Mono", fontsize=6.0, va="top")
    pdf.savefig(fig); plt.close(fig)


def sheet4(pdf, arr):
    a = arr["B"]
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-4", "the hinge harness: route, travel, ties, disconnect; the QMX DC lead re-routed",
          "Hinge axis ESTIMATED (no Peli figure): Y 155 +-8, Z 111 +-5. The crossing of the sealed face is S-95's (EQ-31), not designed here.")
    ax = fig.add_axes((0.04, 0.12, 0.42, 0.76)); ax.set_aspect("equal")
    ax.set_xlim(90, 200); ax.set_ylim(90, 175)
    hy, hz = L.HINGE["y"], L.HINGE["z"]
    ax.plot([hy], [hz], "o", color=INK, ms=3); ax.text(hy + 2, hz - 3, "hinge axis (ESTIMATE)", fontsize=5)
    for phi in (0, 30, 60, 90, 120, 150, 180):
        p = L.rot(L.T_LID, phi)
        ax.plot([p[0]], [p[1]], "o", color="#aa3300", ms=2)
        ax.text(p[0] + 1, p[1] + 1, "%d" % phi, fontsize=4.5, color="#aa3300")
    ax.add_patch(Arc((hy, hz), 2 * math.hypot(L.T_LID[0] - hy, L.T_LID[1] - hz), 2 * math.hypot(L.T_LID[0] - hy, L.T_LID[1] - hz), theta1=-20, theta2=190, lw=0.4, color="#aa3300", ls="--"))
    ax.plot([L.T_PLATE[0]], [L.T_PLATE[1]], "s", color="#1a6a9a", ms=3); ax.text(L.T_PLATE[0] - 30, L.T_PLATE[1] - 4, "T_P on the plate's face near its back edge", fontsize=5, color="#1a6a9a")
    ax.text(L.T_LID[0] - 34, L.T_LID[1] + 2, "T_L on the lid's back wall (closed)", fontsize=5, color="#aa3300")
    # lid closed outline near the back
    ax.plot([100, 130.9, 130.9], [L.CEIL_Z_NOM, L.CEIL_Z_NOM - 14, L.P.PELI["rim_z"]], color=GREY, lw=0.5)
    ax.text(101, L.CEIL_Z_NOM - 4, "lid inner surface (schematic)", fontsize=4.6, color=GREY)
    ax.plot([100, 126.5, 126.5, 131.5], [L.FACE_Z_NOM, L.FACE_Z_NOM, L.FACE_Z_NOM - 2.0, L.FACE_Z_NOM - 2.0], color=INK, lw=0.6)
    ax.text(100, L.FACE_Z_NOM - 5, "face plate: full face to Y 126.5 (top 106.52), rebated band to 131.5 (104.52)", fontsize=4.6)
    ax.plot([100, 140], [L.P.PELI["rim_z"]] * 2, color=GREY, lw=0.4, ls="--")
    ax.set_title("Y-Z at the back wall: the lid tie's path about the hinge axis, 0 to 180 degrees", fontsize=6)
    ax.tick_params(labelsize=4.5)
    bx = plan_ax(fig, (0.50, 0.40, 0.48, 0.50))
    lid_outline(bx); qmx(bx); cells(bx, a, lw=0.1)
    p2 = a["p2_rect"]
    ym = (p2[1] + p2[3]) / 2
    route = [(p2[0], ym), (a["x_w"] + 3.5, ym), (a["x_w"] + 3.5, 122.0), (a["x_w"] + 20.0, 122.0)]
    bx.plot([q[0] for q in route], [q[1] for q in route], color="#aa3300", lw=1.2)
    bx.plot([a["x_w"] + 20.0, a["x_w"] + 20.0 + L.HARNESS["span_x"]], [122.0, 128.0], color="#aa3300", lw=1.2, ls="--")
    bx.text(a["x_w"] + 25, 131, "free lead T_L to T_P, 150 apart in X (bows %.1f closed)" % L.harness_numbers()["sag"], fontsize=4.8, color="#aa3300")
    bx.plot([q[0] for q in L.DC_ROUTE], [q[1] for q in L.DC_ROUTE], color="#aa5500", lw=1.0)
    bx.text(150, -120, "QMX DC lead re-routed east, R 20", fontsize=4.8, color="#aa5500", ha="center")
    bx.set_title("Plan: the pack harness from P2 through the west bay to the back channel; the QMX DC lead", fontsize=6)
    tx = fig.add_axes((0.50, 0.08, 0.48, 0.28)); tx.axis("off")
    H = L.HARNESS
    hn = L.harness_numbers()
    lines = ["CURRENT (ASSUMPTION for fnd/a1elec): 10 A continuous, 18 A for 60 s, 8.6 A charge",
             "CONDUCTOR 12 AWG fine-strand silicone, OD 4.4 (class); 2 x 0.80 m loop 8.34 mOhm:",
             "  150 mV and 2.7 W at 18 A; adiabatic rise 8.9 K over 60 s",
             "TRAVEL the lid tie turns at R %.1f about the axis; the chord T_L..T_P runs" % hn["rad"],
             "  %.1f closed to %.1f at 180 degrees; lead %.1f between the ties" % (hn["c0"], hn["c1"], hn["lead"]),
             "BEND closed bow %.1f (radius about %.0f), open S radius about %.0f," % (hn["sag"], hn["r_bow"], hn["r_s"]),
             "  against 10 x OD = 44 (the requirement on the pick)",
             "STRAIN RELIEF bonded tie mounts at T_L, T_P and every 60 mm or less;",
             "  a printed guide keeps the lead inboard of the lid wall (Y < 130.9)",
             "DISCONNECT XT60 pair and JST XH 1x4 beside P2 (the lid comes off)",
             "CROSSING the sealed face: S-95 (EQ-31), NOT designed: +2 power poles",
             "  of 25 A or more and 4 signal contacts, sealed mated and unmated"]
    tx.text(0, 1, "\n".join(lines), family="DejaVu Sans Mono", fontsize=5.8, va="top")
    pdf.savefig(fig); plt.close(fig)


def sheet5(pdf, arr):
    a = arr["B"]
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-5", "mass and open-lid stability",
          "Masses: cells at the sheet's maximum; the rest ESTIMATE (lid_pack_a1.out section 4). Base contents swept 7 to 14 kg; stop angle TBD (no Peli figure), swept.")
    ax = fig.add_axes((0.04, 0.10, 0.52, 0.80)); ax.set_aspect("equal")
    ax.set_xlim(-180, 460); ax.set_ylim(-20, 460)
    ax.plot([-170, 450], [L.FOOT_Z] * 2, color=INK, lw=0.8)
    ax.add_patch(Rectangle((-135.2, L.FOOT_Z), 270.4, 109.0 - L.FOOT_Z + 8.38, fill=False, ec=INK, lw=0.6))
    ax.plot([L.Y_TIP], [L.FOOT_Z], "^", color="#cc3333", ms=5); ax.text(L.Y_TIP + 3, L.FOOT_Z - 12, "tipping line Y %.2f" % L.Y_TIP, fontsize=5, color="#cc3333")
    items = L.mass_items(a, 9.0, (0.0, 0.0, 55.0))
    for phi, col in ((0, "#333333"), (90, "#1a6a9a"), (120, "#2a8a2a"), (135, "#cc7700"), (180, "#cc3333")):
        corners = [(-130.9, L.P.PELI["rim_z"]), (-130.9, L.CEIL_Z_NOM + 5), (130.9, L.CEIL_Z_NOM + 5), (130.9, L.P.PELI["rim_z"])]
        pts = [L.rot(c, phi) for c in corners]
        ax.add_patch(Polygon(pts, closed=True, fill=False, ec=col, lw=0.5))
        m, x, y, z = L.cg(items, part="lid", phi=phi)
        ax.plot([y], [z], "o", color=col, ms=3)
        mt, xt, yt, zt = L.cg(items, phi=phi)
        ax.plot([yt], [zt], "x", color=col, ms=5)
        ax.text(yt + 4, zt + 3, "%d deg: CG Y %.0f" % (phi, yt), fontsize=4.8, color=col)
    ax.plot([L.HINGE["y"]], [L.HINGE["z"]], "ko", ms=2)
    ax.set_title("Side view (Y-Z): the lid at 0, 90, 120, 135, 180 degrees; o the lid's CG, x the case's CG (base 9 kg at Y 0, Z 55)", fontsize=6)
    ax.tick_params(labelsize=4.5)
    tx = fig.add_axes((0.60, 0.10, 0.38, 0.80)); tx.axis("off")
    lid_m = sum(i[2] for i in items if i[1] == "lid")
    lines = ["LID, arrangement B: %.2f kg in all" % lid_m]
    for nm, wh, mi, _p in items:
        if wh == "lid": lines.append("  %-52s %5.3f" % (nm[:52], mi))
    lines += ["", "WORST OVER THE SWEEP (base 7..14 kg, CG Y -20..+20, Z 45..65,",
              "hinge axis Y 147..163): critical back slope, deg",
              "  lid open    B      A"]
    for phi in (90, 100, 110, 120, 135, 150, 180):
        wB = min(L.critical_slope(L.mass_items(arr["B"], bm, (0.0, by, bz)), phi)[0] for bm in (7.0, 9.0, 14.0) for by in (-20.0, 0.0, 20.0) for bz in (45.0, 65.0))
        wA = min(L.critical_slope(L.mass_items(arr["A"], bm, (0.0, by, bz)), phi)[0] for bm in (7.0, 9.0, 14.0) for by in (-20.0, 0.0, 20.0) for bz in (45.0, 65.0))
        lines.append("   %4d    %5.1f  %5.1f   %s" % (phi, wB, wA, "(tips on level ground)" if wB < 0 else ""))
    lines += ["  (the hinge axis at Y 155, Z 111 here; the .out sweeps Y and Z)", "",
              "VERDICT: stands on level ground to 120 degrees of opening in every",
              "swept case; a light base tips from 135. FIX (SESSION, reversible):",
              "a lid stay stopping the lid at 100 degrees (webbing strap at X",
              "-179, a tab bonded to the lid's west end wall, a tab under the",
              "plate's 6-32 at Y 75.95; 56 to 63 N static; about EUR 10).",
              "With it: back slope 9.5 deg (B), 7.0 (C) at the worst of the",
              "full sweep, 3.6 (B) with the feet inboard; a backward push of",
              "9 to 13 N at the QMX's height tips the lightest case",
              "(lid_pack_a1.out section 4).",
              "The stop angle, the hinge axis and the case's CG are read on the",
              "mock-up (T-A1-3); Peli states no load for its hinges (T-A1-4)."]
    tx.text(0, 1, "\n".join(lines), family="DejaVu Sans Mono", fontsize=5.6, va="top")
    pdf.savefig(fig); plt.close(fig)


def sheet6(pdf, arr):
    fig = plt.figure(figsize=A3)
    frame(fig, "A1-6", "the base pockets: section 8's 4S6P at the same worst figures",
          "East block as ruled (A06, D-06); west block its mirror (section 8's configuration). Rows from frame_seat.out (east) and packfit_west.out (west M6).")
    ax = plan_ax(fig, (0.04, 0.10, 0.56, 0.80), lim=(-200, 200, -140, 140))
    rect(ax, (-171.64, -114.49, 171.64, 114.49), fill=False, ec=INK, lw=0.6)
    ax.text(-170, 116, "flat floor 343.28 x 228.98 (R 15.88 fillets outside)", fontsize=5)
    rect(ax, (-187.0, -130.0, 187.0, 130.0), fill=False, ec=GREY, lw=0.4, ls="--")
    rect(ax, (-120, -80, 120, 80), fill=True, fc="#eeeeee", ec=GREY, lw=0.4); ax.text(0, 0, "board A 240 x 160", ha="center", fontsize=5)
    for sgn, (y0, y1) in ((1, (-30.75, 102.75)), (-1, (-66.75, 66.75))):
        x0, x1 = sorted((sgn * 122.0, sgn * 178.65))
        rect(ax, (x0, y0, x1, y1), fill=True, fc="#f3e3c3", ec="#8a6a2a", lw=0.6)
        ax.text((x0 + x1) / 2, (y0 + y1) / 2, "4S3P block\n56.65 x 133.5\nx 38.1\n(%s)" % ("east, ruled" if sgn > 0 else "west, centred"), ha="center", va="center", fontsize=4.8)
        for sy in (1, -1):
            rect(ax, (sgn * 175.40 if sgn > 0 else -180.17, sy * 106.4 if sy > 0 else -112.4, sgn * 180.17 if sgn > 0 else -175.40, sy * 112.4 if sy > 0 else -106.4), fill=True, fc="#cccccc", ec=INK, lw=0.3)
    rect(ax, (122.0, -102.75, 166.0, -32.75), fill=True, fc="#c8e8c8", ec="#2a6a2a", lw=0.5)
    ax.text(144, -68, "board P\n44 x 70", ha="center", fontsize=4.6, color="#2a6a2a")
    rect(ax, (-190.0, -98.0, -165.0, 98.0), fill=False, ec="#cc3333", lw=0.6, ls="--")
    ax.text(-178, 104, "west jumpers' drop zone\n(X -165 to the wall, |Y| 98)", fontsize=4.6, color="#cc3333", ha="center")
    for nm, y in L.P.WALL_WEST:
        ax.plot([-186.0], [y], "o", color="#cc3333", ms=2.5); ax.text(-196, y, nm, fontsize=3.8, ha="right", va="center")
    ax.set_title("Floor plan: both blocks, the setting legs, the west jumpers' drop zone", fontsize=6)
    tx = fig.add_axes((0.62, 0.10, 0.36, 0.80)); tx.axis("off")
    lines = ["ROW    worst  x2     verdict"]
    for r in L.base_rows():
        lines.append("%-6s %5.2f  %5s  %s" % (r[0].split()[1], r[4], "n/a" if r[5] is None else "%.2f" % r[5], r[6][:52]))
    sites, over, gap = L.west_jumpers()
    lines += ["", "WEST RF JUMPERS: %d of 7 west cables (Y %s)" % (len(over), ", ".join("%.0f" % y for y in over)),
              "fall onto the west block; the slot over it is 7.19 at",
              "the worst less C33's zone (3.99); the only drop east of",
              "it is its 2.0 gap to board A, under one RG-316 (2.49):",
              "FAILS AS ASSUMED, held OPEN (section 8b, the M17 class):",
              "the west RF entry is re-planned before the west block",
              "is taken. Hold-down S-27 open for both blocks.",
              "", "The mirror rows hold only because Peli's cavity is the",
              "same at both ends (ribs at Y 0 and +-76.2 on both end",
              "walls, R 15.88 on all four floor edges: VERIFIED) and the",
              "RF entry plates share one outline (panel1450 C4)."]
    tx.text(0, 1, "\n".join(lines), family="DejaVu Sans Mono", fontsize=5.8, va="top")
    pdf.savefig(fig); plt.close(fig)


def main(out):
    arr = {a["name"].split(":")[0]: a for a in L.arrangements()}
    with PdfPages(out, metadata={"Title": "Option A(i) lid pack drawing set A1-1 to A1-6", "Author": "MeshSat (MESHSAT-1357)"}) as pdf:
        for s in (sheet1, sheet2, sheet3, sheet4, sheet5, sheet6):
            s(pdf, arr)
    print("wrote", out)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "lid-pack-a1-drawings.pdf")
