#!/usr/bin/env python3
"""Q-55 (MESHSAT-1357, set 32; W40 on branch fnd/s32small from main eff28be3, 6 October 2026): V-E16's row 3 in
v2/docs/HW-FW-CONTRACT.md takes N1a's annotation at the place the register's R-176 row 3 carries it, and test_w8l5's
live check then reads V-E16 from the TREE equal to the live register; test_l5pwr's reading of L5-F09 d admits N1a's
words, once, in V-E16 (the third edit, found by the sweep below).

THIS MOVES l4e11_power.out AND THE l4e7 KEY. HW-FW-CONTRACT.md is pinned by l4e11_power.out (its `hwfw` line), which is one
of the l4e7 KEY's files, so set 32 needs a re-key after this script runs. Also pinned at set 31's tip d5d9c252: the PINS
tables of l4e11_power.py (line 54) and l4e9_power_path.py (line 75) hard-code the page's sha256 (tool-moved pins, re-pinned
by the L4 chain), and l4e9_power_path.out, l5r2_interfaces.out, l5r3_panel.out, l8gnd_drafts.out and l9t5_t10.out print it
(re-pinned by set 32's dependency pass). The script prints the page's sha256 before and after. It also moves
v2/docs/test-procedures/TP-SOLAR.md (edit 6), pinned by v2/docs/test-procedures/tp_check.out alone (regenerated by set 32's
chain through regen_out.py; no other file in the tree prints TP-SOLAR.md's sha256 at set 31's 3057ae43).

The decision: the coordinator's of 6 October 2026 15:22 CEST (QUEUE line Q-55, authority SESSION): carrying the annotation
into V-E16 is set 32's, because in set 31 it would have invalidated the re-key then running. The record's own invariant:
V-E16's rows 2 and 3 mirror the register's R-176 rows 2 and 3 verbatim (record l5pwr's L5-F09 d wrote them so).

WHY A SCRIPT AND NOT AN EDIT ON THE BRANCH (authority SESSION, W40, 6 October 2026; reversed by applying the two edits by
hand, three edits): the branch's base, main eff28be3, holds none of what the edit stands on. N1a's annotation of the register (b2564b59),
W8's restatement of V-E16 (8840adda) and test_w8l5.py itself (W8, restated by the coordinator at f0748b49) are all set 31's
(fnd/int31regen). An edit of V-E16's row here would conflict line for line with W8's edit of the same row at set 32's
merge, and the test does not exist here to edit. So the integrator runs this script on set 32's merged tree, after set
31's promotion, and commits its three files with the re-key (four since W47 added edits 5 and 6: TP-SOLAR.md joins them).

What it does, all checks first and nothing written unless every one holds:
  1. the register (v2/docs/records/l4e9/DOWNSTREAM-REGISTER.md): exactly one `| R-176 | TEST |` row, whose third cell
     carries N1A_WORDS exactly once, right after "U5's CSPIN to CSNIN within +-0.240 V" (N1a is in the tree);
  2. HW-FW-CONTRACT.md: exactly one `| V-E16 |` row; OLD found exactly once in it and nowhere else in the page; the row
     with NEW in its place differs; every other line of the page and every cell but the last unchanged; the cell count
     kept; V-E16's rows 2 and 3 (from "(2) " to " (PROVISIONAL until E-1's correction", W8's wording) then equal the
     register's R-176 rows 2 and 3 (from "(2) " to "; (4) ") verbatim; no em or en dash;
  3. test_w8l5.py: the three lines of the coordinator's live check (f0748b49) found exactly once; the new check
     appended after them; the module parses (ast);
  4. test_l5pwr.py: W14's two lines of the L5-F09 reading found exactly once; the Q-55 reading put in their place (N1a's
     words, where a restated field carries them, exactly once in V-E16 right after U5's line, then taken out before the
     script's values are read; nothing else of the reading changes); the module parses (ast).
  5. (W47, QUEUE line Q-65) HW-FW-CONTRACT.md's change record (section 10, the page's last section): Q-55's row CR_ROW
     appended after the V-E16 edit, in the form of W8's row "| 2 (W8, L5-F14) |" (three cells: version, date, change with
     its basis and the wording before); W8's row found once in section 10, the page's last line a three-cell row of that
     table, Q-55's row not yet there; every earlier line unchanged; N1a's words once in the row; no em or en dash. The test
     that pins W8's change record form (test_w8l5's last assertion, `l1[-2]`) reads the page at W8_COMMIT 8840adda, not
     the tree, so it accepts the appended row unchanged; the tree's form of the new row is pinned by TEST_ADD's last lines.
  6. (W47, Q-65) v2/docs/test-procedures/TP-SOLAR.md: its line 297 (set 31's lineage, 3057ae43) is inside a TEXT quote of
     record l4e7's L4E7-CONTROL-DECISION.md (R-176's acceptance, round 2), which carries no N1a words: tp_check.py's C3 finds
     it there verbatim, so that quote stays as it is (adding the words inside it would break C3: a procedure quotes, it never
     paraphrases). The register's annotated U5 line enters the procedure as its own text quote of the register, inserted
     right after that quote block with a dated lead-in (TP_ADD); checked as C3 checks a text quote (the body, '>' marks
     taken off and whitespace collapsed, found verbatim in the register) and as C5 checks a path (every `v2/...` path in the
     insertion exists); a pure insertion, nothing of the page moved; no TBD, no em or en dash. TP-SOLAR.md is pinned by
     v2/docs/test-procedures/tp_check.out (its sha256/16 line and the text-quote count), which set 32's chain regenerates.
A second run finds N1A_WORDS in V-E16, the Q-55 marker in both tests, Q-55's change record row and TP_MARK in the procedure
and exits 3, writing nothing; a partial state is refused (exit 2).

THE SWEEP (6 October 2026, a scratch clone of set 31's tip d5d9c252, v2/docs and v2/ecad checked out): run.py over the 11
light modules that read HW-FW-CONTRACT.md (test_w8l5, test_l5pwr, test_l5r2, test_l5r4, test_lstat31, test_lstat32,
test_requirements, test_w14l5, test_w20oneliners, test_w24l4e9, test_fw_panel) before and after the apply: 156 passed, 26
failed, 2 skipped before (the 26 the clone's environment: no firmware tree, no vendor files); after, the same 26 plus two,
both pins: test_l5r2.t_r3_output_reproduced_and_every_finding_resolved (l5r3_panel.out prints the page's sha256) and
test_w24l4e9.t_the_four_typed_in_pins_equal_their_files (l4e9_power_path.py:75). With the two PINS re-pinned and
l5r3_panel.out regenerated on the clone (one line moved, the pin) both pass. The heavy modules test_l4e5, test_l4e9,
test_l4e11 and test_l9t5 were read, not run: none reads V-E16; their page reads (FW-C08, the keyed outlets, FW-B rows, a
fixed commit) do not move, and their generators' PINS are the chain's re-pin.

Usage (from anywhere): apply_q55_ve16.py [--root <repository root>] [--check]
  --root   the tree to patch (default: this file's repository)
  --check  every check, nothing written
Exit 0 written (or, with --check, would write); 2 refused, nothing written; 3 already applied, nothing written.
"""
import argparse, ast, hashlib, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REG_REL = "v2/docs/records/l4e9/DOWNSTREAM-REGISTER.md"
HWFW_REL = "v2/docs/HW-FW-CONTRACT.md"
TEST_REL = "v2/ecad/tools/tests/test_w8l5.py"

N1A_WORDS = " (under R-240, drafted, not applied: under 10 mV in magnitude, a layout check, L4E7-P0SOL.md section 5)"
U5 = "U5's CSPIN to CSNIN within +-0.240 V"
OLD = U5 + ", U21 turning Q12 off"
NEW = U5 + N1A_WORDS + ", U21 turning Q12 off"
W8_END = " (PROVISIONAL until E-1's correction"

TEST_OLD = (
    '    need(REG, "the register")\n'
    '    live = r176_rows(open(REG, encoding="utf-8").read())\n'
    '    assert live.count(N1A_WORDS) == 1 and live.replace(N1A_WORDS, "") == want, "the live register\'s R-176 rows 2 and 3 '
    'differ from W8\'s by more than N1a\'s annotation"\n')
MARK = "# Q-55 (set 32"
TEST_ADD = (
    '    # Q-55 (set 32, record s32small, applied by apply_q55_ve16.py): V-E16\'s row 3 carries N1a\'s annotation at the place the\n'
    '    # register\'s R-176 row 3 carries it, so V-E16 read from the TREE equals the live register\'s rows 2 and 3 verbatim; the\n'
    '    # fixture form above stays for W8\'s own change. Basis: the record\'s own invariant, V-E16 mirrors the register (record\n'
    '    # l5pwr\'s L5-F09 d wrote it so), and the coordinator\'s decision of 6 October 2026 15:22 CEST (QUEUE line Q-55).\n'
    '    ve16 = [cells(ln) for ln in tree(HWFW_REL).split("\\n") if ln.startswith("| V-E16 |")]\n'
    '    assert len(ve16) == 1, "%d V-E16 rows in the tree" % len(ve16)\n'
    '    v = ve16[0][-1]\n'
    '    assert v[v.index("(2) "):v.index(" (PROVISIONAL until E-1\'s correction")] == live, "V-E16\'s rows 2 and 3 in the tree '
    'are not the live register\'s R-176 rows 2 and 3"\n'
    '    # Q-55\'s change record row (W47, QUEUE line Q-65): one row in the form of W8\'s (three cells), dated, after W8\'s row,\n'
    '    # carrying N1a\'s words and the wording before; the assertion on W8\'s row below reads W8_COMMIT, not the tree. And\n'
    '    # TP-SOLAR.md quotes the register\'s annotated U5 line once as a text quote (tp_check.py\'s C3 holds it verbatim there).\n'
    '    h = tree(HWFW_REL).split("\\n")\n'
    '    q55 = [k for k, ln in enumerate(h) if ln.startswith("| 2 (Q-55, set 32) |")]\n'
    '    w8 = [k for k, ln in enumerate(h) if ln.startswith("| 2 (W8, L5-F14) |")]\n'
    '    assert len(q55) == 1 and len(w8) == 1 and q55[0] > w8[0], "Q-55\'s change record row is not once, after W8\'s"\n'
    '    c = cells(h[q55[0]])\n'
    '    assert len(c) == 3 and c[1] == "6 October 2026" and c[2].count(N1A_WORDS.strip()) == 1, "Q-55\'s row is not in W8\'s form"\n'
    '    assert "\\"U5\'s CSPIN to CSNIN within +-0.240 V, U21 turning Q12 off\\"" in c[2], "Q-55\'s row lacks the wording before"\n'
    '    qs = [flat(re.sub(r"(?m)^\\s*>", "", b)) for b in re.findall(r\'<!-- q src="v2/docs/records/l4e9/DOWNSTREAM-REGISTER\\.md" '
    '-->\\n(.*?)\\n<!-- /q -->\', tree("v2/docs/test-procedures/TP-SOLAR.md"), re.S)]\n'
    '    assert qs.count(flat("U5\'s CSPIN to CSNIN within +-0.240 V" + N1A_WORDS)) == 1, "TP-SOLAR.md does not quote the '
    'register\'s annotated U5 line once"\n')

# Edit 5 (W47, QUEUE line Q-65): Q-55's row in HW-FW-CONTRACT.md's change record, in the form of W8's row (version, date, the
# change with its basis, the wording before as dated history).
CR_W8 = "| 2 (W8, L5-F14) |"
CR_PREFIX = "| 2 (Q-55, set 32) |"
CR_HEAD = "## 10. Change record"
CR_ROW = (CR_PREFIX + " 6 October 2026 | By record s32small for set 32 (MESHSAT-1357, branch `fnd/s32small`, "
          "`records/s32small/apply_q55_ve16.py`; the coordinator's decision Q-55 of 6 October 2026 15:22 CEST): V-E16's row 3 "
          "carries N1a's annotation of U5's line, \"" + N1A_WORDS.strip() + "\", at the place the register's R-176 row 3 carries "
          "it since set 31 (the coordinator's N1a, `b2564b59`, in `records/l4e9/DOWNSTREAM-REGISTER.md`), so V-E16's rows 2 and 3 "
          "again equal the register's R-176 rows 2 and 3 verbatim, the invariant record l5pwr's L5-F09 d wrote; nothing else in "
          "the row changed. R-240 stays drafted and not applied: no interface, pin, level, capacity figure, sequencing field, "
          "bench figure or pass line changed and no claim widened (row 3's \"no loop is claimed to pass\" stands). The wording "
          "before, as version 2 (W8, L5-F14) left it: \"" + OLD + "\" |")

# Edit 6 (W47, Q-65): TP-SOLAR.md takes the register's annotated U5 line as its own text quote, right after the text quote of
# L4E7-CONTROL-DECISION.md whose row 3 (the page's line 297 at 3057ae43) stays as its source prints it.
TP_REL = "v2/docs/test-procedures/TP-SOLAR.md"
TP_ANCHOR = "> 6. no short-circuit trip with C126 at 330 pF in operation and under CS116 (R-174).\n<!-- /q -->\n"
TP_NEXT = "\nThe lines, with U taken as README section 3 states"
TP_MARK = "**Added 6 October 2026 (set 32, Q-55, quotes only):**"
TP_QSRC = "v2/docs/records/l4e9/DOWNSTREAM-REGISTER.md"
TP_ADD = ("\n" + TP_MARK + " the register's R-176 row 3 annotates U5's line with R-240's drafted\n"
          "correction (the coordinator's N1a, set 31), and V-E16's row 3 in `v2/docs/HW-FW-CONTRACT.md` carries the same words since\n"
          "set 32 (Q-55); L4-E7's list above does not carry them. R-240 is drafted, not applied: row 3 above and the Row 3 line below\n"
          "are unchanged.\n"
          "\n"
          "<!-- q src=\"" + TP_QSRC + "\" -->\n"
          "> U5's CSPIN to CSNIN within +-0.240 V (under R-240, drafted, not applied: under 10 mV in magnitude, a layout check,\n"
          "> L4E7-P0SOL.md section 5)\n"
          "<!-- /q -->\n")
Q_RX = re.compile(r"<!-- q (.*?) -->\n(.*?)\n<!-- /q -->", re.S)   # tp_check.py's quote block, as it reads one

# test_l5pwr (W14's restated reading of record l5pwr's L5-F09 d): the script printed V-E16's rows 2 and 3 before N1a, so with
# N1a's words in V-E16 its row 3 value is no longer a verbatim substring of the row. Found by running test_l5pwr on set 31's tip
# with the two edits above applied (a scratch clone of d5d9c252): t_the_contract_restatement_of_l5f09_and_l5f10_is_in_the_tree_
# and_idempotent failed with "L5-F09 d: a value the script printed is gone". The restatement admits exactly N1a's words, once,
# right after U5's line, and nothing else; every other property of the reading is unchanged.
L5PWR_REL = "v2/ecad/tools/tests/test_l5pwr.py"
L5PWR_OLD = (
    '        if i in W8_RESTATED:\n'
    '            assert a.flat(new) not in live, "%s: the script\'s text stands verbatim, so W8 did not restate it" % i\n'
    '            assert _w14_restated(a.flat, i, new, live, quotes, V.values(), "no loop is claimed to pass"), i\n')
L5PWR_NEW = (
    '        if i in W8_RESTATED:\n'
    '            # Q-55 (set 32, record s32small, applied by apply_q55_ve16.py): V-E16\'s row 3 carries N1a\'s annotation of the\n'
    '            # register\'s R-176 row 3 (set 31, b2564b59), which this script printed before N1a. Where a restated field carries\n'
    '            # N1a\'s words they must stand exactly once, in V-E16, right after U5\'s line, and the script\'s values are read with\n'
    '            # those words taken out. Basis: N1a is the one intended difference (test_w8l5 states it so for the register, f0748b49),\n'
    '            # and the coordinator\'s decision of 6 October 2026 15:22 CEST (QUEUE line Q-55).\n'
    '            n1a = " (under R-240, drafted, not applied: under 10 mV in magnitude, a layout check, L4E7-P0SOL.md section 5)"\n'
    '            if n1a in live:\n'
    '                assert where == "| V-E16 |" and live.count(n1a) == 1 and live.count("U5\'s CSPIN to CSNIN within +-0.240 V" + n1a) == 1, \\\n'
    '                    "%s: N1a\'s words stand elsewhere than once after U5\'s line in V-E16" % i\n'
    '                live = live.replace(n1a, "")\n'
    '            assert a.flat(new) not in live, "%s: the script\'s text stands verbatim, so W8 did not restate it" % i\n'
    '            assert _w14_restated(a.flat, i, new, live, quotes, V.values(), "no loop is claimed to pass"), i\n')
L5PWR_MARK = "# Q-55 (set 32"


class Refused(Exception):
    pass


class Done(Exception):
    pass


def cells(line):
    s = line.strip()
    return [c.strip() for c in s[1:-1].split("|")] if s.startswith("|") and s.endswith("|") else None


def one_row(text, prefix, what):
    rows = [ln for ln in text.split("\n") if ln.startswith(prefix)]
    if len(rows) != 1:
        raise Refused("%d rows start with %r in %s" % (len(rows), prefix, what))
    return rows[0]


def sha(b):
    return hashlib.sha256(b).hexdigest()


def plan(root):
    reg = open(os.path.join(root, REG_REL), encoding="utf-8").read()
    hw = open(os.path.join(root, HWFW_REL), encoding="utf-8").read()
    tp = os.path.join(root, TEST_REL)
    if not os.path.isfile(tp):
        raise Refused("%s is not in this tree (set 31's file): run on set 32's merged tree" % TEST_REL)
    tt = open(tp, encoding="utf-8").read()
    lp = os.path.join(root, L5PWR_REL)
    if not os.path.isfile(lp):
        raise Refused("%s is not in this tree" % L5PWR_REL)
    lt = open(lp, encoding="utf-8").read()
    pp = os.path.join(root, TP_REL)
    if not os.path.isfile(pp):
        raise Refused("%s is not in this tree" % TP_REL)
    tpx = open(pp, encoding="utf-8").read()

    ve = one_row(hw, "| V-E16 |", HWFW_REL)
    applied = [N1A_WORDS in ve, MARK in tt, L5PWR_MARK in lt, CR_PREFIX in hw, TP_MARK in tpx]
    if all(applied):
        raise Done("already applied: V-E16 carries N1a's words, test_w8l5 the Q-55 check, test_l5pwr the Q-55 reading, the "
                   "change record Q-55's row and TP-SOLAR.md the register's annotated U5 line")
    if any(applied):
        raise Refused("half applied (V-E16 %s, test_w8l5 %s, test_l5pwr %s, the change record row %s, TP-SOLAR.md %s): mend by hand"
                      % tuple("yes" if a else "no" for a in applied))

    # 1. N1a is in the tree's register
    r176 = cells(one_row(reg, "| R-176 | TEST |", REG_REL))
    if r176[2].count(N1A_WORDS) != 1 or r176[2].count(U5 + N1A_WORDS) != 1:
        raise Refused("the register's R-176 row 3 does not carry N1a's annotation after %r once (N1a, b2564b59, is set 31's)" % U5)
    want = r176[2][r176[2].index("(2) "):r176[2].index("; (4) ")]

    # 2. the page
    if ve.count(OLD) != 1 or hw.count(OLD) != 1:
        raise Refused("OLD is %d times in V-E16 and %d times in the page, not once" % (ve.count(OLD), hw.count(OLD)))
    if W8_END not in ve:
        raise Refused("V-E16 lacks W8's wording %r: run after set 31's promotion" % W8_END)
    ve_new = ve.replace(OLD, NEW, 1)
    hw_new = hw.replace(ve, ve_new, 1)
    if hw_new == hw or ve_new == ve:
        raise Refused("the new page does not differ")
    a, b = hw.split("\n"), hw_new.split("\n")
    moved = [i for i, (x, y) in enumerate(zip(a, b)) if x != y]
    if len(a) != len(b) or len(moved) != 1:
        raise Refused("the edit moved %d lines of the page, not one" % len(moved))
    ca, cb = cells(a[moved[0]]), cells(b[moved[0]])
    if ca is None or cb is None or len(ca) != len(cb) or ca[:-1] != cb[:-1]:
        raise Refused("V-E16's cells other than the last moved, or its cell count changed")
    v = cb[-1]
    if v[v.index("(2) "):v.index(W8_END)] != want:
        raise Refused("after the edit V-E16's rows 2 and 3 are not the register's R-176 rows 2 and 3 verbatim")
    if chr(0x2014) in hw_new or chr(0x2013) in hw_new:
        raise Refused("an em or en dash in the page")

    # 5. (W47) Q-55's change record row, appended after the V-E16 edit (section 10 is the page's last section)
    hv = hw_new.split("\n")
    if hv[-1] != "" or hw_new.count("\n" + CR_HEAD + "\n") != 1:
        raise Refused("the page does not end with a newline, or %r is not once in it" % CR_HEAD)
    sec = hv[hv.index(CR_HEAD):]
    if any(ln.startswith("## ") for ln in sec[1:]):
        raise Refused("section 10 (the change record) is not the page's last section")
    if sum(ln.startswith(CR_W8) for ln in sec) != 1 or sum(ln.startswith(CR_W8) for ln in hv) != 1:
        raise Refused("W8's change record row %r is not once in section 10: run after set 31's promotion" % CR_W8)
    if CR_PREFIX in hw_new:
        raise Refused("Q-55's change record row is already in the page")
    last = cells(hv[-2])
    if last is None or len(last) != 3 or not hv[-2].startswith("| 2 ("):
        raise Refused("the page's last line is not a three-cell row of the change record")
    cr = cells(CR_ROW)
    if len(cr) != 3 or cr[1] != "6 October 2026" or CR_ROW.count(N1A_WORDS.strip()) != 1 or CR_ROW.count(OLD) != 1:
        raise Refused("Q-55's change record row is not in W8's form")
    hw_cr = hw_new + CR_ROW + "\n"
    hc = hw_cr.split("\n")
    if len(hc) != len(hv) + 1 or hc[:-2] != hv[:-1] or hc[-2] != CR_ROW or hc[-1] != "":
        raise Refused("appending the change record row moved another line of the page")
    if chr(0x2014) in CR_ROW or chr(0x2013) in CR_ROW:
        raise Refused("an em or en dash in the change record row")
    hw_new = hw_cr

    # 3. the test
    if tt.count(TEST_OLD) != 1:
        raise Refused("the coordinator's live check (f0748b49) is %d times in %s, not once" % (tt.count(TEST_OLD), TEST_REL))
    tt_new = tt.replace(TEST_OLD, TEST_OLD + TEST_ADD, 1)
    if tt_new == tt:
        raise Refused("the new test does not differ")
    ast.parse(tt_new, TEST_REL)
    if chr(0x2014) in tt_new or chr(0x2013) in tt_new:
        raise Refused("an em or en dash in the test")

    # 4. test_l5pwr's reading of L5-F09 d
    if lt.count(L5PWR_OLD) != 1:
        raise Refused("W14's L5-F09 reading is %d times in %s, not once" % (lt.count(L5PWR_OLD), L5PWR_REL))
    lt_new = lt.replace(L5PWR_OLD, L5PWR_NEW, 1)
    if lt_new == lt:
        raise Refused("the new test_l5pwr does not differ")
    ast.parse(lt_new, L5PWR_REL)
    if chr(0x2014) in lt_new or chr(0x2013) in lt_new:
        raise Refused("an em or en dash in test_l5pwr")

    # 6. (W47) TP-SOLAR.md: the register's annotated U5 line as its own text quote, after L4-E7's quote (which stays)
    if tpx.count(TP_ANCHOR) != 1 or tpx.count(TP_ANCHOR + TP_NEXT) != 1:
        raise Refused("the end of L4-E7's quote of R-176's six rows, followed by the Row lines, is not once in %s" % TP_REL)
    if N1A_WORDS.strip() in tpx or TP_MARK in tpx:
        raise Refused("%s already carries N1a's words or the Q-55 lead-in" % TP_REL)
    i = tpx.index(TP_ANCHOR) + len(TP_ANCHOR)
    tp_new = tpx[:i] + TP_ADD + tpx[i:]
    if tp_new == tpx or tp_new.replace(TP_ADD, "", 1) != tpx:
        raise Refused("the procedure's edit is not a pure insertion")
    blocks = Q_RX.findall(tp_new)
    if tp_new.count("<!-- q ") != len(blocks) or len(blocks) != len(Q_RX.findall(tpx)) + 1:
        raise Refused("the procedure's quote blocks are not well formed, or the insertion is not one block")
    flat = lambda s: " ".join(s.split())
    unq = lambda b: flat(" ".join(ln.strip()[1:] if ln.strip().startswith(">") else ln.strip() for ln in b.split("\n")))
    mine = [unq(b) for a_, b in blocks if 'src="%s"' % TP_QSRC in a_ and "row=" not in a_]
    if mine.count(flat(U5 + N1A_WORDS)) != 1:
        raise Refused("the procedure does not carry the register's annotated U5 line once as a text quote")
    if flat(U5 + N1A_WORDS) not in flat(reg):
        raise Refused("the quote is not found verbatim in the register (tp_check.py's C3)")
    for path in re.findall(r"`(v2/[^`\s]+)`", TP_ADD):
        if not os.path.exists(os.path.join(root, path.rstrip(".,;:"))):
            raise Refused("the path %s in the insertion is not in the tree (tp_check.py's C5)" % path)
    if "TBD" in TP_ADD or chr(0x2014) in tp_new or chr(0x2013) in tp_new:
        raise Refused("a TBD in the insertion, or an em or en dash in the procedure")
    return [(HWFW_REL, hw, hw_new), (TEST_REL, tt, tt_new), (L5PWR_REL, lt, lt_new), (TP_REL, tpx, tp_new)]


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    root = a.root or subprocess.run(["git", "-C", HERE, "rev-parse", "--show-toplevel"], capture_output=True,
                                    text=True, check=True).stdout.strip()
    try:
        edits = plan(root)
    except Done as e:
        print("apply_q55_ve16: %s; nothing written" % e); return 3
    except Refused as e:
        print("apply_q55_ve16: REFUSED: %s; nothing written" % e); return 2
    for rel, old, new in edits:
        print("apply_q55_ve16: %s %s -> %s" % (rel, sha(old.encode())[:16], sha(new.encode())[:16]))
    if a.check:
        print("apply_q55_ve16: CHECK ONLY, every check held, nothing written"); return 0
    for rel, old, new in edits:
        p = os.path.join(root, rel)
        tmp = p + ".q55.tmp"
        with open(tmp, "w", encoding="utf-8", newline="") as fh:
            fh.write(new)
        os.replace(tmp, p)
    # re-read what was written
    for rel, old, new in edits:
        got = open(os.path.join(root, rel), encoding="utf-8").read()
        assert got == new, "%s reads back different" % rel
    for rel, _old, new in edits:
        if rel.endswith(".py"):
            ast.parse(new, rel)
    hw_sha = sha(open(os.path.join(root, HWFW_REL), "rb").read())
    print("apply_q55_ve16: written; %s sha256 now %s: re-pin l4e11_power.py's and l4e9_power_path.py's PINS[\"hwfw\"], "
          "re-key the l4e7 KEY, then the dependency pass" % (HWFW_REL, hw_sha))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
